if(location.hostname!=='127.0.0.1')throw Error('Local prototype only');
let thai=false;
const translations={
 'Collection · Synthetic borrower':'งานติดตาม · ผู้กู้จำลอง','Select charges to receive in this rehearsal.':'เลือกยอดเรียกเก็บสำหรับการทดสอบจำลองนี้','Receiving account':'บัญชีรับชำระ','Synthetic receiving account':'บัญชีรับชำระจำลอง','Review selected charges':'ตรวจสอบยอดที่เลือก','Review synthetic payment':'ตรวจสอบการรับชำระจำลอง','Borrower':'ผู้กู้','Synthetic borrower':'ผู้กู้จำลอง','Selected charges':'ยอดเรียกเก็บที่เลือก','Payment date':'วันที่รับชำระ','Method':'วิธีรับชำระ','Bank Transfer · Selected Charges':'โอนเงินผ่านธนาคาร · ยอดเรียกเก็บที่เลือก','Amount received':'ยอดรับชำระ','Confirm requires an online connection to the local rehearsal server.':'การยืนยันต้องเชื่อมต่อกับเซิร์ฟเวอร์จำลองในเครื่อง','Simulate a lost response after commit':'จำลองการขาดการตอบกลับหลังบันทึกสำเร็จ','Request reference:':'รหัสคำขอ:','Back':'กลับ','Confirm synthetic payment':'ยืนยันการรับชำระจำลอง','Waiting for confirmation…':'กำลังรอผลการยืนยัน…','No second payment will be created while the result is pending.':'จะไม่สร้างการรับชำระครั้งที่สองระหว่างรอผล','Outcome unknown':'ยังไม่ทราบผลลัพธ์','The connection ended without a confirmed result. This does not mean payment failed. The original request and amount are locked.':'การเชื่อมต่อสิ้นสุดโดยยังไม่ได้ยืนยันผล ไม่ได้แปลว่าการชำระล้มเหลว ระบบล็อกคำขอและยอดเดิมไว้','Check status':'ตรวจสอบสถานะ','Retry same request':'ลองคำขอเดิมอีกครั้ง','Posted in disposable database':'บันทึกในฐานข้อมูลทดสอบแล้ว','No actual bank transfer or notification was sent.':'ไม่มีการโอนเงินจริงหรือส่งการแจ้งเตือน','Request conflict':'คำขอขัดแย้งกัน','This reference belongs to different payment details. Do not retry it as this payment.':'รหัสนี้มีรายละเอียดการรับชำระอื่น ห้ามใช้ซ้ำกับการชำระนี้','Request rejected':'คำขอถูกปฏิเสธ','The local command was rejected. Do not assume a different amount or new request will succeed.':'คำขอจำลองถูกปฏิเสธ อย่าสรุปว่าการเปลี่ยนยอดหรือสร้างคำขอใหม่จะสำเร็จ','Checkpoint limits':'ข้อจำกัดของจุดตรวจสอบ','LOCAL · SYNTHETIC ONLY':'ในเครื่อง · ข้อมูลจำลองเท่านั้น','MW Credit · Payment rehearsal':'MW Credit · จำลองการรับชำระ',
 'This isolated demo posts only to a disposable V77 database. Replay protection uses a temporary memory journal; it is not durable or ready for live payments.':'การสาธิตนี้บันทึกเฉพาะฐานข้อมูลทดสอบ V77 การป้องกันคำขอซ้ำใช้หน่วยความจำชั่วคราว ยังไม่คงทนและไม่พร้อมรับชำระจริง',
 'No real borrower, bank transfer, receipt upload or notification delivery. Closing the runner destroys the active test service. Existing receipt correction/deletion prevents a durable replay guarantee without further design.':'ไม่มีผู้กู้จริง การโอนเงิน การอัปโหลดใบเสร็จ หรือการส่งแจ้งเตือน การปิดตัวทดสอบจะหยุดบริการนี้ การแก้ไขหรือลบใบรับชำระเดิมทำให้ยังรับประกันการป้องกันคำขอซ้ำอย่างคงทนไม่ได้'
};
const originalText=new WeakMap();
function translate(root){const walk=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walk.nextNode()){if(node.parentElement?.closest('script,style,#language'))continue;const original=originalText.get(node)??node.nodeValue;originalText.set(node,original);const clean=original.trim();let value=translations[clean];if(clean.startsWith('Sample charge '))value='ยอดจำลอง '+clean.slice(14);if(clean.endsWith(' was confirmed by a new database read.'))value=clean.replace(' was confirmed by a new database read.',' ได้รับการยืนยันจากการอ่านฐานข้อมูลใหม่');node.nodeValue=thai&&value?original.replace(clean,value):original;}}
document.getElementById('language').onclick=()=>{thai=!thai;document.documentElement.lang=thai?'th':'en';document.getElementById('language').textContent=thai?'EN':'ไทย';translate(document.body)};
const flow=document.querySelector('#flow');let fixture,selected=new Set(),command=null,state='select',result=null;
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const whole=value=>{if(!/^[0-9]+(?:\.0+)?$/.test(value))throw Error('Fixture is not whole baht');return BigInt(value.split('.')[0])};
const money=value=>'฿'+whole(value).toLocaleString('en-US');
const amount=()=>fixture.charges.filter(c=>selected.has(c.id)).reduce((sum,c)=>sum+whole(c.amount),0n).toString();
function button(id,label,primary=false){return `<button id="${id}" class="${primary?'primary':''}">${label}</button>`}
function render(){
 if(state==='select')flow.innerHTML=`<h1>Collection · Synthetic borrower</h1><p>Select charges to receive in this rehearsal.</p>${fixture.charges.map((c,i)=>`<label class="charge"><input type="checkbox" value="${c.id}" ${selected.has(c.id)?'checked':''} ${whole(c.amount)<=0n?'disabled':''}><span>Sample charge ${i+1}<br>${escape(c.date)}</span><strong>${money(c.amount)}</strong></label>`).join('')}<h2>Receiving account</h2><select id="account" aria-label="Receiving account">${fixture.accounts.map(a=>`<option value="${a.id}">${escape(a.label)}</option>`).join('')}</select>${button('review','Review selected charges',true)}`;
 if(state==='review')flow.innerHTML=`<h1>Review synthetic payment</h1><dl><div><dt>Borrower</dt><dd>Synthetic borrower</dd></div><div><dt>Selected charges</dt><dd>${fixture.charges.filter(c=>command.selectedChargeIds.includes(c.id)).map(c=>escape(c.date)+' · '+money(c.amount)).join('<br>')}</dd></div><div><dt>Receiving account</dt><dd>${escape(fixture.accounts.find(a=>a.id===command.cashAccountId)?.label??'Unavailable')}</dd></div><div><dt>Payment date</dt><dd>${command.paymentDate}</dd></div><div><dt>Method</dt><dd>Bank Transfer · Selected Charges</dd></div><div><dt>Amount received</dt><dd><strong>${money(command.amountReceived)}</strong></dd></div></dl><p>Confirm requires an online connection to the local rehearsal server.</p><label><input type="checkbox" id="lose"> Simulate a lost response after commit</label><p>Request reference: <code>${command.requestId}</code></p>${button('back','Back')}${button('confirm','Confirm synthetic payment',true)}`;
 if(state==='pending')flow.innerHTML='<h1>Waiting for confirmation…</h1><p>No second payment will be created while the result is pending.</p>';
 if(state==='unknown')flow.innerHTML=`<div class="unknown"><h1>Outcome unknown</h1><p>The connection ended without a confirmed result. This does not mean payment failed. The original request and amount are locked.</p><p>Request reference: <code>${command.requestId}</code></p>${button('status','Check status',true)}<button disabled title="Resolve status before any retry">Retry same request</button></div>`;
 if(state==='posted')flow.innerHTML=`<div class="posted"><h1>Posted in disposable database</h1><p>${money(command.amountReceived)} was confirmed by a new database read.</p><p>Request reference: <code>${command.requestId}</code></p><p>No actual bank transfer or notification was sent.</p>${button('status','Check status')}</div>`;
 if(state==='conflict')flow.innerHTML=`<h1>Request conflict</h1><p>This reference belongs to different payment details. Do not retry it as this payment.</p><p>Request reference: <code>${command.requestId}</code></p>`;
 if(state==='rejected')flow.innerHTML=`<h1>Request rejected</h1><p>The local command was rejected. Do not assume a different amount or new request will succeed.</p><p>Request reference: <code>${command.requestId}</code></p>${button('status','Check status')}`;
 flow.querySelectorAll('input[type=checkbox][value]').forEach(input=>input.onchange=()=>{input.checked?selected.add(input.value):selected.delete(input.value)});
 const bind=(id,fn)=>{const e=document.getElementById(id);if(e)e.onclick=fn};
 bind('review',()=>{if(!selected.size||!fixture.accounts.length)return;command={schemaVersion:1,requestId:crypto.randomUUID(),borrowerId:fixture.borrowerId,selectedChargeIds:[...selected].sort(),cashAccountId:document.getElementById('account').value,paymentDate:fixture.businessDate,amountReceived:amount(),paymentMethod:'Bank Transfer',allocationMethod:'Selected Charges'};state='review';render()});
 if(state==='review'&&!navigator.onLine)document.getElementById('confirm').disabled=true;
 bind('back',()=>{command=null;state='select';render()});bind('confirm',()=>send(document.getElementById('lose').checked));bind('status',checkStatus);
 translate(document.body);
}
let pendingController=null;
async function boundedFetch(url,options={}){const controller=new AbortController();pendingController=controller;const timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(url,{...options,signal:controller.signal});if(!response.ok)throw Error('Local response unavailable');return await response.json()}finally{clearTimeout(timer);if(pendingController===controller)pendingController=null}}
window.addEventListener('offline',()=>{pendingController?.abort();if(state==='review')render()});window.addEventListener('online',()=>{if(state==='review')render()});
async function send(lose){if(!navigator.onLine)return;state='pending';render();try{result=await boundedFetch('/confirm',{method:'POST',headers:{'Content-Type':'application/json',...(lose?{'X-Rehearsal-Scenario':'lose-response'}:{})},body:JSON.stringify(command)});state=['posted','rejected','conflict'].includes(result.status)?result.status:'unknown'}catch{state='unknown'}render()}
async function checkStatus(){state='pending';render();try{result=await boundedFetch('/status?id='+encodeURIComponent(command.requestId));state=['posted','rejected','conflict'].includes(result.status)?result.status:'unknown'}catch{state='unknown'}render()}
try{const response=await fetch('/fixture');if(!response.ok)throw Error();fixture=await response.json();render()}catch{flow.textContent='Local rehearsal unavailable. Start the disposable runner; no live service is used.'}
