steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -t, 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/mw-credit-app/api:$BUILD_ID', .]
images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/mw-credit-app/api:$BUILD_ID'
options:
  logging: CLOUD_LOGGING_ONLY
