import{test,expect}from'@playwright/test';
test('desktop Cash captions fit their buttons after scoped sizing correction',async({page})=>{await page.setViewportSize({width:1440,height:956});await page.route('http://127.0.0.1:4173/',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div><script type="module" src="/tests/e2e/fixtures/back-consumers-harness.tsx"></script>'}));await page.route('**/api/**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({items:[{id:'holder-A',label:'SYNTHETIC holder A',active:true}],nextCursor:null})}));await page.goto('/');await page.evaluate(()=>(window as any).selectBackCase('cash'));await page.getByRole('button',{name:'SYNTHETIC holder A Active',exact:true}).click();const buttons=page.getByRole('button',{name:'New record',exact:true});await expect(buttons).toHaveCount(2);for(const b of await buttons.all()){await expect(b.locator('.record-action-label')).toBeVisible();expect(await b.evaluate(node=>node.scrollWidth<=node.clientWidth)).toBe(true);expect((await b.boundingBox())!.width).toBeGreaterThan(80)}expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(1440);await page.screenshot({path:'outputs/r052-phase6/cash-accounts-two-panes-1440.png'})});
test('direct Accounts retains holder CRUD scoped account paging and Position retains ledger20 and actions',async({page})=>{
 await page.route('http://127.0.0.1:4173/',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div><script type="module" src="/tests/e2e/fixtures/back-consumers-harness.tsx"></script>'}));const reads:string[]=[],writes:string[]=[];
 await page.route('**/api/**',r=>{const u=new URL(r.request().url()),p=u.pathname;reads.push(u.pathname+u.search);if(r.request().method()!=='GET')writes.push(r.request().method());let body:any={items:[],nextCursor:null,businessDate:'2026-10-11'};
 if(p==='/api/management/cash-holders')body.items=[{id:'holder-A',label:'SYNTHETIC holder A',active:true},{id:'holder-B',label:'SYNTHETIC holder B',active:true}];
 else if(p==='/api/management/cash-accounts')body={...body,items:[{id:u.searchParams.get('cursor')?'account-page2':'account-A',label:u.searchParams.get('holderId')==='holder-B'?'SYNTHETIC account B':u.searchParams.get('cursor')?'SYNTHETIC account page2':'SYNTHETIC account A',active:true}],nextCursor:u.searchParams.get('cursor')?null:'account-next'};
 else if(p==='/api/management/cash-movements')body={...body,items:Array.from({length:u.searchParams.get('cursor')?1:20},(_,i)=>({id:'movement-'+i,date:'2026-10-11',movementType:u.searchParams.get('cursor')?'SYNTHETIC page2':'SYNTHETIC movement '+i,amount:'10',fromAccountLabel:'SYNTHETIC account A',toAccountLabel:'SYNTHETIC account B'})),nextCursor:u.searchParams.get('cursor')?null:'ledger-next'};
 else if(p.startsWith('/api/management/cash-holders/'))body={item:{id:'holder-A',label:'SYNTHETIC holder A',version:'a'.repeat(64),active:true,holderName:'SYNTHETIC holder A'}};
 else if(p.startsWith('/api/management/cash-accounts/'))body={item:{id:'account-A',label:'SYNTHETIC account A',version:'a'.repeat(64),active:true}};
 else if(p.startsWith('/api/management/cash-movements/'))body={item:{id:'movement-0',version:'a'.repeat(64),movementType:'Cash Handover',canEdit:true,amount:'10',date:'2026-10-11'}};
 return r.fulfill({contentType:'application/json',body:JSON.stringify(body)})});
 await page.goto('/');await page.setViewportSize({width:440,height:956});await page.evaluate(()=>(window as any).selectBackCase('cash'));
 await page.getByRole('button',{name:'SYNTHETIC holder A Active',exact:true}).click();await expect(page.getByRole('button',{name:'SYNTHETIC account A Active',exact:true})).toBeVisible();expect(reads.some(p=>p.includes('cash-accounts?')&&p.includes('holderId=holder-A'))).toBe(true);
 await page.getByRole('button',{name:'Cash holder details: SYNTHETIC holder A',exact:true}).click();await expect(page.getByRole('button',{name:'Edit',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Delete',exact:true})).toBeVisible();
 const h=page.getByRole('heading',{name:'SYNTHETIC holder A',exact:true}).first();const marker=page.locator('[data-header-back]').first();await expect(marker).toHaveCSS('display','none');expect((await h.boundingBox())!.x).toBeLessThan(30);await page.screenshot({path:'outputs/r052-phase6/cash-header-subject-440.png'});await page.locator('.topbar button').click();await expect(page.getByRole('button',{name:'SYNTHETIC account A Active',exact:true})).toBeVisible();
 await page.getByRole('region',{name:'Holder accounts',exact:true}).getByRole('button',{name:'Next page',exact:true}).click();await expect(page.getByRole('button',{name:'SYNTHETIC account page2 Active',exact:true})).toBeVisible();expect(reads.some(p=>p.includes('holderId=holder-A')&&p.includes('cursor=account-next'))).toBe(true);await page.getByRole('button',{name:'SYNTHETIC holder B Active',exact:true}).click();await expect(page.getByRole('button',{name:'SYNTHETIC account B Active',exact:true})).toBeVisible();
 for(const width of[440,1440]){await page.setViewportSize({width,height:956});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:'outputs/r052-phase6/cash-accounts-two-panes-'+width+'.png'})}
 await page.evaluate(()=>(window as any).selectBackCase('cash-position'));await expect(page.locator('.management-position>article').last().locator('tbody tr')).toHaveCount(20);expect(reads.some(p=>p==='/api/management/cash-movements?limit=20')).toBe(true);await page.getByRole('button',{name:'Next transactions',exact:true}).click();await expect(page.getByRole('button',{name:'SYNTHETIC page2',exact:true})).toBeVisible();expect(reads.some(p=>p.includes('limit=20')&&p.includes('cursor=ledger-next'))).toBe(true);
 await page.getByRole('button',{name:'SYNTHETIC page2',exact:true}).click();await expect(page.getByRole('button',{name:'Edit',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Delete',exact:true})).toBeVisible();await page.locator('.topbar button').click();await expect(page.getByRole('button',{name:'SYNTHETIC page2',exact:true})).toBeVisible();await page.getByRole('button',{name:'New cash movement',exact:true}).click();await expect(page.getByRole('combobox')).toHaveCount(1);await page.locator('.topbar button').click();await expect(page.getByRole('button',{name:'New cash movement',exact:true})).toBeVisible();
 await page.setViewportSize({width:440,height:956});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(440);await page.screenshot({path:'outputs/r052-phase6/cash-position-tables-440.png'});expect(writes).toEqual([]);
});
