import {chooseLanguage,signOut} from './live-controls';
import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
let server:ChildProcess;let base:string;let serverLog="";
test.beforeAll(async({},info)=>{
 const port=5500+info.workerIndex;base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/playwright-live-${port}-${Date.now()}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-test-key',VITE_FIREBASE_APP_ID:'synthetic-app-id',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app'},stdio:'pipe'});
 server.stdout?.on("data",data=>{serverLog+=String(data)});server.stderr?.on("data",data=>{serverLog+=String(data)});
 await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return0()}},{timeout:20000}).toBe(200);
});
function return0(){return 0}
test.afterAll(()=>server?.kill()); test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)console.log(serverLog)});
const authMock=`let listener;export const browserLocalPersistence='local';export const inMemoryPersistence='memory';export const browserPopupRedirectResolver={};export function initializeAuth(a,o){if(o.persistence!=='local')throw Error('persistence');return {}};export function getAuth(){return {}};export async function setPersistence(a,p){if(p!=='local')throw Error('persistence');}export function onAuthStateChanged(a,fn){listener=fn;fn(null);return()=>{listener=null}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){listener({uid:'synthetic-owner',getIdToken:async()=>'synthetic-bearer'})};export async function signOut(){listener(null)};`;
test.use({timezoneId:'America/Los_Angeles'});
const statuses=['not_paid','partially_paid','overdue','fully_paid'];
const rows=Array.from({length:27},(_,i)=>({id:'private-board-'+i,displayName:'ผู้กู้ตัวอย่าง - Synthetic '+i,status:statuses[Math.min(3,Math.floor(i/7))],amountDue:i>=21?'0':'13.75',amountCollected:i>=21?'0':'3.25',amountRemaining:i>=21?'0':'10.50'}));
const charges=Array.from({length:27},(_,i)=>({id:'private-charge-'+i,loanId:'private-loan',loanDisplayKey:'ผู้กู้ตัวอย่างชื่อยาว - Long synthetic borrower English name-฿12,000-07/10-2%',chargeDate:'2026-10-07',paymentStatus:'ชำระบางส่วน',paymentDate:null,amountRemaining:i===0?null:'10.50',totalPaid:'0',receivedToday:'-2.50'}));
test('Collection board child pages financial display rollover errors and route/logout races',async({page},info)=>{
 if(info.project.name.startsWith('desktop'))await page.setViewportSize({width:1440,height:900});async function navigate(name:string){await page.getByRole('button',{name,exact:true}).click();} let code=200,businessDate='2026-10-07',hold=false,release:(()=>void)|undefined;const paths:string[]=[];
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/upcoming')){await r.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({ok:true,source:'dev',businessDate,asOf:'2026-10-07T05:00:00Z',horizonEnd:'2027-01-07',reviewRequired:false,items:[]})});return;}paths.push(u.pathname+u.search);expect(r.request().method()).toBe('GET');const collection=u.pathname.startsWith('/api/collection'),child=u.pathname.endsWith('/charges');const status=collection?code:200;const day=businessDate;if(collection&&hold)await new Promise<void>(resolve=>release=resolve);const source=child?charges:rows;const items=collection?source.slice(u.searchParams.has('cursor')?25:0,u.searchParams.has('cursor')?27:25):[];await r.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(status===200?{ok:true,source:'dev',businessDate:day,timezone:'Asia/Bangkok',asOf:'2026-10-07T05:00:00Z',items,borrower:rows[0],nextCursor:collection&&!u.searchParams.has('cursor')?'synthetic-next':null}:{ok:false,code:status===409?'business_date_changed':'source_unavailable'})}).catch(()=>{})});
 await page.goto(base);await page.getByRole('button',{name:'Continue with Google'}).click();await navigate('Collection');await expect(page.locator('.collection-borrower')).toHaveCount(25);await expect(page.locator('.collection-borrower').first()).toContainText('฿13.75');await expect(page.locator('.collection-borrower.fully-paid').first()).toContainText('฿0');await page.getByRole('button',{name:'Next Collection page',exact:true}).click();await expect(page.locator('.collection-borrower')).toHaveCount(2);await expect(page.getByRole('button',{name:'Next Collection page',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Refresh Collection — return to first page'}).click();await expect(page.locator('.collection-borrower')).toHaveCount(25);
 await page.locator('.collection-borrower').first().click();await expect(page.locator('.collection-charge')).toHaveCount(25);await expect(page.locator('.collection-charge').first()).toContainText('Unavailable');await page.locator('.collection-charge').first().click();await expect(page.getByRole('article',{name:'Charge detail',exact:true})).toContainText('-฿2.5');await page.getByRole('button',{name:'Back to charges',exact:true}).click();await page.getByRole('button',{name:'Next charges page',exact:true}).click();await expect(page.locator('.collection-charge')).toHaveCount(2);await expect(page.getByRole('button',{name:'Next charges page',exact:true})).toHaveCount(0);expect(await page.locator('body').innerText()).not.toMatch(/private-(board|charge|loan)|THB/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`outputs/r052-collection-read/${info.project.name}-TRIM-regression-en.png`,fullPage:true});await chooseLanguage(page,'ไทย');await expect(page.getByRole('region',{name:'พื้นที่งานติดตาม'})).toContainText('ยอดเรียกเก็บในงานติดตามวันนี้');await page.screenshot({path:`outputs/r052-collection-read/${info.project.name}-TRIM-regression-th.png`,fullPage:true});await chooseLanguage(page,'EN');
 code=503;await page.getByRole('button',{name:'First charges page / refresh'}).click();await expect(page.locator('.collection-charge')).toHaveCount(0);await expect(page.getByRole('region',{name:'Collection charge details'})).toContainText(rows[0].displayName);code=200;await page.getByRole('button',{name:'First charges page / refresh'}).click();await expect(page.locator('.collection-charge')).toHaveCount(25);
 code=409;await page.getByRole('button',{name:'Next charges page'}).click();await expect(page.getByRole('heading',{name:'The business date has changed'})).toBeVisible();await expect(page.locator('.collection-borrower,.collection-charge')).toHaveCount(0);code=200;await page.getByRole('button',{name:'Refresh Collection',exact:true}).click();await expect(page.locator('.collection-borrower')).toHaveCount(25);businessDate='2026-10-08';await page.locator('.collection-borrower').first().click();await expect(page.getByRole('heading',{name:'The business date has changed'})).toBeVisible();await expect(page.locator('.collection-charge')).toHaveCount(0);await page.getByRole('button',{name:'Refresh Collection',exact:true}).click();await expect(page.locator('.collection-borrower')).toHaveCount(25);
 hold=true;await page.locator('.collection-borrower').first().click();await expect.poll(()=>!!release).toBe(true);await navigate('Borrowers');hold=false;release!();await expect(page.locator('.collection-charge,.collection-borrower')).toHaveCount(0);await navigate('Collection');await expect(page.locator('.collection-borrower')).toHaveCount(25);hold=true;release=undefined;await page.getByRole('button',{name:'Refresh Collection — return to first page'}).click();await expect.poll(()=>!!release).toBe(true);await signOut(page);release!();await expect(page.getByRole('heading',{name:'Sign in to continue',exact:true})).toBeVisible();await expect(page.locator('.collection-charge,.collection-borrower')).toHaveCount(0);expect(paths.filter(x=>x.includes('/loans')).length).toBe(0);
});
