import {chooseLanguage,signOut} from './live-controls';
import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
let server:ChildProcess;let base:string;let serverLog="";
test.beforeAll(async({},info)=>{
 const port=6100+info.workerIndex;base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/playwright-live-${port}-${Date.now()}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-test-key',VITE_FIREBASE_APP_ID:'synthetic-app-id',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app'},stdio:'pipe'});
 server.stdout?.on("data",data=>{serverLog+=String(data)});server.stderr?.on("data",data=>{serverLog+=String(data)});
 await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return0()}},{timeout:20000}).toBe(200);
});
function return0(){return 0}
test.afterAll(()=>server?.kill()); test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)console.log(serverLog)});
const authMock=`let listener;export const browserLocalPersistence='local';export const inMemoryPersistence='memory';export const browserPopupRedirectResolver={};export function initializeAuth(a,o){if(o.persistence!=='local')throw Error('persistence');return {}};export function getAuth(){return {}};export async function setPersistence(a,p){if(p!=='local')throw Error('persistence');}export function onAuthStateChanged(a,fn){listener=fn;fn(null);return()=>{listener=null}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){listener({uid:'synthetic-owner',getIdToken:async()=>'synthetic-bearer'})};export async function signOut(){listener(null)};`;
test.use({timezoneId:'America/Los_Angeles'});
const statuses=['not_paid','partially_paid','overdue','fully_paid'];
const rows=Array.from({length:27},(_,i)=>({id:'private-board-'+i,displayName:'ผู้กู้ตัวอย่าง - Synthetic '+i,status:statuses[Math.min(3,Math.floor(i/7))],amountDue:i>=21?'0':'13.75',amountCollected:i>=21?'0':'3.25',amountRemaining:i>=21?'0':'10.50'}));
const charges=Array.from({length:27},(_,i)=>({id:'private-charge-'+i,loanId:'private-loan',loanDisplayKey:'ผู้กู้ตัวอย่างชื่อยาว - Long synthetic borrower English name-฿12,000-07/10-2%',chargeDate:'2026-10-07',paymentStatus:'ชำระบางส่วน',paymentDate:null,amountRemaining:i===0?null:'10.50',totalPaid:'0',receivedToday:'-2.50'}));


import {mkdirSync,writeFileSync} from 'node:fs';
for(const userScroll of [false,true])test('Collection completion preserves viewport '+(userScroll?'after user scroll':'without user scroll'),async({page},info)=>{
 await page.setViewportSize({width:info.project.name.startsWith('mobile')?390:1440,height:info.project.name.startsWith('mobile')?844:900});
 let releaseCharges:(()=>void)|undefined,releaseUpcoming:(()=>void)|undefined;
 const envelope={ok:true,source:'dev',businessDate:'2026-10-07',timezone:'Asia/Bangkok',asOf:'2026-10-07T05:00:00Z',horizonEnd:'2027-01-07'};
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{const path=new URL(r.request().url()).pathname;let result:any={...envelope,items:[],nextCursor:null};if(path==='/api/collection')result.items=[rows[0]];else if(path.endsWith('/charges')){await new Promise<void>(done=>releaseCharges=done);result={...envelope,borrower:rows[0],items:charges.slice(0,10),nextCursor:null}}else if(path.endsWith('/upcoming')){await new Promise<void>(done=>releaseUpcoming=done);result={...envelope,reviewRequired:false,items:[{id:'synthetic-date',dueDate:'2026-10-08',totalCharge:'10'}]}}await r.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(result)})});
 await page.goto(base);await page.getByRole('button',{name:'Continue with Google'}).click();await page.getByRole('button',{name:'Collection',exact:true}).click();await expect(page.locator('.collection-borrower')).toHaveCount(1);
 await page.evaluate(()=>{(window as any).scrollCalls=[];const original=Element.prototype.scrollIntoView;Element.prototype.scrollIntoView=function(...args){(window as any).scrollCalls.push({className:this.className,time:performance.now()});return original.apply(this,args)};});
 const snap=()=>page.evaluate(()=>{const box=(selector:string)=>{const el=document.querySelector(selector)!;const r=el.getBoundingClientRect();return {top:r.top,height:r.height,scrollTop:el.scrollTop,scrollHeight:el.scrollHeight}};return{scrollY,header:box('.topbar'),detail:box('.detail-panel'),active:document.activeElement?.className,headerVariable:getComputedStyle(document.documentElement).getPropertyValue('--live-header-height'),calls:[...(window as any).scrollCalls]}});
 const states:any[]=[{stage:'before',...await snap()}];await page.locator('.collection-borrower').click();await expect.poll(()=>!!releaseCharges).toBe(true);const selected=await snap();states.push({stage:'selected',...selected});expect(selected.detail.top).toBeGreaterThanOrEqual(selected.header.top+selected.header.height);if(info.project.name.startsWith('mobile'))expect(selected.calls.length).toBe(1);releaseCharges!();await expect.poll(()=>!!releaseUpcoming).toBe(true);await expect(page.locator('.collection-charge-row')).toHaveCount(10);states.push({stage:'charges',...await snap()});
 if(userScroll)await page.evaluate(()=>{if(innerWidth<=1050)window.scrollTo(0,200);else document.querySelector('.detail-panel')!.scrollTop=200});await page.evaluate(()=>new Promise(requestAnimationFrame));const before=await snap();states.push({stage:'waiting',...before});mkdirSync('outputs/r052-collection-shift',{recursive:true});if(!userScroll)await page.screenshot({path:'outputs/r052-collection-shift/'+info.project.name+'-waiting.png'});releaseUpcoming!();await expect(page.locator('.topbar .collection-update')).toContainText('Updated');const after=await snap();states.push({stage:'complete',...after});if(!userScroll)await page.screenshot({path:'outputs/r052-collection-shift/'+info.project.name+'-complete.png'});mkdirSync('outputs/r052-collection-shift',{recursive:true});writeFileSync('outputs/r052-collection-shift/'+info.project.name+'-'+userScroll+'.json',JSON.stringify(states,null,2));
 expect(after.header.height).toBe(before.header.height);expect(after.scrollY,'completion must not move mobile viewport').toBe(before.scrollY);expect(after.detail.scrollTop,'completion must not reset independent detail scrolling').toBe(before.detail.scrollTop);expect(after.calls.length,'completion must not issue another scrollIntoView').toBe(before.calls.length);
});
