import {chooseLanguage,signOut} from './live-controls';
import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
let server:ChildProcess;let base:string;let serverLog="";
test.beforeAll(async({},info)=>{
 const port=6700+info.workerIndex;base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/playwright-live-${port}-${Date.now()}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-test-key',VITE_FIREBASE_APP_ID:'synthetic-app-id',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app'},stdio:'pipe'});
 server.stdout?.on("data",data=>{serverLog+=String(data)});server.stderr?.on("data",data=>{serverLog+=String(data)});
 await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return0()}},{timeout:20000}).toBe(200);
});
function return0(){return 0}
test.afterAll(()=>server?.kill()); test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)console.log(serverLog)});
const authMock=`let listener;export const browserLocalPersistence='local';export const inMemoryPersistence='memory';export const browserPopupRedirectResolver={};export function initializeAuth(a,o){if(o.persistence!=='local')throw Error('persistence');return {}};export function getAuth(){return {}};export async function setPersistence(a,p){if(p!=='local')throw Error('persistence');}export function onAuthStateChanged(a,fn){listener=fn;fn(null);return()=>{listener=null}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){listener({uid:'synthetic-owner',getIdToken:async()=>'synthetic-bearer'})};export async function signOut(){listener(null)};`;

import {mkdirSync} from 'node:fs';
const ref='12345678-1234-4234-8234-123456789abc';
for(const view of ['Borrowers','Collection'])test(view+' reference copying and scoped manual recovery',async({page},info)=>{
 await page.setViewportSize({width:info.project.name.startsWith('mobile')?320:1440,height:900});
 await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async(v:string)=>{if((window as any).rejectCopy)throw Error('denied');(window as any).copied=v}}}));
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 const row={id:'synthetic-row',name:'Synthetic',borrowerDisplayName:'Synthetic - Example',displayName:'Synthetic - Example',hasActiveLoan:true,createdDate:null,outstandingPrincipal:'100',totalProfitEarned:'0',note:null,status:'not_paid',amountDue:'100',amountCollected:'0',amountRemaining:'100'};
 const env={ok:true,source:'dev',businessDate:'2026-10-08',asOf:'2026-10-08T05:00:00Z'};const root=view==='Borrowers'?'/api/borrowers':'/api/collection';let mode='ok',count=0;const queries:string[]=[];
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{const u=new URL(r.request().url());let body:any={...env,items:[],nextCursor:null};let status=200;let id='';if(u.pathname===root){count++;queries.push(u.searchParams.get('q')??'');if(mode==='network'){await r.abort();return}if(mode!=='ok'){status=503;id=mode==='bad'?'malformed-secret':mode==='missing'?'':ref;body={ok:false,code:'read_unavailable'}}else body={...env,items:[row],nextCursor:null}}await r.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-expose-headers':'X-Request-ID',...(id?{'X-Request-ID':id}:{})},body:JSON.stringify(body)})});
 await page.goto(base);await page.getByRole('button',{name:'Continue with Google'}).click();await page.getByRole('button',{name:view,exact:true}).click();const card=page.locator(view==='Borrowers'?'.borrower-tile-main':'.collection-tile-main');await expect(card).toHaveCount(1);
 await page.getByRole('button',{name:'Search borrowers',exact:true}).click();await page.getByRole('searchbox').fill('Example');await expect.poll(()=>queries.at(-1)).toBe('Example');await page.getByRole('button',{name:'Back from search',exact:true}).click();
 const refresh=()=>page.getByRole('button',{name:'Refresh '+view+' — return to first page',exact:true});const retry=()=>page.getByRole('button',{name:view==='Borrowers'?'Try again':'Refresh Collection',exact:true});
 mode='error';await refresh().click();await expect(page.locator('.read-error-reference')).toContainText(ref);const before=count;await page.getByRole('button',{name:'Copy reference',exact:true}).click();await expect(page.getByText('Copied',{exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).copied)).toBe(ref);await page.evaluate(()=>(window as any).rejectCopy=true);await page.getByRole('button',{name:'Copy reference',exact:true}).click();await expect(page.getByText('Could not copy. Select the reference to copy it.',{exact:true})).toBeVisible();expect(count).toBe(before);
 mkdirSync('outputs/r052-error-recovery',{recursive:true});await page.screenshot({path:'outputs/r052-error-recovery/'+info.project.name+'-'+view+'-error-en.png'});mode='ok';await retry().click();await expect(card).toHaveCount(1);await expect(page.locator('.read-error-reference')).toHaveCount(0);expect(queries.at(-1)).toBe('Example');
 for(const failure of ['bad','missing','network']){mode=failure;await refresh().click();await expect(retry()).toBeVisible();await expect(page.locator('.read-error-reference')).toHaveCount(0);mode='ok';await retry().click();await expect(card).toHaveCount(1)}
 await chooseLanguage(page,'ไทย');mode='error';await page.getByRole('button',{name:view==='Borrowers'?'รีเฟรชผู้กู้ — กลับหน้าแรก':'รีเฟรชงานติดตาม — กลับหน้าแรก',exact:true}).click();await expect(page.locator('.read-error-reference')).toContainText('รหัสอ้างอิง');await expect(page.getByRole('button',{name:'คัดลอกรหัสอ้างอิง',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'outputs/r052-error-recovery/'+info.project.name+'-'+view+'-error-th.png'});
});

for(const view of ['Borrowers','Collection'])test(view+' child error recovery and late route error isolation',async({page})=>{
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 const row={id:'synthetic-row',name:'Synthetic',borrowerDisplayName:'Synthetic - Example',displayName:'Synthetic - Example',hasActiveLoan:true,createdDate:null,outstandingPrincipal:'100',totalProfitEarned:'0',note:null,status:'not_paid',amountDue:'100',amountCollected:'0',amountRemaining:'100'};const env={ok:true,source:'dev',businessDate:'2026-10-08',asOf:'2026-10-08T05:00:00Z',horizonEnd:'2027-01-08',reviewLoans:0};let mode='error';let release:(()=>void)|undefined;
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{const u=new URL(r.request().url());const child=u.pathname.endsWith('/loans')||u.pathname.endsWith('/charges');let body:any={...env,items:[],nextCursor:null};let status=200;if(u.pathname==='/api/borrowers'||u.pathname==='/api/collection')body={...env,items:[row],nextCursor:null};else if(u.pathname.endsWith('/synthetic-row'))body={...env,item:row};else if(u.pathname.endsWith('/upcoming')&&mode==='upcoming'){status=503;body={ok:false,code:'source_unavailable'}}else if(child){if(mode==='late')await new Promise<void>(done=>release=done);if(mode!=='ok'&&mode!=='upcoming'){status=503;body={ok:false,code:'read_unavailable'}}else body={...env,borrower:row,items:[],nextCursor:null}}await r.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-expose-headers':'X-Request-ID',...(status===503?{'X-Request-ID':ref}:{})},body:JSON.stringify(body)}).catch(()=>{})});
 await page.goto(base);await page.getByRole('button',{name:'Continue with Google'}).click();await page.getByRole('button',{name:view,exact:true}).click();await page.locator(view==='Borrowers'?'.borrower-tile-main':'.collection-tile-main').click();await expect(page.locator('.read-error-reference')).toContainText(ref);await expect(page.locator('.detail-panel')).toContainText('Synthetic - Example');mode='ok';const retry=page.getByRole('button',{name:view==='Borrowers'?'Retry loan list':'First charges page / refresh',exact:true});await retry.click();await expect(page.locator('.read-error-reference')).toHaveCount(0);await expect(page.locator('.detail-panel')).toContainText('Synthetic - Example');
 if(view==='Collection'){mode='upcoming';await page.locator('.topbar').getByRole('button',{name:'First charges page / refresh',exact:true}).click();await expect(page.locator('.read-error-reference')).toContainText(ref);mode='ok';await page.getByRole('button',{name:'Retry Upcoming Charges',exact:true}).click();await expect(page.locator('.read-error-reference')).toHaveCount(0)}
 mode='late';await page.getByRole('button',{name:view==='Borrowers'?'First loans page / refresh':'First charges page / refresh',exact:true}).click();await expect.poll(()=>!!release).toBe(true);await page.getByRole('button',{name:view==='Borrowers'?'Collection':'Borrowers',exact:true}).click();release!();await expect(page.locator(view==='Borrowers'?'.collection-compact-tile':'.borrower-tile-main')).toHaveCount(1);await expect(page.locator('.read-error-reference')).toHaveCount(0);
});
