import {chooseLanguage,signOut} from './live-controls';
import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
let server:ChildProcess;let base:string;let serverLog="";
test.beforeAll(async({},info)=>{
 const port=4700+info.workerIndex;base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/playwright-live-${port}-${Date.now()}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-test-key',VITE_FIREBASE_APP_ID:'synthetic-app-id',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app'},stdio:'pipe'});
 server.stdout?.on("data",data=>{serverLog+=String(data)});server.stderr?.on("data",data=>{serverLog+=String(data)});
 await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return0()}},{timeout:20000}).toBe(200);
});
function return0(){return 0}
test.afterAll(()=>server?.kill()); test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)console.log(serverLog)});
const authMock=`let listener;export const browserLocalPersistence='local';export const inMemoryPersistence='memory';export const browserPopupRedirectResolver={};export function initializeAuth(a,o){if(o.persistence!=='local')throw Error('persistence');return {}};export function getAuth(){return {}};export async function setPersistence(a,p){if(p!=='local')throw Error('persistence');}export function onAuthStateChanged(a,fn){listener=fn;fn(null);return()=>{listener=null}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){listener({uid:'synthetic-owner',getIdToken:async()=>'synthetic-bearer'})};export async function signOut(){listener(null)};`;
const borrowers=Array.from({length:27},(_,i)=>({id:`private-b-${i}`,name:`ชื่อ ${i+1}`,borrowerDisplayName:`ชื่อ ${i+1} - English ${i+1}`,totalProfitEarned:i===0?'-12.34':i===1?'0':null,createdDate:'2026-10-07',hasActiveLoan:i<24?true:i<26?false:null,outstandingPrincipal:'9000',note:null}));
const loans=Array.from({length:27},(_,i)=>({id:`private-l-${i}`,borrowerId:'private-b-24',borrowerDisplayName:'ชื่อผู้กู้ตัวอย่างสำหรับทดสอบข้อความยาว - Synthetic borrower with a deliberately long English name',originalDailyInterestRate:i===0?'0':i===26?null:'2',loanDate:i===26?null:'2026-10-07',dueDate:null,closeDate:null,status:i<24?'ยังไม่ปิดยอด':i<26?'ปิดยอดแล้ว':'unexpected',loanType:'ดอกเบี้ยรายวัน',principalAmount:String(12000+i),outstandingPrincipal:'123.45',totalPrincipalReceived:'0',totalInterestReceived:null,totalAmountReceived:'0',defaulted:false,autoChargeEnabled:false}));
test('grouped multi-page presentation and independent detail scrolling',async({page},info)=>{
 if(info.project.name.startsWith('desktop'))await page.setViewportSize({width:1440,height:900});
 let holdNext=false,release:(()=>void)|undefined;const requests:string[]=[];await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{const u=new URL(r.request().url());requests.push(u.pathname+u.search);let items:any[]=borrowers,item:any=borrowers.find(b=>u.pathname.endsWith('/'+b.id));const nested=u.pathname.includes('/loans');if(nested){items=loans;item=loans.find(l=>u.pathname.endsWith('/'+l.id));}const cursor=u.searchParams.get('cursor');if(cursor&&holdNext)await new Promise<void>(resolve=>release=resolve);const start=cursor?25:0;const next=cursor?null:Buffer.from(JSON.stringify(nested?{v:2,borrowerId:'private-b-24',rank:1,loanDate:'2026-10-07',id:'private-l-24'}:{v:2,rank:1,createdDate:'2026-10-07',id:'private-b-24'})).toString('base64url');await r.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({ok:true,source:'dev',items:items.slice(start,start+25),item,nextCursor:next,asOf:'2026-10-07T05:00:00Z'})})});
 await page.goto(base);const keys=await page.evaluate(async()=>{const {loanDisplayKey}=await import('/apps/pwa/src/LoanRecords.tsx');const base={borrowerDisplayName:'สมชาย - Somchai',principalAmount:'12000.49',loanDate:'2026-10-07',originalDailyInterestRate:'0'};return[loanDisplayKey(base),loanDisplayKey({...base,principalAmount:null,loanDate:null,originalDailyInterestRate:null,borrowerDisplayName:' - '}),loanDisplayKey({...base,principalAmount:'-12000.50',originalDailyInterestRate:'2'})]});expect(keys).toEqual(['สมชาย - Somchai-฿12,000-07/10-0%',' - ---Unavailable','สมชาย - Somchai--฿12,001-07/10-2%']);await page.getByRole('button',{name:'Continue with Google'}).click();await expect(page.locator('.borrower-card')).toHaveCount(25);await expect(page.locator('.borrower-card').first()).toContainText('-฿12.34');await expect(page.locator('.borrower-card').nth(1)).toContainText('฿0');
 holdNext=true;await page.getByRole('button',{name:'Next borrowers page',exact:true}).click();await expect.poll(()=>Boolean(release)).toBe(true);await expect(page.locator('.list-foot')).toContainText('Loading records');await expect(page.getByRole('button',{name:'Next borrowers page',exact:true})).toBeDisabled();holdNext=false;release!();await expect(page.locator('.borrower-card')).toHaveCount(2);await expect(page.locator('.list-foot')).toContainText('Borrowers page 2 · End of borrower list');await expect(page.getByRole('button',{name:'Next borrowers page',exact:true})).toHaveCount(0);await expect(page.locator('.list-panel .group-unknown')).toContainText('Loan status unavailable');
 await page.getByRole('button',{name:'First borrowers page / refresh'}).click();await expect(page.locator('.borrower-card')).toHaveCount(25);await expect(page.locator('.borrower-card.inactive')).toHaveCSS('background-color','rgb(233, 233, 233)');await expect(page.locator('.borrower-card.inactive')).toBeEnabled();await page.locator('.borrower-card').last().click();await expect(page.locator('.loan-record')).toHaveCount(25);
 const closed=page.locator('.loan-record.closed').first();await expect(closed).toHaveCSS('background-color','rgb(233, 233, 233)');await expect(closed).toHaveCSS('color','rgb(51, 51, 51)');await expect(closed).toBeEnabled();const listScroll=await page.locator('.list-panel').evaluate(e=>e.scrollTop);await page.locator('.loan-record').last().click();await expect(page.getByRole('article',{name:'Loan details'})).toBeVisible();
 const back=page.getByRole('button',{name:'Back to loans'});const box=await back.boundingBox();const pane=await page.locator('.detail-panel').boundingBox();expect(box!.y,'Back to loans must appear immediately, without manually scrolling up').toBeGreaterThanOrEqual(Math.max((await page.locator('.topbar').boundingBox())!.y+(await page.locator('.topbar').boundingBox())!.height,pane!.y));expect(box!.y+box!.height).toBeLessThanOrEqual(Math.min(page.viewportSize()!.height,pane!.y+pane!.height));
 if(info.project.name.startsWith('desktop')){expect(listScroll).toBeGreaterThan(0);expect(await page.locator('.list-panel').evaluate(e=>e.scrollTop)).toBe(listScroll);}
 await expect(page.getByRole('article',{name:'Loan details'})).toContainText('ชื่อผู้กู้ตัวอย่างสำหรับทดสอบข้อความยาว - Synthetic borrower with a deliberately long English name-฿12,024-07/10-2%');await back.click();await expect(page.locator('.loan-record')).toHaveCount(25);await page.getByRole('button',{name:'Next loans page',exact:true}).click();await expect(page.locator('.loan-record')).toHaveCount(2);await expect(page.locator('.related-loans')).toContainText('Loans page 2 · End of loan list');await expect(page.getByRole('button',{name:'Next loans page',exact:true})).toHaveCount(0);await expect(page.locator('.related-loans')).toContainText('Other / unavailable status');{const heading=page.locator('.related-loans-heading');const h=await heading.boundingBox();const d=await page.locator('.detail-panel').boundingBox();expect(h!.y).toBeGreaterThanOrEqual(Math.max((await page.locator('.topbar').boundingBox())!.y+(await page.locator('.topbar').boundingBox())!.height,d!.y));expect(h!.y).toBeLessThan(Math.max((await page.locator('.topbar').boundingBox())!.y+(await page.locator('.topbar').boundingBox())!.height,d!.y)+100);}
 expect(await page.locator('body').innerText()).not.toMatch(/private-[bl]-|THB/);await page.screenshot({path:`outputs/r052-collection-read/COMPACT-${info.project.name}-groups-en.png`,fullPage:true});await chooseLanguage(page,'ไทย');await expect(page.locator('.related-loans')).toContainText('สิ้นสุดรายการสัญญา');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`outputs/r052-collection-read/COMPACT-${info.project.name}-groups-th.png`,fullPage:true});expect(requests.filter(x=>x.includes('cursor=')).length).toBe(2);await chooseLanguage(page,'EN');await page.getByRole('button',{name:'First loans page / refresh',exact:true}).click();await expect(page.locator('.loan-record')).toHaveCount(25);{const heading=page.locator('.related-loans-heading');const h=await heading.boundingBox();const d=await page.locator('.detail-panel').boundingBox();expect(h!.y).toBeGreaterThanOrEqual(Math.max((await page.locator('.topbar').boundingBox())!.y+(await page.locator('.topbar').boundingBox())!.height,d!.y));expect(h!.y).toBeLessThan(Math.max((await page.locator('.topbar').boundingBox())!.y+(await page.locator('.topbar').boundingBox())!.height,d!.y)+100);}
});
