import {chooseLanguage,signOut} from './live-controls';
import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
let server:ChildProcess;let base:string;let serverLog="";
test.beforeAll(async({},info)=>{
 const port=6500+info.workerIndex;base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/playwright-live-${port}-${Date.now()}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-test-key',VITE_FIREBASE_APP_ID:'synthetic-app-id',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app'},stdio:'pipe'});
 server.stdout?.on("data",data=>{serverLog+=String(data)});server.stderr?.on("data",data=>{serverLog+=String(data)});
 await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return0()}},{timeout:20000}).toBe(200);
});
function return0(){return 0}
test.afterAll(()=>server?.kill()); test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)console.log(serverLog)});
const authMock=`let listener;export const browserLocalPersistence='local';export const inMemoryPersistence='memory';export const browserPopupRedirectResolver={};export function initializeAuth(a,o){if(o.persistence!=='local')throw Error('persistence');return {}};export function getAuth(){return {}};export async function setPersistence(a,p){if(p!=='local')throw Error('persistence');}export function onAuthStateChanged(a,fn){listener=fn;fn(null);return()=>{listener=null}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){listener({uid:'synthetic-owner',getIdToken:async()=>'synthetic-bearer'})};export async function signOut(){listener(null)};`;
test.use({timezoneId:'America/Los_Angeles'});
const statuses=['not_paid','partially_paid','overdue','fully_paid'];
const rows=Array.from({length:27},(_,i)=>({id:'private-board-'+i,displayName:'ผู้กู้ตัวอย่าง - Synthetic '+i,status:statuses[Math.min(3,Math.floor(i/7))],amountDue:i>=21?'0':'13.75',amountCollected:i>=21?'0':'3.25',amountRemaining:i>=21?'0':'10.50'}));
const charges=Array.from({length:27},(_,i)=>({id:'private-charge-'+i,loanId:'private-loan',loanDisplayKey:'ผู้กู้ตัวอย่างชื่อยาว - Long synthetic borrower English name-฿12,000-07/10-2%',chargeDate:'2026-10-07',paymentStatus:'ชำระบางส่วน',paymentDate:null,amountRemaining:i===0?null:'10.50',totalPaid:'0',receivedToday:'-2.50'}));


import {mkdirSync} from 'node:fs';

for(const view of ['Borrowers','Collection'])test(view+' live-search debounce composition dedupe and navigation cancellation',async({page},info)=>{
 await page.setViewportSize({width:info.project.name.startsWith('mobile')?320:1440,height:900});
 const records=Array.from({length:30},(_,i)=>({id:'search-'+i,name:i===29?'เป้าหมาย':'ผู้กู้ '+i,borrowerDisplayName:i===29?'เป้าหมาย - Unique Needle':'ผู้กู้ '+i+' - English '+i,displayName:i===29?'เป้าหมาย - Unique Needle':'ผู้กู้ '+i+' - English '+i,hasActiveLoan:true,createdDate:null,outstandingPrincipal:'100',totalProfitEarned:'1',note:null,status:'not_paid',amountDue:'100',amountCollected:'0',amountRemaining:'100'}));
 const root=view==='Borrowers'?'/api/borrowers':'/api/collection',card=view==='Borrowers'?'.borrower-card':'.collection-borrower';const requests:string[]=[];let releaseOld:(()=>void)|undefined,releaseLatest:(()=>void)|undefined;const envelope={ok:true,source:'dev',businessDate:'2026-10-07',asOf:'2026-10-07T05:00:00Z',horizonEnd:'2027-01-07'};
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{const u=new URL(r.request().url());let result:any={...envelope,items:[],nextCursor:null};if(u.pathname===root){requests.push(u.search);const query=u.searchParams.get('q')??'';const filtered=query==='old'?[records[0]]:records.filter(x=>(x.name+' '+x.borrowerDisplayName).toLowerCase().includes(query.toLowerCase()));const start=u.searchParams.has('cursor')?25:0;result={...envelope,items:filtered.slice(start,start+25),nextCursor:filtered.length>start+25?'synthetic-next':null}}else if(u.pathname.endsWith('/charges'))result={...envelope,borrower:records[29],items:[],nextCursor:null};else if(u.pathname.match(/\/search-\d+$/))result={...envelope,item:records.find(x=>u.pathname.endsWith('/'+x.id))};await r.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(result)}).catch(()=>{})});
 await page.goto(base);await page.getByRole('button',{name:'Continue with Google'}).click();if(view==='Collection')await page.getByRole('button',{name:'Collection',exact:true}).click();await expect(page.locator(card)).toHaveCount(25);await expect(page.locator(card)).not.toContainText(['Unique Needle']);const height=(await page.locator('.topbar').boundingBox())!.height;

 await page.clock.install();await page.clock.pauseAt(new Date());await page.getByRole('button',{name:'Search borrowers',exact:true}).click();const input=page.getByRole('searchbox',{name:'Search Thai or English name',exact:true});const submit=page.getByRole('button',{name:'Submit search',exact:true});let before=requests.length;
 await input.fill('Need');await page.clock.runFor(200);await input.fill('Needle');await page.clock.runFor(299);expect(requests.length).toBe(before);await page.clock.runFor(1);await expect(page.locator(card)).toHaveCount(1);expect(requests.length).toBe(before+1);
 before=requests.length;await input.fill(' Needle ');await input.evaluate((el:HTMLInputElement)=>el.setSelectionRange(2,2));await page.clock.runFor(300);expect(requests.length).toBe(before);await expect(input).toHaveValue(' Needle ');expect(await input.evaluate((el:HTMLInputElement)=>el.selectionStart)).toBe(2);
 await input.dispatchEvent('compositionstart');await input.fill('unfinished IME');await page.getByRole('button',{name:'Back from search',exact:true}).click();await page.getByRole('button',{name:'Search borrowers',exact:true}).click();await input.fill('Unique');await page.clock.runFor(300);await expect.poll(()=>requests.length).toBe(before+1);before=requests.length;await input.dispatchEvent('compositionstart');await input.fill('เป้าหมาย');await page.clock.runFor(600);expect(requests.length).toBe(before);await input.dispatchEvent('compositionend',{data:'เป้าหมาย'});await page.clock.runFor(299);expect(requests.length).toBe(before);await page.clock.runFor(1);await expect.poll(()=>requests.length).toBe(before+1);await expect(page.locator(card)).toHaveCount(1);
 before=requests.length;await input.fill('Needle');await input.press('Enter');await expect.poll(()=>requests.length).toBe(before+1);await page.clock.runFor(600);expect(requests.length).toBe(before+1);
 await input.fill('discarded');await page.getByRole('button',{name:'Back from search',exact:true}).click();before=requests.length;await page.clock.runFor(600);expect(requests.length).toBe(before);await page.getByRole('button',{name:'Search borrowers',exact:true}).click();await expect(input).toHaveValue('Needle');
 await page.getByRole('button',{name:'Clear search',exact:true}).click();await expect(page.locator(card)).toHaveCount(25);before=requests.length;await page.clock.runFor(600);expect(requests.length).toBe(before);
 await input.fill('Needle');await page.locator(card).first().click();await page.clock.runFor(600);expect(requests.length).toBe(before);await expect(page.locator('.work-grid')).toHaveClass(/has-detail/);
 await expect(page.getByRole('search')).toHaveCount(0);await page.getByRole('button',{name:'Refresh '+view+' — return to first page',exact:true}).click();await expect(page.locator(card)).toHaveCount(25);await page.getByRole('button',{name:'Search borrowers',exact:true}).click();await input.fill('Needle');before=requests.length;await page.getByRole('button',{name:view==='Borrowers'?'Next borrowers page':'Next Collection page',exact:true}).click();await expect(page.locator(card)).toHaveCount(5);await page.clock.runFor(600);expect(requests.length).toBe(before+1);expect(new URLSearchParams(requests.at(-1)).get('q')).toBeNull();
 await page.getByRole('button',{name:'Search borrowers',exact:true}).click();await input.fill('Needle');before=requests.length;await page.getByRole('button',{name:view==='Borrowers'?'Collection':'Borrowers',exact:true}).click();await page.clock.runFor(600);expect(requests.length).toBe(before);await expect(page.getByRole('search')).toHaveCount(0);
 await page.getByRole('button',{name:view,exact:true}).click();await expect(page.locator(card)).toHaveCount(25);await page.getByRole('button',{name:'Search borrowers',exact:true}).click();await input.fill('Needle');before=requests.length;await page.evaluate(()=>window.dispatchEvent(new Event('offline')));await page.clock.runFor(600);expect(requests.length).toBe(before);await expect(page.getByRole('button',{name:'Reconnect',exact:true})).toBeVisible();
});
