import {test,expect,type Page} from '@playwright/test';
import {chooseLanguage} from './live-controls';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdirSync} from 'node:fs';
let server:ChildProcess,base:string;
test.beforeAll(async({},info)=>{const port=7300+info.workerIndex;base=`http://127.0.0.1:${port}`;server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/phase5-independent-${port}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-key',VITE_FIREBASE_APP_ID:'synthetic-app',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app',VITE_COMMAND_API_ORIGIN:'https://mw-credit-app-command-dev-test.run.app',VITE_COMMAND_MODE:'dev-owner-testing'},stdio:'pipe'});await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return 0}},{timeout:20000}).toBe(200)});
test.afterAll(()=>server?.kill());test.setTimeout(40000);
// Synthetic auth/HTTP seams with real DOM. Does not claim live authentication or durable operation journal.
const auth=`let listener;const user={uid:'phase5-independent-owner',getIdToken:async()=>'synthetic-bearer'};export const browserLocalPersistence='local',inMemoryPersistence='memory',browserPopupRedirectResolver={};export function initializeAuth(){return {}};export function onAuthStateChanged(a,fn){listener=fn;fn(localStorage.getItem('phase5-owner')?user:null);return()=>{}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){localStorage.setItem('phase5-owner','1');listener(user)};export async function signOut(){localStorage.removeItem('phase5-owner');listener(null)};`;
const fields={name:'ผู้กู้จำลองชื่อยาว / Synthetic borrower',description:'English synthetic name',communicationName:'ชื่อที่ใช้ติดต่อ',instagramUsername:'synthetic_instagram',city:'Bangkok',workingLocation:'Synthetic office',address:'บรรทัดหนึ่ง\nline two',hidden:null,referrerId:'C-referrer',preferredReceivingAccountId:'C-account',note:'หมายเหตุ ไทย\n exact note '};
const record={...fields,id:'C-borrower',version:'a'.repeat(64),createdDate:'2026-10-08',aiCollectionEnabled:true,details:{preferredReceivingAccountLabel:'Synthetic receiving account',referrerName:'ผู้แนะนำจำลอง',hasActiveLoan:true,hasClosedLoan:true,totalAmountLoaned:'200',totalInterestEarned:'75',totalNumberOfLoans:2,outstandingPrincipal:'100',activeInterest:'25',activeReturn:'0.25',activeProfit:'-75',coverageDate:'2026-10-10',closedPrincipal:'100',closedInterest:'50',closedReturn:'0.5'}};
const directory={...record,borrowerDisplayName:fields.name,displayName:fields.name,outstandingPrincipal:'100',totalProfitEarned:'75',hasActiveLoan:true};
type State={writes:any[],status:number,lost:boolean,holdOptions:boolean,releaseOptions?:()=>void,holdWrite:boolean,releaseWrite?:()=>void,statusReads:string[],pendingBeforePosts:any[],statusOutcome:string,readRequests:string[],commandReads:string[],loanAccounts:any[],loanRows:any[],expenseItem:any};
async function pending(page:Page){return page.evaluate(async()=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');return ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'phase5-independent-owner'}).list('pending')})}
async function setup(page:Page){const s:State={writes:[],status:200,lost:false,holdOptions:false,holdWrite:false,statusReads:[],pendingBeforePosts:[],statusOutcome:'unresolved',readRequests:[],commandReads:[],loanAccounts:[{id:'C-account',label:'Synthetic Lisa lending account',isDefault:false,holderId:'ch:lisa',active:true,holderActive:true}],loanRows:[],expenseItem:expenseFullC};
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:auth}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',r=>{const path=new URL(r.request().url()).pathname;s.readRequests.push(path);return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'dev',businessDate:'2026-10-08',asOf:'2026-10-08T05:00:00Z',items:path.endsWith('/loans')?s.loanRows:[directory],item:path.includes('/loans/')?s.loanRows[0]:directory,nextCursor:null})})});
 await page.route('https://mw-credit-app-command-dev-test.run.app/**',async r=>{const path=new URL(r.request().url()).pathname,method=r.request().method();if(method==='GET')s.commandReads.push(path);let result:any={ok:true,items:[],nextCursor:null};
  if(path==='/api/preferences'){result={ok:true,item:{language:null}}} else if(path==='/api/expense-options'){if(s.holdOptions)await new Promise<void>(done=>s.releaseOptions=done);result={ok:true,businessDate:'2026-10-09',categories:expenseCategoriesUiC,accounts:[{id:'C-account',label:'Synthetic Dad paying account',holderId:'ch:dad',holderLabel:'Dad'}]}}
  else if(path==='/api/expense-records'){result={ok:true,items:[s.expenseItem],nextCursor:null}}
  else if(path.startsWith('/api/expense-records/')){result={ok:true,item:s.expenseItem}}
  else if(path==='/api/loan-options'){if(s.holdOptions)await new Promise<void>(done=>s.releaseOptions=done);result={ok:true,businessDate:'2026-10-09',accounts:s.loanAccounts}}
  else if(path==='/api/borrower-options'){if(s.holdOptions)await new Promise<void>(done=>s.releaseOptions=done);result={ok:true,accounts:[{id:'C-account',label:'Synthetic receiving account'}],referrers:[{id:'C-referrer',label:'ผู้แนะนำจำลอง'},{id:record.id,label:'Self must not appear'}]}}
  else if(path.endsWith('/close-preview')){if(s.holdOptions)await new Promise<void>(done=>s.releaseOptions=done);result={ok:true,businessDate:'2026-10-09',sourceVersion:loanFullC.version,amount:'115',planHash:'c'.repeat(64),accounts:s.loanAccounts}}
  else if(path.startsWith('/api/loan-records/')&&(path.endsWith('/charges')||path.endsWith('/payments'))){result={ok:true,items:[],nextCursor:null}}else if(path.startsWith('/api/loan-records/')){result={ok:true,item:loanFullC}}
  else if(path.startsWith('/api/payment-drafts/')){result={ok:true,mode:'dev-owner-testing',scope:'all',businessDate:'2026-10-09',asOf:'2026-10-09T05:00:00Z',borrower:{id:record.id,displayName:'Synthetic payment borrower'},accounts:[{id:'C-account',label:'Synthetic receiving account'}],charges:[{id:'C-charge',chargeDate:'2026-10-09',loanDisplayKey:'Synthetic loan',principalRemaining:'10',interestRemaining:'0',amountRemaining:'10'}],nextCursor:null}}
  else if(path.startsWith('/api/payment-commands/')){result={ok:true,kind:'unresolved',safeToUseNewRequestId:false}}
  else if(path.includes('/borrower-records')){expect(method).toBe('GET');result={ok:true,item:record};}
  else if(path==='/api/operations'&&method==='POST'){const body=r.request().postDataJSON();s.writes.push({method,body});s.pendingBeforePosts.push(await pending(page));if(s.holdWrite)await new Promise<void>(done=>s.releaseWrite=done);if(s.lost)return r.abort('failed');result={ok:s.status===200,kind:'recorded',originalOutcome:{status:s.status===200?'applied':'rejected',code:s.status===200?null:'source_conflict',result:s.status===200?{operation:body.operation,targetType:'borrower',targetId:body.targetId,paymentId:null,plan:null,predecessorRequestId:null}:null}};return r.fulfill({status:s.status,contentType:'application/json',body:JSON.stringify(result)}).catch(()=>{});}
  else if(path.startsWith('/api/operations/')){expect(method).toBe('GET');s.statusReads.push(path.split('/').at(-1)!);result=s.statusOutcome==='unresolved'?{ok:true,kind:'unresolved',safeToUseNewRequestId:false}:{ok:true,kind:'recorded',originalOutcome:{status:s.statusOutcome,code:s.statusOutcome==='rejected'?'source_conflict':null,result:null}};}
  if(result.item?.id&&result.item?.version){result.asOf=Date.now();result.businessDate='2026-10-09'}return r.fulfill({contentType:'application/json',body:JSON.stringify(result)}).catch(()=>{});
 });
 await page.route('https://mw-credit-app-command-dev-test.run.app/api/dashboard',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({collection:{notPaid:0,partiallyPaid:0,overdue:0,fullyPaid:0},forecast:{},portfolio:{},incomeMtd:{},businessCashHeld:[]})}));await page.goto(base);await page.getByRole('button',{name:/Google/}).click();await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();return s;
}
async function openSaved(page:Page){if(page.viewportSize()!.width<=1050)await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:'Saved payment drafts',exact:true}).filter({visible:true}).click()}
async function full(page:Page){await page.locator('.borrower-tile-main').click();await expect(page.getByRole('button',{name:'Edit borrower',exact:true})).toBeVisible()}

for(const width of [320,390,1440])test(`F2 borrower ordered fields/read-only metadata and compact geometry ${width}px`,async({page},info)=>{await page.setViewportSize({width,height:900});const s=await setup(page);await page.getByRole('button',{name:'Add borrower',exact:true}).click();const region=page.getByRole('region',{name:'Borrower record',exact:true});await expect(region.getByRole('button',{name:'Save borrower',exact:true})).toBeVisible();
 const labels=await region.locator('form>label').evaluateAll(es=>es.map(e=>e.childNodes[0]?.textContent?.trim()));expect(labels).toEqual(['Borrower Name - Thai','Creation Date','English Name','Preferred Receiving Cash Account','Communication Name','Instagram Username','AI Collection Enabled','City','Working Location','Address','Referrer','Borrower Note','Hide from Borrowers List']);
 await expect(region.getByRole('textbox',{name:/^Creation\ Date(?: \*)?$/})).toHaveCount(0);await expect(region.getByRole('checkbox',{name:'AI Collection Enabled',exact:true})).toHaveCount(0);await expect(region.getByRole('textbox',{name:/phone|document/i})).toHaveCount(0);
 for(const lang of ['EN','ไทย'] as const){await chooseLanguage(page,lang);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(width);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await expect(page.locator('main')).not.toContainText(/Loading|Checking/);mkdirSync('outputs/r052-phase5-completion',{recursive:true});await page.screenshot({path:`outputs/r052-phase5-completion/borrower-form-${info.project.name}-${width}-${lang==='EN'?'en':'th'}.png`})}expect(s.writes).toHaveLength(0);
});

test('F2 full detail groups precede contact fields, exact notes/referrer and related navigation remain available',async({page})=>{const s=await setup(page);await full(page);const region=page.getByRole('region',{name:'Borrower record',exact:true});await expect(region).toContainText('Active Loans');await expect(region).toContainText('Closed Loans');await expect(region).toContainText('ผู้แนะนำจำลอง');await expect(region).toContainText(fields.note.trim());const order=await region.evaluate(e=>{const nodes=Array.from(e.querySelectorAll('h3,label'));return nodes.map(n=>n.textContent||'')});expect(order.findIndex(t=>t==='Active Loans')).toBeLessThan(order.findIndex(t=>t.startsWith('Communication Name')));await expect(region.getByRole('region',{name:'Related loans',exact:true})).toBeVisible();expect(s.writes).toHaveLength(0)});

test('F1 durable CAS rejection preserves exact edit, header-only busy and persisted-before-POST payload',async({page})=>{const s=await setup(page);await full(page);await page.getByRole('button',{name:'Edit borrower',exact:true}).click();await expect(page.getByRole('option',{name:'Self must not appear',exact:true})).toHaveCount(0);await page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/}).fill('new exact ไทย');s.status=422;s.holdWrite=true;await page.getByRole('button',{name:'Save borrower',exact:true}).click();await expect.poll(()=>!!s.releaseWrite).toBe(true);await expect(page.locator('.topbar .collection-update')).toContainText('Loading');await expect(page.locator('main')).not.toContainText(/Loading|Checking|Saving/);await expect(page.getByRole('button',{name:'Save borrower',exact:true})).toBeDisabled();const command=s.writes[0].body;expect(command).toMatchObject({operation:'borrower.update',targetId:record.id,expectedVersion:record.version,predecessorRequestId:null,receiptId:null,inputs:{note:'new exact ไทย',hidden:null}});expect(s.pendingBeforePosts[0]).toHaveLength(1);expect(s.pendingBeforePosts[0][0].value).toEqual({domain:'borrower',command});s.releaseWrite!();await expect(page.getByText('The record changed. Reload it before editing again.',{exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/})).toHaveValue('new exact ไทย');await expect.poll(async()=>(await pending(page)).length).toBe(0);expect(s.writes).toHaveLength(1);await page.getByRole('button',{name:'Check current borrower',exact:true}).click();await expect(page.getByRole('button',{name:'Edit borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(1)});

test('F1 durable Unknown is immutable across reload and saved-workspace GET-only status recovery',async({page})=>{const s=await setup(page);await full(page);await page.getByRole('button',{name:'Edit borrower',exact:true}).click();await page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/}).fill('unknown attempt ไทย');s.lost=true;await page.getByRole('button',{name:'Save borrower',exact:true}).click();await expect(page.getByText('Outcome unknown. Check this request before making another change.',{exact:true})).toBeVisible();const command=s.writes[0].body;await expect(page.getByText(command.requestId,{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Edit borrower',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Save borrower',exact:true})).toHaveCount(0);expect((await pending(page))[0].value).toEqual({domain:'borrower',command});await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(1);expect(s.statusReads).toHaveLength(0);await openSaved(page);await page.getByRole('button',{name:/^Pending borrower change/}).click();await expect(page.getByText(command.requestId,{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save borrower',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Check current borrower',exact:true}).click();await expect.poll(()=>s.statusReads.length).toBe(1);await expect(page.getByText('Outcome unknown. Check this request before making another change.',{exact:true})).toBeVisible();expect((await pending(page))[0].value).toEqual({domain:'borrower',command});expect(s.writes).toHaveLength(1);s.statusOutcome='applied';await page.getByRole('button',{name:'Check current borrower',exact:true}).click();await expect.poll(async()=>(await pending(page)).length).toBe(0);expect(s.statusReads).toEqual([command.requestId,command.requestId]);expect(s.writes).toHaveLength(1)});

test('F12 pending storage failure sends no operation and leaves exact unsent fields editable',async({page})=>{const s=await setup(page);await full(page);await page.getByRole('button',{name:'Edit borrower',exact:true}).click();await page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/}).fill('not sent ไทย');await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;(window as any).originalPut=original;IDBObjectStore.prototype.put=function(value:any,...rest:any[]){if(value.kind==='pending')throw new DOMException('Synthetic quota','QuotaExceededError');return original.call(this,value,...rest)}});await page.getByRole('button',{name:'Save borrower',exact:true}).click();await expect(page.getByText('Request was not sent. Device storage is unavailable or full.',{exact:true})).toBeVisible();expect(s.writes).toHaveLength(0);expect(await pending(page)).toHaveLength(0);await expect(page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/})).toHaveValue('not sent ไทย');await expect(page.getByRole('button',{name:'Save borrower',exact:true})).toBeEnabled();await page.evaluate(()=>{IDBObjectStore.prototype.put=(window as any).originalPut});});

test('F12 restored Unknown rejection never silently rebases original CAS or retries dispatch',async({page})=>{const s=await setup(page);await full(page);await page.getByRole('button',{name:'Edit borrower',exact:true}).click();await page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/}).fill('preserved rejected draft');s.lost=true;await page.getByRole('button',{name:'Save borrower',exact:true}).click();await expect(page.getByText('Outcome unknown. Check this request before making another change.',{exact:true})).toBeVisible();const command=s.writes[0].body;await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();await openSaved(page);await page.getByRole('button',{name:/^Pending borrower change/}).click();s.statusOutcome='rejected';await page.getByRole('button',{name:'Check current borrower',exact:true}).click();await expect(page.getByText('The record changed. Reload it before editing again.',{exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/})).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit borrower',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'Borrower record',exact:true})).toContainText('preserved rejected draft');await expect.poll(async()=>(await pending(page)).length).toBe(0);expect(s.writes).toHaveLength(1);expect(command.expectedVersion).toBe(record.version);await page.getByRole('button',{name:'Check current borrower',exact:true}).click();await expect(page.getByRole('button',{name:'Edit borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(1)});


test('F12 mixed borrower pending cannot hijack receiving; missing-domain legacy payment pending uses its own status path',async({page})=>{
 const s=await setup(page),borrowerId='96f563ae-a2b7-49b4-9bdd-d3af9b773032',paymentId='197967d0-2334-4a24-8b5e-60f1a2fc1c1d';const borrowerCommand={requestId:borrowerId,operation:'borrower.update',targetId:record.id,expectedVersion:record.version,predecessorRequestId:null,inputs:fields,receiptId:null};
 await page.evaluate(async({id,command})=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');await ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'phase5-independent-owner'}).savePending(id,{domain:'borrower',command})},{id:borrowerId,command:borrowerCommand});
 await page.route('https://mw-credit-app-read-dev-test.run.app/api/collection**',r=>{const path=new URL(r.request().url()).pathname;const borrower={id:record.id,displayName:fields.name,status:'not_paid',amountDue:'10',amountCollected:'0',amountRemaining:'10'};return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'dev',timezone:'Asia/Bangkok',horizonEnd:'2027-01-09',reviewRequired:false,businessDate:'2026-10-09',asOf:new Date().toISOString(),borrower,items:path.endsWith('/upcoming')?[]:path.endsWith('/charges')?[{id:'C-charge',chargeDate:'2026-10-09',amountRemaining:'10',totalPaid:'0',receivedToday:'0'}]:[borrower],nextCursor:null})})});await page.getByRole('button',{name:'Collection',exact:true}).filter({visible:true}).click();await page.locator('.collection-tile-main').click();await page.getByRole('button',{name:'Receive selected charges',exact:true}).click();await expect(page.getByRole('textbox',{name:/^Amount\ received(?: \*)?$/})).toBeVisible();expect(s.writes).toHaveLength(0);expect(s.statusReads).toHaveLength(0);expect(s.commandReads.some(path=>path.includes('undefined'))).toBe(false);
 await page.getByRole('button',{name:'Back to Collection',exact:true}).click();const paymentCommand={schemaVersion:6,requestId:paymentId,borrowerId:record.id,allocations:[{chargeId:'C-charge',principal:'10',interest:'0',expectedPrincipalRemaining:'10',expectedInterestRemaining:'0',chargeDate:'2026-10-09'}],cashAccountId:'C-account',paymentDate:'2026-10-09',amountReceived:'10',paymentMethod:'Cash',notes:'legacy missing domain',receiptId:null};await page.evaluate(async({id,command})=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');await ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'phase5-independent-owner'}).savePending(id,command)},{id:paymentId,command:paymentCommand});
 await page.getByRole('button',{name:'Receive selected charges',exact:true}).click();await expect(page.getByRole('button',{name:'Check status',exact:true})).toBeVisible();await page.getByRole('button',{name:'Check status',exact:true}).click();await expect.poll(()=>s.commandReads.some(path=>path==='/api/payment-commands/'+paymentId)).toBe(true);expect(s.statusReads).toHaveLength(0);expect(s.writes).toHaveLength(0);const retained=await pending(page);expect(retained).toHaveLength(2);expect(retained.find(row=>row.value.domain==='borrower')!.value).toEqual({domain:'borrower',command:borrowerCommand});expect(retained.find(row=>row.value.requestId===paymentId)!.value).toEqual(paymentCommand);
});


async function openPendingLabelC(page:Page,saved:any){const label=saved.borrowerLabel??'Pending change';const row=page.getByRole('region',{name:'Saved offline payment drafts',exact:true}).getByRole('button').filter({hasText:label+' ·'});await expect(row).toHaveCount(1);await row.click()}
async function loanForm(page:Page){await page.locator('.borrower-tile-main').click();await page.getByRole('button',{name:'New loan',exact:true}).click();await expect(page.getByRole('button',{name:'Save loan',exact:true})).toBeEnabled()}
function loanMoneyC(page:Page,label:string){return page.locator('label').filter({has:page.locator('.field-title').filter({hasText:new RegExp('^'+label+'$')})}).getByRole('spinbutton')}
async function loanValues(page:Page){await loanMoneyC(page,'Principal Amount').fill('100.25');await loanMoneyC(page,'Transfer Fee').fill('2.25');await page.getByRole('combobox',{name:/^Disbursing\ Cash\ Account(?: \*)?$/}).selectOption('C-account');await page.getByRole('radio',{name:'Daily interest',exact:true}).check();await page.getByRole('spinbutton',{name:/^Current\ Daily\ Interest(?: \*)?$/}).fill('5.25');await page.getByRole('textbox',{name:/^Loan\ Arrangement(?: \*)?$/}).fill('exact ไทย arrangement')}

test('F4 UI three loan types preserve conditional source fields and strict320 EN/Thai input geometry',async({page},info)=>{await page.setViewportSize({width:320,height:900});const s=await setup(page);await loanForm(page);const region=page.getByRole('region',{name:'Loan form',exact:true});await expect(page.getByLabel(/^Loan\ Date(?: \*)?$/)).toHaveValue('2026-10-09');await expect(page.getByRole('checkbox',{name:'Auto Charge Enabled',exact:true})).toBeChecked();await loanValues(page);await expect(page.getByRole('spinbutton',{name:/^Interest\ Payment\ Interval(?: \*)?$/})).toHaveValue('1');await expect(page.getByLabel(/^Due\ Date(?: \*)?$/)).toHaveCount(0);await expect(region).toContainText('Interest Schedule Anchor Date');
 await page.getByRole('radio',{name:'Daily instalment',exact:true}).check();await expect(page.getByLabel(/^Due\ Date(?: \*)?$/)).toBeVisible();await expect(page.getByRole('spinbutton',{name:/^Daily\ Payment\ Amount(?: \*)?$/})).toBeVisible();await expect(page.getByRole('spinbutton',{name:/^Current\ Daily\ Interest(?: \*)?$/})).toHaveCount(0);
 await page.getByRole('radio',{name:'Fixed due date',exact:true}).check();await expect(page.getByRole('spinbutton',{name:/^Fixed\ Interest(?: \*)?$/})).toBeVisible();await expect(page.getByRole('spinbutton',{name:/^Interest\ Payment\ Interval(?: \*)?$/})).toHaveCount(0);await expect(page.getByRole('spinbutton',{name:/^Daily\ Payment\ Amount(?: \*)?$/})).toHaveCount(0);
 for(const language of ['EN','ไทย'] as const){await chooseLanguage(page,language);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);await expect(page.locator('main')).not.toContainText(/Loading|Checking|Saving/);await page.screenshot({path:`outputs/r052-phase5-completion/loan-form-${info.project.name}-320-${language==='EN'?'en':'th'}.png`})}expect(s.writes).toHaveLength(0)});

test('F4 UI loan pending is stored before POST and immutable reload recovery uses only its UUID GET',async({page})=>{const s=await setup(page);await loanForm(page);await loanValues(page);s.lost=true;await page.getByRole('button',{name:'Save loan',exact:true}).click();await expect(page.getByRole('button',{name:'Check loan request',exact:true})).toBeVisible();const command=s.writes[0].body;expect(command).toMatchObject({operation:'loan.create',expectedVersion:null,predecessorRequestId:null,receiptId:null,inputs:{borrowerId:record.id,loanDate:'2026-10-09',principal:'100.25',transferFee:'2.25',currentDailyInterest:'5.25',arrangement:'exact ไทย arrangement',autoChargeEnabled:true}});expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain:'loan',command});const stored=(await pending(page))[0].value;await expect(page.getByRole('button',{name:'Save loan',exact:true})).toHaveCount(0);await expect(loanMoneyC(page,'Principal Amount')).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(1);expect(s.statusReads).toHaveLength(0);await openSaved(page);await openPendingLabelC(page,stored);await page.getByRole('button',{name:'Check loan request',exact:true}).click();await expect.poll(()=>s.statusReads).toEqual([command.requestId]);expect(s.writes).toHaveLength(1);expect((await pending(page))[0].value).toEqual(stored)});


test('F12 loan pending storage failure sends nothing and retains exact editable source fields',async({page})=>{const s=await setup(page);await loanForm(page);await loanValues(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;(window as any).originalPut=original;IDBObjectStore.prototype.put=function(value:any,...rest:any[]){if(value.kind==='pending')throw new DOMException('Synthetic quota','QuotaExceededError');return original.call(this,value,...rest)}});await page.getByRole('button',{name:'Save loan',exact:true}).click();await expect(page.getByText('Request not sent. Device storage is unavailable or full.',{exact:true})).toBeVisible();expect(s.writes).toHaveLength(0);expect(await pending(page)).toHaveLength(0);await expect(loanMoneyC(page,'Principal Amount')).toHaveValue('100.25');await expect(page.getByRole('textbox',{name:/^Loan\ Arrangement(?: \*)?$/})).toHaveValue('exact ไทย arrangement');await expect(page.getByRole('button',{name:'Save loan',exact:true})).toBeEnabled();await page.evaluate(()=>{IDBObjectStore.prototype.put=(window as any).originalPut});});


test('F2 loan account default uses exact holder/active metadata and multiline terms remain compact',async({page})=>{await page.setViewportSize({width:320,height:900});const s=await setup(page);await page.locator('.borrower-tile-main').click();const base={id:'C-account',label:'Synthetic default Lisa',isDefault:true,holderId:'ch:lisa',active:true,holderActive:true};for(const [accounts,expected] of [[[base],'C-account'],[[{...base,isDefault:false}],''],[[base,{...base,id:'C-second'}],''],[[{...base,active:false}],''],[[{...base,holderId:'ch:dad'}],'']] as const){s.loanAccounts=[...accounts];await page.getByRole('button',{name:'New loan',exact:true}).click();await expect(page.getByRole('button',{name:'Save loan',exact:true})).toBeEnabled();await expect(page.getByRole('combobox',{name:/^Disbursing\ Cash\ Account(?: \*)?$/})).toHaveValue(expected);const terms=page.getByRole('textbox',{name:/^Loan\ Arrangement(?: \*)?$/});expect(await terms.evaluate(e=>e.tagName)).toBe('TEXTAREA');await terms.fill('line one\nไทย line two');await expect(terms).toHaveValue('line one\nไทย line two');expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320);await page.getByRole('button',{name:'Back to loan details',exact:true}).click()}expect(s.writes).toHaveLength(0)});


const loanFullC={id:'C-loan',version:'b'.repeat(64),borrowerId:record.id,borrowerDisplayName:'Synthetic loan borrower',loanDate:'2026-10-06',principal:'100',transferFee:'2',disbursingAccountId:'C-account',disbursingAccountLabel:'Synthetic Lisa account',type:'ดอกเบี้ยรายวัน',dueDate:null,dailyPayment:null,fixedInterest:null,currentDailyInterest:'5',originalRate:5,paymentInterval:1,scheduleAnchor:'2026-10-06',arrangement:'source terms\nไทย',autoChargeEnabled:true,status:'ยังไม่ปิดยอด',defaulted:false,closeDate:null,defaultLoss:null,outstandingPrincipal:'100',principalReceived:'0',interestReceived:'7',amountReceived:'7'};
async function fullLoan(page:Page,s:State){s.loanRows=[{id:'C-loan',borrowerId:record.id,borrowerDisplayName:'Synthetic loan borrower',originalDailyInterestRate:'5',loanDate:'2026-10-06',dueDate:null,closeDate:null,loanType:'ดอกเบี้ยรายวัน',status:'ยังไม่ปิดยอด',principalAmount:'100',outstandingPrincipal:'100',totalPrincipalReceived:'0',totalInterestReceived:'7',totalAmountReceived:'7',defaulted:false,autoChargeEnabled:true}];await page.locator('.borrower-tile-main').click();await page.locator('.loan-record').click();await expect(page.getByRole('button',{name:'Edit loan',exact:true})).toBeVisible()}

test('F6 action held-options double click cannot change confirmation label or payload; only header announces activity',async({page})=>{const s=await setup(page);await fullLoan(page,s);s.holdOptions=true;await page.getByRole('button',{name:'Default Loan',exact:true}).click();await expect.poll(()=>!!s.releaseOptions).toBe(true);await expect(page.getByRole('button',{name:'Generate Charges',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Edit loan',exact:true})).toBeDisabled();await expect(page.locator('.topbar .collection-update')).toContainText('Loading');await expect(page.locator('main')).not.toContainText(/Loading|Checking|Saving/);expect(s.commandReads.filter(p=>p==='/api/loan-options')).toHaveLength(1);s.releaseOptions!();await expect(page.getByRole('heading',{name:'Default Loan',exact:true})).toBeVisible();await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect.poll(()=>s.writes.length).toBe(1);expect(s.writes[0].body).toMatchObject({operation:'loan.default',targetId:loanFullC.id,expectedVersion:loanFullC.version,inputs:{businessDate:'2026-10-09'}});expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain:'loan',recoveryKind:'action',command:s.writes[0].body})});

test('F12 loan action Unknown survives reload and explicit retry keeps identical UUID after status read',async({page})=>{const s=await setup(page);await fullLoan(page,s);await page.getByRole('button',{name:'Generate Charges',exact:true}).click();await expect(page.getByRole('heading',{name:'Generate Charges',exact:true})).toBeVisible();s.lost=true;await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByRole('button',{name:'Check request',exact:true})).toBeVisible();await expect.poll(()=>s.writes.length).toBe(1);await expect.poll(()=>s.pendingBeforePosts.length).toBe(1);const cmd=s.writes[0].body;expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain:'loan',recoveryKind:'action',command:cmd});await expect(page.getByRole('button',{name:'Retry same request',exact:true})).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(1);expect(s.statusReads).toHaveLength(0);await openSaved(page);await openPendingLabelC(page,s.pendingBeforePosts[0][0].value);await expect(page.getByRole('button',{name:'Save loan',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Check request',exact:true}).click();await expect.poll(()=>s.statusReads).toEqual([cmd.requestId]);await expect(page.getByRole('button',{name:'Retry same request',exact:true})).toBeVisible();s.lost=false;await page.getByRole('button',{name:'Retry same request',exact:true}).click();await expect.poll(()=>s.writes.length).toBe(2);expect(s.writes[1].body).toEqual(cmd);await expect.poll(async()=>(await pending(page)).length).toBe(0)});


test('F6 close UI preview is read-only/header-only and exact choices freeze before persistent dispatch',async({page})=>{await page.setViewportSize({width:320,height:900});const s=await setup(page);await fullLoan(page,s);s.holdOptions=true;await page.getByRole('button',{name:'Close Loan',exact:true}).click();await expect.poll(()=>!!s.releaseOptions).toBe(true);await expect(page.locator('.topbar .collection-update')).toContainText('Loading');await expect(page.locator('main')).not.toContainText(/Loading|Checking|Saving/);expect(s.writes).toHaveLength(0);s.holdOptions=false;s.releaseOptions!();await expect(page.getByRole('button',{name:'Review close',exact:true})).toBeDisabled();await expect(page.getByRole('combobox',{name:/^Payment\ Method(?: \*)?$/}).locator('option')).toHaveText(['Bank Transfer','Cash','Net-off at Disbursement']);await page.getByRole('combobox',{name:/^Receiving\ account(?: \*)?$/}).selectOption('C-account');await page.getByRole('combobox',{name:/^Payment\ Method(?: \*)?$/}).selectOption('Cash');await page.getByRole('textbox',{name:/^Notes(?: \*)?$/}).fill('close note\nไทย exact');for(const language of ['EN','ไทย'] as const){await chooseLanguage(page,language);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)}await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Review close',exact:true}).click();expect(s.writes).toHaveLength(0);await expect(page.getByRole('button',{name:'Confirm',exact:true})).toBeVisible();s.lost=true;await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByRole('button',{name:'Check request',exact:true})).toBeVisible();await expect.poll(()=>s.writes.length).toBe(1);await expect.poll(()=>s.pendingBeforePosts.length).toBe(1);const cmd=s.writes[0].body;expect(cmd).toMatchObject({operation:'loan.close',targetId:'C-loan',expectedVersion:loanFullC.version,receiptId:null,inputs:{paymentDate:'2026-10-09',cashAccountId:'C-account',paymentMethod:'Cash',notes:'close note\nไทย exact',expectedAmount:'115',expectedPlanHash:'c'.repeat(64)}});expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain:'loan',recoveryKind:'action',command:cmd});await expect(page.getByRole('combobox',{name:/^Receiving\ account(?: \*)?$/})).toHaveCount(0);expect(s.writes).toHaveLength(1)});

test('F7 charge UI preserves exact signed decimals and multiline notes behind explicit confirmation',async({page})=>{await page.setViewportSize({width:320,height:900});const s=await setup(page);await fullLoan(page,s);s.holdOptions=true;await page.getByRole('button',{name:'New charge',exact:true}).click();await expect.poll(()=>!!s.releaseOptions).toBe(true);await expect(page.getByRole('button',{name:'Review change',exact:true})).toBeDisabled();await expect(page.locator('.topbar .collection-update')).toContainText('Loading');await expect(page.locator('main')).not.toContainText(/Loading|Checking|Saving/);s.releaseOptions!();await expect(page.getByLabel(/^Charge\ Date(?: \*)?$/)).toHaveValue('2026-10-09');await page.getByRole('spinbutton',{name:/^Principal\ Due(?: \*)?$/}).fill('12.25');await page.getByRole('spinbutton',{name:/^Interest\ Due(?: \*)?$/}).fill('-1.25');await page.getByRole('textbox',{name:/^Notes(?: \*)?$/}).fill('charge note\nไทย exact');for(const language of ['EN','ไทย'] as const){await chooseLanguage(page,language);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320)}await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Review change',exact:true}).click();expect(s.writes).toHaveLength(0);await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect.poll(()=>s.writes.length).toBe(1);expect(s.writes[0].body).toMatchObject({operation:'charge.create',expectedVersion:null,receiptId:null,inputs:{loanId:'C-loan',chargeDate:'2026-10-09',principalDue:'12.25',interestDue:'-1.25',notes:'charge note\nไทย exact'}});expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain:'charge',recoveryKind:'action',command:s.writes[0].body})});



const expenseCategoriesUiC=['Collection Cost / ค่าใช้จ่ายติดตามหนี้','Transportation / ค่าเดินทาง','Bank / Transfer Fee / ค่าธรรมเนียมธนาคารและโอนเงิน','Software / Subscription / ค่าซอฟต์แวร์และสมาชิก','Other / อื่น ๆ','Referral Rebate / เงินคืนค่าแนะนำลูกค้า'];
const expenseFullC={id:'C-expense',version:'d'.repeat(64),expenseDate:'2026-10-09',category:expenseCategoriesUiC[4],amount:'10.00',payeeName:'Synthetic expense payee',payeeBorrowerId:null,payeeBorrowerLabel:null,relatedBorrowerId:null,relatedBorrowerLabel:null,relatedLoanId:null,relatedLoanLabel:null,notes:'source expense note',paidByAccountId:'C-account',paidByAccountLabel:'Synthetic Dad paying account',paidByHolderId:'ch:dad',paidByHolderLabel:'Dad',sourceType:'Manual',sourceKey:null,grossProfitBasis:null,allocationBasis:'Expense Date Contribution Ratio',partnerAShare:'0.6',partnerBShare:'0.4',partnerAExpense:'6.00',partnerBExpense:'4.00',ruleVersion:null,createdAt:'2026-10-09 12:00:00',createdBy:'synthetic-origin@example.invalid',canEdit:true,canDelete:true,reimbursements:[]};
async function openExpensesC(page:Page){if(page.viewportSize()!.width<=1050)await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:'Expenses',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add expense',exact:true})).toBeVisible()}
async function expenseValuesUiC(page:Page){await page.getByRole('combobox',{name:/^Expense\ Category(?: \*)?$/}).selectOption(expenseCategoriesUiC[4]);await page.getByRole('textbox',{name:/^Amount(?: \*)?$/}).fill('12');await page.getByRole('textbox',{name:/^Payee\ Name(?: \*)?$/}).fill('exact synthetic payee');await page.getByRole('textbox',{name:/^Notes(?: \*)?$/}).fill('expense note ไทย');await page.getByRole('combobox',{name:/^Paid\ By\ Cash\ Account(?: \*)?$/}).selectOption('C-account')}
async function draftsC(page:Page){return page.evaluate(async()=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');return ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'phase5-independent-owner'}).list('draft')})}

test('F10 UI 10.00 source amount roundtrips through Notes-only edit with all8 fields and strict320 EN/Thai',async({page})=>{await page.setViewportSize({width:320,height:900});const s=await setup(page);await openExpensesC(page);await page.locator('.borrower-card').click();await expect(page.getByRole('button',{name:'Edit expense',exact:true})).toBeVisible();await expect(page.locator('main')).toContainText('Expense Date Contribution Ratio');await expect(page.locator('main')).toContainText('synthetic-origin@example.invalid');s.holdOptions=true;await page.getByRole('button',{name:'Edit expense',exact:true}).click();await expect.poll(()=>!!s.releaseOptions).toBe(true);await expect(page.locator('.topbar .collection-update')).toContainText('Loading');await expect(page.locator('main')).not.toContainText(/Loading|Checking|Saving/);s.releaseOptions!();await expect(page.getByRole('textbox',{name:/^Amount(?: \*)?$/})).toHaveValue('10');await expect(page.getByLabel(/^Expense\ Date(?: \*)?$/)).toBeVisible();for(const label of ['Expense Category','Related Loan','Paid By Cash Account'])await expect(page.getByRole('combobox',{name:new RegExp('^'+label+'(?: \\*)?$')})).toBeVisible();for(const label of ['Amount','Payee Name','Notes'])await expect(page.getByRole('textbox',{name:new RegExp('^'+label+'(?: \\*)?$')})).toBeVisible();await expect(page.getByRole('textbox',{name:/^Find\ borrower(?: \*)?$/})).toBeVisible();await expect(page.getByRole('combobox',{name:/^Expense\ Category(?: \*)?$/}).locator('option')).toHaveText(['—',...expenseCategoriesUiC]);await page.getByRole('textbox',{name:/^Notes(?: \*)?$/}).fill('metadata only ไทย');for(const language of ['EN','ไทย'] as const){await chooseLanguage(page,language);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)}await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Review',exact:true}).click();expect(s.writes).toHaveLength(0);await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect.poll(()=>s.writes.length).toBe(1);expect(s.writes[0].body).toMatchObject({operation:'expense.update',targetId:'C-expense',expectedVersion:expenseFullC.version,inputs:{amount:'10',notes:'metadata only ไทย'}});expect(Object.keys(s.writes[0].body.inputs).sort()).toEqual(['amount','category','expenseDate','notes','paidByAccountId','payeeName','relatedBorrowerId','relatedLoanId'].sort());expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain:'expense',command:s.writes[0].body})});

test('F10 UI generated expense is full read-only detail with original payee and no edit/delete controls',async({page})=>{const s=await setup(page);s.expenseItem={...expenseFullC,sourceType:'Referral Rebate',sourceKey:'REFERRAL_REBATE:C-loan',payeeBorrowerId:'C-original-referrer',payeeBorrowerLabel:'Renamed original referrer',payeeName:'Original captured payee',grossProfitBasis:'100.00',ruleVersion:'REFERRAL_REBATE_V1',canEdit:false,canDelete:false};await openExpensesC(page);await page.locator('.borrower-card').click();await expect(page.locator('main')).toContainText('Original captured payee');await expect(page.locator('main')).toContainText('REFERRAL_REBATE_V1');await expect(page.locator('main')).toContainText('Referral Rebate');await expect(page.getByRole('button',{name:'Edit expense',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Delete expense',exact:true})).toHaveCount(0);expect(s.writes).toHaveLength(0)});

test('F12 expense quiet unsent draft survives reload then immutable Unknown recovery never automatically posts',async({page})=>{const s=await setup(page);await openExpensesC(page);await page.getByRole('button',{name:'Add expense',exact:true}).click();await expenseValuesUiC(page);await expect.poll(async()=>(await draftsC(page)).filter(r=>r.value.domain==='expense').length).toBe(1);const row=(await draftsC(page))[0];expect(row.value.draft.fields.amount).toBe('12');await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();await openSaved(page);await page.getByRole('button',{name:/^Expense draft/}).click();await expect(page.getByRole('textbox',{name:/^Amount(?: \*)?$/})).toHaveValue('12');await expect(page.getByRole('textbox',{name:/^Notes(?: \*)?$/})).toHaveValue('expense note ไทย');expect(s.writes).toHaveLength(0);await page.getByRole('button',{name:'Review',exact:true}).click();s.lost=true;await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByRole('button',{name:'Check request',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Back to details',exact:true})).toBeDisabled();await expect.poll(()=>s.pendingBeforePosts.length).toBe(1);expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain:'expense',command:s.writes[0].body});await expect.poll(async()=>(await draftsC(page)).filter(r=>r.value.domain==='expense').length).toBe(0);const command=s.writes[0].body;await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(1);expect(s.statusReads).toHaveLength(0);await openSaved(page);await page.getByRole('button',{name:/^Review expense/}).click();await page.getByRole('button',{name:'Check request',exact:true}).click();await expect.poll(()=>s.statusReads).toEqual([command.requestId]);expect(s.writes).toHaveLength(1)});

test('F12 expense pending quota failure sends nothing and retains the unsent draft',async({page})=>{const s=await setup(page);await openExpensesC(page);await page.getByRole('button',{name:'Add expense',exact:true}).click();await expenseValuesUiC(page);await expect.poll(async()=>(await draftsC(page)).length).toBe(1);await page.getByRole('button',{name:'Review',exact:true}).click();await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;(window as any).originalPut=original;IDBObjectStore.prototype.put=function(value:any,...rest:any[]){if(value.kind==='pending')throw new DOMException('Synthetic quota','QuotaExceededError');return original.call(this,value,...rest)}});await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByText('Request not sent. Device storage is unavailable or full.',{exact:true})).toBeVisible();expect(s.writes).toHaveLength(0);expect(await pending(page)).toHaveLength(0);expect(await draftsC(page)).toHaveLength(1);await page.evaluate(()=>{IDBObjectStore.prototype.put=(window as any).originalPut})});


test('F12 expense unsent autosave shares the global five-draft limit and cannot evict a pending request',async({page})=>{const s=await setup(page);await page.evaluate(async()=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts'),repo=ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'phase5-independent-owner'});for(const [i,domain] of ['borrower','loan','charge','preference','payment'].entries())await repo.saveDraft('synthetic-'+i,{domain,label:'Synthetic retained '+domain,draft:{id:'synthetic-'+i}});await repo.savePending('synthetic-retained-pending',{domain:'borrower',command:{requestId:'ec7d0be2-2607-49c7-8bc7-5cda99485710',operation:'borrower.update'}})});const originals=await draftsC(page),retained=await pending(page);await openExpensesC(page);await page.getByRole('button',{name:'Add expense',exact:true}).click();await expenseValuesUiC(page);await expect(page.getByText('Draft could not be saved. Device storage is unavailable or full.',{exact:true})).toBeVisible();expect(await draftsC(page)).toEqual(originals);expect(await pending(page)).toEqual(retained);expect(s.writes).toHaveLength(0);await expect(page.getByRole('textbox',{name:/^Amount(?: \*)?$/})).toHaveValue('12')});

test('F12 purged owner namespace cannot be repopulated by a late expense autosave',async({page})=>{const s=await setup(page);await openExpensesC(page);await page.getByRole('button',{name:'Add expense',exact:true}).click();await expenseValuesUiC(page);await expect.poll(async()=>(await draftsC(page)).length).toBe(1);await page.getByRole('textbox',{name:/^Notes(?: \*)?$/}).fill('late queued draft');await page.evaluate(async()=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');await ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'phase5-independent-owner'}).purge()});await expect(page.getByText('Draft could not be saved. Device storage is unavailable or full.',{exact:true})).toBeVisible();expect(await draftsC(page)).toHaveLength(0);expect(await pending(page)).toHaveLength(0);expect(s.writes).toHaveLength(0)});

for(const domain of ['borrower','loan','charge'] as const)test(`F12 ${domain} unsent exact reload converts to immutable pending before explicit POST`,async({page})=>{const s=await setup(page);if(domain==='borrower'){await full(page);await page.getByRole('button',{name:'Edit borrower',exact:true}).click();await page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/}).fill('saved borrower exact ไทย')}else if(domain==='loan'){await loanForm(page);await loanValues(page)}else{await fullLoan(page,s);await page.getByRole('button',{name:'New charge',exact:true}).click();await expect(page.getByLabel(/^Charge\ Date(?: \*)?$/)).toHaveValue('2026-10-09');await page.getByRole('spinbutton',{name:/^Principal\ Due(?: \*)?$/}).fill('12.25');await page.getByRole('spinbutton',{name:/^Interest\ Due(?: \*)?$/}).fill('-1.25');await page.getByRole('textbox',{name:/^Notes(?: \*)?$/}).fill('saved charge exact ไทย')}
 await expect.poll(async()=>(await draftsC(page)).filter(r=>r.value.domain===domain).length).toBe(1);const saved=(await draftsC(page)).find(r=>r.value.domain===domain)!;expect(s.writes).toHaveLength(0);await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(0);expect(s.statusReads).toHaveLength(0);await openSaved(page);const workspace=page.getByRole('region',{name:'Saved offline payment drafts',exact:true});const row=workspace.getByRole('button').filter({hasText:saved.value.label});await expect(row).toHaveCount(1);await row.click();
 if(domain==='borrower'){await expect(page.getByRole('textbox',{name:/^Borrower\ Note(?: \*)?$/})).toHaveValue('saved borrower exact ไทย')}else if(domain==='loan'){await expect(loanMoneyC(page,'Principal Amount')).toHaveValue('100.25');await expect(page.getByRole('textbox',{name:/^Loan\ Arrangement(?: \*)?$/})).toHaveValue('exact ไทย arrangement')}else{await expect(page.getByRole('spinbutton',{name:/^Principal\ Due(?: \*)?$/})).toHaveValue('12.25');await expect(page.getByRole('spinbutton',{name:/^Interest\ Due(?: \*)?$/})).toHaveValue('-1.25');await expect(page.getByRole('textbox',{name:/^Notes(?: \*)?$/})).toHaveValue('saved charge exact ไทย')}
 expect(s.writes).toHaveLength(0);s.lost=true;if(domain==='charge'){await page.getByRole('button',{name:'Review change',exact:true}).click();expect(s.writes).toHaveLength(0);await page.getByRole('button',{name:'Confirm',exact:true}).click()}else await page.getByRole('button',{name:domain==='borrower'?'Save borrower':'Save loan',exact:true}).click();await expect.poll(()=>s.pendingBeforePosts.length).toBe(1);const command=s.writes[0].body;expect(command.operation).toBe(domain==='borrower'?'borrower.update':domain+'.create');expect(command.targetId).toBe(saved.value.draft.id);expect(command.expectedVersion).toBe(domain==='borrower'?record.version:null);expect(command.inputs).toEqual(domain==='charge'?{loanId:saved.value.draft.loanId,chargeDate:saved.value.draft.date,principalDue:saved.value.draft.principal,interestDue:saved.value.draft.interest,notes:saved.value.draft.notes}:saved.value.draft.fields);expect(s.pendingBeforePosts[0][0].value).toMatchObject({domain,command});await expect.poll(async()=>(await draftsC(page)).filter(r=>r.value.domain===domain).length).toBe(0);const locked=(await pending(page))[0].value;await page.reload();await page.getByRole('button',{name:'Borrowers',exact:true}).filter({visible:true}).click();await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();expect(s.writes).toHaveLength(1);expect(s.statusReads).toHaveLength(0);expect((await pending(page))[0].value).toEqual(locked);await openSaved(page);await expect(page.getByRole('region',{name:'Saved offline payment drafts',exact:true})).toContainText(locked.borrowerLabel??(domain==='borrower'?'Pending borrower change':domain==='loan'?'Pending loan change':'New charge'));expect(s.writes).toHaveLength(1)});

test('F12 missing-domain legacy payment draft decodes with current component review without auto command or eviction',async({page})=>{const s=await setup(page);let commands=0;page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/payment-commands')commands++});await page.evaluate(async(id)=>{const repo=(await import('/apps/pwa/src/owner-offline.ts')).ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'phase5-independent-owner'});await repo.saveDraft(id,{formVersion:5,notes:'legacy retained ไทย',paymentMethod:'Cash',account:'C-account',selectionRows:[{id:'C-charge',chargeDate:'2026-10-09',loanDisplayKey:'Synthetic loan',amountRemaining:'10'}],allMode:false})},record.id);await openSaved(page);await page.getByRole('button',{name:/^Saved draft/}).click();await expect(page.getByRole('textbox',{name:/^Notes(?: \*)?$/})).toHaveValue('legacy retained ไทย');await expect(page.getByRole('textbox',{name:/^Amount\ received(?: \*)?$/})).toHaveValue('10');await expect(page.getByRole('textbox',{name:/^Principal\ for\ Synthetic\ loan\ 2026-10-09(?: \*)?$/})).toHaveValue('10');await expect(page.getByRole('checkbox',{name:'Allocate to Synthetic loan 2026-10-09',exact:true})).toBeChecked();await expect(page.getByText('Saved selection needs conversion review with current component balances.',{exact:true})).toBeVisible();expect(commands).toBe(0);expect(s.writes).toHaveLength(0);expect(await pending(page)).toHaveLength(0);expect(await draftsC(page)).toHaveLength(1)});
const dashboardUiC={businessDate:'2026-10-09',asOf:'2026-10-09T05:00:00Z',pendingPaymentAmount:'27',todayProfit:'4',yesterdayProfit:'3',netProfit:'-8',collection:{notPaid:0,partiallyPaid:2,overdue:1,fullyPaid:3},forecast:{expectedDailyInterest:'6',realizedProfitMtd:'12',forecastRemainingInterest:'100',projectedMonthlyProfit:'112'},portfolio:{totalCashPool:'200',activeLoanProfit:'-9',profitCoverageRatio:'0.25'},incomeMtd:{operatingIncomeMtd:'12',expensesMtd:'20',netProfitMtd:'-8',tommyWithdrawnMtd:'1',lisaWithdrawnMtd:'2',unsettledProfitMtd:'-11'},businessCashHeld:[{id:'C-account',label:'Synthetic custody account',holderId:'ch:lisa',holderLabel:'Lisa',currentBalance:null}]};
async function navigateReadC(page:Page,name:string){const button=page.getByRole('button',{name,exact:true}).filter({visible:true});if(!await button.count())await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name,exact:true}).filter({visible:true}).click()}
test('F11 UI Dashboard exact groups zero-status suppression header busy and strict320 EN Thai',async({page},info)=>{
 await page.setViewportSize({width:320,height:900});const s=await setup(page);let release:()=>void=()=>{};let requests=0;await page.route('https://mw-credit-app-command-dev-test.run.app/api/dashboard',async r=>{requests++;await new Promise<void>(done=>release=done);await r.fulfill({contentType:'application/json',body:JSON.stringify(dashboardUiC)})});await navigateReadC(page,'Dashboard');await expect.poll(()=>requests).toBe(1);await expect(page.locator('.topbar .collection-update')).toContainText('Loading');await expect(page.locator('main')).not.toContainText(/Loading|Checking/);release();const region=page.getByRole('region',{name:'Dashboard',exact:true});await expect(region.getByRole('heading',{name:'KPIs',exact:true})).toBeVisible();expect(await region.locator('h2,h3').allTextContents()).toEqual(['KPIs','Collection','Monthly Forecast','Active loans','Income MTD','Business Cash Held','Lisa']);await expect(region.getByText('Not Paid',{exact:true})).toHaveCount(0);await expect(region.getByText('Partially Paid',{exact:true})).toBeVisible();await expect(region.getByText('25%',{exact:true})).toBeVisible();await expect(region.getByText('Unavailable',{exact:true})).toBeVisible();await expect(region).not.toContainText(/Outstanding Principal|Total Outstanding/);await expect(region.getByRole('button')).toHaveCount(0);
 for(const lang of ['EN','ไทย'] as const){await chooseLanguage(page,lang);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);await expect(page.locator('main')).not.toContainText(/Loading|Checking/);await page.screenshot({path:'outputs/r052-phase5-completion/dashboard-'+info.project.name+'-'+(lang==='EN'?'en':'th')+'.png'})}expect(s.writes).toHaveLength(0);
});
test('F11 UI standalone Upcoming date groups exact detail scope global refresh errors and strict320',async({page},info)=>{
 await page.setViewportSize({width:320,height:900});const s=await setup(page);let detailUrl='',fail=false;const context={businessDate:'2026-10-09',asOf:'2026-10-09T05:00:00Z',forecastNote:'Recorded and projected context; synthetic only.'};await page.route('https://mw-credit-app-command-dev-test.run.app/api/upcoming-charges**',async r=>{const url=new URL(r.request().url());if(fail)return r.fulfill({status:409,contentType:'application/json',body:'{"ok":false}'});const detail=url.pathname!='/api/upcoming-charges';if(detail)detailUrl=url.toString();await r.fulfill({contentType:'application/json',body:JSON.stringify(detail?{...context,dueDate:'2026-10-16',totalCharge:'37',items:[{id:'C-event',loanDate:'2026-10-01',loanType:'Daily Loan',loanPrincipal:'100',amount:'11',basis:'Recorded'}],nextCursor:null}:{...context,dateTotals:[{date:'2026-10-10',amount:'26'},{date:'2026-10-16',amount:'37'}],items:[{id:'C-one',borrowerId:'C-future',label:'Synthetic future-only borrower',dueDate:'2026-10-10',totalCharge:'26'},{id:'C-seven',borrowerId:'C-future',label:'Synthetic seventh date borrower',dueDate:'2026-10-16',totalCharge:'37'}],nextCursor:null})})});await navigateReadC(page,'Upcoming Charges');const region=page.getByRole('region',{name:'Upcoming Charges',exact:true});await expect(region.getByRole('heading',{name:'16-Oct · ฿37',exact:true})).toBeVisible();await expect(region.getByRole('button',{name:/Previous upcoming page|Next upcoming page|Refresh/})).toHaveCount(0);await region.getByRole('button',{name:'Synthetic seventh date borrower ฿37',exact:true}).click();await expect(region.locator('.upcoming-row small').filter({hasText:/Recorded$/})).toBeVisible();expect(new URL(detailUrl).pathname).toBe('/api/upcoming-charges/C-future/2026-10-16');expect(new URL(detailUrl).searchParams.get('businessDate')).toBe('2026-10-09');await expect(region.getByRole('heading',{name:'16-Oct · ฿37',exact:true})).toBeVisible();
 for(const lang of ['EN','ไทย'] as const){await chooseLanguage(page,lang);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320);await expect(page.locator('main')).not.toContainText(/Loading|Checking/);await page.screenshot({path:'outputs/r052-phase5-completion/upcoming-'+info.project.name+'-'+(lang==='EN'?'en':'th')+'.png'})}await chooseLanguage(page,'EN');fail=true;await page.locator('.topbar').getByRole('button',{name:'Refresh Upcoming Charges',exact:true}).click();await expect(region.getByRole('button',{name:'Retry Upcoming Charges',exact:true})).toBeVisible();fail=false;await region.getByRole('button',{name:'Retry Upcoming Charges',exact:true}).click();await expect(region.getByRole('alert')).toHaveCount(0);await expect(region.locator('.upcoming-row small').filter({hasText:/Recorded$/})).toBeVisible();expect(s.writes).toHaveLength(0);
});
