import {test,expect,chromium,devices,type Page} from '@playwright/test';
import {spawnSync} from 'node:child_process';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{startCanonicalFixture}from'./fixtures/canonical-server';import{chooseLanguage}from'./live-controls';
let fixture:any,root:string,owned=false,mobile=false;test.beforeEach(async({},info)=>{mobile=info.project.name.startsWith('mobile')});
test.beforeAll(async()=>{root=process.env.PHASE5_STATIC_CAPTURE??mkdtempSync(join(tmpdir(),'mw-phase5-final-ui-'));owned=!process.env.PHASE5_STATIC_CAPTURE;if(owned){const transform=(code:string,id:string)=>{if(id.endsWith('/apps/pwa/src/owner-offline.ts'))return code.replace("async list(kind:'snapshot'|'draft'|'pending'){","async list(kind:'snapshot'|'draft'|'pending'){if(kind==='snapshot')await (globalThis as any).__syntheticSnapshotRead?.();");if(id.endsWith('/apps/pwa/src/live-main.tsx'))return code+";import {getAuth as fixtureGetAuth,signInWithCustomToken as fixtureSignIn} from 'firebase/auth';globalThis.__syntheticSdk={fixtureGetAuth,fixtureSignIn};import {ownerOfflineRepository as fixtureRepository} from './owner-offline';globalThis.__syntheticRepo=fixtureRepository;import {projectViewedSnapshot as fixtureProjection} from './viewed-snapshot';globalThis.__syntheticProjection=fixtureProjection;"};const script='import{build}from"vite";await build(Object.assign('+JSON.stringify({mode:'live-dev',build:{outDir:join(root,'public'),emptyOutDir:true}})+',{plugins:[{name:"synthetic-sdk-bridge",enforce:"pre",transform:'+transform.toString()+'}]}));';const result=spawnSync(process.execPath,['--input-type=module','-e',script],{encoding:'utf8',env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-key',VITE_FIREBASE_APP_ID:'synthetic-app',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app',VITE_COMMAND_API_ORIGIN:'https://mw-credit-app-command-dev-test.run.app',VITE_COMMAND_MODE:'dev-owner-testing'}});expect(result.status,result.stderr).toBe(0)}fixture=await startCanonicalFixture(join(root,'public'))});
test.afterAll(async()=>{await fixture?.close();if(owned)rmSync(root,{recursive:true,force:true})});test.setTimeout(45000);
const v='a'.repeat(64),v2='b'.repeat(64),uid='synthetic-phase5-final-owner',requestId='07eae274-c4e9-44e9-bff4-900c3bf37c9b',receiptId='fe93a8d6-3050-449e-9bba-949da4acf246';
const borrower={id:'C-borrower',borrowerDisplayName:'SYNTHETIC final borrower',createdDate:null,hasActiveLoan:true,outstandingPrincipal:'110',totalProfitEarned:'0'};
const accounts=[{id:'C-account',label:'Synthetic account',holderId:'ch:lisa',holderLabel:'Lisa'}];
const closeA={ok:true,businessDate:'2026-10-09',sourceVersion:v,amount:'115',planHash:v,accounts};
const closeDraft={kind:'close',item:{id:'C-loan',borrowerId:borrower.id,borrowerDisplayName:borrower.borrowerDisplayName},requestId,preview:closeA,account:'C-account',method:'Cash',notes:'exact saved close ไทย',receipt:receiptId,receiptName:'synthetic.png'};
const fields={borrowerId:borrower.id,amountReceived:'10',paymentDate:'2026-10-09',paymentMethod:'Cash',cashAccountId:'C-account',notes:'exact saved correction ไทย',allocationMethod:'Selected Charges',targetChargeId:null,targetLoanId:null};
const line={chargeId:'C-charge',principal:'8',interest:'2',expectedPrincipalRemaining:'10',expectedInterestRemaining:'5',chargeDate:'2026-10-09'};
const previewA={origin:'pwa-plan',sourceVersion:v,predecessorRequestId:requestId,source:{id:'C-payment',borrowerName:borrower.borrowerDisplayName,...fields,receiptReference:'synthetic-reference',allocations:[]},balances:[{chargeId:'C-charge',loanId:'C-loan',chargeDate:'2026-10-09',principalRemaining:'10',interestRemaining:'5'}],loans:[]};
const correctionDraft={kind:'correction',id:'C-payment',requestId,preview:previewA,fields,accounts,lines:{'C-charge':line},closeHash:null,receiptMode:'replace',receiptId};
const preferenceA={item:{id:'C-partner',version:v,language:'English',statementAccountId:'C-account',statementDate:'2026-10-09'},accounts,dates:['2026-10-09']};
type S={posts:any[],pendingAtPost:any[],close:any,correction:any,preferences:any,deleted:boolean,receiptReads:string[],manualFail:boolean,record:any};
async function repo(page:Page,kind:string){return page.evaluate(async kind=>(window as any).__syntheticRepo({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'synthetic-phase5-final-owner'}).list(kind),kind)}
async function seed(page:Page,domain:string,id:string,draft:any){await page.evaluate(async({domain,id,draft})=>{await(window as any).__syntheticRepo({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'synthetic-phase5-final-owner'}).saveDraft(domain+':'+id,{domain,label:'Synthetic '+domain+' final draft',draft})},{domain,id,draft})}
async function saved(page:Page,label:string){await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:'Saved payment drafts',exact:true}).filter({visible:true}).click();await page.getByRole('button',{name:new RegExp('^'+label)}).click()}
async function launch(){
 const context=await chromium.launchPersistentContext('',{headless:true,...(mobile?devices['Pixel 7']:devices['Desktop Chrome']),viewport:{width:320,height:900},args:['--ignore-certificate-errors','--host-resolver-rules=MAP dev-lm.mw-credit.com 127.0.0.1:'+fixture.port,'--no-proxy-server']});const page=await context.newPage();page.on('pageerror',e=>console.log('C synthetic pageerror: '+e.message));const now=Math.floor(Date.now()/1000),token=[{alg:'none',typ:'JWT'},{sub:uid,user_id:uid,aud:'clever-oasis-508610-n7',iss:'https://securetoken.google.com/clever-oasis-508610-n7',iat:now,exp:now+3600,auth_time:now,email:'synthetic@example.test',email_verified:true,firebase:{sign_in_provider:'custom'}}].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.')+'.synthetic';
 const s:S={posts:[],pendingAtPost:[],close:closeA,correction:previewA,preferences:preferenceA,deleted:false,receiptReads:[],manualFail:true,record:null};
 await context.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname==='dev-lm.mw-credit.com')return r.continue();if(u.hostname==='identitytoolkit.googleapis.com')return r.fulfill({contentType:'application/json',body:JSON.stringify(u.pathname.includes('signInWithCustomToken')?{idToken:token,refreshToken:'synthetic-refresh',expiresIn:'3600',isNewUser:false}:{users:[{localId:uid,email:'synthetic@example.test',emailVerified:true,providerUserInfo:[]}]})});if(u.hostname==='mw-credit-app-read-dev-test.run.app')return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'dev',businessDate:'2026-10-09',horizonEnd:'2027-01-09',reviewRequired:false,items:u.pathname.includes('/loans')||u.pathname.endsWith('/upcoming')?[]:[borrower],item:borrower,borrower,nextCursor:null,asOf:new Date().toISOString()})});
 if(u.hostname==='mw-credit-app-command-dev-test.run.app'){
 let data:any={ok:true,items:[],nextCursor:null};
 if(r.request().method()!=='GET'){s.posts.push({path:u.pathname,body:r.request().postDataJSON()});s.pendingAtPost.push(await repo(page,'pending'));return r.abort('failed')}
 if(u.pathname.endsWith('/close-preview'))data=s.close;
 else if(u.pathname.endsWith('/correction-preview')){if(s.deleted)return r.fulfill({status:404,body:'{}'});data={ok:true,item:s.correction}}
 else if(u.pathname==='/api/preferences')data=s.preferences;
 else if(u.pathname==='/api/cash-overview')data={dashboard:{},accounts:[]};
 else if(u.pathname==='/api/cash-statements')data={summary:{openingBalance:'20',moneyIn:'5',moneyOut:'10',netMovement:'-5',closingBalance:'15',transactionCount:1},items:[{id:'C-ledger',date:'2026-10-09',transactionType:'Received',amount:'5',balanceAfter:'15',paymentId:'C-payment',notes:'synthetic ledger note'}],nextCursor:null};
 else if(u.pathname.endsWith('/receipt')){const source=u.searchParams.get('source')??'preferred';s.receiptReads.push(source);if(source!=='agent'&&s.manualFail)return r.fulfill({status:422,body:'{}'});return r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7ZkAAAAASUVORK5CYII=','base64')})}
 else if(u.pathname.startsWith('/api/payment-records/'))data={ok:true,item:{...s.record,asOf:new Date().toISOString(),businessDate:'2026-10-09'}};
 else if(u.pathname==='/api/borrower-options')data={ok:true,accounts,referrers:[{id:'C-other',label:'Synthetic destination'}]};
 return r.fulfill({contentType:'application/json',body:JSON.stringify(data)})}return r.abort()});
 await page.goto('https://dev-lm.mw-credit.com');await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await page.evaluate(async()=>{const sdk=(window as any).__syntheticSdk;await sdk.fixtureSignIn(sdk.fixtureGetAuth(),'synthetic-custom-token')});await expect(page.getByRole('button',{name:'Add borrower',exact:true})).toBeVisible();await chooseLanguage(page,'EN');return{context,page,s};
}
test('F12 static Close retains CAS until explicit adoption then fresh review freezes request receipt and money',async()=>{const{context,page,s}=await launch();try{await seed(page,'loan','close:C-loan',closeDraft);await saved(page,'Synthetic loan');await expect(page.locator('output')).toHaveText('฿115');s.close={...closeA,sourceVersion:v2,planHash:v2,amount:'120'};await page.getByRole('button',{name:'Review close',exact:true}).click();await expect(page.getByRole('button',{name:'Use current closing amount',exact:true})).toBeVisible();expect((await repo(page,'draft'))[0].value.draft.preview).toEqual(closeA);expect(s.posts).toHaveLength(0);await page.getByRole('button',{name:'Retry review',exact:true}).click();await expect(page.locator('output')).toHaveText('฿115');await page.getByRole('button',{name:'Use current closing amount',exact:true}).click();await expect.poll(async()=>(await repo(page,'draft'))[0].value.draft.preview.sourceVersion).toBe(v2);expect((await repo(page,'draft'))[0].value.draft).toMatchObject({requestId,account:'C-account',method:'Cash',notes:closeDraft.notes,receipt:receiptId});await expect(page.getByRole('button',{name:'Confirm',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Review close',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect.poll(()=>s.posts.length).toBe(1);expect(s.posts[0].body).toMatchObject({requestId,receiptId,expectedVersion:v2,inputs:{expectedAmount:'120',expectedPlanHash:v2,notes:closeDraft.notes}});expect(s.pendingAtPost[0][0].value.command).toEqual(s.posts[0].body);await expect(page.getByRole('button',{name:'Check request',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Back to details',exact:true})).toBeDisabled();expect(await repo(page,'draft')).toHaveLength(0)}finally{await context.close()}});
test('F12 static correction preserves head receipt split on stale and deleted source before explicit immutable dispatch',async()=>{const{context,page,s}=await launch();try{await seed(page,'payment','correction:C-payment',correctionDraft);await saved(page,'Synthetic payment');await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue(fields.notes);s.correction={...previewA,sourceVersion:v2,predecessorRequestId:'changed-head'};await page.getByRole('button',{name:'Review correction',exact:true}).click();await expect(page.getByRole('alert')).toContainText('The source changed');expect((await repo(page,'draft'))[0].value.draft.preview.sourceVersion).toBe(v);expect((await repo(page,'draft'))[0].value.draft.receiptId).toBe(receiptId);s.deleted=true;await page.getByRole('button',{name:'Review correction',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm',exact:true})).toHaveCount(0);expect(s.posts).toHaveLength(0);s.deleted=false;s.correction=previewA;await page.getByRole('button',{name:'Review correction',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect.poll(()=>s.posts.length).toBe(1);expect(s.posts[0].body).toMatchObject({requestId,receiptId,expectedVersion:v,predecessorRequestId:requestId,inputs:{receiptMode:'replace',fields:{notes:fields.notes,allocations:[line]}}});expect(s.pendingAtPost[0][0].value.command).toEqual(s.posts[0].body)}finally{await context.close()}});
test('F12 static preference retains stale CAS; cash drilldown manual receipt never silently falls back',async()=>{const{context,page,s}=await launch();try{await seed(page,'preference','own',{preferences:preferenceA,account:'C-account',date:'2026-10-09',language:'English'});await saved(page,'Synthetic preference');s.preferences={...preferenceA,item:{...preferenceA.item,version:v2}};await page.getByRole('button',{name:'Save preferences',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Preferences changed');expect((await repo(page,'draft'))[0].value.draft.preferences.item.version).toBe(v);expect(s.posts).toHaveLength(0);s.preferences=preferenceA;await page.getByRole('combobox',{name:'Account',exact:true}).selectOption('');await page.getByRole('combobox',{name:'Account',exact:true}).selectOption('C-account');await expect(page.getByRole('button',{name:'Payment details',exact:true})).toBeVisible();s.record={id:'C-payment',version:v,borrowerName:'SYNTHETIC receipt borrower',amountReceived:'10',paymentDate:'2026-10-09',paymentMethod:'Cash',allocationMethod:'Selected Charges',status:'Posted',originalOutcomeStatus:'posted',originalRecordedAt:'2026-10-08T01:00:00Z',receiptReference:'unknown-native',agentReceiptPresent:true,allocations:[],repayments:[],cashMovements:[]};await page.getByRole('button',{name:'Payment details',exact:true}).click();await expect(page.getByRole('region',{name:'Full payment details',exact:true})).toBeVisible();await expect.poll(()=>s.receiptReads).toEqual(['preferred']);await expect(page.locator('main')).toContainText('Receipt unavailable');expect(s.receiptReads).not.toContain('agent');await page.getByRole('button',{name:'Agent receipt',exact:true}).click();await expect(page.getByRole('img',{name:'Verified receipt evidence',exact:true})).toBeVisible();expect(s.receiptReads).toEqual(['preferred','agent']);expect(s.posts).toHaveLength(0);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(320)}finally{await context.close()}});

test('F12 static safe projections share20 snapshot capacity and independently expire source and owner lease',async()=>{const{context,page,s}=await launch();try{
 const results=await page.evaluate(async()=>{const repo=(window as any).__syntheticRepo({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'synthetic-phase5-final-owner'}),project=(window as any).__syntheticProjection,now=Date.now(),asOf=new Date(now-1000).toISOString(),version='a'.repeat(64);
 const snap=project('payment',{id:'C-safe-payment',version,amountReceived:'1000',notes:'exact safe note',receiptReference:'private/path.png',createdBy:'private@example.test',token:'private-token',bankNumber:'private-bank',allocations:Array.from({length:80},(_,i)=>({id:String(i),amount:'10',secret:'excluded'})),repayments:Array.from({length:30},(_,i)=>({id:String(i),interest:'1',actorEmail:'excluded'})),cashMovements:[{id:'cash',amount:'1000'}]},'2026-10-09',asOf);
 await repo.saveDraft('retained',{domain:'borrower',draft:{id:'retained'}});await repo.savePending('retained-pending',{domain:'borrower',command:{requestId:'retained-pending'}});
 for(let i=0;i<21;i++){const domain=['borrower','loan','charge','payment','expense'][i%5];await repo.saveViewedSnapshot(project(domain,{id:'C-'+i,version,name:'Synthetic '+i,principal:'10',amountReceived:'10',amount:'10',address:'excluded',createdBy:'excluded',receiptReference:'excluded',notes:'safe'},'2026-10-09',new Date(now-1000+i).toISOString()))}
 const rows=await repo.list('snapshot');await repo.saveViewedSnapshot(snap);const ageBefore=(await repo.snapshot('payment:C-safe-payment')).savedAt;await repo.snapshot('payment:C-safe-payment');const ageAfter=(await repo.snapshot('payment:C-safe-payment')).savedAt;
 const nativeNow=Date.now;Date.now=()=>now+86400001;const authorized=await repo.authorized(),expired=await repo.list('snapshot');await repo.authorize();const renewed=await repo.authorized(),afterLeaseRefresh=await repo.list('snapshot');Date.now=nativeNow;return{snap,rows,ageBefore,ageAfter,authorized,expired,renewed,afterLeaseRefresh,drafts:await repo.list('draft'),pending:await repo.list('pending')};
 });
 expect(results.rows).toHaveLength(20);expect(new Set(results.rows.map((r:any)=>r.value.domain)).size).toBe(5);expect(results.rows.some((r:any)=>r.value.recordId==='C-0')).toBe(false);expect(JSON.stringify(results.snap)).not.toMatch(/private|secret|actorEmail|bankNumber|receiptReference|createdBy|token/);expect(results.snap.record.amountReceived).toBe('1000');expect(results.snap.record.manualReceiptPresent).toBe(true);expect(results.snap.related.allocations.rows).toHaveLength(80);expect(results.snap.related.repayments.rows).toHaveLength(20);expect(results.snap.related.cashMovements.rows).toHaveLength(0);expect(results.snap.related.repayments.truncated).toBe(true);expect(results.ageAfter).toBe(results.ageBefore);expect(results.authorized).toBe(false);expect(results.expired).toHaveLength(0);expect(results.renewed).toBe(true);expect(results.afterLeaseRefresh).toHaveLength(0);expect(results.drafts).toHaveLength(1);expect(results.pending).toHaveLength(1);expect(s.posts).toHaveLength(0);
 }finally{await context.close()}});
test('F12 static viewed record renders truncation and receipt-offline notice then source age expires without navigation',async()=>{const{context,page,s}=await launch();try{
 await page.evaluate(async()=>{const repo=(window as any).__syntheticRepo({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'synthetic-phase5-final-owner'}),project=(window as any).__syntheticProjection;await repo.saveViewedSnapshot(project('payment',{id:'C-expiring',version:'a'.repeat(64),borrowerName:'Synthetic expiring view',amountReceived:'150',receiptReference:'excluded',repayments:Array.from({length:101},(_,i)=>({id:String(i),principal:'1'}))},'2026-10-09',new Date(Date.now()-86400000+3000).toISOString()))});
 await saved(page,'Synthetic expiring view');await expect(page.locator('main')).toContainText('Receipt image unavailable offline.');await expect(page.locator('main')).toContainText('Only part of this related list was saved.');await expect(page.getByText('This saved view is unavailable. Connect to load current records.',{exact:true})).toBeVisible();expect(s.posts).toHaveLength(0);
 }finally{await context.close()}});
test('F12 static workspace revision preserves mounted draft but expired owner lease clears it immediately on focus',async()=>{const{context,page,s}=await launch();try{await seed(page,'loan','close:C-loan',closeDraft);await saved(page,'Synthetic loan');await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue(closeDraft.notes);await page.evaluate(()=>{(window as any).__heldSnapshotStarted=false;(window as any).__syntheticSnapshotRead=()=>{(window as any).__heldSnapshotStarted=true;return new Promise<void>(resolve=>(window as any).__releaseSnapshot=resolve)};window.dispatchEvent(new Event('mw-offline-saved'))});await expect.poll(()=>page.evaluate(()=>(window as any).__heldSnapshotStarted)).toBe(true);await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue(closeDraft.notes);await page.evaluate(()=>{const nativeNow=Date.now;(window as any).__realNow=nativeNow;const future=nativeNow()+86400001;Date.now=()=>future;window.dispatchEvent(new Event('focus'))});await expect(page.getByText('Connect to verify this account before accessing saved records.',{exact:false})).toBeVisible();await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveCount(0);await page.evaluate(()=>{(window as any).__syntheticSnapshotRead=undefined;(window as any).__releaseSnapshot()});await expect(page.locator('.topbar .live-status-text')).not.toContainText('Loading');await expect(page.getByText('Connect to verify this account before accessing saved records.',{exact:false})).toBeVisible();await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveCount(0);expect(s.posts).toHaveLength(0);await page.evaluate(()=>{Date.now=(window as any).__realNow});expect((await repo(page,'draft'))[0].value.draft).toMatchObject({requestId,receipt:receiptId})}finally{await context.close()}});
test('F12 static explicit borrower replacement preserves edited money receipt and ignores late prior destination',async()=>{const{context,page,s}=await launch();try{await seed(page,'payment','correction:C-payment',correctionDraft);await saved(page,'Synthetic payment');let release:()=>void=()=>{};const destination=(id:string)=>({...previewA,proposedBorrowerId:id,proposedBorrowerLabel:'Synthetic '+id,balances:[{chargeId:id+'-charge',loanId:id+'-loan',chargeDate:'2026-10-09',principalRemaining:'10',interestRemaining:'5'}]});await context.route('https://mw-credit-app-command-dev-test.run.app/api/borrower-options**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,accounts,referrers:[{id:'C-B',label:'Synthetic B'},{id:'C-C',label:'Synthetic C'}]})}));await context.route('https://mw-credit-app-command-dev-test.run.app/api/payment-records/C-payment/correction-preview**',async r=>{const id=new URL(r.request().url()).searchParams.get('proposedBorrowerId');if(id==='C-B')await new Promise<void>(done=>release=done);return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,item:destination(id??borrower.id)})})});await page.getByRole('searchbox',{name:'Borrower',exact:true}).fill('synthetic');await page.getByRole('button',{name:'Synthetic B',exact:true}).click();await expect(page.getByRole('button',{name:'Review correction',exact:true})).toBeDisabled();await page.getByRole('searchbox',{name:'Borrower',exact:true}).fill('synthetic C');await page.getByRole('button',{name:'Synthetic C',exact:true}).click();await expect(page.getByRole('button',{name:'Replace allocation selection for this borrower',exact:true})).toBeEnabled();release();await page.getByRole('button',{name:'Replace allocation selection for this borrower',exact:true}).click();await expect(page.getByRole('textbox',{name:'Principal',exact:true})).toHaveValue('0');await expect(page.getByRole('textbox',{name:'Amount Received',exact:true})).toHaveValue('10');await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue(fields.notes);await page.getByRole('textbox',{name:'Principal',exact:true}).fill('8');await page.getByRole('textbox',{name:'Interest',exact:true}).fill('2');await expect.poll(async()=>(await repo(page,'draft'))[0].value.draft.fields.borrowerId).toBe('C-C');expect((await repo(page,'draft'))[0].value.draft.receiptId).toBe(receiptId);expect(s.posts).toHaveLength(0);await page.getByRole('button',{name:'Review correction',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect.poll(()=>s.posts.length).toBe(1);expect(s.posts[0].body.inputs.fields.borrowerId).toBe('C-C');expect(s.posts[0].body.inputs.fields.allocations[0].chargeId).toBe('C-C-charge');expect(s.posts[0].body).toMatchObject({requestId,receiptId,expectedVersion:v,predecessorRequestId:requestId})}finally{await context.close()}});
test('F12 static Collection receipts preserve exact page scope older date manual priority and stable128px geometry',async()=>{const{context,page,s}=await launch();try{const row={id:borrower.id,displayName:'SYNTHETIC Collection borrower',status:'partially_paid',amountDue:'20',amountCollected:'10',amountRemaining:'10'},charge={id:'C-visible-charge',loanId:'C-loan',loanDisplayKey:'Synthetic loan',chargeDate:'2026-10-09',paymentStatus:'ชำระบางส่วน',paymentDate:null,amountRemaining:'10',totalPaid:'10',receivedToday:'10'};await context.route('https://mw-credit-app-read-dev-test.run.app/api/collection**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'dev',businessDate:'2026-10-09',timezone:'Asia/Bangkok',asOf:'2026-10-09T05:00:00Z',horizonEnd:'2027-01-09',reviewRequired:false,items:new URL(r.request().url()).pathname.endsWith('/upcoming')?[]:new URL(r.request().url()).pathname.endsWith('/charges')?[charge]:[row],borrower:row,nextCursor:null})}));let scope:any;await context.route('https://mw-credit-app-command-dev-test.run.app/api/borrowers/**/collection-receipts**',r=>{scope=new URL(r.request().url());return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,businessDate:'2026-10-09',items:[{id:'C-payment',paymentDate:'2026-10-08',amount:'10',manualReceiptPresent:true,agentReceiptPresent:true,receiptAt:'2026-10-09T05:00:00Z'}],nextCursor:null})})});await page.getByRole('button',{name:'Collection',exact:true}).filter({visible:true}).click();await page.locator('.collection-borrower').click();const region=page.getByRole('region',{name:'Collection receipts',exact:true});await expect(region).toContainText('2026-10-08');await expect(region).toContainText('Receipt unavailable');expect(JSON.parse(scope.searchParams.get('chargeIds'))).toEqual(['C-visible-charge']);expect(scope.searchParams.get('businessDate')).toBe('2026-10-09');expect(s.receiptReads).toEqual(['preferred']);await expect(region.getByRole('button',{name:/Previous receipts page|Next receipts page/})).toHaveCount(0);const tile=region.locator('.borrower-card');expect(await tile.locator('span').first().evaluate(e=>e.getBoundingClientRect().height)).toBe(128);for(const lang of ['EN','ไทย'] as const){await chooseLanguage(page,lang);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)}expect(s.posts).toHaveLength(0)}finally{await context.close()}});


for(const status of [401,403])test('F12 static current record '+status+' never falls back to viewed snapshot',async()=>{const{context,page,s}=await launch();try{await seed(page,'preference','own',{preferences:preferenceA,account:'C-account',date:'2026-10-09',language:'English'});await saved(page,'Synthetic preference');await page.getByRole('combobox',{name:'Account',exact:true}).selectOption('');await page.getByRole('combobox',{name:'Account',exact:true}).selectOption('C-account');s.record={id:'C-payment',version:v,borrowerName:'SYNTHETIC cached view must disappear',amountReceived:'10',status:'Posted',allocations:[],repayments:[],cashMovements:[],receiptReference:null,agentReceiptPresent:false};await page.getByRole('button',{name:'Payment details',exact:true}).click();await expect(page.getByRole('region',{name:'Full payment details',exact:true})).toBeVisible();await expect.poll(async()=>(await repo(page,'snapshot')).length).toBe(1);await context.route('https://mw-credit-app-command-dev-test.run.app/api/payment-records/C-payment',r=>r.fulfill({status,contentType:'application/json',body:'{}'}));await page.locator('.topbar').getByRole('button',{name:'Refresh payment details',exact:true}).click();await expect(page.getByRole('region',{name:'Full payment details',exact:true})).toHaveCount(0);await expect(page.locator('main')).not.toContainText('SYNTHETIC cached view must disappear');await expect.poll(async()=>(await repo(page,'snapshot')).length).toBe(0);expect(s.posts).toHaveLength(0)}finally{await context.close()}});

test('F12 final320 correction Close preference form geometry and bilingual visual parity',async({},info)=>{
 for(const [domain,id,draft] of [['payment','correction:C-payment',correctionDraft],['loan','close:C-loan',closeDraft],['preference','own',{preferences:preferenceA,account:'C-account',date:'2026-10-09',language:'English'}]] as const){
  const {context,page,s}=await launch();try{await seed(page,domain,id,draft);await saved(page,'Synthetic '+domain);await expect(domain==='preference'?page.getByRole('combobox',{name:'Language Preference',exact:true}):page.locator('main form').first()).toBeVisible();if(domain!=='preference'){await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue(domain==='loan'?closeDraft.notes:fields.notes);expect(await page.getByRole('combobox',{name:'Payment Method',exact:true}).locator('option').allTextContents()).toEqual(['Bank Transfer','Cash','Net-off at Disbursement'])}
   for(const lang of ['EN','ไทย'] as const){await chooseLanguage(page,lang);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);const overflow=await page.locator('main input,main select,main textarea').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left<0||r.right>320)}).map(e=>({tag:e.tagName,type:(e as HTMLInputElement).type})));expect(overflow).toEqual([]);await page.screenshot({path:'outputs/r052-phase5-completion/final-'+domain+'-'+info.project.name+'-'+(lang==='EN'?'en':'th')+'-320.png',fullPage:true})}expect(s.posts).toHaveLength(0);
  }finally{await context.close()}
 }
});
test('F13 static five root routes preserve responsive order header busy query page Back and delete refresh',async({},info)=>{
 const{context,page,s}=await launch();try{
  const loanRow=(id:string)=>({id,borrowerId:'C-borrower',borrowerDisplayName:'SYNTHETIC root borrower',rank:0,status:'ยังไม่ปิดยอด',loanDate:'2026-10-09',principalAmount:'100',totalInterestReceived:'25',principalRecoveredByInterestRatio:'0.25',originalDailyInterestRate:null});
  const paymentRow=(id:string)=>({id,borrowerId:'C-borrower',borrowerDisplayName:'SYNTHETIC root borrower',status:'Error',paymentDate:'2026-10-09',createdAt:null,amountReceived:'1',postedAmount:'0',month:'2026-10',groupAmountReceived:'26',manualReceiptPresent:false,agentReceiptPresent:false});
  let release:()=>void=()=>{},held=true,deleted=false;const requests:any[]=[];
  await context.route('https://mw-credit-app-command-dev-test.run.app/api/loan-records?**',async r=>{if(held)await new Promise<void>(done=>release=done);requests.push(new URL(r.request().url()));return r.fulfill({contentType:'application/json',body:JSON.stringify({items:[loanRow('C-loan')],nextCursor:null})})});
  await context.route('https://mw-credit-app-command-dev-test.run.app/api/loan-records/C-loan',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({item:{...loanRow('C-loan'),version:v,type:'กำหนดวันชำระ',autoChargeEnabled:false,asOf:new Date().toISOString(),businessDate:'2026-10-09'}})}));
  await context.route('https://mw-credit-app-command-dev-test.run.app/api/payment-records?**',r=>{const u=new URL(r.request().url());requests.push(u);return r.fulfill({contentType:'application/json',body:JSON.stringify({items:u.searchParams.has('cursor')?(deleted?[]:[paymentRow('C-payment')]):Array.from({length:25},(_,i)=>({...paymentRow('C-page-'+i),groupAmountReceived:deleted?'25':'26'})),nextCursor:u.searchParams.has('cursor')||deleted?null:'synthetic-root-page2'})})});
  if(!mobile){await page.setViewportSize({width:1440,height:900});expect((await page.locator('#live-desktop-navigation nav button').allTextContents()).slice(0,5).map(x=>x.replace(/^[^A-Za-z]+/,''))).toEqual(['Dashboard','Collection','Payments','Borrowers','Loans'])}
  await page.setViewportSize({width:320,height:900});const nav=page.locator('.live-bottom-nav');expect(await nav.locator('button').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')))).toEqual(['Dashboard','Collection','Payments','Borrowers','Loans']);
  await nav.getByRole('button',{name:'Loans',exact:true}).click();await expect(page.locator('.topbar')).toContainText('Loading');await expect(page.locator('main')).not.toContainText('Loading');held=false;release();await expect(page.getByRole('region',{name:'Loans list',exact:true})).toContainText('25%');await expect(nav.getByRole('button',{name:'Loans',exact:true})).toHaveAttribute('aria-current','page');await page.getByRole('region',{name:'Loans list',exact:true}).locator('.borrower-card').click();await expect(page.getByRole('region',{name:'Full loan details',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Edit loan',exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to loans',exact:true}).click();await expect(page.getByRole('region',{name:'Loans list',exact:true})).toBeVisible();
  await nav.getByRole('button',{name:'Payments',exact:true}).click();const list=page.getByRole('region',{name:'Payments list',exact:true});await expect(list.locator('.borrower-card')).toHaveCount(25);await expect(list).toContainText('฿26');await page.getByRole('button',{name:'Search borrowers',exact:true}).click();await page.getByRole('searchbox',{name:'Search Thai or English name',exact:true}).fill('synthetic %_ ไทย');await page.getByRole('searchbox',{name:'Search Thai or English name',exact:true}).press('Enter');await page.getByRole('button',{name:'Back from search',exact:true}).click();await page.getByRole('button',{name:'Next payments page',exact:true}).click();await expect(list.locator('.borrower-card')).toHaveCount(1);await expect(page.getByRole('button',{name:'Next payments page',exact:true})).toHaveCount(0);await page.evaluate(()=>window.scrollTo(0,80));const scroll=await page.evaluate(()=>window.scrollY);
  s.record={id:'C-payment',version:v,borrowerName:'SYNTHETIC root borrower',amountReceived:'1',postedAmount:'0',status:'Error',paymentDate:'2026-10-09',allocations:[],repayments:[],cashMovements:[],agentReceiptPresent:false,receiptReference:null};await list.locator('.borrower-card').click();await expect(page.getByRole('region',{name:'Full payment details',exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to payment history',exact:true}).click();await expect(list.locator('.borrower-card')).toHaveCount(1);expect(requests.at(-1).searchParams.get('cursor')).toBe('synthetic-root-page2');expect(requests.at(-1).searchParams.get('q')).toBe('synthetic %_ ไทย');await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(scroll);
  for(const lang of ['EN','ไทย']as const){await chooseLanguage(page,lang);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);expect(await nav.locator('button').count()).toBe(5);await page.screenshot({path:'outputs/r052-phase5-completion/root-payments-'+info.project.name+'-'+(lang==='EN'?'en':'th')+'-320.png',fullPage:true})}await chooseLanguage(page,'EN');
  await page.getByRole('button',{name:'Open navigation',exact:true}).click();const menu=page.getByRole('dialog',{name:'Navigation menu',exact:true});for(const label of ['Dashboard','Collection','Payments','Borrowers','Loans'])await expect(menu.getByRole('button',{name:label,exact:true})).toHaveCount(0);await expect(menu.getByRole('link',{name:'Reporting',exact:true})).toHaveAttribute('href','https://www.appsheet.com/start/9f3422be-bc87-4a5a-a42a-67528ee80393');await menu.getByRole('button',{name:'Close menu',exact:true}).click();
  await list.locator('.borrower-card').click();await page.getByText('Actions',{exact:true}).click();await page.getByRole('button',{name:'Delete payment',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm',exact:true})).toBeVisible();await context.route('https://mw-credit-app-command-dev-test.run.app/api/operations',async r=>{const body=r.request().postDataJSON();s.posts.push(body);s.pendingAtPost.push(await repo(page,'pending'));deleted=true;return r.fulfill({contentType:'application/json',body:JSON.stringify({kind:'recorded',originalOutcome:{status:'applied',result:{operation:'payment.delete',targetId:'C-payment'}}})})});await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(list.locator('.borrower-card')).toHaveCount(25);await expect(list).toContainText('฿25');await expect(page.getByRole('button',{name:'Previous payments page',exact:true})).toHaveCount(0);expect(s.posts).toHaveLength(1);expect(s.pendingAtPost[0][0].value.command).toEqual(s.posts[0]);expect(requests.at(-1).searchParams.get('q')).toBe('synthetic %_ ไทย');expect(requests.at(-1).searchParams.has('cursor')).toBe(false);
 }finally{await context.close()}
});
