import {test,expect,chromium} from '@playwright/test';
import {startCanonicalFixture} from './fixtures/canonical-server';

test('built canonical menu uses real waiting worker and only initiating tab reloads',async({},info)=>{
 test.skip(info.project.name.startsWith('mobile'),'Real two-tab worker integration runs once');const fixture=await startCanonicalFixture();
 const browser=await chromium.launch({args:['--ignore-certificate-errors',`--host-resolver-rules=MAP dev-lm.mw-credit.com 127.0.0.1:${fixture.port},MAP mw-credit-app-dev-737787224638.web.app 127.0.0.1:${fixture.port}`,'--no-proxy-server']});const context=await browser.newContext();
 try{
  await context.route('**/*',r=>['dev-lm.mw-credit.com','mw-credit-app-dev-737787224638.web.app'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
  const page=await context.newPage();await page.goto('https://dev-lm.mw-credit.com');await expect(page.locator('link[rel=manifest]')).toHaveAttribute('href','/manifest.webmanifest');await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await expect(page.getByRole('button',{name:'Update and reload',exact:true})).toHaveCount(0);
  const manifest=await page.evaluate(async()=>await(await fetch('/manifest.webmanifest')).json());expect(manifest).toMatchObject({id:'/',start_url:'/',scope:'/',name:'MW Credit DEV',short_name:'MW Credit DEV',display:'standalone',theme_color:'#e8710a',background_color:'#ffffff'});for(const size of [192,512]){const icon=manifest.icons.find((i:any)=>i.sizes===size+'x'+size);expect(icon.purpose).toBe('any');const dimensions=await page.evaluate(async url=>{const image=new Image();image.src=url;await image.decode();return[image.naturalWidth,image.naturalHeight]},icon.src);expect(dimensions).toEqual([size,size])}
  await page.evaluate(()=>{(window as any).promptCalls=0;const event=new Event('beforeinstallprompt',{cancelable:true});Object.assign(event,{prompt:async()=>{(window as any).promptCalls++},userChoice:Promise.resolve({outcome:'dismissed'})});window.dispatchEvent(event)});await expect(page.getByRole('button',{name:'Install app',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).promptCalls)).toBe(0);await page.getByRole('button',{name:'Install app',exact:true}).click();expect(await page.evaluate(()=>(window as any).promptCalls)).toBe(1);await expect(page.getByRole('button',{name:'Install app',exact:true})).toHaveCount(0);await page.screenshot({path:'outputs/r052-pwa-install/canonical-menu-desktop.png'});
  const second=await context.newPage();await second.goto('https://dev-lm.mw-credit.com');await expect(second.locator('.startup-version')).toHaveCount(0);await expect(page.locator('.startup-version')).toHaveCount(0);await second.evaluate(()=>document.body.dataset.context='keep');let firstLoads=0,secondLoads=0;page.on('load',()=>firstLoads++);second.on('load',()=>secondLoads++);
  fixture.setVersion('B');await page.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration())!.update()});await expect(page.getByRole('button',{name:'Update and reload',exact:true})).toBeVisible();expect(firstLoads).toBe(0);expect(secondLoads).toBe(0);await page.screenshot({path:'outputs/r052-pwa-install/canonical-update-waiting.png'});await page.evaluate(()=>{(window as any).originalPost=ServiceWorker.prototype.postMessage;ServiceWorker.prototype.postMessage=function(){throw Error('synthetic delivery failure')}});await page.getByRole('button',{name:'Update and reload',exact:true}).click();await expect(page.getByRole('button',{name:'Update and reload',exact:true})).toBeEnabled();expect(firstLoads).toBe(0);await page.evaluate(()=>{ServiceWorker.prototype.postMessage=(window as any).originalPost});await page.getByRole('button',{name:'Update and reload',exact:true}).click();await expect.poll(()=>firstLoads).toBe(1);await expect(second.getByRole('button',{name:'Reload app',exact:true})).toBeVisible();expect(secondLoads).toBe(0);expect(await second.evaluate(()=>document.body.dataset.context)).toBe('keep');await second.getByRole('button',{name:'Reload app',exact:true}).click();await expect.poll(()=>secondLoads).toBe(1);
  const fallback=await context.newPage();await fallback.goto('https://mw-credit-app-dev-737787224638.web.app');await expect(fallback.locator('link[rel=manifest]')).toHaveCount(0);expect(await fallback.evaluate(async()=>(await navigator.serviceWorker.getRegistrations()).length)).toBe(0);
  const mobile=await browser.newContext({viewport:{width:320,height:844}});await mobile.route('**/*',r=>new URL(r.request().url()).hostname==='dev-lm.mw-credit.com'?r.continue():r.abort());const m=await mobile.newPage();await m.goto('https://dev-lm.mw-credit.com');await expect.poll(()=>m.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await m.getByRole('button',{name:'Open navigation',exact:true}).click();await expect(m.getByRole('button',{name:'Install app',exact:true})).toHaveCount(0);await m.screenshot({path:'outputs/r052-pwa-install/canonical-menu-mobile.png'});await m.getByRole('button',{name:'ไทย',exact:true}).click();await m.screenshot({path:'outputs/r052-pwa-install/canonical-menu-mobile-th.png'});await mobile.setOffline(true);await m.goto('https://dev-lm.mw-credit.com');await expect(m.getByRole('heading',{name:'Connection required'})).toBeVisible();expect(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await m.screenshot({path:'outputs/r052-pwa-install/offline-mobile.png'});await mobile.close();
 }finally{await context.close();await browser.close();await fixture.close()}
});
