import {test,expect,type Page} from '@playwright/test';
import {chooseLanguage} from './live-controls';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdirSync,writeFileSync} from 'node:fs';
let server:ChildProcess,base:string;
test.beforeAll(async({},info)=>{const port=6700+info.workerIndex;base=`http://127.0.0.1:${port}`;server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/receiving-ux-${port}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-key',VITE_FIREBASE_APP_ID:'synthetic-app',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app',VITE_COMMAND_API_ORIGIN:'https://mw-credit-app-command-dev-test.run.app',VITE_COMMAND_MODE:'dev-owner-testing'},stdio:'pipe'});await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return 0}},{timeout:20000}).toBe(200)});
test.afterAll(()=>server?.kill());test.setTimeout(60000);
const auth=`let listener;const user={uid:'receiving-ux-owner',getIdToken:async()=>'synthetic-bearer'};export const browserLocalPersistence='local',inMemoryPersistence='memory',browserPopupRedirectResolver={};export function initializeAuth(){return {}};export function onAuthStateChanged(a,fn){listener=fn;fn(localStorage.getItem('ux-owner')?user:null);return()=>{}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){localStorage.setItem('ux-owner','1');listener(user)};export async function signOut(){localStorage.removeItem('ux-owner');listener(null)};`;
const borrower={id:'ux-B',displayName:'UX ผู้กู้จำลอง / Synthetic borrower',borrowerDisplayName:'UX ผู้กู้จำลอง / Synthetic borrower',status:'not_paid',amountDue:'520',amountCollected:'0',amountRemaining:'520',hasActiveLoan:true,outstandingPrincipal:'520',totalProfitEarned:'0'};
const due=Array.from({length:52},(_,i)=>({id:'ux-C'+String(i).padStart(2,'0'),chargeDate:'2026-10-07',loanDisplayKey:'UX loan / เงินกู้จำลอง',amountRemaining:'10',principalRemaining:'10',interestRemaining:'0'}));
const future=[{id:'ux-F1',chargeDate:'2026-10-09',loanDisplayKey:'Future synthetic loan',amountRemaining:'7',principalRemaining:'7',interestRemaining:'0'},{id:'ux-F2',chargeDate:'2026-10-09',loanDisplayKey:'Future synthetic loan',amountRemaining:'9',principalRemaining:'9',interestRemaining:'0'}];
const draft={ok:true,mode:'dev-owner-testing',scope:'all',businessDate:'2026-10-08',asOf:'2026-10-08T05:00:00Z',borrower:{id:borrower.id,displayName:borrower.displayName},accounts:[{id:'ux-A',label:'Synthetic receiving account'},{id:'ux-A2',label:'Second synthetic account'}]};
type Fixture={posts:any[];reviewRequests:any[];draftRequests:string[];releaseReview?:()=>void;holdReview:boolean;reviewStatus:number;lost:boolean;readRequests:string[];holdChildren:boolean;holdHistory:boolean;releaseCharges?:()=>void;releaseHistory?:()=>void};
async function setup(page:Page,holdChildren=false){
 const state:Fixture={posts:[],reviewRequests:[],draftRequests:[],holdReview:false,reviewStatus:200,lost:false,readRequests:[],holdChildren,holdHistory:false};
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:auth}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{const u=new URL(r.request().url());state.readRequests.push(u.pathname+u.search);const charges=u.pathname.endsWith('/charges'),upcoming=u.pathname.endsWith('/upcoming');if(charges&&state.holdChildren)await new Promise<void>(resolve=>state.releaseCharges=resolve);return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'dev',businessDate:draft.businessDate,timezone:'Asia/Bangkok',asOf:draft.asOf,items:upcoming?[]:charges?due.slice(0,25).map(x=>({...x,loanId:'ux-L',paymentStatus:'ยังไม่ชำระ',paymentDate:null,totalPaid:'0',receivedToday:'0'})):[borrower],borrower,nextCursor:null,horizonEnd:'2027-01-08',reviewRequired:false})})});
 await page.route('https://mw-credit-app-command-dev-test.run.app/**',async r=>{
  const u=new URL(r.request().url()),path=u.pathname;
  if(path.includes('payment-drafts')){
   if(path.endsWith('/review')){const b=r.request().postDataJSON();state.reviewRequests.push(b);if(state.holdReview)await new Promise<void>(resolve=>state.releaseReview=resolve);const charges=[...due,...future].filter(x=>b.allocations.some((line:any)=>line.chargeId===x.id));return r.fulfill({status:state.reviewStatus,contentType:'application/json',body:JSON.stringify(state.reviewStatus===200?{...draft,charges,nextCursor:null,total:String(charges.reduce((n,x)=>n+Number(x.amountRemaining),0))}:{ok:false,code:'selection_unavailable'})}).catch(()=>{})}
   if(path.endsWith('/select-all'))return r.fulfill({contentType:'application/json',body:JSON.stringify({...draft,charges:due,nextCursor:null,total:'520'})});
   state.draftRequests.push(u.search);const cursor=Number(u.searchParams.get('cursor')||0),all=[...due,...future];return r.fulfill({contentType:'application/json',body:JSON.stringify({...draft,charges:all.slice(cursor,cursor+25),nextCursor:cursor+25<all.length?String(cursor+25):null})});
  }
  if(path.endsWith('/payments')){if(state.holdHistory)await new Promise<void>(resolve=>state.releaseHistory=resolve);return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,items:[],nextCursor:null})});}
  if(r.request().method()==='POST'){state.posts.push(r.request().postDataJSON());if(state.lost)return r.abort('failed');return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,kind:'recorded',originalOutcome:{status:'posted',paymentId:'synthetic-ux-payment',code:null,recordedAt:draft.asOf}})})}
  if(path.endsWith('/result'))return r.fulfill({status:503,contentType:'application/json',body:'{"ok":false}'});
  return r.fulfill({contentType:'application/json',body:'{"ok":true,"kind":"unresolved","safeToUseNewRequestId":false}'});
 });
 await page.goto(base);await expect(page.getByRole('button',{name:/Google/})).toBeVisible();await page.getByRole('button',{name:/Google/}).click();await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Collection',exact:true}).click();await page.locator('.collection-borrower').first().click();await expect(page.getByRole('button',{name:'Receive selected charges',exact:true})).toBeVisible();return state;
}
async function openReceiving(page:Page){await page.getByRole('button',{name:'Receive selected charges',exact:true}).click();await expect(page.getByRole('textbox',{name:'Amount received',exact:true})).toBeVisible()}
async function savedRepo(page:Page){return page.evaluate(async()=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');return ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'receiving-ux-owner'}).list('draft')})}
for(const width of [1440,390,320])test(`UX1 compact receiving screenshot and accessible controls ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:900});const fixture=await setup(page);const button=page.getByRole('button',{name:'Receive selected charges',exact:true});await expect(page.locator('.related-loans-heading').filter({has:button})).toHaveCount(1);expect(await page.locator('.collection-charges-heading').evaluate(e=>getComputedStyle(e).display)).toBe('grid');const receiveBox=await button.boundingBox(),headerBox=await page.locator('.collection-charges-heading').boundingBox();expect(receiveBox!.x+receiveBox!.width).toBeGreaterThan(headerBox!.x+headerBox!.width-30);expect(await button.boundingBox()).toMatchObject({width:expect.any(Number)});for(const collectionLanguage of ['EN','ไทย'] as const){await chooseLanguage(page,collectionLanguage);mkdirSync('outputs/r052-unified-receiving',{recursive:true});await page.screenshot({path:'outputs/r052-unified-receiving/collection-'+info.project.name+'-'+width+'-'+(collectionLanguage==='ไทย'?'th':'en')+'.png'});}await chooseLanguage(page,'EN');await openReceiving(page);
 for(const language of ['EN','ไทย'] as const){await chooseLanguage(page,language);const thai=language==='ไทย',receive=page.getByRole('button',{name:thai?'ตรวจสอบการรับชำระ':'Review payment',exact:true});await expect(receive).toBeVisible();await expect(page.getByRole('textbox',{name:thai?'ยอดรับชำระ':'Amount received',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/^(Receive all due charges|Future charge — Single Full|Save unsent draft|Discard unsent draft)$/})).toHaveCount(0);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(width);const rect=await receive.boundingBox();expect(rect!.width).toBeGreaterThanOrEqual(44);expect(rect!.height).toBeGreaterThanOrEqual(44);mkdirSync('outputs/r052-unified-receiving',{recursive:true});await page.screenshot({path:`outputs/r052-unified-receiving/independent-${info.project.name}-${width}-${thai?'th':'en'}.png`});}expect(fixture.posts).toHaveLength(0);
});
test('UX2/3 unified manual due/future plan and previous cursor refetch',async({page})=>{
 const fixture=await setup(page);await openReceiving(page);await expect(page.getByRole('button',{name:'Previous charge page',exact:true})).toHaveCount(0);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('10');await page.locator('.payment-allocation-row').first().getByRole('textbox',{name:/Principal for/}).fill('10');await page.getByRole('button',{name:'Next charge page',exact:true}).click();await expect(page.getByRole('button',{name:'Previous charge page',exact:true})).toBeVisible();await page.getByRole('button',{name:'Next charge page',exact:true}).click();await expect(page.getByRole('button',{name:'Next charge page',exact:true})).toHaveCount(0);await page.locator('.payment-allocation-row').filter({hasText:'Future synthetic loan'}).first().getByRole('textbox',{name:/Principal for/}).fill('7');await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('17');await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Previous charge page',exact:true}).click();await expect.poll(()=>fixture.draftRequests.filter(x=>x.includes('cursor=25')).length).toBe(2);await page.getByRole('button',{name:'Previous charge page',exact:true}).click();await expect(page.getByRole('button',{name:'Previous charge page',exact:true})).toHaveCount(0);await expect(page.locator('.payment-allocation-row').first().getByRole('textbox',{name:/Principal for/})).toHaveValue('10');expect(fixture.posts).toHaveLength(0);
});
test('UX7 quiet autosave latest draft retains tender/account/Thai edits with no POST',async({page})=>{
 const fixture=await setup(page);await openReceiving(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('10');await page.locator('.payment-allocation-row').first().getByRole('textbox',{name:/Principal for/}).fill('10');await page.getByRole('combobox',{name:'Payment method',exact:true}).selectOption('Cash');await page.getByRole('combobox',{name:'Receiving account',exact:true}).selectOption('ux-A2');await page.getByRole('textbox',{name:'Notes',exact:true}).fill('old');await page.getByRole('textbox',{name:'Notes',exact:true}).fill('ล่าสุด ไทย\nnewest');await expect.poll(async()=>{const rows=await savedRepo(page);return rows[0]?.value?.notes}).toBe('ล่าสุด ไทย\nnewest');const saved=(await savedRepo(page))[0].value;expect(saved).toMatchObject({allocations:[{chargeId:'ux-C00',principal:'10',interest:'0'}],account:'ux-A2',paymentMethod:'Cash',notes:'ล่าสุด ไทย\nnewest'});expect(fixture.posts).toHaveLength(0);await page.reload();await page.getByRole('button',{name:'Collection',exact:true}).click();await page.locator('.collection-borrower').first().click();await openReceiving(page);await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('ล่าสุด ไทย\nnewest');await expect(page.getByRole('combobox',{name:'Payment method',exact:true})).toHaveValue('Cash');expect(fixture.posts).toHaveLength(0);
});
test('UX8 immediate review uses existing orange header only, one request and disabled Confirm',async({page},info)=>{
 const fixture=await setup(page);await openReceiving(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('10');await page.locator('.payment-allocation-row').first().getByRole('textbox',{name:/Principal for/}).fill('10');fixture.holdReview=true;const before=await page.locator('.topbar').boundingBox(),start=Date.now();await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeVisible();const visibleMs=Date.now()-start;await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeDisabled();await expect.poll(()=>fixture.reviewRequests.length).toBe(1);await expect(page.locator('.topbar')).toContainText(/Loading|Checking|Updating/);await expect(page.locator('.selected-payment').getByText(/Checking current amounts|Loading…/)).toHaveCount(0);const after=await page.locator('.topbar').boundingBox();expect(after!.height).toBe(before!.height);fixture.holdReview=false;fixture.releaseReview!();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeEnabled();expect(fixture.posts).toHaveLength(0);mkdirSync('outputs/r052-unified-receiving',{recursive:true});writeFileSync(`outputs/r052-unified-receiving/review-visibility-${info.project.name}.json`,JSON.stringify({synthetic:true,visibleMs,reviewRequests:fixture.reviewRequests.length,headerHeightBefore:before!.height,headerHeightAfter:after!.height},null,2));
});
test('UX6 recorded response returns Collection without secondary result wait; autosave cannot revive Posted draft',async({page})=>{
 const fixture=await setup(page);await openReceiving(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('10');await page.locator('.payment-allocation-row').first().getByRole('textbox',{name:/Principal for/}).fill('10');await page.getByRole('combobox',{name:'Payment method',exact:true}).selectOption('Net-off at Disbursement');await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Confirm payment online',exact:true}).click();await expect(page.getByRole('heading',{name:'Collection borrowers',exact:true})).toBeVisible();expect(fixture.posts).toHaveLength(1);expect(fixture.posts[0]).toMatchObject({schemaVersion:6,paymentMethod:'Net-off at Disbursement',allocations:[{chargeId:'ux-C00',principal:'10',interest:'0'}],amountReceived:'10'});await expect.poll(async()=> (await savedRepo(page)).length).toBe(0);
});



test('UX7 draft quota failure is visible and does not dispatch or claim saved',async({page})=>{
 const fixture=await setup(page);await openReceiving(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;(window as any).uxOriginalPut=original;IDBObjectStore.prototype.put=function(value:any,...rest:any[]){if(value.kind==='draft')throw new DOMException('Synthetic quota','QuotaExceededError');return original.call(this,value,...rest)}});await page.getByRole('textbox',{name:'Notes',exact:true}).fill('must not claim saved');await expect(page.getByRole('alert')).toContainText('Draft could not be saved');expect(fixture.posts).toHaveLength(0);expect((await savedRepo(page))[0]?.value?.notes).not.toBe('must not claim saved');await page.evaluate(()=>{IDBObjectStore.prototype.put=(window as any).uxOriginalPut});await page.getByRole('textbox',{name:'Notes',exact:true}).fill('recovered latest');await expect.poll(async()=> (await savedRepo(page))[0]?.value?.notes).toBe('recovered latest');expect(fixture.posts).toHaveLength(0);
});
test('UX8 cancelled delayed review cannot revive Confirm; failed fresh review never dispatches',async({page})=>{
 const fixture=await setup(page);await openReceiving(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('10');await page.locator('.payment-allocation-row').first().getByRole('textbox',{name:/Principal for/}).fill('10');fixture.holdReview=true;await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect.poll(()=>!!fixture.releaseReview).toBe(true);await page.getByRole('button',{name:'Back to Collection',exact:true}).click();fixture.holdReview=false;fixture.releaseReview!();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toHaveCount(0);expect(fixture.posts).toHaveLength(0);await openReceiving(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('10');await page.locator('.payment-allocation-row').first().getByRole('textbox',{name:/Principal for/}).fill('10');fixture.reviewStatus=409;await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect(page.getByRole('alert')).toContainText(/selection changed|review/i);await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toHaveCount(0);expect(fixture.posts).toHaveLength(0);
});

test('UX7 Clear draft cancels queued edits and offline transition cannot revive it',async({page,context})=>{
 const fixture=await setup(page);await openReceiving(page);await page.getByRole('textbox',{name:'Notes',exact:true}).fill('durable old draft');await expect.poll(async()=> (await savedRepo(page))[0]?.value?.notes).toBe('durable old draft');await page.getByRole('textbox',{name:'Notes',exact:true}).fill('queued newer edit');await page.getByLabel('Payment options',{exact:true}).click();await page.getByRole('button',{name:'Clear draft',exact:true}).click();await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('');await expect.poll(async()=> (await savedRepo(page)).length).toBe(0);await context.setOffline(true);await page.waitForTimeout(650);expect(await savedRepo(page)).toHaveLength(0);expect(fixture.posts).toHaveLength(0);await context.setOffline(false);
});


test('UX8 overlapping charge and history requests keep the orange header busy until both settle',async({page})=>{
 const fixture=await setup(page,true);await expect.poll(()=>!!fixture.releaseCharges).toBe(true);fixture.holdHistory=true;await page.getByRole('button',{name:'Payment history',exact:true}).click();await expect.poll(()=>!!fixture.releaseHistory).toBe(true);await expect(page.locator('.topbar')).toContainText('Loading');await expect(page.locator('main').getByText(/^Loading…$|Checking current amounts|Checking saved workspace access/)).toHaveCount(0);fixture.holdHistory=false;fixture.releaseHistory!();await page.waitForTimeout(50);await expect(page.locator('.topbar')).toContainText('Loading');fixture.holdChildren=false;fixture.releaseCharges!();await expect(page.locator('.topbar')).toContainText('Updated');expect(fixture.posts).toHaveLength(0);
});


