import {chooseLanguage,signOut} from './live-controls';
import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
let server:ChildProcess;let base:string;let serverLog="";
test.beforeAll(async({},info)=>{
 const port=5900+info.workerIndex;base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/playwright-live-${port}-${Date.now()}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-test-key',VITE_FIREBASE_APP_ID:'synthetic-app-id',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app'},stdio:'pipe'});
 server.stdout?.on("data",data=>{serverLog+=String(data)});server.stderr?.on("data",data=>{serverLog+=String(data)});
 await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return0()}},{timeout:20000}).toBe(200);
});
function return0(){return 0}
test.afterAll(()=>server?.kill()); test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)console.log(serverLog)});
const authMock=`let listener;export const browserLocalPersistence='local';export const inMemoryPersistence='memory';export const browserPopupRedirectResolver={};export function initializeAuth(a,o){if(o.persistence!=='local')throw Error('persistence');return {}};export function getAuth(){return {}};export async function setPersistence(a,p){if(p!=='local')throw Error('persistence');}export function onAuthStateChanged(a,fn){listener=fn;fn(null);return()=>{listener=null}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){listener({uid:'synthetic-owner',getIdToken:async()=>'synthetic-bearer'})};export async function signOut(){listener(null)};`;
const borrowers=Array.from({length:27},(_,i)=>({id:`private-b-${i}`,name:`ชื่อ ${i+1}`,borrowerDisplayName:`ชื่อ ${i+1} - English ${i+1}`,totalProfitEarned:i===0?'-12.34':i===1?'0':null,createdDate:'2026-10-07',hasActiveLoan:i<24?true:i<26?false:null,outstandingPrincipal:'9000',note:null}));
const loans=Array.from({length:27},(_,i)=>({id:`private-l-${i}`,borrowerId:'private-b-24',borrowerDisplayName:'ชื่อผู้กู้ตัวอย่างสำหรับทดสอบข้อความยาว - Synthetic borrower with a deliberately long English name',originalDailyInterestRate:i===0?'0':i===26?null:'2',loanDate:i===26?null:'2026-10-07',dueDate:null,closeDate:null,status:i<24?'ยังไม่ปิดยอด':i<26?'ปิดยอดแล้ว':'unexpected',loanType:'ดอกเบี้ยรายวัน',principalAmount:String(12000+i),outstandingPrincipal:'123.45',totalPrincipalReceived:'0',totalInterestReceived:null,totalAmountReceived:'0',defaulted:false,autoChargeEnabled:false}));

test.use({hasTouch:true});
test('tablet touch keyboard and narrow effective-viewport reflow gaps',async({page},info)=>{
 test.skip(!info.project.name.startsWith('desktop'),'Single gap check covers three responsive widths');
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',r=>{const u=new URL(r.request().url()),nested=u.pathname.includes('/loans');return r.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({ok:true,source:'dev',items:nested?loans.slice(0,25):borrowers.slice(0,2),item:nested?loans.find(l=>u.pathname.endsWith('/'+l.id)):borrowers[0],nextCursor:null,asOf:'2026-10-07T05:00:00Z'})})});
 for(const width of [1024,768,640]){
 await page.setViewportSize({width,height:900});await page.goto(base);await page.getByRole('button',{name:'Continue with Google'}).click();await expect(page.locator('.borrower-tile-main')).toHaveCount(2);await page.locator('.borrower-tile-main').first().tap();await expect(page.locator('.loan-record')).toHaveCount(25);await page.locator('.loan-record').last().tap();await expect(page.getByRole('article',{name:'Loan details'})).toBeVisible();
 const back=page.getByRole('button',{name:'Back to loans'});const b=await back.boundingBox(),header=await page.locator('.topbar').boundingBox(),bottom=await page.locator('.live-bottom-nav').boundingBox();expect(b!.y).toBeGreaterThanOrEqual(header!.y+header!.height);expect(b!.y+b!.height).toBeLessThan(bottom!.y);await back.tap();await page.locator('.loan-record').last().scrollIntoViewIfNeeded();const refresh=await page.locator('.loan-record').last().boundingBox();expect(refresh!.y+refresh!.height).toBeLessThanOrEqual(bottom!.y);
 await page.getByRole('button',{name:'Open navigation',exact:true}).tap();const menu=page.getByRole('dialog',{name:'Navigation menu'});for(let i=0;i<5;i++){await page.keyboard.press('Tab');expect(await menu.evaluate(e=>e.contains(document.activeElement))).toBe(true)}await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Open navigation',exact:true})).toBeFocused();await chooseLanguage(page,'ไทย');expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:'outputs/r052-custom-domain/gap-'+width+'-th.png'});
 }
});
