import {test,expect,chromium,devices,type Page} from '@playwright/test';
import {spawnSync} from 'node:child_process';import{mkdtempSync,rmSync,readFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{startCanonicalFixture}from'./fixtures/canonical-server';import{chooseLanguage}from'./live-controls';
let fixture:any,root:string,owned=false,mobile=false;const builds:Record<string,string>={};test.beforeEach(async({},info)=>{mobile=info.project.name.startsWith('mobile')});
test.beforeAll(async()=>{root=mkdtempSync(join(tmpdir(),'mw-startup-generations-'));owned=true;for(const label of ['A','B','C']){builds[label]=join(root,label);const transform=(code:string,id:string)=>{if(id.endsWith('/apps/pwa/src/live-main.tsx'))return code+';import {getAuth as fixtureGetAuth,signInWithCustomToken as fixtureSignIn} from "firebase/auth";globalThis.__syntheticSdk={fixtureGetAuth,fixtureSignIn};import {ownerOfflineRepository as fixtureRepository} from "./owner-offline";globalThis.__syntheticRepo=fixtureRepository;globalThis.__syntheticBuildLabel='+JSON.stringify(label)+';';};const script='import{build}from"vite";await build(Object.assign('+JSON.stringify({mode:'live-dev',build:{outDir:builds[label],emptyOutDir:true}})+',{plugins:[{name:"synthetic-sdk-bridge",enforce:"pre",transform:'+transform.toString().replace('JSON.stringify(label)',JSON.stringify(JSON.stringify(label)))+'}]}));';const result=spawnSync(process.execPath,['--input-type=module','-e',script],{encoding:'utf8',env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-key',VITE_FIREBASE_APP_ID:'synthetic-app',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app',VITE_COMMAND_API_ORIGIN:'https://mw-credit-app-command-dev-test.run.app',VITE_COMMAND_MODE:'dev-owner-testing'}});expect(result.status,result.stderr).toBe(0)}fixture=await startCanonicalFixture(builds.A)});
test.afterAll(async()=>{await fixture?.close();if(owned)rmSync(root,{recursive:true,force:true})});test.setTimeout(45000);
const v='a'.repeat(64),v2='b'.repeat(64),uid='synthetic-phase5-final-owner',requestId='07eae274-c4e9-44e9-bff4-900c3bf37c9b',receiptId='fe93a8d6-3050-449e-9bba-949da4acf246';
const borrower={id:'C-borrower',borrowerDisplayName:'SYNTHETIC final borrower',createdDate:null,hasActiveLoan:true,outstandingPrincipal:'110',totalProfitEarned:'0'};
const accounts=[{id:'C-account',label:'Synthetic account',holderId:'ch:lisa',holderLabel:'Lisa'}];
const closeA={ok:true,businessDate:'2026-10-09',sourceVersion:v,amount:'115',planHash:v,accounts};
const closeDraft={kind:'close',item:{id:'C-loan',borrowerId:borrower.id,borrowerDisplayName:borrower.borrowerDisplayName},requestId,preview:closeA,account:'C-account',method:'Cash',notes:'exact saved close ไทย',receipt:receiptId,receiptName:'synthetic.png'};
const fields={borrowerId:borrower.id,amountReceived:'10',paymentDate:'2026-10-09',paymentMethod:'Cash',cashAccountId:'C-account',notes:'exact saved correction ไทย',allocationMethod:'Selected Charges',targetChargeId:null,targetLoanId:null};
const line={chargeId:'C-charge',principal:'8',interest:'2',expectedPrincipalRemaining:'10',expectedInterestRemaining:'5',chargeDate:'2026-10-09'};
const previewA={origin:'pwa-plan',sourceVersion:v,predecessorRequestId:requestId,source:{id:'C-payment',borrowerName:borrower.borrowerDisplayName,...fields,receiptReference:'synthetic-reference',allocations:[]},balances:[{chargeId:'C-charge',loanId:'C-loan',chargeDate:'2026-10-09',principalRemaining:'10',interestRemaining:'5'}],loans:[]};
const correctionDraft={kind:'correction',id:'C-payment',requestId,preview:previewA,fields,accounts,lines:{'C-charge':line},closeHash:null,receiptMode:'replace',receiptId};
const preferenceA={item:{id:'C-partner',version:v,language:'English',statementAccountId:'C-account',statementDate:'2026-10-09'},accounts,dates:['2026-10-09']};
type S={posts:any[],pendingAtPost:any[],close:any,correction:any,preferences:any,deleted:boolean,receiptReads:string[],manualFail:boolean,record:any};
async function repo(page:Page,kind:string){return page.evaluate(async kind=>(window as any).__syntheticRepo({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'synthetic-phase5-final-owner'}).list(kind),kind)}
async function seed(page:Page,domain:string,id:string,draft:any){await page.evaluate(async({domain,id,draft})=>{await(window as any).__syntheticRepo({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'synthetic-phase5-final-owner'}).saveDraft(domain+':'+id,{domain,label:'Synthetic '+domain+' final draft',draft})},{domain,id,draft})}
async function saved(page:Page,label:string){if(page.viewportSize()!.width<=1050)await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:'Saved payment drafts',exact:true}).filter({visible:true}).click();await page.getByRole('button',{name:new RegExp('^'+label)}).click()}
async function launch(setup?:(context:any,page:Page)=>Promise<void>){console.log('C static stage: launch');
 const context=await chromium.launchPersistentContext('',{headless:true,...(mobile?devices['Pixel 7']:devices['Desktop Chrome']),viewport:{width:320,height:900},args:['--ignore-certificate-errors','--host-resolver-rules=MAP dev-lm.mw-credit.com 127.0.0.1:'+fixture.port,'--no-proxy-server']});console.log('C static stage: context ready');const page=await context.newPage();page.on('pageerror',e=>console.log('C synthetic pageerror: '+e.message));const now=Math.floor(Date.now()/1000),token=[{alg:'none',typ:'JWT'},{sub:uid,user_id:uid,aud:'clever-oasis-508610-n7',iss:'https://securetoken.google.com/clever-oasis-508610-n7',iat:now,exp:now+3600,auth_time:now,email:'synthetic@example.test',email_verified:true,firebase:{sign_in_provider:'custom'}}].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.')+'.synthetic';
 const s:S={posts:[],pendingAtPost:[],close:closeA,correction:previewA,preferences:preferenceA,deleted:false,receiptReads:[],manualFail:true,record:null};
 await context.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname==='dev-lm.mw-credit.com')return r.continue();if(u.hostname==='identitytoolkit.googleapis.com')return r.fulfill({contentType:'application/json',body:JSON.stringify(u.pathname.includes('signInWithCustomToken')?{idToken:token,refreshToken:'synthetic-refresh',expiresIn:'3600',isNewUser:false}:{users:[{localId:uid,email:'synthetic@example.test',emailVerified:true,providerUserInfo:[]}]})});if(u.hostname==='mw-credit-app-read-dev-test.run.app')return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'dev',businessDate:'2026-10-09',horizonEnd:'2027-01-09',reviewRequired:false,items:u.pathname.includes('/loans')||u.pathname.endsWith('/upcoming')?[]:[borrower],item:borrower,borrower,nextCursor:null,asOf:new Date().toISOString()})});
 if(u.hostname==='mw-credit-app-command-dev-test.run.app'){
 let data:any={ok:true,items:[],nextCursor:null};
 if(r.request().method()!=='GET'){s.posts.push({path:u.pathname,body:r.request().postDataJSON()});s.pendingAtPost.push(await repo(page,'pending'));return r.abort('failed')}
 if(u.pathname.endsWith('/close-preview'))data=s.close;
 else if(u.pathname.endsWith('/correction-preview')){if(s.deleted)return r.fulfill({status:404,body:'{}'});data={ok:true,item:s.correction}}
 else if(u.pathname==='/api/preferences')data=s.preferences;
 else if(u.pathname==='/api/cash-overview')data={dashboard:{},accounts:[]};
 else if(u.pathname==='/api/cash-statements')data={summary:{openingBalance:'20',moneyIn:'5',moneyOut:'10',netMovement:'-5',closingBalance:'15',transactionCount:1},items:[{id:'C-ledger',date:'2026-10-09',transactionType:'Payment details',amount:'5',balanceAfter:'15',paymentId:'C-payment',notes:'synthetic ledger note'}],nextCursor:null};
 else if(u.pathname.endsWith('/receipt')){const source=u.searchParams.get('source')??'preferred';s.receiptReads.push(source);if(source!=='agent'&&s.manualFail)return r.fulfill({status:422,body:'{}'});return r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7ZkAAAAASUVORK5CYII=','base64')})}
 else if(u.pathname.startsWith('/api/payment-records/'))data={ok:true,item:{...s.record,asOf:new Date().toISOString(),businessDate:'2026-10-09'}};
 else if(u.pathname==='/api/borrower-options')data={ok:true,accounts,referrers:[{id:'C-other',label:'Synthetic destination'}]};
 return r.fulfill({contentType:'application/json',body:JSON.stringify(data)})}return r.abort()});
 await context.route('https://mw-credit-app-command-dev-test.run.app/api/dashboard',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({collection:{notPaid:0,partiallyPaid:0,overdue:0,fullyPaid:0},forecast:{},portfolio:{},incomeMtd:{},businessCashHeld:[]})}));if(setup)await setup(context,page);await page.goto('https://dev-lm.mw-credit.com');console.log('C static stage: page loaded');await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await page.evaluate(async()=>{const sdk=(window as any).__syntheticSdk;await sdk.fixtureSignIn(sdk.fixtureGetAuth(),'synthetic-custom-token')});console.log('C static stage: SDK signed in');return{context,page,s};
}


test('real startup gates reads across held metadata failed asset retry and three builds without forcing old edited tab',async()=>{fixture.hold('/build-version.json');let apiReads=0;const{context,page,s}=await launch(async context=>{context.on('request',(request:any)=>{if(/mw-credit-app-(command|read)-dev-test/.test(request.url()))apiReads++})});let old:any;try{await expect(page.getByRole('heading',{name:'Checking app version…',exact:true})).toBeVisible();expect(apiReads).toBe(0);fixture.release('/build-version.json');await expect(page.getByRole('heading',{name:'KPIs',exact:true})).toBeVisible();const initialReads=apiReads;expect(initialReads).toBeGreaterThan(0);await seed(page,'loan','close:C-loan',closeDraft);await page.evaluate(async({requestId})=>{await(window as any).__syntheticRepo({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'synthetic-phase5-final-owner'}).savePending(requestId,{domain:'loan',command:{requestId,operation:'loan.close'}})},{requestId});old=await context.newPage();await old.goto('https://dev-lm.mw-credit.com');await expect(old.getByRole('heading',{name:'KPIs',exact:true})).toBeVisible();await saved(old,'Synthetic loan final draft');await expect(old.getByRole('region',{name:'Closing amount',exact:true}).locator('dd').last()).toHaveText('฿115');await old.getByRole('textbox',{name:'Notes',exact:true}).fill('old tab exact latest ไทย');await expect.poll(async()=>(await repo(old,'draft'))[0].value.draft.notes).toBe('old tab exact latest ไทย');let oldLoads=0;old.on('load',()=>oldLoads++);const oldEntry=JSON.parse(readFileSync(join(builds.A,'build-version.json'),'utf8')).entry;
 const b=JSON.parse(readFileSync(join(builds.B,'build-version.json'),'utf8'));fixture.setBuildRoot(builds.B);fixture.fail(b.entry,503);const baseline=apiReads;await page.reload();await expect(page.getByRole('heading',{name:'Unable to check app version',exact:true})).toBeVisible();expect(apiReads).toBe(baseline);expect(await page.evaluate(()=>(window as any).__syntheticBuildLabel)).toBe('A');const oldVersion=JSON.parse(readFileSync(join(builds.A,'build-version.json'),'utf8')).version;expect(await page.evaluate(()=>caches.keys())).toContain('mw-credit-dev-public-'+oldVersion);expect((await repo(page,'pending'))[0].value.command.requestId).toBe(requestId);fixture.fail(b.entry,null);fixture.hold(b.entry);await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('heading',{name:'App upgrade in progress',exact:true})).toBeVisible();await expect.poll(()=>fixture.heldCount(b.entry)).toBeGreaterThan(0);expect(apiReads).toBe(baseline);let autoLoads=0;page.on('load',()=>autoLoads++);fixture.release(b.entry);await expect.poll(async()=>{try{return await page.evaluate(()=>(window as any).__syntheticBuildLabel)}catch{return null}}).toBe('B');await expect(page.getByRole('heading',{name:'KPIs',exact:true})).toBeVisible();expect(autoLoads).toBe(1);expect(oldLoads).toBe(0);await expect(old.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('old tab exact latest ไทย');expect((await repo(old,'pending'))[0].value.command.requestId).toBe(requestId);
 fixture.setBuildRoot(builds.C);await page.reload();await expect.poll(async()=>{try{return await page.evaluate(()=>(window as any).__syntheticBuildLabel)}catch{return null}}).toBe('C');await expect(page.getByRole('heading',{name:'KPIs',exact:true})).toBeVisible();expect(oldLoads).toBe(0);await expect(old.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('old tab exact latest ไทย');const response=await old.evaluate(async(path:string)=>{const response=await fetch(path);return{status:response.status,body:await response.text()}},oldEntry);expect(response.status).toBe(200);expect(response.body).toContain('__syntheticBuildLabel');expect((await repo(old,'pending'))[0].value.command.requestId).toBe(requestId);const entries=await old.evaluate(async()=>Promise.all((await caches.keys()).map(async name=>(await(await caches.open(name)).keys()).map(r=>new URL(r.url).pathname))));expect(entries.flat().filter(path=>/^\/(api|auth|receipt)\//.test(path))).toEqual([]);expect(s.posts).toHaveLength(0)}finally{fixture.release('/build-version.json');for(const label of ['A','B','C'])fixture.release(JSON.parse(readFileSync(join(builds[label],'build-version.json'),'utf8')).entry);await context.close()}});


