import {test,expect,type Page} from '@playwright/test';
import {chooseLanguage} from './live-controls';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdirSync} from 'node:fs';
let server:ChildProcess,base:string;
test.beforeAll(async({},info)=>{const port=7100+info.workerIndex;base=`http://127.0.0.1:${port}`;server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/unified-independent-${port}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-key',VITE_FIREBASE_APP_ID:'synthetic-app',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app',VITE_COMMAND_API_ORIGIN:'https://mw-credit-app-command-dev-test.run.app',VITE_COMMAND_MODE:'dev-owner-testing'},stdio:'pipe'});await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return 0}},{timeout:20000}).toBe(200)});
test.afterAll(()=>server?.kill());test.setTimeout(45000);
// Explicit synthetic auth/HTTP seams; this file never claims actual Firebase SDK/offline worker proof.
const auth=`let listener;const user={uid:'unified-independent-owner',getIdToken:async()=>'synthetic-bearer'};export const browserLocalPersistence='local',inMemoryPersistence='memory',browserPopupRedirectResolver={};export function initializeAuth(){return {}};export function onAuthStateChanged(a,fn){listener=fn;fn(localStorage.getItem('unified-owner')?user:null);return()=>{}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){localStorage.setItem('unified-owner','1');listener(user)};export async function signOut(){localStorage.removeItem('unified-owner');listener(null)};`;
const borrower={id:'uni-B',displayName:'Unified ผู้กู้จำลอง / Synthetic borrower',borrowerDisplayName:'Unified ผู้กู้จำลอง / Synthetic borrower',status:'not_paid',amountDue:'215',amountCollected:'0',amountRemaining:'215',hasActiveLoan:true,outstandingPrincipal:'230',totalProfitEarned:'0'};
const primary=[{id:'uni-new-z',chargeDate:'2026-10-08',loanDisplayKey:'Newest Z / เงินกู้จำลอง',principalRemaining:'80',interestRemaining:'20',amountRemaining:'100'},{id:'uni-new-a',chargeDate:'2026-10-08',loanDisplayKey:'Newest A / เงินกู้จำลอง',principalRemaining:'60',interestRemaining:'10',amountRemaining:'70'},{id:'uni-old',chargeDate:'2026-10-07',loanDisplayKey:'Older / เงินกู้จำลอง',principalRemaining:'40',interestRemaining:'5',amountRemaining:'45'},{id:'uni-future',chargeDate:'2026-10-09',loanDisplayKey:'Future / เงินกู้จำลอง',principalRemaining:'50',interestRemaining:'7',amountRemaining:'57'}];
const fillers=Array.from({length:30},(_,i)=>({id:'uni-fill'+i,chargeDate:'2026-10-09',loanDisplayKey:'Future filler '+i,principalRemaining:'1',interestRemaining:'0',amountRemaining:'1'}));
const rows=[...primary,...fillers];
const draft={ok:true,mode:'dev-owner-testing',scope:'all',businessDate:'2026-10-08',asOf:'2026-10-08T05:00:00Z',borrower:{id:borrower.id,displayName:borrower.displayName},accounts:[{id:'uni-A',label:'Synthetic receiving account'},{id:'uni-A2',label:'Second synthetic account'}]};
const plan=(row:typeof primary[number],p:string,i:string)=>({chargeId:row.id,principal:p,interest:i,expectedPrincipalRemaining:row.principalRemaining,expectedInterestRemaining:row.interestRemaining,chargeDate:row.chargeDate});
type State={posts:any[],autos:any[],reviews:any[],holdAuto:boolean,holdReview:boolean,releaseAuto?:()=>void,releaseReview?:()=>void,reviewStatus:number,lost:boolean,reviewRows?:typeof rows};
async function setup(page:Page){
 const state:State={posts:[],autos:[],reviews:[],holdAuto:false,holdReview:false,reviewStatus:200,lost:false};
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:auth}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',r=>{const u=new URL(r.request().url()),charges=u.pathname.endsWith('/charges'),upcoming=u.pathname.endsWith('/upcoming');return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'dev',businessDate:draft.businessDate,timezone:'Asia/Bangkok',asOf:draft.asOf,items:upcoming?[]:charges?primary.map(x=>({...x,loanId:'uni-L',paymentStatus:'ยังไม่ชำระ',paymentDate:null,totalPaid:'0',receivedToday:'0'})):[borrower],borrower,nextCursor:null,horizonEnd:'2027-01-08',reviewRequired:false})})});
 await page.route('https://mw-credit-app-command-dev-test.run.app/**',async r=>{
  const u=new URL(r.request().url()),path=u.pathname;
  if(path.includes('/payment-drafts/')){
   if(path.endsWith('/auto-assign')){const body=r.request().postDataJSON();state.autos.push(body);if(state.holdAuto)await new Promise<void>(resolve=>state.releaseAuto=resolve);let remain=BigInt(body.amountReceived);const allocations=[];for(const row of [primary[0],primary[1],primary[2]]){const interest=remain<BigInt(row.interestRemaining)?remain:BigInt(row.interestRemaining);remain-=interest;const principal=remain<BigInt(row.principalRemaining)?remain:BigInt(row.principalRemaining);remain-=principal;if(principal+interest>0n)allocations.push(plan(row,principal.toString(),interest.toString()))}return r.fulfill({contentType:'application/json',body:JSON.stringify({...draft,charges:rows,allocations,amountReceived:body.amountReceived,allocated:(BigInt(body.amountReceived)-remain).toString(),unallocated:remain.toString(),nextCursor:null})}).catch(()=>{})}
   if(path.endsWith('/review')){const body=r.request().postDataJSON();state.reviews.push(body);if(state.holdReview)await new Promise<void>(resolve=>state.releaseReview=resolve);return r.fulfill({status:state.reviewStatus,contentType:'application/json',body:JSON.stringify(state.reviewStatus===200?{...draft,charges:rows.filter(row=>(body.allocations?.map((line:any)=>line.chargeId)??body.selectedChargeIds).includes(row.id)),allocations:body.allocations,total:body.amountReceived,nextCursor:null}:{ok:false,code:'plan_changed',charges:state.reviewRows??rows,businessDate:draft.businessDate})}).catch(()=>{})}
   const cursor=Number(u.searchParams.get('cursor')||0);return r.fulfill({contentType:'application/json',body:JSON.stringify({...draft,charges:rows.slice(cursor,cursor+25),nextCursor:cursor+25<rows.length?String(cursor+25):null})});
  }
  if(path.endsWith('/payments'))return r.fulfill({contentType:'application/json',body:'{"ok":true,"items":[],"nextCursor":null}'});
  if(path.endsWith('/api/payment-commands')&&r.request().method()==='POST'){state.posts.push(r.request().postDataJSON());if(state.lost)return r.abort('failed');return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,kind:'recorded',originalOutcome:{status:'posted',paymentId:'synthetic-unified',code:null,recordedAt:draft.asOf}})});}
  return r.fulfill({contentType:'application/json',body:'{"ok":true,"kind":"unresolved","safeToUseNewRequestId":false}'});
 });
 await page.goto(base);await expect(page.getByRole('button',{name:/Google/})).toBeVisible();await page.getByRole('button',{name:/Google/}).click();await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Collection',exact:true}).click();await page.locator('.collection-borrower').first().click();await page.getByRole('button',{name:'Receive selected charges',exact:true}).click();await expect(page.getByRole('textbox',{name:'Amount received',exact:true})).toBeVisible();return state;
}
const rowFor=(page:Page,key:string)=>page.locator('.payment-allocation-row').filter({hasText:key});
async function manual(page:Page){await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('130');await rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/}).fill('80');await rowFor(page,'Future /').getByRole('textbox',{name:/Principal for/}).fill('50');await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeEnabled()}
async function drafts(page:Page){return page.evaluate(async()=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');return ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'unified-independent-owner'}).list('draft')})}

for(const width of [1440,390,320])test(`U10 compact top amount and persistent summary during embedded scrolling ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:900});const s=await setup(page);await manual(page);
 for(const language of ['EN','ไทย'] as const){await chooseLanguage(page,language);const top=page.getByRole('textbox',{name:language==='EN'?'Amount received':'ยอดรับชำระ',exact:true});await top.scrollIntoViewIfNeeded();const summary=page.locator('.allocation-summary'),before=await summary.boundingBox();expect(before!.y).toBeGreaterThanOrEqual(0);expect(before!.y+before!.height).toBeLessThan(900);const region=page.getByRole('region',{name:language==='EN'?'Payment allocation':'จัดสรรการรับชำระ',exact:true});const bounds=await region.boundingBox();expect(bounds!.height).toBeLessThan(650);await region.evaluate(e=>e.scrollTop=e.scrollHeight);const after=await summary.boundingBox();expect(after!.y).toBe(before!.y);expect(await region.evaluate(e=>e.scrollTop)).toBeGreaterThan(0);expect(await page.locator('body').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(width);await region.evaluate(e=>e.scrollTop=0);mkdirSync('outputs/r052-unified-receiving',{recursive:true});await page.screenshot({path:`outputs/r052-unified-receiving/independent-top-${info.project.name}-${width}-${language==='EN'?'en':'th'}.png`});}
 expect(s.posts).toHaveLength(0);
});

test('U3/U4 exact manual future and amount changes keep splits and block inequality/caps',async({page})=>{
 const s=await setup(page);await manual(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('129');await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('80');await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeDisabled();await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('130');await rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/}).fill('81');await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeDisabled();await rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/}).fill('80');await page.getByRole('combobox',{name:'Payment method',exact:true}).selectOption('Net-off at Disbursement');await page.getByRole('textbox',{name:'Notes',exact:true}).fill('manual ไทย\nfuture exact');await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeEnabled();expect(s.reviews[0].amountReceived).toBe('130');expect(s.reviews[0].allocations).toHaveLength(2);expect(s.reviews[0].allocations).toEqual(expect.arrayContaining([expect.objectContaining({chargeId:'uni-new-z',principal:'80',interest:'0'}),expect.objectContaining({chargeId:'uni-future',principal:'50',interest:'0'})]));expect(s.posts).toHaveLength(0);await page.getByRole('button',{name:'Confirm payment online',exact:true}).click();await expect(page.getByRole('heading',{name:'Collection borrowers',exact:true})).toBeVisible();expect(s.posts).toHaveLength(1);expect(s.posts[0]).toMatchObject({schemaVersion:6,paymentMethod:'Net-off at Disbursement',notes:'manual ไทย\nfuture exact',amountReceived:'130'});expect(s.posts[0]).not.toHaveProperty('allocationMethod');expect(s.posts[0]).not.toHaveProperty('selectedChargeIds');
});

test('U2/U10 Auto fills same editable plan and replacement requires explicit confirmation',async({page})=>{
 const s=await setup(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('130');await page.getByRole('button',{name:'Auto-assign',exact:true}).click();await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('80');await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Interest for/})).toHaveValue('20');await expect(rowFor(page,'Newest A').getByRole('textbox',{name:/Principal for/})).toHaveValue('20');await rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/}).fill('70');await rowFor(page,'Newest A').getByRole('textbox',{name:/Principal for/}).fill('30');let prompted=false;page.once('dialog',async dialog=>{prompted=true;await dialog.dismiss()});await page.getByRole('button',{name:'Auto-assign',exact:true}).click();expect(prompted).toBe(true);await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('70');expect(s.posts).toHaveLength(0);
});

test('U11 delayed Auto cannot replace a newer manual edit',async({page})=>{
 const s=await setup(page);await page.getByRole('textbox',{name:'Amount received',exact:true}).fill('130');s.holdAuto=true;await page.getByRole('button',{name:'Auto-assign',exact:true}).click();await expect.poll(()=>!!s.releaseAuto).toBe(true);await rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/}).fill('70');s.holdAuto=false;s.releaseAuto!();await expect(page.locator('.topbar')).toContainText('Updated');await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('70');expect(s.posts).toHaveLength(0);
});

test('U5/U11 immediate held review uses only header busy and stale result cannot enable Confirm',async({page})=>{
 const s=await setup(page);await manual(page);s.holdReview=true;await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeDisabled();await expect(page.locator('.topbar')).toContainText('Loading');await expect(page.locator('main').getByText(/^Loading…$|Checking current|Checking saved/)).toHaveCount(0);s.reviewStatus=409;s.holdReview=false;s.releaseReview!();await expect(page.getByRole('alert')).toContainText(/plan changed/i);await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toHaveCount(0);await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('80');expect(s.posts).toHaveLength(0);
});

test('U10/U11 autosave retains exact plan/account/method/Thai Notes and reconnect never posts',async({page,context})=>{
 const s=await setup(page);await manual(page);await page.getByRole('combobox',{name:'Receiving account',exact:true}).selectOption('uni-A2');await page.getByRole('combobox',{name:'Payment method',exact:true}).selectOption('Cash');await page.getByRole('textbox',{name:'Notes',exact:true}).fill('preserved ไทย\noffline plan');await expect.poll(async()=> (await drafts(page))[0]?.value?.received).toBe('130');const saved=(await drafts(page))[0].value;expect(saved).toMatchObject({received:'130',account:'uni-A2',paymentMethod:'Cash',notes:'preserved ไทย\noffline plan',allocations:[{chargeId:'uni-new-z',principal:'80',interest:'0',expectedPrincipalRemaining:'80',expectedInterestRemaining:'20'},{chargeId:'uni-future',principal:'50',interest:'0'}]});await context.setOffline(true);await expect(page.getByText('Saved on this device — may be outdated')).toBeVisible();await page.getByRole('button',{name:/Unified ผู้กู้จำลอง/}).click();await rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/}).fill('79');await expect.poll(async()=> (await drafts(page))[0]?.value?.allocations.find((line:any)=>line.chargeId==='uni-new-z')?.principal).toBe('79');await context.setOffline(false);page.once('dialog',dialog=>void dialog.accept());await page.reload();await page.getByRole('button',{name:'Collection',exact:true}).click();await page.locator('.collection-borrower').first().click();await page.getByRole('button',{name:'Receive selected charges',exact:true}).click();await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('79');await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeDisabled();expect(s.posts).toHaveLength(0);expect(s.autos).toHaveLength(0);
});

test('U6/U11 unknown v6 retry preserves the frozen exact original payload',async({page})=>{
 const s=await setup(page);await manual(page);s.lost=true;await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Confirm payment online',exact:true}).click();await expect(page.getByRole('heading',{name:'Outcome unknown',exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:'Amount received',exact:true})).toHaveCount(0);expect(s.posts).toHaveLength(1);const original=JSON.stringify(s.posts[0]);await page.getByRole('button',{name:'Check status',exact:true}).click();await expect(page.getByRole('button',{name:'Retry same command',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Retry same command',exact:true}).click();await expect.poll(()=>s.posts.length).toBe(2);expect(JSON.stringify(s.posts[1])).toBe(original);
});

test('U5 explicit current-balance adoption preserves paid plan and requires fresh review',async({page})=>{
 const s=await setup(page);await manual(page);s.reviewStatus=409;s.reviewRows=rows.map(row=>row.id==='uni-new-z'?{...row,principalRemaining:'85',amountRemaining:'105'}:row);await page.getByRole('button',{name:'Review payment',exact:true}).click();await page.getByRole('button',{name:'Use current balances',exact:true}).click();await expect(page.getByRole('textbox',{name:'Amount received',exact:true})).toHaveValue('130');await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('80');await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toHaveCount(0);s.reviewStatus=200;await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toBeEnabled();expect(s.reviews).toHaveLength(2);expect(s.reviews[1].allocations.find((line:any)=>line.chargeId==='uni-new-z')).toMatchObject({principal:'80',interest:'0',expectedPrincipalRemaining:'85'});expect(s.posts).toHaveLength(0);
});
for(const scenario of ['over-cap','missing'])test('U5 adopted '+scenario+' line preserves money but blocks Review',async({page})=>{
 const s=await setup(page);await manual(page);s.reviewStatus=409;s.reviewRows=scenario==='over-cap'?rows.map(row=>row.id==='uni-new-z'?{...row,principalRemaining:'79',amountRemaining:'99'}:row):rows.filter(row=>row.id!=='uni-future');await page.getByRole('button',{name:'Review payment',exact:true}).click();await page.getByRole('button',{name:'Use current balances',exact:true}).click();await expect(page.getByRole('textbox',{name:'Amount received',exact:true})).toHaveValue('130');await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('80');await expect(rowFor(page,'Future /').getByRole('textbox',{name:/Principal for/})).toHaveValue('50');await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeDisabled();expect(s.posts).toHaveLength(0);
});

test('U11 late409 after scope cancellation cannot expose adoption or Confirm',async({page})=>{
 const s=await setup(page);await manual(page);s.holdReview=true;s.reviewStatus=409;await page.getByRole('button',{name:'Review payment',exact:true}).click();await expect.poll(()=>!!s.releaseReview).toBe(true);await page.getByRole('button',{name:'Back to Collection',exact:true}).click();s.holdReview=false;s.releaseReview!();await expect(page.getByRole('button',{name:'Receive selected charges',exact:true})).toBeVisible();await expect(page.locator('.topbar')).toContainText('Updated');await expect(page.getByRole('button',{name:'Use current balances',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toHaveCount(0);expect(s.posts).toHaveLength(0);
});

test('U10 old unsent v5 draft converts only with fresh components and visible review notice',async({page})=>{
 const s=await setup(page);await page.getByRole('button',{name:'Back to Collection',exact:true}).click();await page.evaluate(async row=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');const repo=ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'unified-independent-owner'});await repo.saveDraft('uni-B',{formVersion:5,notes:'legacy ไทย',account:'uni-A2',paymentMethod:'Cash',selectionRows:[{...row,principalRemaining:undefined,interestRemaining:undefined}],selectedChargeIds:[row.id],allMode:false,scope:'all',image:null})},primary[0]);await page.getByRole('button',{name:'Receive selected charges',exact:true}).click();await expect(page.getByRole('alert')).toContainText('conversion review');await expect(page.getByRole('textbox',{name:'Amount received',exact:true})).toHaveValue('100');await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Principal for/})).toHaveValue('80');await expect(rowFor(page,'Newest Z').getByRole('textbox',{name:/Interest for/})).toHaveValue('20');expect(s.reviews[0]).toMatchObject({selectedChargeIds:['uni-new-z'],allocationMethod:'Single Full'});await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('legacy ไทย');await expect(page.getByRole('combobox',{name:'Receiving account',exact:true})).toHaveValue('uni-A2');expect(s.posts).toHaveLength(0);await expect(page.getByRole('button',{name:'Confirm payment online',exact:true})).toHaveCount(0);
});

test('U10 submitted old v5 pending is never converted and retries exact original UUID',async({page})=>{
 const s=await setup(page);await page.getByRole('button',{name:'Back to Collection',exact:true}).click();const old={schemaVersion:5,requestId:'ca7762ab-4e22-4b46-b7fc-6fac1981c6a3',borrowerId:'uni-B',selectedChargeIds:['uni-new-z'],cashAccountId:'uni-A',paymentDate:draft.businessDate,amountReceived:'100',paymentMethod:'Cash',allocationMethod:'Single Full',notes:'submitted old',receiptId:null};await page.evaluate(async command=>{const {ownerOfflineRepository}=await import('/apps/pwa/src/owner-offline.ts');await ownerOfflineRepository({issuer:'https://securetoken.google.com/clever-oasis-508610-n7',uid:'unified-independent-owner'}).savePending(command.requestId,command)},old);await page.getByRole('button',{name:'Receive selected charges',exact:true}).click();await expect(page.getByRole('heading',{name:'Outcome unknown',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Use current balances',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Check status',exact:true}).click();await page.getByRole('button',{name:'Retry same command',exact:true}).click();await expect.poll(()=>s.posts.length).toBe(1);expect(s.posts[0]).toEqual(old);expect(s.reviews).toHaveLength(0);
});
