import {chooseLanguage,signOut} from './live-controls';
import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
let server:ChildProcess;let base:string;let serverLog="";
test.beforeAll(async({},info)=>{
 const port=5700+info.workerIndex;base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,['--input-type=module','-e',`import {createServer} from 'vite';const s=await createServer({mode:'live-dev',cacheDir:'node_modules/.cache/playwright-live-${port}-${Date.now()}',server:{host:'127.0.0.1',port:${port},strictPort:true}});await s.listen();`],{env:{...process.env,VITE_FIREBASE_PROJECT_ID:'clever-oasis-508610-n7',VITE_FIREBASE_AUTH_DOMAIN:'clever-oasis-508610-n7.firebaseapp.com',VITE_FIREBASE_API_KEY:'synthetic-public-test-key',VITE_FIREBASE_APP_ID:'synthetic-app-id',VITE_API_ORIGIN:'https://mw-credit-app-read-dev-test.run.app'},stdio:'pipe'});
 server.stdout?.on("data",data=>{serverLog+=String(data)});server.stderr?.on("data",data=>{serverLog+=String(data)});
 await expect.poll(async()=>{try{return(await fetch(base)).status}catch{return0()}},{timeout:20000}).toBe(200);
});
function return0(){return 0}
test.afterAll(()=>server?.kill()); test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)console.log(serverLog)});
const authMock=`let listener;export const browserLocalPersistence='local';export const inMemoryPersistence='memory';export const browserPopupRedirectResolver={};export function initializeAuth(a,o){if(o.persistence!=='local')throw Error('persistence');return {}};export function getAuth(){return {}};export async function setPersistence(a,p){if(p!=='local')throw Error('persistence');}export function onAuthStateChanged(a,fn){listener=fn;fn(null);return()=>{listener=null}};export class GoogleAuthProvider{setCustomParameters(){}};export async function signInWithPopup(){listener({uid:'synthetic-owner',getIdToken:async()=>'synthetic-bearer'})};export async function signOut(){listener(null)};`;
test.use({timezoneId:'America/Los_Angeles'});
const statuses=['not_paid','partially_paid','overdue','fully_paid'];
const rows=Array.from({length:27},(_,i)=>({id:'private-board-'+i,displayName:'ผู้กู้ตัวอย่าง - Synthetic '+i,status:statuses[Math.min(3,Math.floor(i/7))],amountDue:i>=21?'0':'13.75',amountCollected:i>=21?'0':'3.25',amountRemaining:i>=21?'0':'10.50'}));
const charges=Array.from({length:27},(_,i)=>({id:'private-charge-'+i,loanId:'private-loan',loanDisplayKey:'ผู้กู้ตัวอย่างชื่อยาว - Long synthetic borrower English name-฿12,000-07/10-2%',chargeDate:'2026-10-07',paymentStatus:'ชำระบางส่วน',paymentDate:null,amountRemaining:i===0?null:'10.50',totalPaid:'0',receivedToday:'-2.50'}));

test('Upcoming two-request status, compact local detail, five-date paging and partial failure',async({page},info)=>{
 if(info.project.name.startsWith('desktop'))await page.setViewportSize({width:1440,height:900});else await page.setViewportSize({width:390,height:844});
 async function navigate(name:string){await page.getByRole('button',{name,exact:true}).click();} let hold=false,release:(()=>void)|undefined,upcomingError=false,review=false;const paths:string[]=[];
 const envelope={ok:true,source:'dev',businessDate:'2026-10-07',timezone:'Asia/Bangkok',asOf:'2026-10-07T05:00:00Z',horizonEnd:'2027-01-07'};
 const dates=Array.from({length:5},(_,i)=>({id:'private-date-'+i,dueDate:'2026-10-'+String(8+i).padStart(2,'0'),totalCharge:'270.125'}));
 const events=Array.from({length:27},(_,i)=>({id:'private-event-'+i,loanId:'private-loan-'+i,loanDisplayKey:'ผู้กู้ตัวอย่างชื่อยาว - Long synthetic borrower name-฿12,000-07/10-2%',principalRemaining:'0',interestRemaining:'10.125',amountRemaining:'10.125',basis:i%2?'Recorded':'Projected'}));
 await page.route('**/deps/firebase_app.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function initializeApp(){return {}}'}));await page.route('**/deps/firebase_auth.js*',r=>r.fulfill({contentType:'text/javascript',body:authMock}));
 await page.route('https://mw-credit-app-read-dev-test.run.app/**',async r=>{
  const u=new URL(r.request().url());paths.push(u.pathname+u.search);expect(r.request().method()).toBe('GET');let result:any={...envelope,items:[],nextCursor:null};let status=200;
  if(u.pathname==='/api/collection')result={...envelope,items:[rows[0]],nextCursor:null};
  else if(u.pathname.endsWith('/charges'))result={...envelope,borrower:rows[0],items:charges.slice(0,2).map(x=>({...x,totalPaid:'125.75'})),nextCursor:null};
  else if(u.pathname.endsWith('/upcoming')){if(hold)await new Promise<void>(resolve=>release=resolve);status=upcomingError?503:200;result=status===200?{...envelope,reviewRequired:review,items:dates,previews:dates.map(d=>({...envelope,reviewRequired:review,dueDate:d.dueDate,totalCharge:d.totalCharge,items:events.slice(0,25),nextCursor:'synthetic-next'}))}:{ok:false,code:'source_unavailable'};}
  else if(u.pathname.includes('/upcoming/'))result={...envelope,reviewRequired:review,dueDate:'2026-10-12',totalCharge:'270.125',items:events.slice(u.searchParams.has('cursor')?25:0,u.searchParams.has('cursor')?27:25),nextCursor:u.searchParams.has('cursor')?null:'synthetic-next'};
  await r.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(result)}).catch(()=>{});
 });
 await page.clock.install({time:new Date('2026-10-07T05:00:00Z')});await page.goto(base);await expect(page.getByRole('heading',{name:'Sign in to continue',exact:true})).toBeVisible();await expect(page.locator('.live-bottom-nav')).toHaveCount(0);await expect(page.getByRole('button',{name:'Sign out',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Collection',exact:true})).toHaveCount(0);await chooseLanguage(page,'ไทย');await expect(page.getByRole('heading',{name:'ลงชื่อเข้าใช้เพื่อดำเนินการต่อ',exact:true})).toBeVisible();await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Continue with Google'}).click();
 if(info.project.name.startsWith('desktop')){
 await expect(page.locator('.work-grid')).toBeVisible();
 for(const width of [1440,2560]){await page.setViewportSize({width,height:900});const grid=await page.locator('.work-grid').boundingBox(),list=await page.locator('.list-panel').boundingBox();expect(list!.width).toBe(grid!.width);await expect(page.locator('.detail-panel.unselected')).not.toBeVisible();}
 await page.setViewportSize({width:1440,height:900});
 }
 if(info.project.name.startsWith('mobile')){
  const toggle=page.getByRole('button',{name:'Open navigation',exact:true});await toggle.click();const dialog=page.getByRole('dialog',{name:'Navigation menu'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Borrowers',exact:true})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Collection',exact:true})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Sign out',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Close menu',exact:true})).toBeFocused();
  for(let i=0;i<5;i++){await page.keyboard.press('Tab');expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);}
  await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(toggle).toBeFocused();await toggle.click();await dialog.getByRole('button',{name:'Close menu',exact:true}).click();await expect(toggle).toBeFocused();
 }
 await navigate('Collection');await expect(page.locator('.collection-borrower')).toHaveCount(1);
 const marker=page.locator('.topbar .collection-update');await expect(marker).toHaveCount(1);await expect(marker).toHaveAttribute('aria-live','polite');await expect(page.locator('.topbar .language,.topbar .live-sign-out,.topbar .live-environment')).toHaveCount(0);await expect(page.locator('.topbar .live-status-text')).toHaveCSS('clip','rect(0px, 0px, 0px, 0px)');
 if(info.project.name.startsWith('mobile')){await expect(page.locator('.live-bottom-nav button')).toHaveCount(2);await expect(page.locator('.live-bottom-nav').getByRole('button',{name:'Collection',exact:true})).toHaveAttribute('aria-current','page');const h=await page.locator('.topbar').boundingBox();expect(h!.height).toBeLessThanOrEqual(80);}else await expect(page.locator('.live-bottom-nav')).not.toBeVisible();
 if(info.project.name.startsWith('desktop')){
 for(const width of [1440,2560]){await page.setViewportSize({width,height:900});for(const collapsed of [false,true]){const grid=await page.locator('.work-grid').boundingBox(),list=await page.locator('.list-panel').boundingBox();expect(list!.width).toBe(grid!.width);await expect(page.locator('.detail-panel.unselected')).not.toBeVisible();await page.screenshot({path:'outputs/r052-collection-read/desktop-'+width+'-COMPACT-list-'+(collapsed?'collapsed':'expanded')+'.png'});await page.getByRole('button',{name:collapsed?'Expand navigation':'Collapse navigation',exact:true}).click();}}await page.setViewportSize({width:1440,height:900});
 const nav=page.locator('.live-desktop-nav'),main=page.locator('main');const expandedWidth=(await main.boundingBox())!.width;
 await expect(page.getByRole('button',{name:'Collapse navigation',exact:true})).toHaveAttribute('aria-expanded','true');await expect(nav.getByRole('button',{name:'Collection',exact:true})).toHaveAttribute('aria-current','page');
 await page.getByRole('button',{name:'Collapse navigation',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Expand navigation',exact:true})).toHaveAttribute('aria-expanded','false');expect((await main.boundingBox())!.width).toBeGreaterThan(expandedWidth);await expect(nav.getByRole('button',{name:'Collection',exact:true})).toHaveAttribute('title','Collection');await expect(nav.locator('.live-nav-label').first()).not.toBeVisible();const language=nav.getByRole('button',{name:'Language',exact:true});await expect(language).toHaveAttribute('title','Language');await expect(nav.getByRole('button',{name:'Sign out',exact:true})).toHaveAttribute('title','Sign out');await language.focus();await page.keyboard.press('Enter');await expect(language).toHaveAttribute('aria-expanded','true');await page.getByRole('button',{name:'EN',exact:true}).focus();await page.keyboard.press('Escape');await expect(language).toBeFocused();await expect(language).toHaveAttribute('aria-expanded','false');await page.getByRole('button',{name:'Expand navigation',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Collapse navigation',exact:true})).toHaveAttribute('aria-expanded','true');
 }
await expect(marker).toHaveText('✓Updated');hold=true;await page.locator('.collection-borrower').click();await expect.poll(()=>!!release).toBe(true);await expect(page.locator('.collection-charge-row')).toHaveCount(2);await expect(marker).toContainText('Loading');await expect(page.getByRole('region',{name:'Collection charge details'})).toHaveAttribute('aria-busy','true');
 const geometry=()=>page.locator('.topbar').evaluate(el=>({height:el.getBoundingClientRect().height,nextTop:document.querySelector('.work-grid')?.getBoundingClientRect().top,scroll:window.scrollY}));const loading=await geometry();
 await page.screenshot({path:`outputs/r052-collection-read/${info.project.name}-COMPACT-loading.png`,fullPage:true});hold=false;release!();await expect(marker).toHaveText('✓Updated');const finished=await geometry();expect(finished.height).toBe(loading.height);expect((finished.nextTop??0)+finished.scroll).toBe((loading.nextTop??0)+loading.scroll);
 await expect(page.locator('.upcoming-date-row')).toHaveCount(5);await expect(page.locator('.issue-note')).toHaveCount(0);await expect(page.locator('.collection-charge-row').first()).toContainText('฿125.75');await expect(page.locator('.collection-charge-row').first()).not.toContainText('-฿2.5');await expect(page.locator('.collection-charge-row').first()).not.toContainText('Long synthetic');
 const count=paths.length;await page.locator('.collection-charge-row').first().click();await expect(page.getByRole('article',{name:'Charge detail',exact:true})).toContainText('-฿2.5');await expect(page.getByRole('article',{name:'Charge detail',exact:true})).toContainText('12:00');const backBox=await page.getByRole('button',{name:'Back to charges',exact:true}).boundingBox();const headerBox=await page.locator('.topbar').boundingBox();expect(backBox!.y).toBeGreaterThanOrEqual(headerBox!.y+headerBox!.height);await expect(page.getByRole('article',{name:'Charge detail',exact:true}).getByText('Payment date',{exact:true})).toHaveCount(0);expect(paths.length).toBe(count);await page.getByRole('button',{name:'Back to charges',exact:true}).click();expect(paths.length).toBe(count);
 await page.screenshot({path:'outputs/r052-collection-read/'+info.project.name+'-COMPACT-summary-en.png',fullPage:true});
 if(info.project.name.startsWith('desktop')){
 await page.setViewportSize({width:2560,height:1440});
 for(const collapsed of [false,true]){
 const header=await page.locator('.topbar').boundingBox(),main=await page.locator('main').boundingBox(),nav=await page.locator('.live-desktop-nav').boundingBox(),grid=await page.locator('.work-grid').boundingBox();
 const list=await page.locator('.list-panel').boundingBox(),detail=await page.locator('.detail-panel').boundingBox();expect(list!.width/(list!.width+detail!.width)).toBeCloseTo(0.4,1);expect(header!.x).toBe(0);expect(header!.width).toBe(2560);expect(nav!.width).toBe(collapsed?72:180);expect(main!.x).toBe(nav!.width);expect(main!.x+main!.width).toBe(2560);expect(grid!.x-main!.x).toBeLessThanOrEqual(20);expect(2560-(grid!.x+grid!.width)).toBeLessThanOrEqual(20);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
 await page.screenshot({path:'outputs/r052-collection-read/desktop-2560-COMPACT-'+(collapsed?'collapsed':'expanded')+'.png'});
 await page.getByRole('button',{name:collapsed?'Expand navigation':'Collapse navigation',exact:true}).click();
 }
 await page.setViewportSize({width:1440,height:900});await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();await page.screenshot({path:'outputs/r052-collection-read/desktop-chromium-COMPACT-collapsed.png'});await page.getByRole('button',{name:'Expand navigation',exact:true}).click();const pane=page.locator('.detail-panel');await pane.evaluate(e=>e.scrollTop=e.scrollHeight);expect(await page.locator('.topbar').evaluate(e=>e.getBoundingClientRect().top)).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBe(true);await pane.evaluate(e=>e.scrollTop=0);}
 else{await page.locator('.upcoming-date-row').last().scrollIntoViewIfNeeded();expect(await page.locator('.topbar').evaluate(e=>e.getBoundingClientRect().top)).toBe(0);await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.screenshot({path:'outputs/r052-collection-read/mobile-chromium-COMPACT-menu.png'});await page.keyboard.press('Escape');}
await chooseLanguage(page,'ไทย');await page.screenshot({path:`outputs/r052-collection-read/${info.project.name}-COMPACT-summary-th.png`,fullPage:true});await chooseLanguage(page,'EN');
 const previewRequests=paths.length;await page.locator('.upcoming-date-row').last().click();await expect(page.locator('.upcoming-charges article')).toHaveCount(25);expect(paths.length).toBe(previewRequests);await expect(page.locator('.upcoming-charges')).toContainText('12:00');await expect(page.locator('.upcoming-charges')).toContainText('฿270');await expect(page.locator('.upcoming-charges')).toContainText('Projected');await expect(page.locator('.upcoming-charges')).toContainText('Recorded');await page.getByRole('button',{name:'Next upcoming details page',exact:true}).click();await expect(page.locator('.upcoming-charges article')).toHaveCount(2);await expect(page.locator('.upcoming-charges')).toContainText('฿270');await expect(page.getByRole('button',{name:'Next upcoming details page',exact:true})).toHaveCount(0);if(info.project.name.startsWith('mobile')){const pager=page.getByRole('button',{name:'First upcoming details page / refresh',exact:true});await pager.scrollIntoViewIfNeeded();const p=await pager.boundingBox(),bottom=await page.locator('.live-bottom-nav').boundingBox();expect(p!.y+p!.height).toBeLessThanOrEqual(bottom!.y);await page.getByRole('button',{name:'Back to borrower summary',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'outputs/r052-collection-read/mobile-chromium-COMPACT-bottom-en-viewport.png'});}
 await page.screenshot({path:`outputs/r052-collection-read/${info.project.name}-COMPACT-upcoming-en.png`,fullPage:true});await chooseLanguage(page,'ไทย');await expect(page.locator('.upcoming-charges')).toContainText('คาดการณ์');if(info.project.name.startsWith('mobile')){expect(await page.locator('.topbar').evaluate(e=>e.getBoundingClientRect().top)).toBe(0);await page.screenshot({path:'outputs/r052-collection-read/mobile-chromium-COMPACT-upcoming-th-viewport.png'});}await page.screenshot({path:`outputs/r052-collection-read/${info.project.name}-COMPACT-upcoming-th.png`,fullPage:true});await chooseLanguage(page,'EN');await page.getByRole('button',{name:'Back to borrower summary',exact:true}).click();await expect(page.locator('.collection-charge-row')).toHaveCount(2);
 upcomingError=true;await page.getByRole('button',{name:'First charges page / refresh',exact:true}).click();await expect(marker).toContainText('Could not update');await expect(page.locator('.collection-charge-row')).toHaveCount(2);await expect(page.locator('.upcoming-date-row')).toHaveCount(0);await expect(page.locator('.upcoming-charges')).toContainText('Unable to load');expect((await geometry()).height).toBe(loading.height);
 upcomingError=false;review=true;await page.getByRole('button',{name:'Refresh Upcoming Charges',exact:true}).click();await expect(marker).toHaveText('✓Updated');await expect(page.locator('.issue-note')).toContainText('Schedule data is incomplete');await page.emulateMedia({reducedMotion:'reduce'});hold=true;release=undefined;await page.getByRole('button',{name:'Refresh Upcoming Charges',exact:true}).click();await expect.poll(()=>!!release).toBe(true);await expect(page.locator('.collection-spinner')).toHaveCSS('animation-name','none');hold=false;release!();await expect(marker).toHaveText('✓Updated');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('body').innerText()).not.toMatch(/private-(board|loan|event|date)|THB/);// Cache expires by elapsed time, visibility resumption and Bangkok date; fresh paging never reuses it.
 const detailRequests=()=>paths.filter(x=>/\/upcoming\//.test(x)).length;
 const openLast=async()=>{await page.locator('.upcoming-date-row').last().click();await expect(page.locator('.upcoming-charges article')).toHaveCount(25);};
 const backSummary=()=>page.getByRole('button',{name:'Back to borrower summary',exact:true}).click();
 const refreshSummary=async()=>{hold=true;release=undefined;await page.getByRole('button',{name:'Refresh Upcoming Charges',exact:true}).click();await expect.poll(()=>!!release).toBe(true);await expect(marker).toContainText('Loading');hold=false;release!();await expect(marker).toHaveText('✓Updated');await expect(page.locator('.upcoming-date-row')).toHaveCount(5);};
 let beforeDetail=detailRequests();await openLast();expect(detailRequests()).toBe(beforeDetail);await page.getByRole('button',{name:'First upcoming details page / refresh',exact:true}).click();await expect.poll(detailRequests).toBe(beforeDetail+1);await backSummary();
 await refreshSummary();await page.clock.fastForward(60_001);beforeDetail=detailRequests();await openLast();expect(detailRequests()).toBe(beforeDetail+1);await backSummary();
 await refreshSummary();await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));beforeDetail=detailRequests();await openLast();expect(detailRequests()).toBe(beforeDetail+1);await backSummary();
 await refreshSummary();await page.clock.setSystemTime(new Date('2026-10-07T17:00:01Z'));beforeDetail=detailRequests();await openLast();expect(detailRequests()).toBe(beforeDetail+1);await backSummary();await page.clock.setSystemTime(new Date('2026-10-07T05:00:00Z'));
 if(info.project.name.startsWith('desktop')){await page.getByRole('button',{name:'Back to Collection',exact:true}).click();await expect(page.locator('.work-grid')).not.toHaveClass(/has-detail/);const grid=await page.locator('.work-grid').boundingBox(),list=await page.locator('.list-panel').boundingBox();expect(list!.width).toBe(grid!.width);await page.locator('.collection-borrower').click();await expect(page.locator('.upcoming-date-row')).toHaveCount(5);await expect(page.getByRole('button',{name:'Refresh Upcoming Charges',exact:true})).toBeEnabled();}
expect(await page.evaluate(()=>Object.keys(localStorage).some(k=>/collection|upcoming|private-/i.test(k)))).toBe(false);hold=true;release=undefined;await page.getByRole('button',{name:'Refresh Upcoming Charges',exact:true}).click();await expect.poll(()=>!!release).toBe(true);await navigate('Borrowers');hold=false;release!();await expect(page.locator('.upcoming-date-row,.collection-charge-row')).toHaveCount(0);
});
