import test,{before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {createBorrowerReadStore} from '../../services/api/borrower-read-store.mjs';
import {encodeCollectionCursor} from '../../services/api/collection-read-contract.mjs';
if(process.env.COLLECTION_TEST_DISPOSABLE!=='1'||!/^\d+$/.test(process.env.COLLECTION_TEST_PORT||''))throw Error('Run only with the disposable Collection fixture runner');
const connection={host:'127.0.0.1',port:Number(process.env.COLLECTION_TEST_PORT),database:'collection_fixture'};
const admin=new pg.Pool({...connection,user:'postgres'});const reader=new pg.Pool({...connection,user:'synthetic_reader'});
const owner='synthetic-owner@example.test';let instant='2026-10-07T05:00:00Z';const queries=[];
const pool={connect:async()=>{const c=await reader.connect();return{release:()=>c.release(),query:(sql,params)=>{queries.push(sql);if(sql.startsWith('SELECT CURRENT_TIMESTAMP AS'))return c.query(`SELECT $1::timestamptz AS "asOf",($1::timestamptz AT TIME ZONE 'Asia/Bangkok')::date::text AS "businessDate"`,[instant]);return c.query(sql,params)}}}};
const store=createBorrowerReadStore({pool,config:{ownerEmail:owner,database:'collection_fixture',dbUser:'synthetic_reader'}});
const q=(sql,p)=>admin.query(sql,p);const pending='รอชำระ',partial='ชำระบางส่วน',paid='ชำระแล้ว';
before(async()=>{await q(`CREATE ROLE synthetic_reader LOGIN; CREATE TABLE "Partners"("Row ID" text PRIMARY KEY,"Login Email" text); CREATE TABLE "Borrowers"("Row ID" text PRIMARY KEY,"Borrower Name" text,"Description" text,"Hidden Flag" boolean,"Creation Date" date,"Has Active Loan" boolean,"Total Interest Earned" numeric,"Total Outstanding Principal" numeric,"Borrower Note" text); CREATE TABLE "Loans"("Row ID" text PRIMARY KEY,"Ref Borrowers" text,"Principal Amount" money,"Loan Date" date,"Original Daily Interest Rate" integer); CREATE TABLE "Charges"("Row ID" text PRIMARY KEY,"Ref Loans" text,"Charge Date" date,"Payment Status" text,"Payment Date" date,"Amount Remaining" numeric,"Total Paid" numeric); CREATE TABLE "Repayments"("Ref Charges" text,"Payment Date" date,"Principal Paid" money,"Interest Paid" money); GRANT SELECT ON ALL TABLES IN SCHEMA public TO synthetic_reader;`)});
after(async()=>{await reader.end();await admin.end()});
beforeEach(async()=>{instant='2026-10-07T05:00:00Z';queries.length=0;await q('TRUNCATE "Repayments","Charges","Loans","Borrowers","Partners"');await q('INSERT INTO "Partners" VALUES ($1,$2)',['partner',owner])});
async function borrower(id,hidden=false){await q('INSERT INTO "Borrowers" VALUES ($1,$2,$3,$4,$5,true,0,1000,NULL)',[id,'ชื่อ '+id,'Synthetic '+id,hidden,'2026-01-01']);await q('INSERT INTO "Loans" VALUES ($1,$2,12000,$3,2)',['loan-'+id,id,'2026-10-01'])}
async function charge(id,b,status=pending,date='2026-10-07',remaining='100.25',paymentDate=null,total='0'){await q('INSERT INTO "Charges" VALUES ($1,$2,$3,$4,$5,$6,$7)',[id,'loan-'+b,date,status,paymentDate,remaining,total])}
async function repayment(id,principal,interest,date='2026-10-07'){await q('INSERT INTO "Repayments" VALUES ($1,$2,$3,$4)',[id,date,principal,interest])}
const board=()=>store.listCollection(owner,{limit:100});const detail=b=>store.getCollectionCharges(owner,b,{limit:100});
test('eligibility covers three arms, future receipts, hidden and fully paid zero without directory leak',async()=>{for(const id of ['due','paid','future','hidden','excluded'])await borrower(id,id==='hidden');await charge('c-due','due');await charge('c-paid','paid',paid,'2026-10-06','0','2026-10-07');await charge('c-future','future',pending,'2026-10-09','500');await repayment('c-future','12.34','1.66');await charge('c-hidden','hidden');await charge('c-excluded','excluded',paid,'2026-10-01','0',null);const result=await board();assert.equal(result.ok,true);assert.deepEqual(result.items.map(x=>x.id),['due','future','hidden','paid']);assert.deepEqual(result.items.find(x=>x.id==='future'),{id:'future',displayName:'ชื่อ future - Synthetic future',status:'not_paid',amountDue:'14.00',amountCollected:'14.00',amountRemaining:'0'});assert.equal(result.items.at(-1).status,'fully_paid');assert.equal(result.items.at(-1).amountDue,'0');assert.equal((await detail('excluded')).status,404);assert.equal((await store.getBorrower(owner,'hidden')).status,404);assert.equal((await detail('hidden')).items.length,1)});
test('status precedence and global display order differ',async()=>{for(const b of ['pending','partial','mixed','overdue','paid'])await borrower(b);await charge('p','pending');await charge('s','partial',partial);await charge('m1','mixed');await charge('m2','mixed',paid,'2026-10-07','0','2026-10-07');await charge('o1','overdue',pending,'2026-10-06');await charge('o2','overdue',paid,'2026-10-07','0','2026-10-07');await charge('f','paid',paid,'2026-10-07','0','2026-10-07');const result=await board();assert.deepEqual(result.items.map(x=>[x.id,x.status]),[['pending','not_paid'],['mixed','partially_paid'],['partial','partially_paid'],['overdue','overdue'],['paid','fully_paid']])});
test('multiple repayments aggregate once per charge and preserve signed exact decimals',async()=>{await borrower('a');await charge('c1','a',partial,'2026-10-07','10.125');await charge('c2','a',partial,'2026-10-07','-2.125');await repayment('c1','10.10','0.20');await repayment('c1','2.00','0.30');await repayment('c2','-1.00','-0.25');await repayment('c2','999','999','2026-10-06');await repayment('c2','999','999',null);const r=(await board()).items[0];assert.equal(r.amountCollected,'11.35');assert.equal(r.amountRemaining,'8.000');assert.equal(r.amountDue,'19.350');const children=await detail('a');assert.equal(children.ok,true);assert.deepEqual(children.items.map(x=>[x.id,x.receivedToday]),[['c1','12.60'],['c2','-1.25']]);assert.equal(children.items[0].loanDisplayKey,'ชื่อ a - Synthetic a-฿12,000-01/10-2%')});
test('relevant null inputs propagate while empty sums and irrelevant nulls do not',async()=>{await borrower('a');await charge('c','a',pending,'2026-10-07',null,null,null);await repayment('c',null,'2');let r=(await board()).items[0];assert.equal(r.amountDue,null);assert.equal(r.amountCollected,null);assert.equal(r.amountRemaining,null);assert.equal((await detail('a')).items[0].totalPaid,null);await q('DELETE FROM "Repayments"');await q('UPDATE "Charges" SET "Charge Date"=$1',['2026-10-09']);await repayment('c','1','2');r=(await board()).items[0];assert.equal(r.amountRemaining,'0');assert.equal(r.amountDue,'3.00')});
test('candidate quality fails before eligibility; paid null date valid; orphan and other scope excluded',async()=>{await borrower('a');await borrower('b');await charge('a-good','a');await charge('bad','b','unknown','2026-10-20');assert.equal((await board()).code,'source_unavailable');assert.equal((await detail('a')).ok,true);assert.equal((await detail('b')).code,'source_unavailable');await q('UPDATE "Charges" SET "Payment Status"=$1 WHERE "Row ID"=$2',[paid,'bad']);assert.equal((await board()).ok,true);await q('UPDATE "Charges" SET "Charge Date"=NULL WHERE "Row ID"=$1',['bad']);assert.equal((await board()).code,'source_unavailable');await q('DELETE FROM "Charges" WHERE "Row ID"=$1',['bad']);await q('INSERT INTO "Charges" VALUES ($1,$2,NULL,NULL,NULL,NULL,NULL)',['orphan','missing-loan']);assert.equal((await board()).items.length,1)});
test('board and charge keyset traverse more than25 ties without missing/duplicate records',async()=>{for(let i=0;i<28;i++){const id='b'+String(i).padStart(2,'0');await borrower(id);await charge('c'+id,id,i<13?pending:i<26?partial:paid,'2026-10-07','0',i>=26?'2026-10-07':null)}let cursor=null,ids=[];do{const r=await store.listCollection(owner,{cursor});assert.equal(r.ok,true);ids.push(...r.items.map(x=>x.id));cursor=r.nextCursor}while(cursor);assert.equal(ids.length,28);assert.equal(new Set(ids).size,28);await borrower('many');for(let i=0;i<28;i++)await charge('m'+String(i).padStart(2,'0'),'many',pending,i<14?'2026-10-07':'2026-10-06');cursor=null;ids=[];do{const r=await store.getCollectionCharges(owner,'many',{cursor});assert.equal(r.ok,true);ids.push(...r.items.map(x=>x.id));cursor=r.nextCursor}while(cursor);assert.deepEqual(ids,Array.from({length:28},(_,i)=>'m'+String(i).padStart(2,'0')))});
test('Bangkok midnight invalidates old cursor and no query-selected date is accepted',async()=>{await borrower('a');await charge('c','a');instant='2026-10-07T16:59:59Z';assert.equal((await board()).businessDate,'2026-10-07');const cursor=encodeCollectionCursor({kind:'collection',businessDate:'2026-10-07',rank:0,id:'a'});instant='2026-10-07T17:00:00Z';const r=await store.listCollection(owner,{cursor});assert.deepEqual(r,{ok:false,status:409,code:'business_date_changed'});assert.equal((await board()).businessDate,'2026-10-08')});
test('owner mapping identity and repeatable read remain default deny with no writes',async()=>{await borrower('a');await charge('c','a');assert.equal((await store.listCollection('wrong@example.test')).status,403);assert.equal(queries.length,0);await q('INSERT INTO "Partners" VALUES ($1,$2)',['duplicate',owner]);assert.equal((await board()).status,403);assert.equal(queries.some(s=>s.includes('WITH today_repayments')),false);await q('DELETE FROM "Partners" WHERE "Row ID"=$1',['duplicate']);await board();assert.ok(queries.includes('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY'));assert.equal(queries.some(s=>/^\s*(INSERT|UPDATE|DELETE|ALTER|DROP)\b/i.test(s)),false);const c=await reader.connect();try{await assert.rejects(c.query('UPDATE "Charges" SET "Total Paid"=0'),/permission denied/)}finally{c.release()}});

test('nonfinite and out-of-public-range charge dates fail the source guard',async()=>{await borrower('a');for(const date of ['infinity','-infinity','10000-01-01']){await q('DELETE FROM "Charges"');await charge('bad','a',pending,date);assert.equal((await board()).code,'source_unavailable');assert.equal((await detail('a')).code,'source_unavailable')}});
