import test,{before,after}from'node:test';import assert from'node:assert/strict';import{randomUUID,createHash}from'node:crypto';import{disposablePool}from'../../scripts/rehearsal/disposable-pool.mjs';import{seedPaymentFixture}from'../../scripts/rehearsal/payment-fixture.mjs';import{commandIdentity}from'../../services/contracts/payment-command.mjs';
let pool;before(async()=>{pool=await disposablePool(78)});after(async()=>pool?.end());const actor={issuer:'synthetic-issuer',subject:'synthetic-subject',partnerId:'4A-ACTOR',loginEmail:'4A-owner@example.invalid'};
async function fixture(prefix){await seedPaymentFixture(pool,prefix);const day=(await pool.query("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date::text AS day")).rows[0].day;const command={schemaVersion:3,requestId:randomUUID(),borrowerId:prefix+'-B',selectedChargeIds:[prefix+'-C2',prefix+'-C1'],cashAccountId:'4A-RECEIVE',paymentDate:day,amountReceived:'330',paymentMethod:'Bank Transfer',allocationMethod:'Selected Charges',notes:'  ไทย😀\r\n"quoted" \\ slash / <Notes>\t ',receiptId:null};return{command,identity:commandIdentity(command,actor,null)}}
async function submit(i,client=pool){return(await client.query('SELECT public.pwa_submit_selected_charges_v1($1) AS result',[i.canonicalJson])).rows[0].result}
async function status(id){return(await pool.query('SELECT public.pwa_command_status_v1($1,$2,$3) AS result',[id,actor.issuer,actor.subject])).rows[0].result}
async function count(id){return(await pool.query('SELECT (SELECT count(*) FROM public.pwa_payment_commands WHERE request_id=$1)::int AS journal,(SELECT count(*) FROM "Payments" WHERE "Row ID"=\'pwa:\'||$1)::int AS payments',[id])).rows[0]}
test('SQL retains exact JS canonical bytes/hash/Notes and rejects alternate JSON encodings',async()=>{const{command,identity}=await fixture('4A-JC-BYTES');const result=await submit(identity);assert.equal(result.originalOutcome.status,'posted');const row=(await pool.query('SELECT canonical_json,payload_sha256 FROM public.pwa_payment_commands WHERE request_id=$1',[command.requestId])).rows[0];assert.equal(row.canonical_json,identity.canonicalJson);assert.equal(row.payload_sha256,identity.payloadSha256);assert.equal((await pool.query('SELECT "Notes" FROM "Payments" WHERE "Row ID"=$1',['pwa:'+command.requestId])).rows[0].Notes,command.notes);for(const text of[JSON.stringify(JSON.parse(identity.canonicalJson),null,2),identity.canonicalJson.replace('ไทย','\\u0e44ทย'),identity.canonicalJson.replace('"contractVersion":1','"contractVersion":1,"contractVersion":1')])await assert.rejects(pool.query('SELECT public.pwa_submit_selected_charges_v1($1)',[text]),e=>e.code==='22023');assert.deepEqual(await count(command.requestId),{journal:1,payments:1})});
test('outer rollback removes both posted source and journal; committed result survives fresh connection',async()=>{const{command,identity}=await fixture('4A-JC-ATOMIC');const c=await pool.connect();try{await c.query('BEGIN');assert.equal((await submit(identity,c)).originalOutcome.status,'posted');await c.query('ROLLBACK')}finally{c.release()}assert.deepEqual(await count(command.requestId),{journal:0,payments:0});const committed=await submit(identity);const fresh=await pool.connect();try{assert.deepEqual((await fresh.query('SELECT public.pwa_command_status_v1($1,$2,$3) AS result',[command.requestId,actor.issuer,actor.subject])).rows[0].result,committed)}finally{fresh.release()}assert.deepEqual(await count(command.requestId),{journal:1,payments:1})});
test('original journal survives actual correction/delete and replay never reinserts the payment',async()=>{const{command,identity}=await fixture('4A-JC-RETAIN');const original=await submit(identity);await pool.query('UPDATE "Payments" SET "Amount Received"=55::money,"Selected Charge IDs"=$2 WHERE "Row ID"=$1',['pwa:'+command.requestId,'4A-JC-RETAIN-UNSELECTED']);assert.deepEqual(await status(command.requestId),original);assert.deepEqual(await submit(identity),original);await pool.query('DELETE FROM "Payments" WHERE "Row ID"=$1',['pwa:'+command.requestId]);assert.deepEqual(await submit(identity),original);assert.deepEqual(await count(command.requestId),{journal:1,payments:0});assert.equal((await submit(commandIdentity({...command,notes:'changed'},actor,null))).kind,'conflict')});
test('append-only and nullable CHECK edges reject direct corruption; PUBLIC has no execute grant',async()=>{const{command,identity}=await fixture('4A-JC-GUARD');await submit(identity);for(const sql of['UPDATE public.pwa_payment_commands SET actor_subject=actor_subject WHERE request_id=$1','DELETE FROM public.pwa_payment_commands WHERE request_id=$1'])await assert.rejects(pool.query(sql,[command.requestId]),e=>e.code==='55000');await assert.rejects(pool.query('TRUNCATE public.pwa_payment_commands'),e=>e.code==='55000');for(const malformed of[false,true]){const id=randomUUID(),text=malformed?'{}':commandIdentity({...command,requestId:id},actor,null).canonicalJson,hash=createHash('sha256').update(text).digest('hex');await assert.rejects(pool.query('INSERT INTO public.pwa_payment_commands(request_id,contract_version,actor_issuer,actor_subject,actor_partner_id,actor_login_email,canonical_json,payload_sha256,outcome,payment_id,rejection_code) VALUES($1,1,$2,$3,$4,$5,$6,$7,\'posted\',NULL,NULL)',[id,actor.issuer,actor.subject,actor.partnerId,actor.loginEmail.toLowerCase(),text,hash]),e=>e.code==='23514')}
 const publicGrants=(await pool.query("SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a WHERE n.nspname='public' AND p.proname=ANY($1) AND a.grantee=0 AND a.privilege_type='EXECUTE'",[['pwa_submit_selected_charges_v1','pwa_command_status_v1','guard_pwa_payment_commands_immutable']])).rows;assert.deepEqual(publicGrants,[])});
test('typed rejection persists without payment, untyped financial error and mapping denial do not',async()=>{const{command}=await fixture('4A-JC-REJECT');const badAccount={...command,requestId:randomUUID(),cashAccountId:'4A-NO-ACCOUNT'};const rejected=await submit(commandIdentity(badAccount,actor,null));assert.equal(rejected.originalOutcome.status,'rejected');assert.equal(rejected.originalOutcome.code,'account_unavailable');assert.deepEqual(await count(badAccount.requestId),{journal:1,payments:0});const wrongAmount={...command,requestId:randomUUID(),amountReceived:'329'};await assert.rejects(submit(commandIdentity(wrongAmount,actor,null)),e=>e.code==='P0001');assert.deepEqual(await count(wrongAmount.requestId),{journal:0,payments:0});const noActor={...command,requestId:randomUUID()};await assert.rejects(submit(commandIdentity(noActor,{...actor,partnerId:'missing'},null)),e=>e.code==='42501');assert.deepEqual(await count(noActor.requestId),{journal:0,payments:0})});
test('AppSheet-style source insert wins held borrower lock without duplicate journal posting',async()=>{
 const {command,identity}=await fixture('4A-JC-APPSHEET');const direct=await pool.connect(),api=await pool.connect();let pending;
 try{await direct.query('BEGIN');await direct.query('SELECT 1 FROM "Borrowers" WHERE "Row ID"=$1 FOR UPDATE',[command.borrowerId]);const pid=(await api.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;pending=submit(identity,api).then(value=>({value}),error=>({error}));let blocked=false;for(let attempt=0;attempt<100;attempt++){const state=(await pool.query('SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1',[pid])).rows[0];if(state?.wait_event_type==='Lock'){blocked=true;break}await new Promise(resolve=>setTimeout(resolve,20))}assert.ok(blocked,'API must be observed waiting on the competing borrower lock');await direct.query('INSERT INTO "Payments"("Row ID","Ref Borrower","Ref Received By Cash Account","Status","Amount Received","Payment Date","Allocation Method","Selected Charge IDs","Payment Method","Created By") VALUES($1,$2,$3,\'Processing\',330::money,$4,\'Selected Charges\',$5,\'Bank Transfer\',$6)',['4A-JC-APPSHEET-DIRECT',command.borrowerId,command.cashAccountId,command.paymentDate,command.selectedChargeIds.join(' , '),actor.loginEmail]);await direct.query('COMMIT');const result=await pending;assert.equal(result.error?.code,'P0001');assert.deepEqual(await count(command.requestId),{journal:0,payments:0});assert.equal((await pool.query('SELECT "Status" FROM "Payments" WHERE "Row ID"=\'4A-JC-APPSHEET-DIRECT\'')).rows[0].Status,'Posted');
 }finally{await direct.query('ROLLBACK').catch(()=>{});if(pending)await pending;direct.release();api.release()}
});
test('changed actor conflicts, scoped status hides result and current mapping denial applies to known replay',async()=>{
 const {command,identity}=await fixture('4A-JC-ACTOR');await submit(identity);assert.equal((await submit(commandIdentity(command,{...actor,subject:'different-subject'},null))).kind,'conflict');assert.deepEqual((await pool.query('SELECT public.pwa_command_status_v1($1,$2,$3) AS result',[command.requestId,actor.issuer,'different-subject'])).rows[0].result,{kind:'unresolved'});await pool.query('UPDATE "Partners" SET "Login Email"=\'temporarily-unmapped@example.invalid\' WHERE "Row ID"=\'4A-ACTOR\'');try{await assert.rejects(submit(identity),e=>e.code==='42501');await assert.rejects(status(command.requestId),e=>e.code==='42501');assert.deepEqual(await count(command.requestId),{journal:1,payments:1})}finally{await pool.query('UPDATE "Partners" SET "Login Email"=$1 WHERE "Row ID"=\'4A-ACTOR\'',[actor.loginEmail])}
});
test('explicit historical retained-outcome fixture replays before new-command day validation',async()=>{
 const {command}=await fixture('4A-JC-HISTORIC');const old={...command,paymentDate:'2020-01-01'},identity=commandIdentity(old,actor,null);await pool.query('INSERT INTO public.pwa_payment_commands(request_id,contract_version,actor_issuer,actor_subject,actor_partner_id,actor_login_email,canonical_json,payload_sha256,outcome,payment_id,rejection_code) VALUES($1,1,$2,$3,$4,$5,$6,$7,\'posted\',$8,NULL)',[old.requestId,actor.issuer,actor.subject,actor.partnerId,actor.loginEmail.toLowerCase(),identity.canonicalJson,identity.payloadSha256,'pwa:'+old.requestId]);const replay=await submit(identity);assert.equal(replay.originalOutcome.status,'posted');assert.deepEqual(await count(old.requestId),{journal:1,payments:0});const fresh={...old,requestId:randomUUID()};assert.equal((await submit(commandIdentity(fresh,actor,null))).originalOutcome.code,'invalid_date');
});
