import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {disposablePool} from '../../scripts/rehearsal/disposable-pool.mjs';
import {createPaymentRehearsal,canonicalPayment,paymentId,TRUSTED_ACTOR} from '../../scripts/rehearsal/payment-command.mjs';
import {seedPaymentFixture} from '../../scripts/rehearsal/payment-fixture.mjs';
let pool;before(async()=>{pool=await disposablePool()});after(async()=>{await pool?.end()});
async function fixture(prefix){await seedPaymentFixture(pool,prefix);const provider=createPaymentRehearsal({pool});const command={schemaVersion:2,notes:null,receiptId:null,requestId:randomUUID(),borrowerId:prefix+'-B',selectedChargeIds:[prefix+'-C2',prefix+'-C1'],cashAccountId:'4A-RECEIVE',paymentDate:await provider.businessDate(),amountReceived:'330',paymentMethod:'Bank Transfer',allocationMethod:'Selected Charges'};return{provider,command}}
async function counts(id){return(await pool.query('SELECT (SELECT count(*) FROM "Payments" WHERE "Row ID"=$1)::integer AS payments,(SELECT count(*) FROM "Payment Allocations" WHERE "Ref Payment"=$1)::integer AS allocations,(SELECT count(*) FROM "Repayments" WHERE "Ref Payment"=$1)::integer AS repayments,(SELECT count(*) FROM "Cash Ledger" WHERE "Ref Payment"=$1)::integer AS ledger',[paymentId(id)])).rows[0]}
test('canonical payload is strict whole-baht, selected scope and actor cannot be supplied',()=>{const input={schemaVersion:2,notes:null,receiptId:null,requestId:randomUUID(),borrowerId:'4A-B',selectedChargeIds:['4A-Z','4A-A'],cashAccountId:'4A-C',paymentDate:'2026-10-08',amountReceived:'330',paymentMethod:'Bank Transfer',allocationMethod:'Selected Charges'};assert.deepEqual(canonicalPayment(input,input.paymentDate).selectedChargeIds,['4A-A','4A-Z']);for(const patch of [{actor:'evil'},{amountReceived:'330.5'},{amountReceived:'0'},{selectedChargeIds:['4A-A','4A-A']},{paymentDate:'2026-02-30'},{selectedChargeIds:['4A-A,B']}])assert.throws(()=>canonicalPayment({...input,...patch},input.paymentDate))});
test('actual V77 selected posting conserves330; same key once, changed payload or actor conflicts',async()=>{const{provider,command}=await fixture('4A-POST');const replies=await Promise.all([provider.submit(command),provider.submit(command)]);assert.ok(replies.every(r=>r.status==='posted'));assert.deepEqual(await counts(command.requestId),{payments:1,allocations:2,repayments:2,ledger:1});const amounts=(await pool.query('SELECT sum("Principal Paid"::numeric)::text AS principal,sum("Interest Paid"::numeric)::text AS interest FROM "Repayments" WHERE "Ref Payment"=$1',[paymentId(command.requestId)])).rows[0];assert.equal(amounts.principal,'300.00');assert.equal(amounts.interest,'30.00');assert.equal((await provider.submit({...command,amountReceived:'55'})).status,'conflict');assert.equal((await provider.submit(command,'other@example.invalid')).status,'conflict');assert.equal((await provider.status(command.requestId)).status,'posted');assert.equal((await pool.query('SELECT "Amount Remaining"::text AS remaining FROM "Charges" WHERE "Row ID"=$1',['4A-POST-UNSELECTED'])).rows[0].remaining,'55.00')});
test('invalid amount, foreign and future selection roll back all effects',async()=>{const{provider,command}=await fixture('4A-REJECT');for(const patch of [{amountReceived:'329'},{selectedChargeIds:['4A-REJECT-FOREIGN'],amountReceived:'33'},{selectedChargeIds:['4A-REJECT-FUTURE'],amountReceived:'10'}]){const next={...command,...patch,requestId:randomUUID()};assert.equal((await provider.submit(next)).status,'rejected');assert.deepEqual(await counts(next.requestId),{payments:0,allocations:0,repayments:0,ledger:0})}});
test('two different request IDs contend for same charges, at most one posts',async()=>{const{provider,command}=await fixture('4A-RACE');const other={...command,requestId:randomUUID()};const results=await Promise.all([provider.submit(command),provider.submit(other)]);assert.deepEqual(results.map(x=>x.status).sort(),['posted','rejected']);assert.equal((await counts(command.requestId)).ledger+(await counts(other.requestId)).ledger,1)});
test('AppSheet-style direct Processing insertion contends through the same V77 locks',async()=>{const{provider,command}=await fixture('4A-DIRECT');const directId='4A-DIRECT-PAY';const direct=pool.query('INSERT INTO "Payments"("Row ID","Ref Borrower","Ref Received By Cash Account","Status","Amount Received","Payment Date","Allocation Method","Selected Charge IDs","Payment Method","Created By") VALUES($1,$2,$3,\'Processing\',330::money,$4,\'Selected Charges\',$5,\'Bank Transfer\',$6)',[directId,command.borrowerId,command.cashAccountId,command.paymentDate,command.selectedChargeIds.join(' , '),TRUSTED_ACTOR]).then(()=>true,()=>false);const[result,directPosted]=await Promise.all([provider.submit(command),direct]);assert.equal(Number(result.status==='posted')+Number(directPosted),1)});
test('V77 correction/delete demonstrate missing durable original payload and tombstone',async()=>{const{provider,command}=await fixture('4A-GAP');assert.equal((await provider.submit(command)).status,'posted');await pool.query('UPDATE "Payments" SET "Selected Charge IDs"=$2,"Amount Received"=55::money WHERE "Row ID"=$1',[paymentId(command.requestId),'4A-GAP-UNSELECTED']);assert.equal((await provider.status(command.requestId)).code,'source_changed');const restarted=createPaymentRehearsal({pool});assert.equal((await restarted.status(command.requestId)).code,'journal_missing');await pool.query('DELETE FROM "Payments" WHERE "Row ID"=$1',[paymentId(command.requestId)]);assert.equal((await provider.status(command.requestId)).code,'source_missing');assert.equal((await restarted.submit(command)).status,'posted','This intentionally demonstrates absent durable tombstone; not production-safe');});