import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {disposablePool} from '../../scripts/rehearsal/disposable-pool.mjs';import {createLocalReceipts,MAX_RECEIPT_BYTES} from '../../scripts/rehearsal/local-receipts.mjs';import {createPaymentRehearsal,paymentId,TRUSTED_ACTOR} from '../../scripts/rehearsal/payment-command.mjs';import {seedPaymentFixture} from '../../scripts/rehearsal/payment-fixture.mjs';
let pool,receipts,png;before(async()=>{pool=await disposablePool();receipts=await createLocalReceipts({dataDirectory:process.env.PAYMENT_REHEARSAL_DIRECTORY});png=execFileSync(process.env.CLOUDSDK_PYTHON,['-c','from PIL import Image;import sys;Image.new("RGB",(2,2),(255,128,0)).save(sys.stdout.buffer,format="PNG")'],{windowsHide:true})});after(async()=>pool?.end());
async function snapshot(id){const result=await pool.query(`SELECT jsonb_build_object('payment',(SELECT to_jsonb(p)-'Uploaded Receipt'-'Uploaded Receipt At' FROM "Payments" p WHERE "Row ID"=$1),'repayments',(SELECT jsonb_agg(to_jsonb(r) ORDER BY "Row ID") FROM "Repayments" r WHERE "Ref Payment"=$1),'allocations',(SELECT jsonb_agg(to_jsonb(a) ORDER BY "Row ID") FROM "Payment Allocations" a WHERE "Ref Payment"=$1),'cash',(SELECT jsonb_agg(to_jsonb(c) ORDER BY "Row ID") FROM "Cash Ledger" c WHERE "Ref Payment"=$1)) AS value`,[paymentId(id)]);return result.rows[0].value}
test('actual V52 metadata lifecycle preserves exact notes, all financial rows and agent evidence',async()=>{
 await seedPaymentFixture(pool,'4A-C-RECEIPT');const provider=createPaymentRehearsal({pool,receipts});const id=randomUUID(),scope={requestId:id,actor:TRUSTED_ACTOR};const first=await receipts.upload({...scope,bytes:png,mime:'image/png'}),second=await receipts.upload({...scope,bytes:png,mime:'image/png'});const notes='  ไทย exact\n<script>not executable</script>\n trailing  ';const command={schemaVersion:2,requestId:id,borrowerId:'4A-C-RECEIPT-B',selectedChargeIds:['4A-C-RECEIPT-C1','4A-C-RECEIPT-C2'],cashAccountId:'4A-RECEIVE',paymentDate:await provider.businessDate(),amountReceived:'330',paymentMethod:'Bank Transfer',allocationMethod:'Selected Charges',notes,receiptId:first.receiptId};
 const posted=await provider.submit(command);assert.equal(posted.status,'posted');assert.equal(posted.notes,notes);assert.ok(posted.uploadedReceiptAt);assert.equal(posted.receipt.receiptId,first.receiptId);const baseline=await snapshot(id);assert.equal(baseline.payment.Notes,notes);assert.equal(baseline.payment['Receipt Image'],null);assert.equal(baseline.payment['IG Receipt ID'],null);assert.equal(baseline.payment['Receipt Received At'],null);
 const unchanged=await provider.attachReceipt({requestId:id,expectedReceiptId:first.receiptId,newReceiptId:first.receiptId});assert.equal(unchanged.ok,true);assert.equal((await provider.status(id)).uploadedReceiptAt,posted.uploadedReceiptAt);
 assert.equal((await provider.attachReceipt({requestId:id,expectedReceiptId:first.receiptId,newReceiptId:second.receiptId})).ok,true);const replaced=await provider.status(id);assert.ok(replaced.uploadedReceiptAt>posted.uploadedReceiptAt);assert.equal(replaced.receipt.receiptId,second.receiptId);assert.deepEqual(await snapshot(id),baseline);
 assert.equal((await provider.attachReceipt({requestId:id,expectedReceiptId:first.receiptId,newReceiptId:null})).code,'attachment_conflict');assert.equal((await provider.submit({...command,notes:notes+'changed'})).status,'conflict');assert.equal((await provider.submit({...command,receiptId:second.receiptId})).status,'conflict');assert.equal((await provider.submit(command)).status,'posted');
 assert.equal((await provider.attachReceipt({requestId:id,expectedReceiptId:second.receiptId,newReceiptId:null})).ok,true);const removed=await provider.status(id);assert.equal(removed.receipt,null);assert.equal(removed.uploadedReceiptAt,null);assert.deepEqual(await snapshot(id),baseline);
});
test('receipt decoder, scope and restart reject unsafe or unavailable references',async()=>{
 const scope={requestId:randomUUID(),actor:TRUSTED_ACTOR};const d=await receipts.upload({...scope,bytes:png,mime:'image/png'});assert.deepEqual((await receipts.retrieve(d.receiptId,scope)).bytes,png);
 for(const entry of [{bytes:png,mime:'image/jpeg'},{bytes:Buffer.from([137,80,78,71,13,10,26,10]),mime:'image/png'},{bytes:Buffer.alloc(MAX_RECEIPT_BYTES+1),mime:'image/png'},{bytes:png,mime:'image/heic'}])await assert.rejects(receipts.upload({...scope,...entry}));
 for(const badScope of [{...scope,actor:'other@example.invalid'},{...scope,requestId:randomUUID()}])assert.throws(()=>receipts.resolve(d.receiptId,badScope));assert.throws(()=>receipts.resolve('../../outside.png',scope));
 const restarted=await createLocalReceipts({dataDirectory:process.env.PAYMENT_REHEARSAL_DIRECTORY});assert.throws(()=>restarted.resolve(d.receiptId,scope),'Bytes alone must not reconstruct the lost descriptor journal');
});
test('missing receipt descriptor cannot erase a confirmed financial posting',async()=>{
 await seedPaymentFixture(pool,'4A-C-RECEIPT-MISSING');const id=randomUUID();const receipt=await receipts.upload({requestId:id,actor:TRUSTED_ACTOR,bytes:png,mime:'image/png'});let unavailable=false;const scoped={...receipts,resolve:(...args)=>{if(unavailable)throw Error('receipt_unavailable');return receipts.resolve(...args)}};const provider=createPaymentRehearsal({pool,receipts:scoped});const command={schemaVersion:2,requestId:id,borrowerId:'4A-C-RECEIPT-MISSING-B',selectedChargeIds:['4A-C-RECEIPT-MISSING-C1','4A-C-RECEIPT-MISSING-C2'],cashAccountId:'4A-RECEIVE',paymentDate:await provider.businessDate(),amountReceived:'330',paymentMethod:'Bank Transfer',allocationMethod:'Selected Charges',notes:'Back\nNotes',receiptId:receipt.receiptId};assert.equal((await provider.submit(command)).status,'posted');const baseline=await snapshot(id);unavailable=true;const status=await provider.status(id);assert.equal(status.status,'posted','Financial confirmation survives unavailable attachment metadata');assert.equal(status.amountReceived,'330');assert.equal((await provider.submit(command)).status,'posted','Known replay must reconcile despite unavailable original attachment');assert.equal((await provider.submit({...command,requestId:randomUUID()})).status,'rejected','New command with unavailable descriptor rejects');assert.equal((await provider.submit({...command,notes:'changed'})).status,'conflict','Changed known payload conflicts before attachment resolution');assert.deepEqual(await snapshot(id),baseline);
});
