import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {connect,principal,command} from './phase6-populated-fixture.mjs';
test('M3-B01 contribution create read update and delete use existing journal and source',async()=>{const {admin,app,store}=await connect(85);try{const fixture=JSON.parse(readFileSync(process.env.PHASE6_POPULATED_SNAPSHOT,'utf8')).fixture,day=(await admin.query("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date::text AS day")).rows[0].day;const c=command('capital-contribution.create',{partnerId:fixture.actorId,contributionDate:day,transactionType:'Contribution',amount:'123.45',notes:'M3 smoke'});const r=await store.operation(principal,c);assert.equal(r.originalOutcome?.status,'applied',JSON.stringify(r));assert.deepEqual(await store.operation(principal,c),r);const current=await store.management(principal,'contributions',{id:c.targetId});assert.equal(current.status,200);assert.equal(current.item.amount,'123.45');const u=command('capital-contribution.update',{...c.inputs,notes:'M3 exact update'},c.targetId,current.item.version);assert.equal((await store.operation(principal,u)).originalOutcome?.status,'applied');const fresh=await store.management(principal,'contributions',{id:c.targetId});assert.equal(fresh.item.notes,'M3 exact update');const d=command('capital-contribution.delete',{},c.targetId,fresh.item.version);assert.equal((await store.operation(principal,d)).originalOutcome?.status,'applied');assert.equal((await store.management(principal,'contributions',{id:c.targetId})).status,404);}finally{await app.end();await admin.end()}});

test('M5-B02 opening preview and native initialization plus assessment create/read refresh',async()=>{const {admin,app,store}=await connect(85);try{
 const fixture=JSON.parse(readFileSync(process.env.PHASE6_POPULATED_SNAPSHOT,'utf8')).fixture,day=(await admin.query("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date::text AS day")).rows[0].day;
 const preview=await store.management(principal,'openings',{id:'ch:dad'});assert.equal(preview.status,200,JSON.stringify(preview));
 const uninitialized=preview.item.accounts.filter(a=>!a.initialized);assert.ok(uninitialized.length);assert.equal(preview.item.accounts.some(a=>a.initialized),false);
 const init=command('cash-openings.initialize',{openings:uninitialized.map((a,n)=>({accountId:a.accountId,amount:n===0?preview.item.holderBalance.replace(/\.0+$/,''):'0'})),reviewedBasisHash:preview.item.reviewedBasisHash,notes:'Synthetic opening smoke'},'ch:dad',preview.item.version);
 const initialized=await store.operation(principal,init);assert.equal(initialized.originalOutcome?.status,'applied',JSON.stringify(initialized));assert.deepEqual(await store.operation(principal,init),initialized);
 assert.equal((await store.management(principal,'openings',{id:'ch:dad'})).item.accounts.every(a=>a.initialized),true);
 const a=command('assessment.create',{assessmentId:'Synthetic assessment',borrowerId:fixture.borrowerId,proposedLoanAmount:'100',minimumDailyProfitRate:'0.01',forecastStart:day,forecastEnd:day});
 const created=await store.operation(principal,a);assert.equal(created.originalOutcome?.status,'applied',JSON.stringify(created));
 const read=await store.management(principal,'assessments',{id:a.targetId});assert.equal(read.status,200,JSON.stringify(read));assert.equal(read.item.forecastStart,day);assert.equal(read.item.freshness,'current');
 const refreshed=await store.operation(principal,command('assessment.refresh',{},a.targetId,read.item.version));assert.equal(refreshed.originalOutcome?.status,'applied',JSON.stringify(refreshed));
 }finally{await app.end();await admin.end()}});

test('M7-B03 analytics provider reads and native Recent refresh replay',async()=>{const {admin,app,store}=await connect(85);try{
 await admin.query(`INSERT INTO public."Statistics"("Row ID","Statistics ID") SELECT 'M7-B-SYNTHETIC','Synthetic analytics' WHERE NOT EXISTS(SELECT 1 FROM public."Statistics")`);
 const overview=await store.management(principal,'analytics-overview',{});assert.equal(overview.status,200,JSON.stringify(overview));assert.ok(overview.metrics.totalProfit!==undefined);assert.ok(overview.refreshTarget);
 for(const metric of ['distribution','profit30','dailyInterest','projected','daily','weekly','monthly','outstanding30','profit30Line']){const chart=await store.management(principal,'analytics-chart',{metric});assert.equal(chart.status,200,metric+JSON.stringify(chart));assert.ok(Array.isArray(chart.items));}
 const op=command('analytics.refresh',{mode:'Recent'},overview.refreshTarget.id,overview.refreshTarget.version);const refreshed=await store.operation(principal,op);assert.equal(refreshed.originalOutcome?.status,'applied',JSON.stringify(refreshed));assert.deepEqual(await store.operation(principal,op),refreshed);
 const validation=await store.management(principal,'analytics-validation',{});assert.equal(validation.status,200,JSON.stringify(validation));assert.ok(validation.items.length>=2);
 }finally{await app.end();await admin.end()}});
