import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {randomUUID,createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {disposablePool} from '../../scripts/rehearsal/disposable-pool.mjs';
import {seedPaymentFixture} from '../../scripts/rehearsal/payment-fixture.mjs';
import {planApplicationRole,reconcileApplicationRole} from '../../scripts/database/app-role-policy.mjs';
import {attestDisposableApplicationTarget} from '../../services/payment-command/application-target.mjs';
import {createApplicationRoleCommandStore} from '../../services/payment-command/store.mjs';
import {canonicalOperation,operationIdentity} from '../../services/contracts/operation-command.mjs';
import {canonicalCommand,commandIdentity} from '../../services/contracts/payment-command.mjs';
import {OWNER_EMAIL,DEV_PROJECT} from '../../services/api/dev-read-config.mjs';
let admin,app,store,proof,fixture;const user='mw_app_dev_c_root_lists_fixture';
const principal={ok:true,email:OWNER_EMAIL,subject:'independent-generalized-owner'};
const fields=()=>({name:'C operation '+randomUUID(),description:'Synthetic English',communicationName:null,instagramUsername:null,city:null,workingLocation:null,address:null,hidden:null,referrerId:null,preferredReceivingAccountId:fixture.receivingAccountId,note:' exact ไทย\n '});
const command=(inputs=fields())=>({requestId:randomUUID(),operation:'borrower.create',targetId:randomUUID(),expectedVersion:null,predecessorRequestId:null,inputs,receiptId:null});
const actor=()=>({issuer:`https://securetoken.google.com/${DEV_PROJECT}`,subject:principal.subject,partnerId:fixture.actorId,loginEmail:OWNER_EMAIL});
before(async()=>{
 admin=await disposablePool(83);await admin.query(`CREATE ROLE ${user} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);await admin.query(`GRANT mw_app_dev TO ${user}`);const c=await admin.connect();try{const plan=await planApplicationRole(c,{database:'payment_rehearsal',creators:['postgres']});assert.deepEqual(plan.violations,[]);await reconcileApplicationRole(c,{database:'payment_rehearsal',creators:['postgres']},{apply:true})}finally{c.release()}
 app=new pg.Pool({host:'127.0.0.1',port:Number(process.env.PAYMENT_REHEARSAL_PORT),database:'payment_rehearsal',user,password:'',max:4});proof=await attestDisposableApplicationTarget({adminPool:admin,expectedDirectory:process.env.PAYMENT_REHEARSAL_DIRECTORY,runtimeUser:user,expectedVersion:83});store=createApplicationRoleCommandStore({pool:app,targetAttestation:proof,ownerTesting:true});
 fixture=await seedPaymentFixture(admin,'C-P5-ROOTS');await admin.query('UPDATE "Partners" SET "Login Email"=$1 WHERE "Row ID"=$2',[OWNER_EMAIL,fixture.actorId]);const role=(await app.query('SELECT current_user AS name,rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user')).rows[0];assert.deepEqual(role,{name:user,rolsuper:false,rolbypassrls:false});
});
after(async()=>{await app?.end();await admin?.end()});
async function assertSameBusinessReadC(current,expected){
 const day=(await admin.query("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date::text AS day")).rows[0].day;
 const business=row=>{const {asOf,businessDate,...value}=row;assert.match(asOf,/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);assert.equal(new Date(asOf).toISOString(),asOf);assert.equal(businessDate,day);return value};
 assert.deepEqual(business(current),business(expected));
}
async function rows(id){return(await admin.query('SELECT to_jsonb(j) AS value FROM pwa_payment_commands j WHERE request_id=$1',[id])).rows}
async function source(id){return(await admin.query('SELECT to_jsonb(b) AS value FROM "Borrowers" b WHERE "Row ID"=$1',[id])).rows}
async function create(c=command()){const r=await store.operation(principal,c);assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.originalOutcome.status,'applied');return {c,r,item:(await store.borrowerRecord(principal,c.targetId)).item}}

const byteSort=(a,b)=>Buffer.compare(Buffer.from(a??''),Buffer.from(b??''));
async function allRootC(kind,q,limit=7){let cursor=null,items=[],firstCursor;do{const page=await store.recordList(principal,kind,{q,limit,cursor});assert.equal(page.status,200,JSON.stringify(page));items.push(...page.items);firstCursor??=page.nextCursor;cursor=page.nextCursor;assert.ok(items.length<300)}while(cursor);assert.equal(new Set(items.map(x=>x.id)).size,items.length);return {items,firstCursor}}
test('F13-C01 root Loans and Payments preserve complete source groups ordering literal search and closed cursors',async()=>{
 const tag='C-root-'+randomUUID(),a=await create(command({...fields(),name:tag+' - X',description:'Y %_ ไทย',hidden:true})),b=await create(command({...fields(),name:tag,description:'X - Y %_ ไทย',hidden:false}));
 const day=(await admin.query("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date::text AS day")).rows[0].day;
 const loanIds=[];for(let i=0;i<28;i++){const id=randomUUID(),borrower=i%2?a.c.targetId:b.c.targetId,status=['ยังไม่ปิดยอด','ปิดยอดแล้ว',null][i%3];await app.query('INSERT INTO "Loans"("Row ID","Ref Borrowers","Ref Disbursed From Cash Account","Loan Date","Principal Amount","Loan Status","Loan Type","Auto Charge Enabled","Created By") VALUES($1,$2,$3,$4::date-900,1000::money,$5,$6,false,$7)',[id,borrower,fixture.lendingAccountId,day,status,'กำหนดวันชำระ',OWNER_EMAIL]);loanIds.push(id)}
 for(const [id,borrower] of [[loanIds[0],b.c.targetId],[loanIds[1],a.c.targetId]])await app.query('INSERT INTO "Charges"("Row ID","Ref Loans","Charge Date","Principal Due","Interest Due") VALUES($1,$2,$3::date-900,0::money,10000::money)',[randomUUID(),id,day]);
 const paymentIds=[];for(let i=0;i<29;i++){const id=randomUUID(),borrower=i<26?a.c.targetId:b.c.targetId;await app.query('INSERT INTO "Payments"("Row ID","Status","Ref Borrower","Amount Received","Payment Date","Payment Method","Allocation Method","Ref Received By Cash Account","Created By","Created At") VALUES($1,$2,$3,1::money,$4,$5,$6,$7,$8,$9::timestamp)',[id,'Processing',borrower,day,'Cash','Lump Sum',fixture.receivingAccountId,OWNER_EMAIL,i%2?'2026-01-01 01:00:00':null]);paymentIds.push(id)}

 const loans=await allRootC('loans',tag);assert.equal(loans.items.length,28);assert.deepEqual(new Set(loans.items.map(r=>r.id)),new Set(loanIds));assert.deepEqual(new Set(loans.items.map(r=>r.rank)),new Set([0,1,2]));
 const rawLoans=(await admin.query('SELECT l."Row ID" id,l."Ref Borrowers" borrower,l."Loan Status" status,l."Loan Date"::text AS day,l."Principal Amount"::numeric::text principal,l."Total Interest Received"::numeric::text interest FROM "Loans" l WHERE l."Row ID"=ANY($1::text[])',[loanIds])).rows;
 const expected=rawLoans.sort((x,y)=>['ยังไม่ปิดยอด','ปิดยอดแล้ว',null].indexOf(x.status)-['ยังไม่ปิดยอด','ปิดยอดแล้ว',null].indexOf(y.status)||byteSort(x.borrower,y.borrower)||byteSort(y.day,x.day)||byteSort(x.id,y.id));assert.deepEqual(loans.items.map(r=>r.id),expected.map(r=>r.id));for(const row of loans.items){const raw=rawLoans.find(r=>r.id===row.id);assert.equal(Number(row.principalRecoveredByInterestRatio),Number(raw.interest)/Number(raw.principal));assert.equal(row.totalInterestReceived,raw.interest)}
 const borrowerIds=[a.c.targetId,b.c.targetId];
 async function insertPayment(borrower,date){const id=randomUUID();await app.query('INSERT INTO "Payments"("Row ID","Status","Ref Borrower","Amount Received","Payment Date","Payment Method","Allocation Method","Ref Received By Cash Account","Created By","Created At") VALUES($1,$2,$3,1::money,$4,$5,$6,$7,$8,$9::timestamp)',[id,'Processing',borrower,date,'Cash','Lump Sum',fixture.receivingAccountId,OWNER_EMAIL,paymentIds.length%2?'2026-01-01 01:00:00':null]);paymentIds.push(id);return id}
 // Source-valid historical payments, never fabricated nonPosted rows or disabled triggers.
 for(let i=0;i<75;i++)await insertPayment(a.c.targetId,day);
 for(let i=1;i<=25;i++){const historical=(await admin.query('SELECT ($1::date-$2*interval\'1 month\')::date::text AS day',[day,i])).rows[0].day;await insertPayment(a.c.targetId,historical)}
 for(let i=0;i<24;i++){const borrower=await create(command({...fields(),name:tag+' '+String(i).padStart(2,'0'),description:'literal %_ ไทย'})),loan=randomUUID();borrowerIds.push(borrower.c.targetId);await app.query('INSERT INTO "Loans"("Row ID","Ref Borrowers","Ref Disbursed From Cash Account","Loan Date","Principal Amount","Loan Status","Loan Type","Auto Charge Enabled","Created By") VALUES($1,$2,$3,$4::date-900,1::money,$5,$6,false,$7)',[loan,borrower.c.targetId,fixture.lendingAccountId,day,'ยังไม่ปิดยอด','กำหนดวันชำระ',OWNER_EMAIL]);await app.query('INSERT INTO "Charges"("Row ID","Ref Loans","Charge Date","Principal Due","Interest Due") VALUES($1,$2,$3::date-900,0::money,1000::money)',[randomUUID(),loan,day]);await insertPayment(borrower.c.targetId,day)}
 async function collect(options,level){let cursor=null,items=[],firstCursor,pages=[];do{const p=await store.recordList(principal,'payments',{q:tag,limit:25,...options,cursor});assert.equal(p.status,200,JSON.stringify(p));assert.equal(p.level,level);pages.push(p.items.length);items.push(...p.items);firstCursor??=p.nextCursor;cursor=p.nextCursor;assert.ok(pages.length<10)}while(cursor);return {items,firstCursor,pages}}
 const root=await collect({},'borrowers');assert.deepEqual(root.pages,[25,1]);assert.deepEqual(new Set(root.items.map(r=>r.borrowerId)),new Set(borrowerIds));assert.equal(new Set(root.items.map(r=>r.id)).size,26);assert.equal(root.items.filter(r=>r.borrowerDisplayName===a.item.name+' - '+a.item.description).length,2);
 const rootOrder=(await admin.query('SELECT b."Row ID" id,coalesce(b."Borrower Name",\'\')||\' - \'||coalesce(b."Description",\'\') label FROM "Borrowers" b WHERE b."Row ID"=ANY($1::text[]) ORDER BY (coalesce(b."Borrower Name",\'\')||\' - \'||coalesce(b."Description",\'\')) COLLATE "C",b."Row ID" COLLATE "C"',[borrowerIds])).rows;assert.deepEqual(root.items.map(r=>r.id),rootOrder.map(r=>r.id));
 const months=await collect({borrowerId:a.c.targetId},'months');assert.deepEqual(months.pages,[25,1]);assert.equal(months.items.length,26);
 const rawMonths=(await admin.query('SELECT to_char("Payment Date",\'YYYY-MM\') AS month,sum("Amount Received")::numeric::text amount,count(*)::int count FROM "Payments" WHERE "Ref Borrower"=$1 GROUP BY 1 ORDER BY 1 DESC',[a.c.targetId])).rows;assert.deepEqual(months.items.map(r=>({month:r.month,amount:r.amountReceived,count:r.count})),rawMonths);
 const current=months.items[0];assert.equal(current.count,101);assert.equal(Number(current.amountReceived),101);
 const children=await collect({borrowerId:a.c.targetId,month:current.month},'payments');assert.deepEqual(children.pages,[25,25,25,25,1]);assert.equal(new Set(children.items.map(r=>r.id)).size,101);assert.equal(Number((await store.recordList(principal,'payments',{q:tag,borrowerId:a.c.targetId})).items[0].amountReceived),101);
 const rawChildren=(await admin.query('SELECT "Row ID" id,"Payment Date"::text AS day,"Created At"::text created FROM "Payments" WHERE "Ref Borrower"=$1 AND to_char("Payment Date",\'YYYY-MM\')=$2 ORDER BY "Payment Date" DESC,"Created At" DESC NULLS LAST,"Row ID" COLLATE "C"',[a.c.targetId,current.month])).rows;assert.deepEqual(children.items.map(r=>r.id),rawChildren.map(r=>r.id));for(const row of children.items){assert.equal(row.status,'Posted');assert.equal(Number(row.amountReceived),1);assert.ok(!('receiptReference'in row))}
 assert.equal((await store.recordList(principal,'payments',{q:'%_',limit:100})).items.filter(r=>borrowerIds.includes(r.id)).length,26);assert.equal((await store.recordList(principal,'payments',{q:'ไทย',limit:100})).items.filter(r=>borrowerIds.includes(r.id)).length,26);assert.equal((await store.recordList(principal,'loans',{q:tag+' absent'})).items.length,0);
 for(const options of [{cursor:months.firstCursor},{borrowerId:a.c.targetId,cursor:root.firstCursor},{borrowerId:b.c.targetId,cursor:months.firstCursor},{borrowerId:a.c.targetId,month:current.month,cursor:months.firstCursor},{borrowerId:a.c.targetId,month:months.items[1].month,cursor:children.firstCursor},{q:tag+' changed',cursor:root.firstCursor},{cursor:root.firstCursor+'='},{month:current.month},{borrowerId:a.c.targetId,unassigned:true},{limit:101}])assert.equal((await store.recordList(principal,'payments',{q:tag,...options})).status,400,JSON.stringify(options));
 assert.equal((await store.recordList(principal,'loans',{q:tag,cursor:root.firstCursor})).status,400);assert.equal((await store.recordList(principal,'payments',{q:tag,cursor:loans.firstCursor})).status,400);
 const denial=createApplicationRoleCommandStore({pool:{connect(){throw Error('businessSQLmustnotopen')}},targetAttestation:proof,ownerTesting:true});for(const kind of ['loans','payments'])assert.equal((await denial.recordList({...principal,email:'foreign@example.invalid'},kind,{})).status,403);
});
