import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {randomUUID,createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {writeFileSync,mkdirSync} from 'node:fs';
import {disposablePool} from '../../scripts/rehearsal/disposable-pool.mjs';
import {seedPaymentFixture} from '../../scripts/rehearsal/payment-fixture.mjs';
import {planApplicationRole,reconcileApplicationRole} from '../../scripts/database/app-role-policy.mjs';
import {attestDisposableApplicationTarget} from '../../services/payment-command/application-target.mjs';
import {readCommandResult} from '../../services/payment-command/result.mjs';
import {createApplicationRoleCommandStore} from '../../services/payment-command/store.mjs';
import {canonicalCommand,commandIdentity} from '../../services/contracts/payment-command.mjs';
import {OWNER_EMAIL,DEV_PROJECT} from '../../services/api/dev-read-config.mjs';
let admin,app,store;const runtimeUser='mw_app_dev_unified_independent';
const principal={ok:true,email:OWNER_EMAIL,subject:'unified-independent-owner'};
const actor={issuer:`https://securetoken.google.com/${DEV_PROJECT}`,subject:principal.subject,partnerId:'4A-ACTOR',loginEmail:OWNER_EMAIL};
before(async()=>{
 admin=await disposablePool(82);
 await admin.query(`CREATE ROLE ${runtimeUser} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);
 await admin.query(`GRANT mw_app_dev TO ${runtimeUser}`);
 const client=await admin.connect();try{const plan=await planApplicationRole(client,{database:'payment_rehearsal',creators:['postgres']});assert.deepEqual(plan.violations,[]);await reconcileApplicationRole(client,{database:'payment_rehearsal',creators:['postgres']},{apply:true})}finally{client.release()}
 app=new pg.Pool({host:'127.0.0.1',port:Number(process.env.PAYMENT_REHEARSAL_PORT),database:'payment_rehearsal',user:runtimeUser,password:'',max:4});
 const proof=await attestDisposableApplicationTarget({adminPool:admin,expectedDirectory:process.env.PAYMENT_REHEARSAL_DIRECTORY,runtimeUser,expectedVersion:82});
 store=createApplicationRoleCommandStore({pool:app,targetAttestation:proof,ownerTesting:true});
 const identity=(await app.query('SELECT current_user AS name,rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user')).rows[0];assert.deepEqual(identity,{name:runtimeUser,rolsuper:false,rolbypassrls:false});
 await assert.rejects(app.query('SET ROLE mw_app_dev_journal_owner'),e=>e.code==='42501');
});
after(async()=>{await app?.end();await admin?.end()});
async function seed(prefix){
 await seedPaymentFixture(admin,prefix);await admin.query('UPDATE "Partners" SET "Login Email"=$1 WHERE "Row ID"=\'4A-ACTOR\'',[OWNER_EMAIL]);
 await admin.query('DELETE FROM "Charges" WHERE "Ref Loans"=ANY($1::text[])',[[prefix+'-L1',prefix+'-L2']]);
 for(const [id,days,p,i] of [['new-z',0,80,20],['new-a',0,60,10],['old',-1,40,5],['future',1,50,7]])await admin.query('INSERT INTO "Charges"("Row ID","Ref Loans","Charge Date","Principal Due","Interest Due") VALUES($1,$2,(CURRENT_TIMESTAMP AT TIME ZONE \'Asia/Bangkok\')::date+$3::integer,$4::numeric::money,$5::numeric::money)',[prefix+'-'+id,prefix+'-L1',days,p,i]);
 const draft=await store.draft(principal,prefix+'-B',{scope:'all'});assert.equal(draft.status,200,JSON.stringify(draft));return {prefix,borrowerId:prefix+'-B',draft};
}
function line(f,suffix,p,i){const r=f.draft.charges.find(x=>x.id===f.prefix+'-'+suffix);assert.ok(r);return {chargeId:r.id,principal:String(p),interest:String(i),expectedPrincipalRemaining:r.principalRemaining,expectedInterestRemaining:r.interestRemaining,chargeDate:r.chargeDate}}
function command(f,allocations,total='130'){return {schemaVersion:6,requestId:randomUUID(),borrowerId:f.borrowerId,allocations,cashAccountId:'4A-RECEIVE',paymentDate:f.draft.businessDate,amountReceived:total,paymentMethod:'Cash',notes:'independent ไทย\nexact allocation',receiptId:null}}
function split(rows,prefix=''){return rows.map(r=>({id:prefix?r.chargeId.replace(prefix+'-',''):r.chargeId,p:Number(r.principal),i:Number(r.interest)})).sort((a,b)=>a.id.localeCompare(b.id))}
async function financial(id){return (await admin.query(`SELECT (SELECT count(*) FROM "Payments" WHERE "Row ID"=$1)::int p,(SELECT count(*) FROM "Payment Allocations" WHERE "Ref Payment"=$1)::int a,(SELECT count(*) FROM "Repayments" WHERE "Ref Payment"=$1)::int r,(SELECT count(*) FROM "Cash Ledger" WHERE "Ref Payment"=$1)::int c`,[id])).rows[0]}
async function posted(f,c){const review=await store.review(principal,f.borrowerId,{amountReceived:c.amountReceived,allocations:c.allocations});assert.equal(review.status,200,JSON.stringify(review));assert.deepEqual(review.allocations,canonicalCommand(c).allocations);const out=await store.submit(principal,c);assert.equal(out.status,200,JSON.stringify(out));assert.equal(out.originalOutcome.status,'posted');const result=await store.result(principal,c.requestId);assert.equal(result.currentSource,'present',JSON.stringify(result));assert.deepEqual(split(result.allocations),split(c.allocations));assert.deepEqual(split(result.repayments),split(c.allocations));assert.equal(result.cashMovements.length,1);assert.equal(Number(result.cashMovements[0].amount),Number(c.amountReceived));return {out,result,id:out.originalOutcome.paymentId}}

test('U1 v6 canonical bytes/hash agree with SQL and malformed envelopes have no journal',async()=>{
 const f=await seed('UC-CONTRACT'),c=command(f,[line(f,'new-z',80,0),line(f,'future',50,0)]);
 const identity=commandIdentity(c,actor,null);assert.equal(identity.payloadSha256,createHash('sha256').update(identity.canonicalJson).digest('hex'));
 const out=await store.submit(principal,c);assert.equal(out.status,200,JSON.stringify(out));const row=(await admin.query('SELECT canonical_json,payload_sha256 FROM pwa_payment_commands WHERE request_id=$1',[c.requestId])).rows[0];assert.deepEqual(row,{canonical_json:identity.canonicalJson,payload_sha256:identity.payloadSha256});
 const invalid=[{...c,requestId:randomUUID(),allocations:[{...c.allocations[0],principal:null}]},{...c,requestId:randomUUID(),allocations:[{...c.allocations[0],extra:'x'}]}, {...c,requestId:randomUUID(),amountReceived:'129'}, {...c,requestId:randomUUID(),allocations:[c.allocations[0],c.allocations[0]]}, {...c,requestId:randomUUID(),allocations:[{...c.allocations[0],principal:'1.5'}]}, {...c,requestId:randomUUID(),allocations:[{...c.allocations[0],principal:'-0'}]}];
 for(const bad of invalid){assert.throws(()=>canonicalCommand(bad));assert.equal((await store.submit(principal,bad)).status,400);await assert.rejects(app.query('SELECT pwa_submit_selected_charges_v1($1)',[JSON.stringify({contractVersion:1,command:bad,actor,receipt:null})]),e=>e.code==='22023');assert.equal((await admin.query('SELECT count(*)::int n FROM pwa_payment_commands WHERE request_id=$1',[bad.requestId])).rows[0].n,0)}
 const sparse={...c,allocations:Array(2)};assert.throws(()=>canonicalCommand(sparse));
 const large={...c,notes:'x'.repeat(65537)};assert.throws(()=>canonicalCommand(large));
 const rows=Array.from({length:3000},(_,n)=>({...line(f,'new-z',1,0),chargeId:'synthetic-'+String(n).padStart(5,'0')+'x'.repeat(100)}));assert.throws(()=>commandIdentity({...c,requestId:randomUUID(),allocations:rows,amountReceived:'3000'},actor,null));
});

test('U2 Auto is full-provider newest-date/C-ID/interest-first legacy Lump Sum parity',async()=>{
 const f=await seed('UC-AUTO'),auto=await store.autoAssign(principal,f.borrowerId,{amountReceived:'130'});assert.equal(auto.status,200,JSON.stringify(auto));assert.deepEqual(split(auto.allocations,f.prefix),[{id:'new-a',p:20,i:10},{id:'new-z',p:80,i:20}]);assert.equal(auto.allocated,'130');assert.equal(auto.unallocated,'0');assert.ok(!auto.allocations.some(x=>x.chargeId.endsWith('future')));assert.equal((await admin.query('SELECT count(*)::int n FROM pwa_payment_commands WHERE canonical_json::jsonb->\'command\'->>\'borrowerId\'=$1',[f.borrowerId])).rows[0].n,0);
 await posted(f,command(f,auto.allocations));const legacy=await seed('UC-LEGACY');const id='ordinary-'+randomUUID();await app.query('INSERT INTO "Payments"("Row ID","Ref Borrower","Ref Received By Cash Account","Status","Amount Received","Payment Date","Payment Method","Allocation Method","Created By") VALUES($1,$2,\'4A-RECEIVE\',\'Processing\',130::money,$3::date,\'Cash\',\'Lump Sum\',$4)',[id,legacy.borrowerId,legacy.draft.businessDate,OWNER_EMAIL]);const rows=(await admin.query('SELECT "Ref Charge" AS "chargeId","Allocated Principal"::numeric::text AS principal,"Allocated Interest"::numeric::text AS interest FROM "Payment Allocations" WHERE "Ref Payment"=$1',[id])).rows;assert.deepEqual(split(rows,legacy.prefix),split(auto.allocations,f.prefix));
 const excess=await seed('UC-EXCESS'),proposal=await store.autoAssign(principal,excess.borrowerId,{amountReceived:'300'});assert.equal(proposal.allocated,'215');assert.equal(proposal.unallocated,'85');assert.equal((await store.submit(principal,command(excess,proposal.allocations,'300'))).status,400);assert.deepEqual(await financial('pwa:'+randomUUID()),{p:0,a:0,r:0,c:0});
});

for(const [name,parts] of [['manual',[['new-z',80,0],['future',50,0]]],['hybrid',[['new-z',70,20],['new-a',30,10]]],['multiple future',[['future',20,7],['future2',20,3]]]])test('U3 exact '+name+' keeps principal and interest independent',async()=>{
 const f=await seed('UC-'+name.replace(/ /g,'-'));if(name==='multiple future'){await admin.query('INSERT INTO "Charges"("Row ID","Ref Loans","Charge Date","Principal Due","Interest Due") VALUES($1,$2,(CURRENT_TIMESTAMP AT TIME ZONE \'Asia/Bangkok\')::date+2,20::money,3::money)',[f.prefix+'-future2',f.prefix+'-L1']);f.draft=await store.draft(principal,f.borrowerId,{scope:'all'})}const rows=parts.map(([s,p,i])=>line(f,s,p,i)),amount=String(parts.reduce((sum,[,p,i])=>sum+p+i,0));const c=command(f,rows,amount),{out}=await posted(f,c);assert.deepEqual(await store.submit(principal,c),out);assert.equal((await store.submit(principal,{...c,paymentMethod:'Bank Transfer'})).status,409);assert.equal((await store.submit({...principal,subject:'different'},c)).status,409);
});

test('U4 foreign/missing charge and changed component/date source reject without derived effects',async()=>{
 for(const [suffix,mutation] of [['principal','"Principal Due"=81::money'],['interest','"Interest Due"=21::money'],['same-total','"Principal Due"=79::money,"Interest Due"=21::money'],['date','"Charge Date"="Charge Date"-1']]){const f=await seed('UC-STALE-'+suffix),c=command(f,[line(f,'new-z',10,0)],'10');await admin.query(`UPDATE "Charges" SET ${mutation} WHERE "Row ID"=$1`,[f.prefix+'-new-z']);const review=await store.review(principal,f.borrowerId,{amountReceived:'10',allocations:c.allocations});assert.equal(review.status,409,JSON.stringify(review));assert.equal(review.code,'plan_changed');const out=await store.submit(principal,c);assert.equal(out.status,422,JSON.stringify(out));assert.equal(out.originalOutcome.code,'selection_unavailable');assert.deepEqual(await financial('pwa:'+c.requestId),{p:0,a:0,r:0,c:0});assert.deepEqual(await store.submit(principal,c),out)}
 for(const suffix of ['FOREIGN','MISSING']){const f=await seed('UC-'+suffix),c=command(f,[{chargeId:f.prefix+'-'+suffix,principal:'1',interest:'0',expectedPrincipalRemaining:'30',expectedInterestRemaining:'3',chargeDate:f.draft.businessDate}],'1');const out=await store.submit(principal,c);assert.equal(out.status,422,JSON.stringify(out));assert.deepEqual(await financial('pwa:'+c.requestId),{p:0,a:0,r:0,c:0})}
});

test('U5 concurrent reviewed commands cannot overpay a component; exact replay survives',async()=>{
 const f=await seed('UC-RACE'),c=command(f,[line(f,'new-z',80,0)],'80'),other={...c,requestId:randomUUID()};const outcomes=await Promise.all([store.submit(principal,c),store.submit(principal,other)]);assert.deepEqual(outcomes.map(x=>x.status).sort(),[200,422]);const rows=(await admin.query('SELECT sum("Principal Paid"::numeric)::text p,sum("Interest Paid"::numeric)::text i FROM "Repayments" WHERE "Ref Charges"=$1',[f.prefix+'-new-z'])).rows[0];assert.equal(Number(rows.p),80);assert.equal(Number(rows.i),0);const winner=outcomes.findIndex(x=>x.status===200);assert.deepEqual(await store.submit(principal,winner?other:c),outcomes[winner]);
});

for(const stage of ['Payments','Payment Allocations','Repayments'])test('U6 technical fault during '+stage+' rolls provisional journal and every child back',async()=>{
 const f=await seed('UC-FAULT-'+stage.replace(/ /g,'-')),c=command(f,[line(f,'new-z',80,0),line(f,'future',50,0)]),key='pwa:'+c.requestId;
 await admin.query(`CREATE FUNCTION public.uc_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF ${stage==='Payments'?'NEW."Row ID"':'NEW."Ref Payment"'}='${key}' THEN IF NOT EXISTS(SELECT 1 FROM public.pwa_payment_commands WHERE request_id='${c.requestId}' AND outcome='posted') THEN RAISE EXCEPTION 'Provisional journal absent';END IF;RAISE EXCEPTION USING ERRCODE='XX000',MESSAGE='Synthetic child failure';END IF;RETURN NEW;END $$;CREATE TRIGGER zzz_uc_fault BEFORE INSERT ON public."${stage}" FOR EACH ROW EXECUTE FUNCTION public.uc_fault()`);
 try{const out=await store.submit(principal,c);assert.equal(out.status,503,JSON.stringify(out));assert.equal(out.code,'command_outcome_unknown');assert.deepEqual(await financial(key),{p:0,a:0,r:0,c:0});assert.equal((await admin.query('SELECT count(*)::int n FROM pwa_payment_commands WHERE request_id=$1',[c.requestId])).rows[0].n,0)}finally{await admin.query(`DROP TRIGGER zzz_uc_fault ON "${stage}";DROP FUNCTION public.uc_fault()`)}
 await posted(f,c);
});

test('U7/U13 actual non-owner retained-ID recreation and wrong-engine bypass fail',async()=>{
 const f=await seed('UC-FORGE'),c=command(f,[line(f,'new-z',80,0),line(f,'future',50,0)]),{id,out}=await posted(f,c);
 await assert.rejects(app.query('SELECT post_payment_legacy_v59($1)',[id]));await app.query('SELECT post_payment_explicit_v6($1)',[id]);await app.query('SELECT post_payment($1)',[id]);assert.deepEqual(await financial(id),{p:1,a:2,r:2,c:1});
 await app.query('DELETE FROM "Payments" WHERE "Row ID"=$1',[id]);assert.deepEqual(await financial(id),{p:0,a:0,r:0,c:0});assert.deepEqual(await store.submit(principal,c),out);assert.equal((await store.result(principal,c.requestId)).currentSource,'missing');
 const recreated=[id,f.borrowerId,c.amountReceived,c.paymentDate,c.paymentMethod,c.allocations.map(x=>x.chargeId).sort().join(' , '),OWNER_EMAIL];const insert='INSERT INTO "Payments"("Row ID","Ref Borrower","Ref Received By Cash Account","Status","Amount Received","Payment Date","Payment Method","Allocation Method","Selected Charge IDs","Created By") VALUES($1,$2,\'4A-RECEIVE\',\'Processing\',$3::numeric::money,$4::date,$5,\'Selected Charges\',$6,$7)';
 await assert.rejects(app.query(insert,recreated),e=>e.code==='42501');const client=await app.connect();try{await client.query('BEGIN');await client.query("SET LOCAL pwa.origin='6'; SET LOCAL payment_crud.parents='{}'");await assert.rejects(client.query(insert,recreated),e=>e.code==='42501');await client.query('ROLLBACK')}finally{client.release()}
 await assert.rejects(app.query('UPDATE pwa_payment_commands SET canonical_json=canonical_json WHERE request_id=$1',[c.requestId]),e=>e.code==='42501');assert.deepEqual(await financial(id),{p:0,a:0,r:0,c:0});
 const ordinary='pwa:'+randomUUID();await app.query(insert,[ordinary,f.borrowerId,'100',c.paymentDate,'Cash',f.prefix+'-new-z',OWNER_EMAIL]);await assert.rejects(app.query('SELECT post_payment_explicit_v6($1)',[ordinary]));assert.equal((await admin.query('SELECT "Status" status FROM "Payments" WHERE "Row ID"=$1',[ordinary])).rows[0].status,'Posted');
});

test('U8 compatible source corrections preserve explicit plan; unsupported scope rolls back atomically',async()=>{
 const f=await seed('UC-EDIT'),c=command(f,[line(f,'new-z',70,0),line(f,'future',50,0)],'120'),{id}=await posted(f,c);const baseline=(await admin.query('SELECT canonical_json FROM pwa_payment_commands WHERE request_id=$1',[c.requestId])).rows[0].canonical_json;
 await app.query('UPDATE "Payments" SET "Notes"=\'corrected ไทย\',"Payment Method"=\'Bank Transfer\',"Ref Received By Cash Account"=\'4A-LEND\',"Payment Date"="Payment Date"-1 WHERE "Row ID"=$1',[id]);const current=await store.result(principal,c.requestId);assert.equal(current.currentSource,'changed');assert.deepEqual(split(current.allocations),split(c.allocations));assert.deepEqual(split(current.repayments),split(c.allocations));assert.equal(current.cashMovements.length,1);assert.equal(Number(current.cashMovements[0].amount),120);
 const fingerprint=JSON.stringify({p:current.payment,a:current.allocations,r:current.repayments,c:current.cashMovements});for(const sql of ['"Amount Received"=121::money','"Ref Borrower"=\''+f.prefix+'-OTHER\'','"Selected Charge IDs"=\''+f.prefix+'-old\'','"Allocation Method"=\'Lump Sum\'','"Ref Target Loan"=\''+f.prefix+'-L1\'']){await assert.rejects(app.query(`UPDATE "Payments" SET ${sql} WHERE "Row ID"=$1`,[id]));const after=await store.result(principal,c.requestId);assert.equal(JSON.stringify({p:after.payment,a:after.allocations,r:after.repayments,c:after.cashMovements}),fingerprint)}assert.equal((await admin.query('SELECT canonical_json FROM pwa_payment_commands WHERE request_id=$1',[c.requestId])).rows[0].canonical_json,baseline);
});

test('U8/U9 later legitimate payments do not prevent correction; Notes CAS never changes original plan',async()=>{
 const f=await seed('UC-LATER'),c=command(f,[line(f,'new-z',40,0)],'40'),first=await posted(f,c);f.draft=await store.draft(principal,f.borrowerId,{scope:'all'});await posted(f,command(f,[line(f,'new-z',20,0)],'20'));await app.query('UPDATE "Payments" SET "Payment Method"=\'Bank Transfer\' WHERE "Row ID"=$1',[first.id]);const result=await store.result(principal,c.requestId);assert.deepEqual(split(result.allocations),split(c.allocations));assert.equal((await store.metadata(principal,c.requestId,{expectedVersion:result.payment.version,notes:'guarded'})).code,'source_changed');await app.query('UPDATE "Payments" SET "Payment Method"=\'Cash\' WHERE "Row ID"=$1',[first.id]);const restored=await store.result(principal,c.requestId);const saved=await store.metadata(principal,c.requestId,{expectedVersion:restored.payment.version,notes:'CAS ไทย'});assert.equal(saved.status,200,JSON.stringify(saved));assert.deepEqual(saved.originalCommand,canonicalCommand(c));assert.deepEqual(split(saved.allocations),split(c.allocations));assert.equal((await store.metadata(principal,c.requestId,{expectedVersion:result.payment.version,notes:'stale'})).status,409);
});

test('U13/U14 v3-v5 old protected commands retain legacy effects/replay and ordinary correction/delete',async()=>{
 for(const version of [3,4,5]){const f=await seed('UC-OLD'+version),ids=[f.prefix+'-new-a',f.prefix+'-new-z'];const c={schemaVersion:version,requestId:randomUUID(),borrowerId:f.borrowerId,selectedChargeIds:ids,cashAccountId:'4A-RECEIVE',paymentDate:f.draft.businessDate,amountReceived:'170',paymentMethod:'Bank Transfer',allocationMethod:'Selected Charges',notes:null,receiptId:null};const out=await store.submit(principal,c);assert.equal(out.status,200,JSON.stringify(out));const result=await store.result(principal,c.requestId);assert.deepEqual(split(result.allocations,f.prefix),[{id:'new-a',p:60,i:10},{id:'new-z',p:80,i:20}]);await app.query('SELECT post_payment_legacy_v59($1)',[out.originalOutcome.paymentId]);await assert.rejects(app.query('SELECT post_payment_explicit_v6($1)',[out.originalOutcome.paymentId]));assert.deepEqual(await store.submit(principal,c),out);await app.query('UPDATE "Payments" SET "Notes"=\'legacy correction\' WHERE "Row ID"=$1',[out.originalOutcome.paymentId]);await app.query('DELETE FROM "Payments" WHERE "Row ID"=$1',[out.originalOutcome.paymentId]);assert.deepEqual(await store.submit(principal,c),out);assert.equal((await store.result(principal,c.requestId)).currentSource,'missing')}
});

test('U15 labelled local 4-line and 100-line request timings with exact generated effects',async()=>{
 const timings=[];for(const count of [4,100]){const f=await seed('UC-SCALE'+count);await admin.query('DELETE FROM "Charges" WHERE "Ref Loans"=$1',[f.prefix+'-L1']);await admin.query('INSERT INTO "Charges"("Row ID","Ref Loans","Charge Date","Principal Due","Interest Due") SELECT $1||lpad(n::text,3,\'0\'),$2,(CURRENT_TIMESTAMP AT TIME ZONE \'Asia/Bangkok\')::date,1::money,1::money FROM generate_series(1,$3::integer)n',[f.prefix+'-scale-',f.prefix+'-L1',count]);const start=performance.now(),auto=await store.autoAssign(principal,f.borrowerId,{amountReceived:String(count*2)}),proposalMs=performance.now()-start;assert.equal(auto.allocations.length,count);const c=command(f,auto.allocations,String(count*2)),reviewAt=performance.now(),review=await store.review(principal,f.borrowerId,{amountReceived:c.amountReceived,allocations:c.allocations}),reviewMs=performance.now()-reviewAt;assert.equal(review.status,200);const postAt=performance.now(),out=await store.submit(principal,c),postMs=performance.now()-postAt;assert.equal(out.status,200,JSON.stringify(out));assert.deepEqual(await financial(out.originalOutcome.paymentId),{p:1,a:count,r:count,c:1});timings.push({count,proposalMs,reviewMs,postMs,allocations:count,repayments:count,cashRows:1})}mkdirSync('outputs/r052-unified-receiving',{recursive:true});writeFileSync('outputs/r052-unified-receiving/independent-local-request-timings.json',JSON.stringify({environment:'owned loopback disposable; sequential first-run samples, no CloudRun/cold-warm claim',timings},null,2));
});


test('U4 inactive receiving account and unmapped actor produce no financial effects',async()=>{
 const f=await seed('UC-ACCOUNT'),c={...command(f,[line(f,'new-z',10,0)],'10'),cashAccountId:'UC-INACTIVE'};await admin.query('INSERT INTO "Cash Accounts"("Row ID","Ref Cash Holder","Account Label","Bank Name","Active") VALUES(\'UC-INACTIVE\',\'ch:dad\',\'Synthetic inactive account\',\'Synthetic\',false)');try{const out=await store.submit(principal,c);assert.equal(out.status,422,JSON.stringify(out));assert.equal(out.originalOutcome.code,'account_unavailable');assert.deepEqual(await financial('pwa:'+c.requestId),{p:0,a:0,r:0,c:0})}finally{}
 const other={...c,cashAccountId:'4A-RECEIVE',requestId:randomUUID()};await admin.query('UPDATE "Partners" SET "Login Email"=\'unmapped@example.invalid\' WHERE "Row ID"=\'4A-ACTOR\'');try{assert.equal((await store.submit(principal,other)).status,403);assert.equal((await admin.query('SELECT count(*)::int n FROM pwa_payment_commands WHERE request_id=$1',[other.requestId])).rows[0].n,0)}finally{await admin.query('UPDATE "Partners" SET "Login Email"=$1 WHERE "Row ID"=\'4A-ACTOR\'',[OWNER_EMAIL])}
});

test('U6 deferred before-COMMIT fault leaves no externally Posted journal or derived rows',async()=>{
 const f=await seed('UC-COMMITFAULT'),c=command(f,[line(f,'new-z',10,0)],'10'),key='pwa:'+c.requestId;
 await admin.query(`CREATE FUNCTION public.uc_commit_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."Row ID"='${key}' THEN RAISE EXCEPTION USING ERRCODE='XX000',MESSAGE='Synthetic deferred commit failure';END IF;RETURN NEW;END $$;CREATE CONSTRAINT TRIGGER zzz_uc_commit_fault AFTER INSERT ON "Payments" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.uc_commit_fault()`);
 try{const out=await store.submit(principal,c);assert.equal(out.status,503,JSON.stringify(out));assert.equal(out.code,'command_outcome_unknown');assert.equal((await admin.query('SELECT count(*)::int n FROM pwa_payment_commands WHERE request_id=$1',[c.requestId])).rows[0].n,0);assert.deepEqual(await financial(key),{p:0,a:0,r:0,c:0})}finally{await admin.query('DROP TRIGGER zzz_uc_commit_fault ON "Payments";DROP FUNCTION public.uc_commit_fault()')}
 await posted(f,c);
});

test('U6 committed acknowledgement loss resolves through a fresh store/status without duplicates',async()=>{
 const f=await seed('UC-ACK'),c=command(f,[line(f,'new-z',10,0)],'10');let dropped=false;
 const lossyPool={connect:async()=>{const client=await app.connect();return {query:async(text,args)=>{const value=await client.query(text,args);if(text==='COMMIT'&&!dropped){dropped=true;throw Error('Synthetic acknowledgement loss after committed transaction')}return value},release:quarantine=>client.release(quarantine)}}};
 const proof=await attestDisposableApplicationTarget({adminPool:admin,expectedDirectory:process.env.PAYMENT_REHEARSAL_DIRECTORY,runtimeUser,expectedVersion:82});const lossy=createApplicationRoleCommandStore({pool:lossyPool,targetAttestation:proof,ownerTesting:true});const out=await lossy.submit(principal,c);assert.equal(out.status,503,JSON.stringify(out));assert.equal(out.code,'command_outcome_unknown');assert.equal(dropped,true);const resumed=createApplicationRoleCommandStore({pool:app,targetAttestation:proof,ownerTesting:true});const status=await resumed.status(principal,c.requestId);assert.equal(status.originalOutcome.status,'posted');const replay=await resumed.submit(principal,c);assert.equal(replay.originalOutcome.paymentId,status.originalOutcome.paymentId);assert.deepEqual(await financial(status.originalOutcome.paymentId),{p:1,a:1,r:1,c:1});
});

test('U9 direct child tamper denied; synthetic same-total split projection reports changed',async()=>{
 const f=await seed('UC-SPLIT'),c=command(f,[line(f,'new-z',70,10)],'80'),{id}=await posted(f,c);
 await assert.rejects(admin.query('UPDATE "Payment Allocations" SET "Allocated Principal"=69::money,"Allocated Interest"=11::money WHERE "Ref Payment"=$1',[id]),/immutable/);const result=await readCommandResult({query:async(text,args)=>{const value=await app.query(text,args);if(text.includes('\"Allocated Principal\"'))return {...value,rows:value.rows.map(row=>({...row,principal:'69.00',interest:'11.00'}))};return value}},actor,c.requestId);assert.equal(result.currentSource,'changed',JSON.stringify(result));assert.equal(Number(result.allocations[0].amount),80);assert.deepEqual(result.originalCommand,canonicalCommand(c));
});

