import {normalizeSearchQuery} from '../api/search-query.mjs';
import {validBorrowerId} from './borrowers.mjs';
const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
const version=alias=>`encode(sha256(convert_to(to_jsonb(${alias})::text,'UTF8')),'hex') version`;
const partnerProjection=`p."Row ID" id,p."Partner Name" label,p."Partner Role" AS "partnerRole",p."Login Email" AS "loginEmail",p."Email" email,p."Instagram Username" AS "instagramUsername",p."Language Preference" AS "languagePreference",p."IG Integration Enabled" AS "igIntegrationEnabled",p."AI Reviewer" AS "aiReviewer",${version('p')}`;
const accountProjection=`a."Row ID" id,a."Account Label" label,a."Ref Cash Holder" AS "holderId",h."Holder Name" AS "holderLabel",a."Bank Name" AS "bankName",a."Account Number" AS "accountNumber",a."Alternative Account Number" AS "alternativeAccountNumber",a."Default Account" AS "isDefault",a."Active" active,a."Sort Order" AS "sortOrder",a."Created At"::text AS "createdAt",${version('a')}`;
const holderProjection=`h."Row ID" id,h."Holder Name" label,h."Active" active,h."Sort Order" AS "sortOrder",h."Created At"::text AS "createdAt",${version('h')}`;
/** Existing source rows only. Owner/current-partner verification remains in the shared store. */
export async function readManagement(client,kind,{id=null,q='',limit=25,cursor=null}={}){
 if(!['cash-accounts','cash-holders','partners'].includes(kind)||!Number.isInteger(limit)||limit<1||limit>100)throw Error('invalid_request');
 let query;try{query=normalizeSearchQuery(q)}catch{throw Error('invalid_request')}
 if(id!==null&&(!validBorrowerId(id)||query||cursor!==null))throw Error('invalid_request');
 const account=kind==='cash-accounts',partner=kind==='partners',alias=partner?'p':account?'a':'h',name=partner?'Partner Name':account?'Account Label':'Holder Name';
 const source=partner?'public."Partners" p':account?'public."Cash Accounts" a LEFT JOIN public."Cash Holders" h ON h."Row ID"=a."Ref Cash Holder"':'public."Cash Holders" h';
 const projection=partner?partnerProjection:account?accountProjection:holderProjection;
 if(id!==null){const item=(await client.query(`SELECT ${projection} FROM ${source} WHERE ${alias}."Row ID"=$1`,[id])).rows[0]??null;if(item&&partner){Object.assign(item,(await client.query(`WITH capital AS (SELECT coalesce(sum(CASE WHEN "Transaction Type"='Contribution' THEN "Amount"::numeric ELSE -"Amount"::numeric END) FILTER(WHERE "Ref Partner"=$1),0) owned,coalesce(sum(CASE WHEN "Transaction Type"='Contribution' THEN "Amount"::numeric ELSE -"Amount"::numeric END),0) pool FROM public."Cash Pool Contributions"), settlements AS (SELECT coalesce(sum("Amount"::numeric) FILTER(WHERE "Status"='Completed'),0) completed,coalesce(sum("Amount"::numeric) FILTER(WHERE "Status"='Pending'),0) pending,coalesce(sum("Amount"::numeric) FILTER(WHERE "Status"<>'Cancelled'),0) created FROM public."Settlements" WHERE "Ref Partner"=$1) SELECT owned::text AS "currentPoolContribution",(CASE WHEN pool>0 THEN owned/pool ELSE 0 END)::text AS "currentPoolShare",public.partner_net_profit($1)::text AS "netProfitEarned",created::text AS "totalSettlementCreated",(CASE WHEN (SELECT "Partner Role" FROM public."Partners" WHERE "Row ID"=$1) IN('A','B') THEN public.partner_net_profit($1)+coalesce((SELECT sum(CASE (SELECT "Partner Role" FROM public."Partners" WHERE "Row ID"=$1) WHEN 'A' THEN "Partner A Expense"::numeric WHEN 'B' THEN "Partner B Expense"::numeric END) FROM public."Business Expenses"),0) ELSE NULL END)::text AS "totalProfitEarned",completed::text AS "completedSettlement",pending::text AS "pendingSettlement",(public.partner_net_profit($1)-created)::text AS "netAvailableToSettle" FROM capital CROSS JOIN settlements`,[id])).rows[0]);}return {item};}
 let after=null;if(cursor!==null){try{after=JSON.parse(Buffer.from(cursor,'base64url').toString('utf8'));if(encode(after)!==cursor||Object.keys(after).join(',')!=='v,kind,q,label,id'||after.v!==1||after.kind!==kind||after.q!==query||typeof after.label!=='string'||!validBorrowerId(after.id))throw Error()}catch{throw Error('invalid_request')}}
 const partnerJoins=partner?` LEFT JOIN (SELECT "Ref Partner" id,sum(CASE WHEN "Transaction Type"='Contribution' THEN "Amount"::numeric ELSE -"Amount"::numeric END) owned FROM public."Cash Pool Contributions" GROUP BY "Ref Partner") capital ON capital.id=p."Row ID" CROSS JOIN (SELECT coalesce(sum(CASE WHEN "Transaction Type"='Contribution' THEN "Amount"::numeric ELSE -"Amount"::numeric END),0) pool FROM public."Cash Pool Contributions") portfolio LEFT JOIN (SELECT "Ref Partner" id,coalesce(sum("Amount"::numeric) FILTER(WHERE "Status"='Completed'),0) completed,coalesce(sum("Amount"::numeric) FILTER(WHERE "Status"='Pending'),0) pending,coalesce(sum("Amount"::numeric) FILTER(WHERE "Status"<>'Cancelled'),0) created FROM public."Settlements" GROUP BY "Ref Partner") settlement ON settlement.id=p."Row ID"`:'';
 const listProjection=projection+(partner?`,(CASE WHEN portfolio.pool>0 THEN coalesce(capital.owned,0)/portfolio.pool ELSE 0 END)::text AS "currentPoolShare",public.partner_net_profit(p."Row ID")::text AS "netProfitEarned",coalesce(settlement.completed,0)::text AS "completedSettlement",coalesce(settlement.pending,0)::text AS "pendingSettlement",(public.partner_net_profit(p."Row ID")-coalesce(settlement.created,0))::text AS "netAvailableToSettle"`:'');
 const rows=(await client.query(`SELECT ${listProjection} FROM ${source}${partnerJoins} WHERE ($1='' OR strpos(lower(coalesce(${alias}."${name}",'')),lower($1))>0) AND ($2::text IS NULL OR (coalesce(${alias}."${name}",'') COLLATE "C",${alias}."Row ID" COLLATE "C")>($2::text COLLATE "C",$3::text COLLATE "C")) ORDER BY coalesce(${alias}."${name}",'') COLLATE "C",${alias}."Row ID" COLLATE "C" LIMIT $4`,[query,after?.label??null,after?.id??null,limit+1])).rows;
 const items=rows.slice(0,limit),last=items.at(-1);return {items,nextCursor:rows.length>limit?encode({v:1,kind,q:query,label:last.label??'',id:last.id}):null};
}
