import {validBorrowerId} from './borrowers.mjs';
/** Explicit current source projection; immutable operation outcomes are separate. */
export async function readPaymentRecord(client,id){
 if(!validBorrowerId(id))throw Error('invalid_request');
 const item=(await client.query(`SELECT p."Row ID" id,p."Ref Borrower" AS "borrowerId",b."Borrower Name" AS "borrowerName",b."Description" AS "borrowerDescription",p."Amount Received"::numeric::text AS "amountReceived",p."Posted Amount"::numeric::text AS "postedAmount",p."Payment Date"::text AS "paymentDate",p."Payment Method" AS "paymentMethod",p."Allocation Method" AS "allocationMethod",p."Ref Target Charge" AS "targetChargeId",p."Ref Target Loan" AS "targetLoanId",p."Selected Charge IDs" AS "selectedChargeIdsText",p."Ref Received By Cash Account" AS "cashAccountId",a."Account Label" AS "cashAccountLabel",p."Notes" notes,p."Uploaded Receipt" AS "receiptReference",p."Uploaded Receipt At"::text AS "receiptAt",(nullif(btrim(p."Receipt Image"),'') IS NOT NULL) AS "agentReceiptPresent",p."Receipt Received At"::text AS "agentReceiptAt",p."Status" status,p."Created By" AS "createdBy",p."Created At"::text AS "createdAt",p."Processed At"::text AS "processedAt" FROM public."Payments" p LEFT JOIN public."Borrowers" b ON b."Row ID"=p."Ref Borrower" LEFT JOIN public."Cash Accounts" a ON a."Row ID"=p."Ref Received By Cash Account" WHERE p."Row ID"=$1`,[id])).rows[0];
 if(!item)return null;
 item.version=(await client.query('SELECT public.pwa_payment_version_v2($1) version',[id])).rows[0].version;
 item.provenance=(await client.query('SELECT public.pwa_effective_payment_plan_v2($1) value',[id])).rows[0].value;
 const original=(await client.query(`SELECT outcome,"recorded_at" AS "recordedAt" FROM public.pwa_payment_commands WHERE (contract_version=1 AND outcome='posted' AND payment_id=$1) OR (contract_version=2 AND outcome='applied' AND result_json->>'paymentId'=$1 AND canonical_json::jsonb#>>'{command,operation}' IN('loan.create','loan.close','charge.create')) ORDER BY recorded_at,request_id LIMIT 2`,[id])).rows;
 if(original.length>1)throw Error('Invalid original receipt lineage');
 item.originalOutcomeStatus=original[0]?.outcome??null;item.originalRecordedAt=original[0]?.recordedAt?new Date(original[0].recordedAt).toISOString():null;
 item.allocations=(await client.query(`SELECT "Row ID" id,"Ref Charge" AS "chargeId","Charge Date Snapshot"::text AS "chargeDate","Allocation Order" AS "allocationOrder","Allocated Principal"::numeric::text principal,"Allocated Interest"::numeric::text interest,"Allocated Amount"::numeric::text amount FROM public."Payment Allocations" WHERE "Ref Payment"=$1 ORDER BY "Allocation Order","Row ID" COLLATE "C"`,[id])).rows;
 item.repayments=(await client.query(`SELECT "Row ID" id,"Ref Charges" AS "chargeId","Ref Payment Allocation" AS "allocationId","Payment Date"::text AS "paymentDate","Principal Paid"::numeric::text principal,"Interest Paid"::numeric::text interest FROM public."Repayments" WHERE "Ref Payment"=$1 ORDER BY "Payment Date","Row ID" COLLATE "C"`,[id])).rows;
 item.cashMovements=(await client.query(`SELECT c."Row ID" id,c."Movement Date"::text AS "movementDate",c."Movement Type" AS "movementType",c."Amount"::numeric::text amount,f."Account Label" AS "fromAccount",t."Account Label" AS "toAccount" FROM public."Cash Ledger" c LEFT JOIN public."Cash Accounts" f ON f."Row ID"=c."Ref From Cash Account" LEFT JOIN public."Cash Accounts" t ON t."Row ID"=c."Ref To Cash Account" WHERE c."Ref Payment"=$1 ORDER BY c."Movement Date",c."Row ID" COLLATE "C"`,[id])).rows;
 return item;
}
export async function readPaymentCorrectionPreview(client,id,{targetLoanId=null,paymentDate=null,proposedBorrowerId=null}={}){
 const item=await readPaymentRecord(client,id);if(!item)return null;
 const destination=proposedBorrowerId??item.borrowerId;
 if(!validBorrowerId(destination))throw Error('invalid_request');
 const borrower=(await client.query('SELECT "Borrower Name" name,"Description" description FROM public."Borrowers" WHERE "Row ID"=$1',[destination])).rows[0];if(!borrower)throw Error('invalid_request');
 const proposedBorrowerLabel=[borrower.name,borrower.description].filter(Boolean).join(' - ');
 const predecessor=(await client.query(`SELECT j.request_id::text id FROM public.pwa_payment_commands j WHERE j.contract_version=2 AND j.outcome='applied' AND j.canonical_json::jsonb#>>'{command,operation}'='payment.correct' AND j.canonical_json::jsonb#>>'{command,targetId}'=$1 AND NOT EXISTS(SELECT 1 FROM public.pwa_payment_commands child WHERE child.contract_version=2 AND child.outcome='applied' AND child.canonical_json::jsonb#>>'{command,operation}'='payment.correct' AND child.canonical_json::jsonb#>>'{command,targetId}'=$1 AND child.canonical_json::jsonb#>>'{command,predecessorRequestId}'=j.request_id::text)`,[id])).rows;
 if(predecessor.length>1)throw Error('Invalid payment revision lineage');
 const original=(await client.query(`SELECT request_id::text id FROM public.pwa_payment_commands WHERE contract_version=1 AND outcome='posted' AND payment_id=$1`,[id])).rows[0];
 const balances=(await client.query(`SELECT c."Row ID" AS "chargeId",c."Ref Loans" AS "loanId",c."Charge Date"::text AS "chargeDate",(c."Principal Due"::numeric-coalesce(paid.p,0))::text AS "principalRemaining",(c."Interest Due"::numeric-coalesce(paid.i,0))::text AS "interestRemaining" FROM public."Charges" c JOIN public."Loans" l ON l."Row ID"=c."Ref Loans" LEFT JOIN LATERAL(SELECT sum(r."Principal Paid"::numeric) p,sum(r."Interest Paid"::numeric) i FROM public."Repayments" r WHERE r."Ref Charges"=c."Row ID" AND r."Ref Payment" IS DISTINCT FROM $2) paid ON true WHERE l."Ref Borrowers"=$1 ORDER BY c."Charge Date",c."Row ID" COLLATE "C" LIMIT 10001`,[destination,id])).rows;
 if(balances.length>10000)throw Error('Correction scope exceeds technical limit');
 const loans=(await client.query(`SELECT "Row ID" id,"Loan Date"::text AS "loanDate","Loan Type" AS type,"Principal Amount"::numeric::text AS principal FROM public."Loans" WHERE "Ref Borrowers"=$1 ORDER BY "Loan Date" DESC,"Row ID" COLLATE "C" LIMIT 10001`,[destination])).rows;if(loans.length>10000)throw Error('Correction scope exceeds technical limit');
 let closePreparation=null;
 if(targetLoanId!==null||paymentDate!==null){
  if(!item.provenance||!validBorrowerId(targetLoanId)||typeof paymentDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(paymentDate)||!Number.isFinite(Date.parse(paymentDate+'T00:00:00Z'))||new Date(paymentDate+'T00:00:00Z').toISOString().slice(0,10)!==paymentDate)throw Error('invalid_request');
  const target=(await client.query('SELECT "Ref Borrowers" borrower,"Defaulted" defaulted,"Loan Status" status,"Ref Closing Payment" closing FROM public."Loans" WHERE "Row ID"=$1',[targetLoanId])).rows[0];
  const today=(await client.query("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date::text AS day")).rows[0].day;
  if(!target||target.borrower!==destination||target.defaulted||paymentDate!==today||(target.status!=='ยังไม่ปิดยอด'&&target.closing!==id))throw Error('invalid_request');
  const calculation=(await client.query('SELECT public.loan_close_calculation_v83($1,$2::date,$3) value',[targetLoanId,paymentDate,id])).rows[0].value;
  closePreparation={planHash:calculation.planHash,plan:{borrowerId:calculation.borrowerId,amountReceived:calculation.amount,allocations:calculation.allocations,allocationMethod:'Loan Close',targetChargeId:calculation.targetChargeId,targetLoanId,cashAccountId:item.cashAccountId,paymentDate,paymentMethod:item.paymentMethod}};
 }
 return {proposedBorrowerId:destination,proposedBorrowerLabel,sourceVersion:item.version,predecessorRequestId:predecessor[0]?.id??item.provenance?.originRequestId??original?.id??null,origin:item.provenance?'pwa-plan':'legacy-source',source:item,effectivePlan:item.provenance?.plan??null,balances,loans,closePreparation};
}
