import {normalizeSearchQuery} from '../api/search-query.mjs';
import {loanRankSql} from '../api/loan-read-contract.mjs';
const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url');
const label=`CASE WHEN b."Row ID" IS NULL THEN 'Unavailable' ELSE coalesce(b."Borrower Name",'') || ' - ' || coalesce(b."Description",'') END`;
const search=`($1='' OR strpos(lower(coalesce(b."Borrower Name",'')),lower($1))>0 OR strpos(lower(coalesce(b."Description",'')),lower($1))>0)`;
export async function readRecordList(client,kind,{q='',limit=25,cursor=null}={}){
 let query;try{query=normalizeSearchQuery(q)}catch{throw Error('invalid_request')}
 if(!['loans','payments'].includes(kind)||!Number.isInteger(limit)||limit<1||limit>100)throw Error('invalid_request');
 const loan=kind==='loans';
 const keys=loan?[['rank','ASC','number'],['borrowerDisplayName','ASC','string'],['borrowerNull','ASC','number'],['borrowerSort','ASC','string'],['dateNull','ASC','number'],['dateSort','DESC','string'],['id','ASC','string']]:[['borrowerDisplayName','ASC','string'],['borrowerNull','ASC','number'],['borrowerSort','ASC','string'],['monthNull','ASC','number'],['monthSort','DESC','string'],['dateNull','ASC','number'],['dateSort','DESC','string'],['createdNull','ASC','number'],['createdSort','DESC','string'],['id','ASC','string']];
 let after=null;if(cursor!==null){try{if(typeof cursor!=='string'||cursor.length>16384)throw Error();const v=JSON.parse(Buffer.from(cursor,'base64url').toString('utf8'));if(Object.keys(v).join(',')!=='v,kind,q,tuple'||v.v!==1||v.kind!==kind||v.q!==query||!Array.isArray(v.tuple)||v.tuple.length!==keys.length||encode(v)!==cursor||v.tuple.some((x,i)=>typeof x!==keys[i][2]||(typeof x==='number'&&(!Number.isInteger(x)||x<0||x>2))||(typeof x==='string'&&(x.length>4096||/[\u0000-\u001f]/.test(x)))))throw Error();after=v.tuple}catch{throw Error('invalid_request')}}
 const base=loan?`SELECT l."Row ID" id,l."Ref Borrowers" AS "borrowerId",${label} AS "borrowerDisplayName",${loanRankSql} rank,l."Loan Status" status,l."Defaulted" defaulted,l."Loan Date"::text AS "loanDate",l."Principal Amount"::numeric::text AS "principalAmount",l."Total Interest Received"::numeric::text AS "totalInterestReceived",l."Original Daily Interest Rate"::text AS "originalDailyInterestRate",CASE WHEN l."Principal Amount" IS NULL OR l."Total Interest Received" IS NULL THEN NULL WHEN l."Principal Amount"::numeric>0 THEN (l."Total Interest Received"::numeric/l."Principal Amount"::numeric)::numeric::text ELSE '0' END AS "principalRecoveredByInterestRatio",(l."Ref Borrowers" IS NULL)::int AS "borrowerNull",coalesce(l."Ref Borrowers",'') AS "borrowerSort",(l."Loan Date" IS NULL)::int AS "dateNull",coalesce(l."Loan Date"::text,'') AS "dateSort" FROM public."Loans" l LEFT JOIN public."Borrowers" b ON b."Row ID"=l."Ref Borrowers" WHERE ${search}`:
 `SELECT p."Row ID" id,p."Ref Borrower" AS "borrowerId",${label} AS "borrowerDisplayName",p."Payment Date"::text AS "paymentDate",p."Created At"::text AS "createdAt",p."Status" status,p."Amount Received"::numeric::text AS "amountReceived",p."Posted Amount"::numeric::text AS "postedAmount",a."Account Label" AS "accountLabel",nullif(btrim(p."Uploaded Receipt"),'') IS NOT NULL AS "manualReceiptPresent",nullif(btrim(p."Receipt Image"),'') IS NOT NULL AS "agentReceiptPresent",to_char(p."Payment Date",'YYYY-MM') AS month,sum(p."Amount Received") OVER(PARTITION BY p."Ref Borrower",to_char(p."Payment Date",'YYYY-MM'))::numeric::text AS "groupAmountReceived",(p."Ref Borrower" IS NULL)::int AS "borrowerNull",coalesce(p."Ref Borrower",'') AS "borrowerSort",(p."Payment Date" IS NULL)::int AS "monthNull",coalesce(to_char(p."Payment Date",'YYYY-MM'),'') AS "monthSort",(p."Payment Date" IS NULL)::int AS "dateNull",coalesce(p."Payment Date"::text,'') AS "dateSort",(p."Created At" IS NULL)::int AS "createdNull",coalesce(p."Created At"::text,'') AS "createdSort" FROM public."Payments" p LEFT JOIN public."Borrowers" b ON b."Row ID"=p."Ref Borrower" LEFT JOIN public."Cash Accounts" a ON a."Row ID"=p."Ref Received By Cash Account" WHERE ${search}`;
 const column=([key,,type])=>`"${key}"${type==='string'?' COLLATE "C"':''}`;
 const params=[query];let where='';if(after){params.push(...after);where='WHERE '+keys.map((key,i)=>'('+keys.slice(0,i).map((k,j)=>`${column(k)}=$${j+2}`).concat(`${column(key)}${key[1]==='ASC'?'>':'<'}$${i+2}`).join(' AND ')+')').join(' OR ')}params.push(limit+1);
 const rows=(await client.query(`WITH records AS (${base}) SELECT * FROM records ${where} ORDER BY ${keys.map(k=>column(k)+' '+k[1]).join(',')} LIMIT $${params.length}`,params)).rows;
 const visible=rows.slice(0,limit),last=visible.at(-1),nextCursor=rows.length>limit?encode({v:1,kind,q:query,tuple:keys.map(([key])=>last[key])}):null;
 const items=visible.map(row=>{const result={...row};for(const key of ['borrowerNull','borrowerSort','dateNull','dateSort','monthNull','monthSort','createdNull','createdSort'])delete result[key];return result});return {items,nextCursor};
}
