import {validBorrowerId} from './borrowers.mjs';
const day=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
const decimal=value=>value===null||typeof value==='string'&&/^-?\d+(?:\.\d+)?$/.test(value);
const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
export async function readStandaloneUpcoming(client,{borrowerId=null,dueDate=null,businessDate=null,limit=25,cursor=null}={}){
 if(!Number.isInteger(limit)||limit<1||limit>100||(borrowerId!==null&&(!validBorrowerId(borrowerId)||!day(dueDate)||!day(businessDate))))throw Error('invalid_request');
 const rows=(await client.query(`SELECT "As Of Date"::text AS "businessDate","From Date"::text AS "fromDate","Through Date"::text AS "throughDate","Calculated At" AS "asOf","Forecast Note" AS "forecastNote" FROM public.oltp_upcoming_charge_context_v1 LIMIT 2`)).rows;
 if(rows.length!==1||!day(rows[0].businessDate)||!day(rows[0].fromDate)||!day(rows[0].throughDate))throw Error('Upcoming source unavailable');const context={...rows[0],asOf:new Date(rows[0].asOf).toISOString()};
 const current=(await client.query("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date::text AS day")).rows[0].day;if(context.businessDate!==current||(businessDate!==null&&businessDate!==current))throw Error('business_date_changed');
 const kind=borrowerId?'detail':'summary';let after=null;
 if(cursor!==null){try{if(typeof cursor!=='string'||cursor.length>8192)throw Error();after=JSON.parse(Buffer.from(cursor,'base64url').toString());if(after.day!==current)throw Error('business_date_changed');if(Object.keys(after).sort().join(',')!=='borrowerId,date,day,id,kind,label,v'||after.v!==1||after.kind!==kind||after.borrowerId!==borrowerId||!validBorrowerId(after.id)||typeof after.label!=='string'||!day(after.date)||encode(after)!==cursor)throw Error();if(borrowerId&&after.date!==dueDate)throw Error()}catch(error){if(error.message==='business_date_changed')throw error;throw Error('invalid_request')}}
 if(borrowerId){
  if(dueDate<context.fromDate||dueDate>context.throughDate)throw Error('invalid_request');
  const summary=(await client.query(`SELECT s."Total Charge"::text amount,b."Borrower Name" name,b."Description" description FROM public.oltp_upcoming_charge_summary_v2 s JOIN public."Borrowers" b ON b."Row ID"=s."Ref Borrower" WHERE s."As Of Date"=$1::date AND s."Ref Borrower"=$2 AND s."Due Date"=$3::date`,[current,borrowerId,dueDate])).rows;
  if(summary.length!==1||!decimal(summary[0].amount))throw Error('invalid_request');
  const result=(await client.query(`SELECT e."Row ID" id,e."Ref Loan" AS "loanId",l."Loan Date"::text AS "loanDate",l."Loan Type" AS "loanType",l."Principal Amount"::numeric::text AS "loanPrincipal",e."Principal Remaining"::text AS principal,e."Interest Remaining"::text AS interest,e."Amount Remaining"::text AS amount,e."Basis" AS basis FROM public.oltp_upcoming_charge_events_v1 e JOIN public."Loans" l ON l."Row ID"=e."Ref Loan" AND l."Ref Borrowers"=$2 WHERE e."As Of Date"=$1::date AND e."Ref Borrower"=$2 AND e."Due Date"=$3::date AND ($4::text IS NULL OR e."Row ID" COLLATE "C">$4 COLLATE "C") ORDER BY e."Row ID" COLLATE "C" LIMIT $5`,[current,borrowerId,dueDate,after?.id??null,limit+1])).rows;
  if(result.some(row=>![row.principal,row.interest,row.amount].every(decimal)||!['Recorded','Recorded settlement','Recorded - review status','Projected'].includes(row.basis)))throw Error('Upcoming source unavailable');
  const items=result.slice(0,limit);return {...context,borrowerId,borrowerLabel:[summary[0].name,summary[0].description].filter(Boolean).join(' - '),dueDate,totalCharge:summary[0].amount,items,nextCursor:result.length>limit?encode({v:1,kind,day:current,borrowerId,date:dueDate,label:'',id:items.at(-1).id}):null};
 }
 const result=(await client.query(`WITH source AS(SELECT s."Row ID" id,s."Ref Borrower" AS "borrowerId",s."Due Date"::text AS "dueDate",s."Total Charge"::text AS "totalCharge",concat_ws(' - ',nullif(b."Borrower Name",''),nullif(b."Description",'')) AS label FROM public.oltp_upcoming_charge_summary_v2 s JOIN public."Borrowers" b ON b."Row ID"=s."Ref Borrower" WHERE s."As Of Date"=$1::date AND s."Due Date" BETWEEN $2::date AND $3::date) SELECT * FROM source WHERE ($4::text IS NULL OR ("dueDate",label COLLATE "C","borrowerId" COLLATE "C")>($4,$5 COLLATE "C",$6 COLLATE "C")) ORDER BY "dueDate",label COLLATE "C","borrowerId" COLLATE "C" LIMIT $7`,[current,context.fromDate,context.throughDate,after?.date??null,after?.label??null,after?.id??null,limit+1])).rows;
 if(result.some(row=>!decimal(row.totalCharge)||!day(row.dueDate)))throw Error('Upcoming source unavailable');const items=result.slice(0,limit),last=items.at(-1);const dateTotals=(await client.query(`SELECT "Due Date"::text AS date,CASE WHEN bool_or("Total Charge" IS NULL) THEN NULL ELSE sum("Total Charge"::numeric)::text END AS amount FROM public.oltp_upcoming_charge_summary_v2 WHERE "As Of Date"=$1::date AND "Due Date" BETWEEN $2::date AND $3::date GROUP BY "Due Date" ORDER BY "Due Date"`,[current,context.fromDate,context.throughDate])).rows;return {...context,dateTotals,items,nextCursor:result.length>limit?encode({v:1,kind,day:current,borrowerId:null,date:last.dueDate,label:last.label,id:last.borrowerId}):null};
}
