import {displayDate} from './display-date';import {wholeBaht} from './display-money';import {yesterdayBangkok,previousDay,statementTime} from './cash-view';
import {ExpenseRecords} from './ExpenseRecords';import React,{useEffect,useRef,useState} from 'react';import type {CommandAccess} from './SelectedCharges';import {beginRequest} from './request-activity';import {useContextRefresh} from './context-refresh';import {CompactPager} from './CompactPager';import {PaymentRecord} from './PaymentRecord';import {LoanRecord} from './LoanRecord';
export function CashWorkspace({access,thai,savedDraft}:{access:CommandAccess;thai:boolean;savedDraft?:any;onLanguage:(thai:boolean)=>void}){
 const t=(en:string,th:string)=>thai?th:en,[overview,setOverview]=useState<any>(null),[accounts,setAccounts]=useState<any[]>([]),[account,setAccount]=useState<string|null>(savedDraft?.account??null),[date,setDate]=useState(savedDraft?.date??yesterdayBangkok()),[statement,setStatement]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState<{kind:string;id:string}|null>(null),[page,setPage]=useState(0),generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]),flight=useRef<AbortController|null>(null);
 function cancel(){generation.current++;flight.current?.abort();flight.current=null}
 async function request(path:string,signal:AbortSignal){const response=await fetch(access.origin+path,{headers:{Authorization:'Bearer '+await access.token()},signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();return response.json()}
 async function run(job:(signal:AbortSignal)=>Promise<any>,apply:(data:any)=>void){cancel();const current=generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);flight.current=controller;setBusy(true);setError('');try{const data=await Promise.race([job(controller.signal),new Promise<never>((_,reject)=>controller.signal.addEventListener('abort',()=>reject(Error('Cancelled')),{once:true}))]);if(current===generation.current)apply(data)}catch{if(current===generation.current)setError(t('Cash records unavailable for this account and date.','ไม่พบข้อมูลเงินสดสำหรับบัญชีและวันที่นี้'))}finally{clearTimeout(timer);done();if(current===generation.current){setBusy(false);flight.current=null}}}
 function loadStatement(nextAccount:string|null,nextDate:string,cursor?:string,index=0){setAccount(nextAccount);setDate(nextDate);setStatement(null);if(!nextAccount||!/^\d{4}-\d{2}-\d{2}$/.test(nextDate)||access.offlineOnly||!navigator.onLine){cancel();setBusy(false);return;}void run(signal=>request('/api/cash-statements?accountId='+encodeURIComponent(nextAccount)+'&date='+nextDate+(cursor?'&cursor='+encodeURIComponent(cursor):''),signal),data=>{if(index===0)cursors.current=[undefined];cursors.current[index]=cursor;setPage(index);setStatement(data)})}
 function load(){void run(signal=>Promise.all([request('/api/cash-overview',signal),request('/api/preferences',signal)]),([cash,prefs])=>{setOverview(cash);setAccounts(prefs.accounts);const chosen=savedDraft?.account??prefs.item.statementAccountId??null,day=savedDraft?.date??(cash.businessDate?previousDay(cash.businessDate):yesterdayBangkok());setAccount(chosen);setDate(day);if(chosen)loadStatement(chosen,day)})}
 useEffect(()=>{if(!access.offlineOnly&&navigator.onLine)load();return cancel},[]);useContextRefresh(!detail,t('Refresh cash records','รีเฟรชข้อมูลเงินสด'),()=>{if(account)loadStatement(account,date);else load()});
 if(detail?.kind==='payment')return <PaymentRecord access={access} id={detail.id} thai={thai} onBack={()=>setDetail(null)}/>;
 if(detail?.kind==='expense')return <ExpenseRecords access={access} thai={thai} initialId={detail.id} readOrigin={import.meta.env.VITE_API_ORIGIN} onBack={()=>setDetail(null)}/>;
 if(detail?.kind==='loan')return <LoanRecord access={access} id={detail.id} thai={thai} onBack={()=>setDetail(null)}/>;
 const fields=[['operatingIncomeMtd','Operating Income MTD','รายรับดำเนินงานเดือนนี้'],['expensesMtd','Expenses MTD','ค่าใช้จ่ายเดือนนี้'],['netProfitMtd','Net Profit MTD','กำไรสุทธิเดือนนี้'],['tommyWithdrawnMtd','Tommy Withdrawn MTD','ทอมมี่ถอนเดือนนี้'],['lisaWithdrawnMtd','Lisa Withdrawn MTD','ลิซ่าถอนเดือนนี้'],['unsettledProfitMtd','Unsettled Profit MTD','กำไรที่ยังไม่จัดสรรเดือนนี้'],['cashPoolRemaining','Cash Pool Remaining','เงินกองกลางคงเหลือ']];
 return <section className="borrower-record cash-workspace" aria-busy={busy}>{error&&<p role="alert">{error}<button onClick={()=>account?loadStatement(account,date):load()}>{t('Retry','ลองอีกครั้ง')}</button></p>}{overview&&<section className="cash-dashboard-card"><h2>{t('Cash Dashboard','ภาพรวมเงินสด')}</h2><dl>{fields.map(([key,en,th])=><React.Fragment key={key}><dt>{t(en,th)}</dt><dd>{wholeBaht(overview.dashboard[key])}</dd></React.Fragment>)}</dl></section>}
 <div className="cash-report-layout"><div className="cash-report-controls"><section className="cash-statement-paper"><h3>{t('Cash Statement','รายการบัญชีเงินสด')}</h3><label>{t('Account','บัญชี')}<select value={account??''} disabled={!accounts.length||access.offlineOnly} onChange={event=>loadStatement(event.target.value||null,date)}><option value="">—</option>{accounts.map(row=><option key={row.id} value={row.id}>{row.holderLabel} · {row.label}</option>)}</select></label><label>{t('Statement Date','วันที่รายการ')}<input type="date" value={date} disabled={access.offlineOnly} onChange={event=>loadStatement(account,event.target.value)}/></label></section>
 <section className="cash-statement-paper"><h3>{t('Daily Summary','สรุปประจำวัน')}</h3>{statement?<dl>{[['openingBalance','Opening Balance','ยอดยกมา'],['moneyIn','Money In','เงินเข้า'],['moneyOut','Money Out','เงินออก'],['netMovement','Net Movement','การเปลี่ยนแปลงสุทธิ'],['closingBalance','Closing Balance','ยอดปิด'],['transactionCount','Transaction Count','จำนวนรายการ']].map(([key,en,th])=><React.Fragment key={key}><dt>{t(en,th)}</dt><dd className={statement.summary[key]!=null&&Number(statement.summary[key])===0?'zero-currency':key==='moneyIn'?'money-in':key==='moneyOut'?'money-out':''}>{key==='transactionCount'?statement.summary[key]:wholeBaht(statement.summary[key])}</dd></React.Fragment>)}</dl>:<p>{t('Select an account and date.','เลือกบัญชีและวันที่')}</p>}</section></div>
 <section className="cash-statement-paper cash-transactions"><h3>{t('Transactions','รายการเคลื่อนไหว')} · {displayDate(date)}</h3><p>{accounts.find(row=>row.id===account)?.label??'—'}</p>{statement&&<><div className="cash-table-scroll"><table><thead><tr>{[t('Time','เวลา'),t('Transaction','รายการ'),t('From / To','จาก / ถึง'),t('Amount','จำนวนเงิน'),t('Balance','ยอดคงเหลือ')].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{statement.items.map((row:any)=><tr key={row.id}><td>{statementTime(row.timestamp)}</td><td>{row.paymentId||row.expenseId||row.loanId?<button className="text-action" onClick={()=>setDetail({kind:row.paymentId?'payment':row.expenseId?'expense':'loan',id:row.paymentId??row.expenseId??row.loanId})}>{row.transactionType}</button>:row.transactionType}{row.notes&&<small>{row.notes}</small>}</td><td>{row.borrowerLabel??row.otherAccountLabel??row.partnerLabel??row.counterpartyText??'—'}</td><td className={Number(row.amount)>0?'money-in':Number(row.amount)<0?'money-out':''}>{wholeBaht(row.amount)}</td><td>{wholeBaht(row.balanceAfter)}</td></tr>)}</tbody></table></div><CompactPager busy={busy} previous={page>0?()=>loadStatement(account,date,cursors.current[page-1],page-1):undefined} next={statement.nextCursor?()=>loadStatement(account,date,statement.nextCursor,page+1):undefined} previousLabel={t('Previous statement page','รายการบัญชีหน้าก่อน')} nextLabel={t('Next statement page','รายการบัญชีหน้าถัดไป')}/></>}</section></div></section>;
}
