import {displayDate,displayTimestamp,displayValue} from './display-date';
import {useDomainDraft} from './domain-draft';
import {ExpenseRecords} from './ExpenseRecords';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {useContextRefresh} from './context-refresh';
import {CompactPager} from './CompactPager';
import {OperationConfirm} from './OperationConfirm';
import {PaymentRecord} from './PaymentRecord';
import {LoanRecord} from './LoanRecord';
export function CashWorkspace({access,thai,savedDraft,onLanguage}:{access:CommandAccess;thai:boolean;savedDraft?:any;onLanguage:(thai:boolean)=>void}){
 const t=(en:string,th:string)=>thai?th:en,[overview,setOverview]=useState<any>(null),[preferences,setPreferences]=useState<any>(savedDraft?.preferences??null),[account,setAccount]=useState<string|null>(savedDraft?.account??null),[date,setDate]=useState<string|null>(savedDraft?.date??null),[language,setLanguage]=useState(savedDraft?.language??(thai?'ไทย':'English')),[statement,setStatement]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[command,setCommand]=useState<any>(null),[detail,setDetail]=useState<{kind:string;id:string}|null>(null),[page,setPage]=useState(0),generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]),restored=useRef(!!savedDraft);
 const draft=useDomainDraft({repository:access.offline,id:'own',domain:'preference',label:t('Preferences','การตั้งค่า'),value:{preferences,account,date,language},enabled:!!preferences&&!command&&!busy,restore:value=>{if(value?.preferences?.item){restored.current=true;setPreferences(value.preferences);setAccount(value.account);setDate(value.date);setLanguage(value.language)}}});
 async function savePreferences(){if(busy||access.offlineOnly||!navigator.onLine)return;setBusy(true);try{const latest=await request('/api/preferences');if(latest.item.version!==preferences.item.version){setError(t('Preferences changed. Refresh current values before saving this draft.','การตั้งค่าเปลี่ยนแล้ว โปรดรีเฟรชค่าปัจจุบันก่อนบันทึกร่าง'));return;}await draft.freeze();setCommand({requestId:crypto.randomUUID(),operation:'preference.update',targetId:preferences.item.id,expectedVersion:preferences.item.version,predecessorRequestId:null,receiptId:null,inputs:{language,statementAccountId:account,statementDate:date}})}catch{setError(t('Current preferences unavailable.','ไม่สามารถโหลดการตั้งค่าปัจจุบัน'))}finally{setBusy(false)}}
 async function request(path:string){const done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(access.origin+path,{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();return await response.json()}finally{clearTimeout(timer);done()}}
 async function load(){const current=++generation.current;setBusy(true);setError('');try{const [cash,prefs]=await Promise.all([request('/api/cash-overview'),request('/api/preferences')]);if(current!==generation.current)return;setOverview(cash);if(restored.current)return;setPreferences(prefs);setAccount(prefs.item.statementAccountId);setDate(prefs.item.statementDate);setLanguage(prefs.item.language??(thai?'ไทย':'English'));setStatement(null);if(prefs.item.statementAccountId&&prefs.dates.includes(prefs.item.statementDate))await loadStatement(prefs.item.statementAccountId,prefs.item.statementDate)}catch{if(current===generation.current)setError(t('Cash records unavailable.','ไม่สามารถโหลดข้อมูลเงินสด'))}finally{if(current===generation.current)setBusy(false)}}
 async function loadStatement(nextAccount:string|null,nextDate:string|null,cursor?:string,index=0){const current=++generation.current;setAccount(nextAccount);setDate(nextDate);setError('');if(access.offlineOnly||!navigator.onLine||!nextAccount||!nextDate){setStatement(null);setBusy(false);return;}setBusy(true);try{const data=await request('/api/cash-statements?accountId='+encodeURIComponent(nextAccount)+'&date='+nextDate+(cursor?'&cursor='+encodeURIComponent(cursor):''));if(current!==generation.current)return;if(index===0)cursors.current=[undefined];cursors.current[index]=cursor;setPage(index);setStatement(data)}catch{if(current===generation.current){setStatement(null);setError(t('Statement unavailable. Select a current statement date.','ไม่สามารถโหลดรายการบัญชี เลือกวันที่รายการปัจจุบัน'))}}finally{if(current===generation.current)setBusy(false)}}
 useEffect(()=>{if(!access.offlineOnly&&navigator.onLine)void load();return()=>{generation.current++}},[]);useContextRefresh(!command&&!detail,t('Refresh cash records','รีเฟรชข้อมูลเงินสด'),()=>{if(statement)void loadStatement(account,date);else void load()});
 const money=(value:any)=>value===null||value===undefined?t('Unavailable','ไม่มีข้อมูล'):'฿'+value;
 if(command)return <OperationConfirm access={access} command={command} domain="preference" draftKey={draft.key} label={t('Save preferences','บันทึกการตั้งค่า')} thai={thai} onBack={()=>{setCommand(null);draft.resume()}} onApplied={()=>{restored.current=false;setCommand(null);onLanguage(language==='ไทย');void load()}}><p>{language} · {preferences.accounts.find((a:any)=>a.id===account)?.label??'—'} · {displayDate(date)}</p></OperationConfirm>;
 if(detail?.kind==='payment')return <PaymentRecord access={access} id={detail.id} thai={thai} onBack={()=>setDetail(null)}/>;
 if(detail?.kind==='expense')return <ExpenseRecords access={access} thai={thai} initialId={detail.id} readOrigin={import.meta.env.VITE_API_ORIGIN} onBack={()=>setDetail(null)}/>;
 if(detail?.kind==='loan')return <LoanRecord access={access} id={detail.id} thai={thai} onBack={()=>setDetail(null)}/>;
 const dashboardFields=[['operatingIncomeMtd','Operating Income MTD','รายรับดำเนินงานเดือนนี้'],['expensesMtd','Expenses MTD','ค่าใช้จ่ายเดือนนี้'],['netProfitMtd','Net Profit MTD','กำไรสุทธิเดือนนี้'],['tommyWithdrawnMtd','Tommy Withdrawn MTD','ทอมมี่ถอนเดือนนี้'],['lisaWithdrawnMtd','Lisa Withdrawn MTD','ลิซ่าถอนเดือนนี้'],['unsettledProfitMtd','Unsettled Profit MTD','กำไรที่ยังไม่จัดสรรเดือนนี้'],['cashPoolRemaining','Cash Pool Remaining','เงินกองกลางคงเหลือ']];
 return <section className="borrower-record cash-workspace" aria-busy={busy}>{error&&<p role="alert">{error}<button className="text-action" onClick={()=>void load()}>{t('Retry','ลองอีกครั้ง')}</button></p>}{overview&&<><h2>{t('Cash Dashboard','ภาพรวมเงินสด')}</h2><dl>{dashboardFields.map(([key,en,th])=><React.Fragment key={key}><dt>{t(en,th)}</dt><dd>{money(overview.dashboard[key])}</dd></React.Fragment>)}</dl></>}
 {draft.error&&<p role="alert">{t('Draft not saved. Device storage is unavailable or full.','บันทึกร่างไม่ได้ พื้นที่จัดเก็บใช้ไม่ได้หรือเต็ม')}</p>}{preferences&&<><h3>{t('Cash Statement','รายการบัญชีเงินสด')}</h3><label>{t('Account','บัญชี')}<select value={account??''} disabled={busy} onChange={e=>void loadStatement(e.target.value||null,date)}><option value="">—</option>{preferences.accounts.map((a:any)=><option key={a.id} value={a.id}>{a.holderLabel} · {a.label}</option>)}</select></label><label>{t('Statement Date','วันที่รายการ')}<select value={date??''} disabled={busy} onChange={e=>void loadStatement(account,e.target.value||null)}><option value="">—</option>{date&&!preferences.dates.includes(date)&&<option value={date}>{displayDate(date)}</option>}{preferences.dates.map((day:string)=><option key={day} value={day}>{displayDate(day)}</option>)}</select></label><label>{t('Language Preference','ภาษาที่ต้องการ')}<select value={language} disabled={busy} onChange={e=>setLanguage(e.target.value)}><option>English</option><option>ไทย</option></select></label><button className="text-action" disabled={busy||access.offlineOnly||!navigator.onLine} onClick={()=>void savePreferences()}>{t('Save preferences','บันทึกการตั้งค่า')}</button><details><summary>{t('Draft actions','จัดการร่าง')}</summary><button disabled={busy} onClick={()=>void draft.discard().then(()=>{restored.current=false;void load()}).catch(()=>setError(t('Draft could not be cleared.','ล้างร่างไม่ได้')))}>{t('Clear draft','ล้างร่าง')}</button></details></>}
 {statement&&<section className="cash-statement-paper"><h3>{t('Cash Statement','รายการบัญชีเงินสด')} · {displayDate(date)}</h3><p>{preferences?.accounts.find((row:any)=>row.id===account)?.label??'—'}</p><dl>{[['openingBalance','Opening Balance','ยอดยกมา'],['moneyIn','Money In','เงินเข้า'],['moneyOut','Money Out','เงินออก'],['netMovement','Net Movement','การเปลี่ยนแปลงสุทธิ'],['closingBalance','Closing Balance','ยอดปิด'],['transactionCount','Transaction Count','จำนวนรายการ']].map(([key,en,th])=><React.Fragment key={key}><dt>{t(en,th)}</dt><dd>{key==='transactionCount'?statement.summary[key]:money(statement.summary[key])}</dd></React.Fragment>)}</dl>{statement.items.map((row:any)=><article className="collection-charge" key={row.id}><strong>{displayValue(row.date)} · {row.transactionType} · {money(row.amount)}</strong><p>{row.borrowerLabel??row.otherAccountLabel??row.partnerLabel??row.counterpartyText}</p><p>{t('Balance after','ยอดหลังรายการ')}: {money(row.balanceAfter)}</p><pre>{row.notes}</pre>{row.paymentId?<button className="text-action" onClick={()=>setDetail({kind:'payment',id:row.paymentId})}>{t('Payment details','รายละเอียดรับชำระ')}</button>:row.expenseId?<button className="text-action" onClick={()=>setDetail({kind:'expense',id:row.expenseId})}>{t('Expense details','รายละเอียดค่าใช้จ่าย')}</button>:row.loanId?<button className="text-action" onClick={()=>setDetail({kind:'loan',id:row.loanId})}>{t('Loan details','รายละเอียดสินเชื่อ')}</button>:null}</article>)}<CompactPager busy={busy} previous={page>0?()=>void loadStatement(account,date,cursors.current[page-1],page-1):undefined} next={statement.nextCursor?()=>void loadStatement(account,date,statement.nextCursor,page+1):undefined} previousLabel={t('Previous statement page','รายการบัญชีหน้าก่อน')} nextLabel={t('Next statement page','รายการบัญชีหน้าถัดไป')}/></section>}
 </section>;
}
