import {RecordAction} from './RecordAction';
import {HeaderBack} from './HeaderBack';
import {displayDate,displayTimestamp,displayValue} from './display-date';
import {PaymentRecord} from './PaymentRecord';import {CompactPager} from './CompactPager';
import React,{useEffect,useRef,useState} from 'react';import type {CommandAccess} from './SelectedCharges';import {beginRequest} from './request-activity';import {useContextRefresh} from './context-refresh';import {useViewedSnapshot} from './useViewedSnapshot';import {ChargeForm} from './ChargeForm';import {OperationConfirm} from './OperationConfirm';
export function ChargeRecord({access,id,thai,onBack,onChanged,backLabel}:{access:CommandAccess;id:string;thai:boolean;onBack:()=>void;onChanged?:()=>void;backLabel?:string}){
 const t=(en:string,th:string)=>thai?th:en,[item,setItem]=useState<any>(null),[error,setError]=useState(false),[editing,setEditing]=useState(false),[command,setCommand]=useState<any>(null),[payment,setPayment]=useState<string|null>(null),[relatedPage,setRelatedPage]=useState({repayments:0,allocations:0}),generation=useRef(0);useViewedSnapshot(access,'charge',item);
 async function load(){const current=++generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);setError(false);try{const response=await fetch(access.origin+'/api/charge-records/'+encodeURIComponent(id),{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const data=await response.json();if(current===generation.current)setItem(data.item)}catch{if(current===generation.current)setError(true)}finally{clearTimeout(timer);done()}}
 useEffect(()=>{void load();return()=>{generation.current++}},[id]);useContextRefresh(!editing&&!command&&!payment,t('Refresh charge details','โหลดรายละเอียดเรียกเก็บใหม่'),()=>void load());
 if(payment)return <PaymentRecord access={access} id={payment} thai={thai} onBack={()=>setPayment(null)}/>;
 if(editing)return <ChargeForm access={access} loanId={item.loanId} label={item.borrowerLabel??item.borrowerName??''} source={item} thai={thai} onBack={()=>setEditing(false)} onApplied={()=>{setEditing(false);void load();onChanged?.()}}/>;
 if(command)return <OperationConfirm access={access} domain="charge" command={command} label={t('Delete charge','ลบรายการเรียกเก็บ')} thai={thai} onBack={()=>setCommand(null)} onApplied={()=>{onChanged?.();onBack()}}><p>{displayValue(item.chargeDate)} · ฿{item.principalDue} / ฿{item.interestDue}</p></OperationConfirm>;
 return <section className="borrower-record"><div className="related-loans-heading"><HeaderBack className="icon-action" aria-label={backLabel??t('Back to loan details','กลับรายละเอียดสินเชื่อ')} onClick={onBack}>←</HeaderBack><h2>{item?.borrowerLabel??item?.borrowerName} · {displayValue(item?.chargeDate)}</h2>{item&&<RecordAction icon="✎" className="icon-action" aria-label={t('Edit charge','แก้ไขรายการเรียกเก็บ')} onClick={()=>setEditing(true)} disabled={access.offlineOnly}>✎</RecordAction>}{item&&<div className="borrower-direct-actions"><RecordAction icon="×" disabled={access.offlineOnly||!navigator.onLine} onClick={()=>setCommand({requestId:crypto.randomUUID(),operation:'charge.delete',targetId:id,expectedVersion:item.version,predecessorRequestId:null,receiptId:null,inputs:{}})}>{t('Delete charge','ลบรายการเรียกเก็บ')}</RecordAction></div>}</div>{error&&<p role="alert">{t('Charge unavailable.','ไม่สามารถโหลดรายการเรียกเก็บ')}<button onClick={()=>void load()}>{t('Retry charge','ลองอีกครั้ง')}</button></p>}{item&&<><dl>{[['chargeDate','Charge Date','วันที่เรียกเก็บ'],['principalDue','Principal Due','เงินต้นเรียกเก็บ'],['interestDue','Interest Due','ดอกเบี้ยเรียกเก็บ'],['totalPaid','Total Paid','ยอดชำระแล้ว'],['amountRemaining','Amount Remaining','ยอดคงเหลือ'],['notes','Notes','หมายเหตุ']].map(([key,en,th])=><div key={key}><dt>{t(en,th)}</dt><dd className="borrower-field-value">{/(Date|At)$/.test(key)?displayValue(item[key]):item[key]??'—'}</dd></div>)}</dl>{(['repayments','allocations'] as const).map(kind=><section key={kind}><h3>{kind==='repayments'?t('Related Repayments','รายการชำระที่เกี่ยวข้อง'):t('Payment Allocations','รายการจัดสรร')}</h3>{(item[kind]??[]).slice(relatedPage[kind]*25,relatedPage[kind]*25+25).map((row:any)=><button key={row.id} className="borrower-card" disabled={!row.paymentId} onClick={()=>setPayment(row.paymentId)}><span>{displayValue(row.paymentDate??row.chargeDate)}</span><strong>{t('Principal','เงินต้น')} ฿{row.principal} · {t('Interest','ดอกเบี้ย')} ฿{row.interest}</strong></button>)}<CompactPager previous={relatedPage[kind]>0?()=>setRelatedPage(old=>({...old,[kind]:old[kind]-1})):undefined} next={(relatedPage[kind]+1)*25<(item[kind]?.length??0)?()=>setRelatedPage(old=>({...old,[kind]:old[kind]+1})):undefined} previousLabel={t('Previous related page','รายการที่เกี่ยวข้องหน้าก่อน')} nextLabel={t('Next related page','รายการที่เกี่ยวข้องหน้าถัดไป')}/></section>)}</>}</section>;
}
