import {useDomainDraft} from './domain-draft';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {OperationConfirm} from './OperationConfirm';
export function ChargeForm({access,loanId,label,source,savedDraft,thai,onBack,onApplied}:{access:CommandAccess;loanId:string;label:string;source?:any;savedDraft?:any;thai:boolean;onBack:()=>void;onApplied:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,id=useRef(source?.id??savedDraft?.id??crypto.randomUUID()),generation=useRef(0);
 const [date,setDate]=useState(savedDraft?.date??source?.chargeDate??''),[principal,setPrincipal]=useState(savedDraft?.principal??source?.principalDue??''),[interest,setInterest]=useState(savedDraft?.interest??source?.interestDue??''),[notes,setNotes]=useState(savedDraft?.notes??source?.notes??''),[error,setError]=useState(''),[command,setCommand]=useState<any>(null),[busy,setBusy]=useState(false);
 const draft=useDomainDraft({repository:access.offline,id:id.current,domain:'charge',label,value:{id:id.current,loanId,label,source:source??null,date,principal,interest,notes},enabled:!busy&&!command,restore:value=>{if(value?.id===id.current){setDate(value.date);setPrincipal(value.principal);setInterest(value.interest);setNotes(value.notes)}}});
 useEffect(()=>{if(source||access.offlineOnly||!navigator.onLine)return;const current=++generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);void(async()=>{try{const response=await fetch(access.origin+'/api/loan-options',{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const data=await response.json();if(current===generation.current)setDate((value:string)=>value||data.businessDate);}catch{if(current===generation.current)setError(t('Current date unavailable. Return and try again.','ไม่สามารถโหลดวันที่ปัจจุบัน กลับแล้วลองอีกครั้ง'));}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}})();return()=>{generation.current++;controller.abort()}},[]);
 async function review(){if(busy)return;setError('');if(!/^(0|[1-9][0-9]*)(\.[0-9]{1,2})?$/.test(principal)||! /^-?(0|[1-9][0-9]*)(\.[0-9]{1,2})?$/.test(interest)){setError(t('Enter exact amounts with up to two decimal places.','ระบุยอดตรงตามจริง ทศนิยมไม่เกินสองตำแหน่ง'));return;}setBusy(true);await draft.freeze();setBusy(false);setCommand({requestId:crypto.randomUUID(),operation:source?'charge.update':'charge.create',targetId:id.current,expectedVersion:source?.version??null,predecessorRequestId:null,receiptId:null,inputs:{loanId,chargeDate:date,principalDue:principal,interestDue:interest,notes:notes||null}})}
 if(command)return <OperationConfirm key={command.requestId} access={access} command={command} domain="charge" draftKey={draft.key} label={source?t('Edit charge','แก้ไขรายการเรียกเก็บ'):t('New charge','เพิ่มรายการเรียกเก็บ')} thai={thai} onBack={()=>{setCommand(null);draft.resume()}} onApplied={onApplied}><dl><div><dt>{label}</dt><dd>{date}</dd></div><div><dt>{t('Principal Due','เงินต้นเรียกเก็บ')}</dt><dd>฿{principal}</dd></div><div><dt>{t('Interest Due','ดอกเบี้ยเรียกเก็บ')}</dt><dd>฿{interest}</dd></div><div><dt>{t('Notes','หมายเหตุ')}</dt><dd className="borrower-field-value">{notes||'—'}</dd></div></dl></OperationConfirm>;
 return <section className="borrower-record" aria-busy={busy}><div className="related-loans-heading"><button className="icon-action" aria-label={t('Back to loan details','กลับรายละเอียดสินเชื่อ')} onClick={onBack}>←</button><h2>{source?t('Edit charge','แก้ไขรายการเรียกเก็บ'):t('New charge','เพิ่มรายการเรียกเก็บ')} · {label}</h2></div>{error&&<p role="alert">{error}</p>}{draft.error&&<p role="alert">{t('Draft not saved. Device storage is unavailable or full.','บันทึกร่างไม่ได้ พื้นที่จัดเก็บใช้ไม่ได้หรือเต็ม')}</p>}<form onSubmit={event=>{event.preventDefault();void review()}}><label>{t('Charge Date','วันที่เรียกเก็บ')}<input required type="date" value={date} disabled={busy} onChange={event=>setDate(event.target.value)}/></label><label>{t('Principal Due','เงินต้นเรียกเก็บ')}<input required type="number" step="0.01" min="0" value={principal} disabled={busy} onChange={event=>setPrincipal(event.target.value)}/></label><label>{t('Interest Due','ดอกเบี้ยเรียกเก็บ')}<input required type="number" step="0.01" value={interest} disabled={busy} onChange={event=>setInterest(event.target.value)}/></label><label>{t('Notes','หมายเหตุ')}<textarea value={notes} disabled={busy} onChange={event=>setNotes(event.target.value)}/></label><button disabled={busy||access.offlineOnly||!navigator.onLine}>{t('Review change','ตรวจสอบการเปลี่ยนแปลง')}</button></form></section>;
}
