import {displayDate,displayTimestamp,displayValue} from './display-date';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {useContextRefresh} from './context-refresh';
import {CompactPager} from './CompactPager';
function ReceiptThumbnail({access,row,thai}:{access:CommandAccess;row:any;thai:boolean}){
 const [url,setUrl]=useState<string|null>(null),[unavailable,setUnavailable]=useState(false);
 useEffect(()=>{let active=true,created:string|null=null;setUrl(null);setUnavailable(false);if(!row.manualReceiptPresent&&!row.agentReceiptPresent)return;const done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);void(async()=>{try{const response=await fetch(access.origin+'/api/payment-records/'+encodeURIComponent(row.id)+'/receipt',{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const blob=await response.blob();if(active){created=URL.createObjectURL(blob);setUrl(created)}}catch{if(active)setUnavailable(true)}finally{clearTimeout(timer);done()}})();return()=>{active=false;controller.abort();if(created)URL.revokeObjectURL(created)}},[row.id,row.receiptAt,row.manualReceiptPresent,row.agentReceiptPresent]);
 return <span style={{display:'grid',placeItems:'center',width:'100%',height:128,background:'#f4f4f4',overflow:'hidden'}}>{url?<img src={url} alt={thai?'หลักฐานรับชำระ':'Receipt evidence'} style={{width:'100%',height:128,objectFit:'contain'}}/>:unavailable?(thai?'หลักฐานใช้ไม่ได้':'Receipt unavailable'):!row.manualReceiptPresent&&!row.agentReceiptPresent?(thai?'ไม่มีรูปหลักฐาน':'No receipt image'):null}</span>;
}
export function CollectionReceipts({access,borrowerId,businessDate,chargeIds,thai,onOpen}:{access:CommandAccess;borrowerId:string;businessDate:string;chargeIds:string[];thai:boolean;onOpen:(id:string)=>void}){
 const t=(en:string,th:string)=>thai?th:en,[data,setData]=useState<any>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[page,setPage]=useState(0),generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]),scope=JSON.stringify([borrowerId,businessDate,chargeIds]);
 async function load(cursor?:string,index=0){const current=++generation.current;if(!chargeIds.length){setData(null);return;}const done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const params=new URLSearchParams({businessDate,chargeIds:JSON.stringify(chargeIds),limit:'25'});if(cursor)params.set('cursor',cursor);let value:any;const seen=new Set<string>();while(true){const response=await fetch(access.origin+'/api/borrowers/'+encodeURIComponent(borrowerId)+'/collection-receipts?'+params,{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();value=await response.json();if(value.items.some((row:any)=>row.manualReceiptPresent||row.agentReceiptPresent)||!value.nextCursor)break;if(seen.has(value.nextCursor))throw Error();seen.add(value.nextCursor);cursor=value.nextCursor;params.set('cursor',cursor!);}if(current!==generation.current)return;if(index>0&&!value.items.some((row:any)=>row.manualReceiptPresent||row.agentReceiptPresent)){setData((previous:any)=>previous?{...previous,nextCursor:null}:value);return;}if(index===0)cursors.current=[undefined];cursors.current[index]=cursor;setPage(index);setData(value)}catch{if(current===generation.current){setData(null);setError(true)}}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}}
 useEffect(()=>{setData(null);void load();return()=>{generation.current++}},[scope]);useContextRefresh(chargeIds.length>0,t('Refresh collection receipts','โหลดหลักฐานงานติดตามใหม่'),()=>void load());
 const receipts=data?.items?.filter((row:any)=>row.manualReceiptPresent||row.agentReceiptPresent)??[];
 if(!error&&!receipts.length)return null;
 return <section aria-label={t('Collection receipts','หลักฐานรับชำระงานติดตาม')}><h3>{t('Receipts','หลักฐานรับชำระ')}</h3>{error&&<p role="alert">{t('Receipts unavailable.','ไม่สามารถโหลดหลักฐาน')}<button onClick={()=>void load(cursors.current[page],page)}>{t('Retry receipts','ลองโหลดหลักฐานอีกครั้ง')}</button></p>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,180px),1fr))',gap:8}}>{receipts.map((row:any)=><button className="borrower-card" key={row.id} disabled={busy} onClick={()=>onOpen(row.id)} style={{minWidth:0,textAlign:'left'}}><ReceiptThumbnail access={access} row={row} thai={thai}/><span>{displayValue(row.paymentDate??'—')}</span><strong>฿{row.amount}</strong>{row.receiptAt&&<small>{displayTimestamp(row.receiptAt)}</small>}</button>)}</div><CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={data?.nextCursor?()=>void load(data.nextCursor,page+1):undefined} previousLabel={t('Previous receipts page','หลักฐานหน้าก่อน')} nextLabel={t('Next receipts page','หลักฐานหน้าถัดไป')}/></section>;
}
