import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {useContextRefresh} from './context-refresh';
export function Dashboard({access,thai}:{access:CommandAccess;thai:boolean}){
 const t=(en:string,th:string)=>thai?th:en,[data,setData]=useState<any>(null),[error,setError]=useState(false),generation=useRef(0);
 async function load(){const current=++generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);setError(false);try{const response=await fetch(access.origin+'/api/dashboard',{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const value=await response.json();if(current===generation.current)setData(value)}catch{if(current===generation.current){setData(null);setError(true)}}finally{clearTimeout(timer);done()}}
 useEffect(()=>{void load();return()=>{generation.current++}},[]);useContextRefresh(true,t('Refresh Dashboard','รีเฟรชภาพรวม'),()=>void load());
 // Colors follow the owning OLTP Statistics and Cash Dashboard format rules.
 const color=(key:string,value:unknown)=>{if(value===null||value===undefined)return undefined;if(key==='pendingPaymentAmount')return Number(value)>0?'red':undefined;if(key==='profitCoverageRatio'){const ratio=Number(value);return ratio>=1?'#00838f':ratio>=.6?'#9a7800':ratio>0?'orange':ratio===0?'var(--text-muted, #666)':undefined;}return ({todayProfit:'green',yesterdayProfit:'green',netProfit:'green',activeLoanProfit:'green',notPaid:'red',partiallyPaid:'red',overdue:'purple',fullyPaid:'green',expectedDailyInterest:'#9a7800',realizedProfitMtd:'#9a7800',forecastRemainingInterest:'#9a7800',projectedMonthlyProfit:'#9a7800',totalCashPool:'#FF8C00',operatingIncomeMtd:'#188038',netProfitMtd:'#188038',expensesMtd:'#d93025',tommyWithdrawnMtd:'#d93025',lisaWithdrawnMtd:'#d93025',unsettledProfitMtd:'#1a73e8'} as Record<string,string>)[key]};
 const numeric=(value:unknown,counts=false)=>value===null||value===undefined?t('Unavailable','ไม่มีข้อมูล'):new Intl.NumberFormat(thai?'th-TH':'en-US',{useGrouping:true,minimumFractionDigits:0,maximumFractionDigits:counts?0:2}).format(Number(value));
 const rows=(source:any,entries:string[][],counts=false)=><dl>{entries.filter(([key])=>!counts||source[key]!==0).map(([key,en,th])=><div key={key}><dt>{t(en,th)}</dt><dd style={{color:color(key,source[key])}}>{source[key]===null||source[key]===undefined?t('Unavailable','ไม่มีข้อมูล'):key==='profitCoverageRatio'?new Intl.NumberFormat(thai?'th-TH':'en-US',{style:'percent',maximumFractionDigits:2}).format(Number(source[key])):(counts?'':'฿')+numeric(source[key],counts)}</dd></div>)}</dl>;
 return <section className="borrower-record dashboard-record" aria-label={t('Dashboard','ภาพรวม')}>{error&&<p role="alert">{t('Dashboard unavailable.','ไม่สามารถโหลดภาพรวม')}<button onClick={()=>void load()}>{t('Retry Dashboard','ลองโหลดภาพรวมอีกครั้ง')}</button></p>}{data&&<><section className="dashboard-section"><h2>{t('KPIs','ตัวชี้วัด')}</h2>{rows(data,[['pendingPaymentAmount','Pending Payment Amount','ยอดรอรับชำระ'],['todayProfit',"Today’s Profit",'กำไรวันนี้'],['yesterdayProfit',"Yesterday’s Profit",'กำไรเมื่อวาน'],['netProfit','Net Profit','กำไรสุทธิ']])}<h3>{t('Collection','งานติดตาม')}</h3>{rows(data.collection,[['notPaid','Not Paid','ยังไม่ชำระ'],['partiallyPaid','Partially Paid','ชำระบางส่วน'],['overdue','Overdue','เกินกำหนด'],['fullyPaid','Fully Paid','ชำระครบ']],true)}<h3>{t('Monthly Forecast','ประมาณการรายเดือน')}</h3>{rows(data.forecast,[['expectedDailyInterest','Expected Daily Interest','ดอกเบี้ยรายวันที่คาดการณ์'],['realizedProfitMtd','Realized Profit MTD','กำไรที่รับรู้เดือนนี้'],['forecastRemainingInterest','Forecast Remaining Interest','ประมาณการดอกเบี้ยที่เหลือ'],['projectedMonthlyProfit','Projected Monthly Profit','ประมาณการกำไรรายเดือน']])}<h3>{t('Active loans','สินเชื่อที่ยังไม่ปิด')}</h3>{rows(data.portfolio,[['totalCashPool','Total Cash Pool','เงินทุนรวม'],['activeLoanProfit','Total Profit of Outstanding Loans','กำไรรวมจากสินเชื่อที่ยังไม่ปิด'],['profitCoverageRatio','Profit Coverage','อัตราครอบคลุมเงินต้นด้วยกำไร']])}</section><section className="dashboard-section"><h2>{t('Income MTD','รายได้เดือนนี้')}</h2>{rows(data.incomeMtd,[['operatingIncomeMtd','Operating Income MTD','รายได้ดำเนินงานเดือนนี้'],['expensesMtd','Expenses MTD','ค่าใช้จ่ายเดือนนี้'],['netProfitMtd','Net Profit MTD','กำไรสุทธิเดือนนี้'],['tommyWithdrawnMtd','Tommy Withdrawn MTD','ทอมมี่ถอนเดือนนี้'],['lisaWithdrawnMtd','Lisa Withdrawn MTD','ลิซ่าถอนเดือนนี้'],['unsettledProfitMtd','Unsettled Profit MTD','กำไรยังไม่จัดสรรเดือนนี้']])}</section><section className="dashboard-section"><h2>{t('Business Cash Held','เงินธุรกิจที่ถืออยู่')}</h2>{data.businessCashHeld.map((account:any,index:number)=><React.Fragment key={account.id}>{(index===0||data.businessCashHeld[index-1].holderId!==account.holderId)&&<h3>{account.holderLabel}</h3>}<dl><dt>{account.label}</dt><dd>{account.currentBalance===null?t('Unavailable','ไม่มีข้อมูล'):'฿'+numeric(account.currentBalance)}</dd></dl></React.Fragment>)}</section></>}</section>;
}
