import {useDomainDraft} from './domain-draft';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
type Fields={borrowerId:string;loanDate:string|null;principal:string|null;transferFee:string|null;disbursingAccountId:string|null;type:string|null;dueDate:string|null;dailyPayment:string|null;fixedInterest:string|null;currentDailyInterest:string|null;paymentInterval:number|null;arrangement:string|null;autoChargeEnabled:boolean|null};
const types=['กำหนดวันชำระ','ดอกเบี้ยรายวัน','ผ่อนชำระรายวัน'];
export function LoanForm({access,borrowerId,borrowerLabel,source,recovery,savedDraft,thai,onBack,onSaved}:{access:CommandAccess;borrowerId:string;borrowerLabel:string;source?:any;recovery?:any;savedDraft?:any;thai:boolean;onBack:()=>void;onSaved:(id:string)=>void}){
 const t=(en:string,th:string)=>thai?th:en,identity=useRef(recovery?.command.targetId??source?.id??savedDraft?.id??crypto.randomUUID()),generation=useRef(0),sending=useRef(false),pending=useRef<any>(recovery?.command??null);
 const [fields,setFields]=useState<Fields>(()=>recovery?recovery.command.inputs:savedDraft?savedDraft.fields:source?Object.fromEntries(['borrowerId','loanDate','principal','transferFee','disbursingAccountId','type','dueDate','dailyPayment','fixedInterest','currentDailyInterest','paymentInterval','arrangement','autoChargeEnabled'].map(key=>[key,source[key]])) as Fields:{borrowerId,loanDate:null,principal:null,transferFee:null,disbursingAccountId:null,type:null,dueDate:null,dailyPayment:null,fixedInterest:null,currentDailyInterest:null,paymentInterval:1,arrangement:null,autoChargeEnabled:true});
 const [accounts,setAccounts]=useState<{id:string;label:string}[]>(savedDraft?.accounts??[]),[busy,setBusy]=useState(true),[unknown,setUnknown]=useState(!!recovery),[error,setError]=useState('');
 const draft=useDomainDraft({repository:access.offline,id:identity.current,domain:'loan',label:borrowerLabel,value:{id:identity.current,fields,source:source??null,borrowerLabel,accounts},enabled:!busy&&!unknown&&!pending.current,restore:value=>{if(value?.id===identity.current&&value?.fields){setFields(value.fields);setAccounts(value.accounts??[])}}});
 async function request(path:string,init:RequestInit={}){const done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(access.origin+path,{...init,headers:{Authorization:'Bearer '+await access.token(),'Content-Type':'application/json'},signal:controller.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);return {response,data:await response.json()}}finally{clearTimeout(timer);done()}}
 useEffect(()=>{const current=++generation.current;if(access.offlineOnly||!navigator.onLine){setBusy(false);return()=>{generation.current++};}void request('/api/loan-options').then(({response,data})=>{if(current!==generation.current)return;if(!response.ok)throw Error();setAccounts(data.accounts);if(!source&&!recovery&&!savedDraft)setFields(value=>({...value,loanDate:value.loanDate??data.businessDate,disbursingAccountId:value.disbursingAccountId??(data.accounts.filter((account:any)=>account.isDefault&&account.holderId==='ch:lisa'&&account.active&&account.holderActive).length===1?data.accounts.find((account:any)=>account.isDefault&&account.holderId==='ch:lisa'&&account.active&&account.holderActive).id:null)}));}).catch(()=>{if(current===generation.current)setError(t('Loan choices unavailable. Return and try again.','ไม่สามารถโหลดตัวเลือกสินเชื่อ กลับแล้วลองอีกครั้ง'))}).finally(()=>{if(current===generation.current)setBusy(false)});return()=>{generation.current++}},[]);
 function failed(code:string){setUnknown(false);pending.current=null;draft.resume();setError(code==='source_conflict'?t('The loan changed. Return and reopen current details before editing.','สินเชื่อเปลี่ยนแล้ว กลับไปเปิดรายละเอียดปัจจุบันก่อนแก้ไข'):code==='account_unavailable'?t('Choose an active disbursing account.','เลือกบัญชีจ่ายเงินกู้ที่ใช้งานอยู่'):t('Loan was not saved. Check the terms and first-day charge components.','ไม่ได้บันทึกสินเชื่อ ตรวจสอบเงื่อนไขและเงินต้น/ดอกเบี้ยวันแรก'));}
 async function finish(data:any,current:number){if(current!==generation.current)return false;if(data.kind!=='recorded')return false;const id=pending.current?.requestId;if(id)await access.offline?.remove('pending',id);if(current!==generation.current)return true;if(data.originalOutcome.status==='applied'){pending.current=null;onSaved(identity.current)}else failed(data.originalOutcome.code);return true;}
 async function check(){if(sending.current||!pending.current||access.offlineOnly||!navigator.onLine)return;const current=generation.current;sending.current=true;setBusy(true);try{const {data}=await request('/api/operations/'+pending.current.requestId);if(!await finish(data,current)&&current===generation.current)setError(t('The outcome is still unknown. Check again when connected.','ยังไม่ทราบผล ตรวจสอบอีกครั้งเมื่อเชื่อมต่อ'))}catch{if(current===generation.current)setError(t('Status unavailable. The request remains unchanged.','ตรวจสอบสถานะไม่ได้ คำขอยังไม่เปลี่ยนแปลง'))}finally{sending.current=false;if(current===generation.current)setBusy(false)}}
 async function save(){if(sending.current||pending.current||access.offlineOnly||!navigator.onLine)return;const current=generation.current,command={requestId:crypto.randomUUID(),operation:source?'loan.update':'loan.create',targetId:identity.current,expectedVersion:source?.version??null,predecessorRequestId:null,inputs:{...fields},receiptId:null};sending.current=true;setBusy(true);setError('');pending.current=command;
  let stored=false;try{await draft.freeze();if(!access.offline)throw Error();await access.offline.savePending(command.requestId,{domain:'loan',command,borrowerLabel,source:source??null});stored=true;await access.offline.remove('draft',draft.key);}catch{if(stored){setUnknown(true);}else{pending.current=null;draft.resume();}sending.current=false;setBusy(false);setError(t('Request not sent. Device storage is unavailable or full.','ยังไม่ได้ส่งคำขอ พื้นที่จัดเก็บใช้ไม่ได้หรือเต็ม'));return;}
  if(current!==generation.current){sending.current=false;return;}
  try{const {response,data}=await request('/api/operations',{method:'POST',body:JSON.stringify(command)});if(current!==generation.current)return;if(await finish(data,current))return;if(response.status===400){await access.offline?.remove('pending',command.requestId);failed('invalid_request');return;}setUnknown(true);setError(t('Outcome unknown. Check this request before making another change.','ยังไม่ทราบผล ตรวจสอบคำขอนี้ก่อนเปลี่ยนแปลงอีกครั้ง'));}catch{if(current===generation.current){setUnknown(true);setError(t('Outcome unknown. Check this request.','ยังไม่ทราบผล กรุณาตรวจสอบคำขอนี้'))}}finally{sending.current=false;if(current===generation.current)setBusy(false)}
 }
 const update=(key:keyof Fields,value:any)=>setFields(prior=>({...prior,[key]:value}));
 const input=(key:keyof Fields,en:string,th:string,kind='text',required=false)=><label>{t(en,th)}<input type={kind} inputMode={kind==='number'?'decimal':undefined} step={kind==='number'?'0.01':undefined} value={String(fields[key]??'')} required={required} disabled={busy} onChange={e=>update(key,e.target.value||null)}/></label>;
 return <section className="borrower-record" aria-label={t('Loan form','แบบฟอร์มสินเชื่อ')} aria-busy={busy}><div className="related-loans-heading"><button className="icon-action" aria-label={t('Back to loan details','กลับรายละเอียดสินเชื่อ')} disabled={busy} onClick={onBack}>←</button><h2>{source?t('Edit loan','แก้ไขสินเชื่อ'):t('New loan','สินเชื่อใหม่')} · {borrowerLabel}</h2></div>{error&&<p role="alert">{error}</p>}{draft.error&&<p role="alert">{t('Draft not saved. Device storage is unavailable or full.','บันทึกร่างไม่ได้ พื้นที่จัดเก็บใช้ไม่ได้หรือเต็ม')}</p>}{unknown?<div><p>{t('Request reference','รหัสคำขอ')}: <code>{pending.current?.requestId}</code></p><button disabled={busy||access.offlineOnly||!navigator.onLine} onClick={()=>void check()}>{t('Check loan request','ตรวจสอบคำขอสินเชื่อ')}</button></div>:<form onSubmit={e=>{e.preventDefault();void save()}}>
 {input('loanDate','Loan Date','วันที่กู้','date',true)}{input('principal','Principal Amount','เงินต้น','number',true)}{input('transferFee','Transfer Fee','ค่าธรรมเนียมโอน','number')}
 <label>{t('Disbursing Cash Account','บัญชีจ่ายเงินกู้')}<select required value={fields.disbursingAccountId??''} disabled={busy||source?.defaulted} onChange={e=>update('disbursingAccountId',e.target.value||null)}><option value="">—</option>{source?.disbursingAccountId&&!accounts.some(a=>a.id===source.disbursingAccountId)&&<option value={source.disbursingAccountId}>{source.disbursingAccountLabel}</option>}{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label>
 <label>{t('Loan Type','ประเภทเงินกู้')}<select value={fields.type??''} required disabled={busy} onChange={e=>update('type',e.target.value||null)}><option value="">—</option>{types.map(type=><option key={type}>{type}</option>)}</select></label>
 {fields.type!=='ดอกเบี้ยรายวัน'&&fields.type&&input('dueDate','Due Date','วันครบกำหนด','date',true)}
 {fields.type==='ผ่อนชำระรายวัน'&&input('dailyPayment','Daily Payment Amount','ยอดชำระรายวัน','number',true)}
 {fields.type==='กำหนดวันชำระ'&&input('fixedInterest','Fixed Interest','ดอกเบี้ยกำหนด','number',true)}
 {fields.type==='ดอกเบี้ยรายวัน'&&(source?<label>{t('Current Daily Interest','ดอกเบี้ยรายวันปัจจุบัน')}<span>{source.currentDailyInterest??'—'}</span></label>:input('currentDailyInterest','Current Daily Interest','ดอกเบี้ยรายวันปัจจุบัน','number',true))}
 {source&&<label>{t('Original Daily Interest Rate','อัตราดอกเบี้ยรายวันเริ่มต้น')}<span>{source.originalRate??'—'}</span></label>}
 {['ดอกเบี้ยรายวัน','ผ่อนชำระรายวัน'].includes(fields.type??'')&&<label>{t('Interest Payment Interval','รอบชำระดอกเบี้ย')}<input type="number" min="1" step="1" required value={fields.paymentInterval??''} disabled={busy} onChange={e=>update('paymentInterval',e.target.value?Number(e.target.value):null)}/></label>}
 {fields.type==='ดอกเบี้ยรายวัน'&&<label>{t('Interest Schedule Anchor Date','วันที่เริ่มรอบดอกเบี้ย')}<span>{source?.scheduleAnchor??fields.loanDate??'—'}</span></label>}
 <label>{t('Loan Arrangement','ข้อตกลงการกู้ยืม')}<textarea value={fields.arrangement??''} disabled={busy} onChange={e=>update('arrangement',e.target.value||null)}/></label><label>{t('Auto Charge Enabled','เรียกเก็บอัตโนมัติ')}<input type="checkbox" checked={fields.autoChargeEnabled===true} disabled={busy} onChange={e=>update('autoChargeEnabled',e.target.checked)}/></label>
 <button type="submit" disabled={busy||access.offlineOnly||!navigator.onLine}>{t('Save loan','บันทึกสินเชื่อ')}</button></form>}</section>;
}
