import {useDomainDraft} from './domain-draft';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {OperationConfirm} from './OperationConfirm';
export function LoanClose({access,item,savedDraft,thai,onBack,onApplied}:{access:CommandAccess;item:any;savedDraft?:any;thai:boolean;onBack:()=>void;onApplied:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,requestId=useRef(savedDraft?.requestId??crypto.randomUUID()),generation=useRef(0),uploadGeneration=useRef(0),reviewFlight=useRef(false),restored=useRef(!!savedDraft);
 const [preview,setPreview]=useState<any>(savedDraft?.preview??null),[account,setAccount]=useState(savedDraft?.account??''),[method,setMethod]=useState(savedDraft?.method??'Bank Transfer'),[notes,setNotes]=useState(savedDraft?.notes??''),[receipt,setReceipt]=useState<string|null>(savedDraft?.receipt??null),[receiptName,setReceiptName]=useState(savedDraft?.receiptName??''),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[error,setError]=useState(''),[command,setCommand]=useState<any>(null),[checking,setChecking]=useState(false),[changedPreview,setChangedPreview]=useState<any>(null);
 const draft=useDomainDraft({repository:access.offline,id:'close:'+item.id,domain:'loan',label:item.borrowerDisplayName??t('Close Loan','ปิดสินเชื่อ'),value:{kind:'close',item,requestId:requestId.current,preview,account,method,notes,receipt,receiptName},enabled:!!preview&&!command&&!uploading,restore:value=>{if(value?.item?.id===item.id&&value.kind==='close'){restored.current=true;requestId.current=value.requestId;setPreview(value.preview);setAccount(value.account);setMethod(value.method);setNotes(value.notes);setReceipt(value.receipt);setReceiptName(value.receiptName)}}});
 async function request(path:string,init:RequestInit={}){const done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(access.origin+path,{...init,headers:{Authorization:'Bearer '+await access.token(),...init.headers},signal:controller.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);return {response,data:await response.json()}}finally{clearTimeout(timer);done()}}
 async function load(initial=false){const current=++generation.current;setError('');if(access.offlineOnly||!navigator.onLine){setError(t('Connect to review the current close amount.','เชื่อมต่อเพื่อตรวจสอบยอดปิดปัจจุบัน'));return;}try{const {response,data}=await request('/api/loan-records/'+encodeURIComponent(item.id)+'/close-preview');if(current!==generation.current||(initial&&restored.current))return;if(!response.ok)throw Error();if(preview&&(preview.sourceVersion!==data.sourceVersion||preview.planHash!==data.planHash)){setChangedPreview(data);return;}setPreview(data);}catch{if(current===generation.current)setError(t('This loan cannot be reviewed for closing. Check the current terms and charge balances.','ไม่สามารถตรวจสอบยอดปิด ตรวจสอบเงื่อนไขและยอดเรียกเก็บปัจจุบัน'));}}
 useEffect(()=>{if(!savedDraft)void load(true);return()=>{generation.current++;uploadGeneration.current++}},[]);
 async function upload(file:File|null){const sequence=++uploadGeneration.current,current=generation.current;setUploading(false);setReceipt(null);setReceiptName('');setUploadError('');if(!file)return;if(access.offlineOnly||!navigator.onLine||!['image/png','image/jpeg'].includes(file.type)||file.size>5242880){setUploadError(t('Choose a PNG or JPEG up to 5 MiB while connected.','เลือก PNG หรือ JPEG ไม่เกิน 5 MiB ขณะเชื่อมต่อ'));return;}setUploading(true);const id=crypto.randomUUID();try{const {response}=await request('/api/payment-commands/'+requestId.current+'/receipts/'+id,{method:'POST',headers:{'Content-Type':file.type,'X-Borrower-ID':item.borrowerId},body:file});if(current!==generation.current||sequence!==uploadGeneration.current)return;if(!response.ok)throw Error();setReceipt(id);setReceiptName(file.name);}catch{if(current===generation.current&&sequence===uploadGeneration.current)setUploadError(t('Receipt upload failed. Retry or explicitly remove it before continuing.','อัปโหลดหลักฐานไม่สำเร็จ ลองอีกครั้งหรือลบก่อนดำเนินการ'));}finally{if(current===generation.current&&sequence===uploadGeneration.current)setUploading(false)}}
 async function review(){if(reviewFlight.current||!preview||!account||uploading||uploadError||access.offlineOnly||!navigator.onLine)return;reviewFlight.current=true;setChecking(true);const scope=generation.current;try{const {response,data}=await request('/api/loan-records/'+encodeURIComponent(item.id)+'/close-preview');if(scope!==generation.current)return;if(!response.ok)throw Error();if(data.sourceVersion!==preview.sourceVersion||data.planHash!==preview.planHash){setChangedPreview(data);setError(t('Closing balances changed. Review the current amount before continuing.','ยอดปิดเปลี่ยนแล้ว โปรดตรวจสอบยอดปัจจุบันก่อนดำเนินการ'));return;}await draft.freeze();if(scope!==generation.current)return;setCommand({requestId:requestId.current,operation:'loan.close',targetId:item.id,expectedVersion:preview.sourceVersion,predecessorRequestId:null,receiptId:receipt,inputs:{paymentDate:preview.businessDate,cashAccountId:account,paymentMethod:method,notes:notes===''?null:notes,expectedAmount:preview.amount,expectedPlanHash:preview.planHash}})}catch{setError(t('Current closing details unavailable.','ไม่สามารถโหลดข้อมูลปิดปัจจุบัน'))}finally{reviewFlight.current=false;if(scope===generation.current)setChecking(false)}}
 if(command)return <OperationConfirm access={access} command={command} domain="loan" draftKey={draft.key} label={t('Close Loan','ปิดสินเชื่อ')} thai={thai} onBack={()=>{setCommand(null);draft.resume()}} onApplied={onApplied}><dl><div><dt>{item.borrowerDisplayName}</dt><dd>฿{command.inputs.expectedAmount}</dd></div><div><dt>{t('Receiving account','บัญชีรับเงิน')}</dt><dd>{preview.accounts.find((value:any)=>value.id===account)?.label}</dd></div><div><dt>{t('Payment Method','วิธีชำระเงิน')}</dt><dd>{method}</dd></div><div><dt>{t('Notes','หมายเหตุ')}</dt><dd className="borrower-field-value">{notes||'—'}</dd></div>{receipt&&<div><dt>{t('Receipt','หลักฐานรับเงิน')}</dt><dd>{receiptName}</dd></div>}</dl></OperationConfirm>;
 return <section className="borrower-record"><div className="related-loans-heading"><button className="icon-action" aria-label={t('Back to loan details','กลับรายละเอียดสินเชื่อ')} onClick={onBack}>←</button><h2>{t('Close Loan','ปิดสินเชื่อ')} · {item.borrowerDisplayName}</h2></div>{draft.error&&<p role="alert">{t('Draft not saved. Device storage is unavailable or full.','บันทึกร่างไม่ได้ พื้นที่จัดเก็บใช้ไม่ได้หรือเต็ม')}</p>}{changedPreview&&<p role="alert">{t('Current closing amount','ยอดปิดปัจจุบัน')} ฿{changedPreview.amount}<button type="button" onClick={()=>{setPreview(changedPreview);setChangedPreview(null);setError('')}}>{t('Use current closing amount','ใช้ยอดปิดปัจจุบัน')}</button></p>}{error&&<p role="alert">{error}<button onClick={()=>void load()}>{t('Retry review','ลองตรวจสอบอีกครั้ง')}</button></p>}{preview&&<form onSubmit={event=>{event.preventDefault();void review()}}><output>฿{preview.amount}</output><label><span className="field-title">{t('Receiving account','บัญชีรับเงิน')}</span><select disabled={checking} required value={account} onChange={event=>setAccount(event.target.value)}><option value="">—</option>{preview.accounts.map((value:any)=><option key={value.id} value={value.id}>{value.label}</option>)}</select></label><label><span className="field-title">{t('Payment Method','วิธีชำระเงิน')}</span><select required disabled={checking} value={method} onChange={event=>setMethod(event.target.value)}>{['Bank Transfer','Cash','Net-off at Disbursement'].map(value=><option key={value}>{value}</option>)}</select></label><label><span className="field-title">{t('Notes','หมายเหตุ')}</span><textarea disabled={checking} value={notes} onChange={event=>setNotes(event.target.value)}/></label><label><span className="field-title">{t('Receipt','หลักฐานรับเงิน')}</span><input type="file" accept="image/png,image/jpeg" disabled={checking||access.offlineOnly||!navigator.onLine} onChange={event=>void upload(event.target.files?.[0]??null)}/></label>{(receipt||uploadError||uploading)&&<button type="button" disabled={checking} onClick={()=>void upload(null)}>{t('Remove receipt','ลบหลักฐาน')}</button>}{uploadError&&<p role="alert">{uploadError}</p>}<button disabled={checking||!account||uploading||!!uploadError||access.offlineOnly||!navigator.onLine}>{t('Review close','ตรวจสอบการปิด')}</button></form>}<details><summary>{t('Draft actions','จัดการร่าง')}</summary><button type="button" disabled={checking} onClick={()=>void draft.discard().then(onBack).catch(()=>setError(t('Draft could not be cleared.','ล้างร่างไม่ได้')))}>{t('Clear draft','ล้างร่าง')}</button></details></section>;
}
