import {HeaderBack} from './HeaderBack';
import {ManagementExpenseReference} from './ManagementExpenseReference';
import {displayValue} from './display-date';
import React,{useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {useDomainDraft} from './domain-draft';
import {OperationConfirm} from './OperationConfirm';
import {ManagementReference} from './ManagementReference';
export type FinancialKind='capital-contribution'|'settlement'|'cash-movement';
const fields:Record<FinancialKind,[string,string,string,string,boolean?][]>={
 'capital-contribution':[['partnerId','Partner','หุ้นส่วน','partners',true],['contributionDate','Contribution Date','วันที่ลงทุน','date',true],['transactionType','Transaction Type','ประเภทรายการ','contribution-type',true],['amount','Amount','จำนวนเงิน','number',true],['notes','Notes','หมายเหตุ','textarea']],
 settlement:[['settlementDate','Settlement Date','วันที่จัดสรร','date',true],['partnerId','Partner','หุ้นส่วน','partners',true],['amount','Amount','จำนวนเงิน','number',true],['status','Status','สถานะ','status',true],['transferDate','Transfer Date','วันที่โอน','date'],['notes','Notes','หมายเหตุ','textarea'],['cashAccountId','Cash Account','บัญชีเงินสด','cash-accounts']],
 'cash-movement':[['movementDate','Movement Date','วันที่รายการ','date',true],['movementType','Movement Type','ประเภทรายการ','movement-type',true],['amount','Amount','จำนวนเงิน','number',true],['fromAccountId','From Account','จากบัญชี','cash-accounts',true],['toAccountId','To Account','ไปยังบัญชี','cash-accounts',true],['businessExpenseId','Related Expense','ค่าใช้จ่ายที่เกี่ยวข้อง','expense'],['notes','Notes','หมายเหตุ','textarea']],
};
function initial(kind:FinancialKind,source:any,day:string,partnerId?:string){if(kind==='capital-contribution')return {partnerId:source?.partnerId??partnerId??null,contributionDate:source?.date??day,transactionType:source?.transactionType??'Contribution',amount:source?.amount??'',notes:source?.notes??null};if(kind==='settlement')return {settlementDate:source?.date??day,partnerId:source?.partnerId??partnerId??null,amount:source?.amount??'',status:source?.status??'Pending',transferDate:source?.transferDate??null,notes:source?.notes??null,cashAccountId:source?.cashAccountId??null};return {movementDate:source?.date??day,movementType:source?.movementType??'Cash Handover',amount:source?.amount??'',fromAccountId:source?.fromAccountId??null,toAccountId:source?.toAccountId??null,businessExpenseId:source?.businessExpenseId??null,notes:source?.notes??null};}
export function ManagementFinancialForm({access,thai,kind,source,savedDraft,businessDate,partnerId,partnerLabel,onBack,onApplied}:{access:CommandAccess;thai:boolean;kind:FinancialKind;source?:any;savedDraft?:any;businessDate:string;partnerId?:string;partnerLabel?:string;onBack:()=>void;onApplied:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,id=useRef(savedDraft?.id??source?.id??crypto.randomUUID()),original=useRef(savedDraft?.source??source??null),[inputs,setInputs]=useState<any>(savedDraft?.inputs??initial(kind,source,businessDate,partnerId)),[labels,setLabels]=useState<any>(savedDraft?.labels??{partnerId:source?.partnerLabel??partnerLabel,cashAccountId:source?.cashAccountLabel,fromAccountId:source?.fromAccountLabel,toAccountId:source?.toAccountLabel}),[edited,setEdited]=useState(!!savedDraft),[command,setCommand]=useState<any>(null),[error,setError]=useState('');
 const title=t(source?'Edit record':'New record',source?'แก้ไขรายการ':'เพิ่มรายการ'),draft=useDomainDraft({repository:access.offline,id:id.current,domain:'management',label:labels.partnerId||title,value:{kind,id:id.current,source:original.current,inputs,labels,businessDate},enabled:edited&&!command,restore:value=>{if(value?.kind===kind&&value.id===id.current){original.current=value.source;setInputs(value.inputs);setLabels(value.labels);setEdited(true)}}});
 async function review(){setError('');if(fields[kind].some(([key,,,type,required])=>required&&!inputs[key])||Number(inputs.amount)<=0||(kind==='cash-movement'&&!/^[1-9][0-9]*$/.test(inputs.amount))){setError(t('Check the required fields and exact amount.','ตรวจสอบช่องที่จำเป็นและจำนวนเงิน'));return;}await draft.freeze();setCommand({requestId:crypto.randomUUID(),operation:kind+(original.current?'.update':'.create'),targetId:id.current,expectedVersion:original.current?.version??null,predecessorRequestId:null,receiptId:null,inputs});}
 if(command)return <OperationConfirm access={access} thai={thai} command={command} domain="management" label={title} draftKey={draft.key} onBack={()=>{setCommand(null);draft.resume()}} onApplied={onApplied}><dl>{fields[kind].map(([key,en,th])=><div key={key}><dt>{t(en,th)}</dt><dd>{key==='amount'?'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(inputs[key])):labels[key]??displayValue(inputs[key])}</dd></div>)}</dl></OperationConfirm>;
 return <section className="borrower-record"><div className="related-loans-heading"><HeaderBack className="icon-action" aria-label={t('Back to details','กลับรายละเอียด')} onClick={onBack}>←</HeaderBack><h2>{title}</h2></div>{error&&<p role="alert">{error}</p>}{draft.error&&<p role="alert">{t('Draft not saved. Keep this form open.','ยังไม่ได้บันทึกร่าง โปรดเปิดหน้านี้ไว้')}</p>}<form onSubmit={event=>{event.preventDefault();void review()}}>{fields[kind].filter(([key])=>key!=='businessExpenseId'||inputs.movementType==='Expense Reimbursement').map(([key,en,th,type,required])=><label key={key}><span className="field-title">{t(en,th)}</span>{type==='expense'?<ManagementExpenseReference access={access} thai={thai} value={inputs[key]} label={labels[key]} onChange={(value,label)=>{setEdited(true);setInputs({...inputs,[key]:value});setLabels({...labels,[key]:label})}}/>:type==='partners'||type==='cash-accounts'?<ManagementReference access={access} thai={thai} kind={type} value={inputs[key]} label={labels[key]} required={required} onChange={(value,label)=>{setEdited(true);setInputs({...inputs,[key]:value});setLabels({...labels,[key]:label})}}/>:type==='textarea'?<textarea value={inputs[key]??''} onChange={event=>{setEdited(true);setInputs({...inputs,[key]:event.target.value})}}/>:['status','movement-type','contribution-type'].includes(type)?<select value={inputs[key]??''} required={required} onChange={event=>{setEdited(true);setInputs({...inputs,[key]:event.target.value})}}>{(type==='status'?['Pending','Completed']:type==='movement-type'?['Cash Handover','Expense Reimbursement']:['Contribution','Withdrawal']).map(value=><option key={value}>{value}</option>)}</select>:<input required={required} type={type} step={type==='number'?(kind==='cash-movement'?'1':'0.01'):undefined} value={inputs[key]??''} onChange={event=>{setEdited(true);setInputs({...inputs,[key]:event.target.value||null})}}/>}</label>)}<button disabled={!draft.ready||access.offlineOnly||!navigator.onLine}>{t('Review change','ตรวจสอบการเปลี่ยนแปลง')}</button></form></section>;
}
