import {HeaderBack} from './HeaderBack';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {OperationConfirm} from './OperationConfirm';
import {useDomainDraft} from './domain-draft';
export function ManagementOpenings({access,thai,holderId,savedDraft,onBack,onApplied}:{access:CommandAccess;thai:boolean;holderId:string;savedDraft?:any;onBack:()=>void;onApplied:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,id=useRef(savedDraft?.id??crypto.randomUUID()),generation=useRef(0),[basis,setBasis]=useState<any>(savedDraft?.basis??null),[amounts,setAmounts]=useState<Record<string,string>>(savedDraft?.amounts??{}),[notes,setNotes]=useState(savedDraft?.notes??''),[edited,setEdited]=useState(!!savedDraft),[busy,setBusy]=useState(false),[error,setError]=useState(''),[command,setCommand]=useState<any>(null);
 const draft=useDomainDraft({repository:access.offline,id:id.current,domain:'management',label:basis?.holderLabel??t('Account openings','ยอดยกมาบัญชี'),value:{kind:'cash-openings',id:id.current,holderId,basis,amounts,notes},enabled:edited&&!command,restore:value=>{if(value?.kind==='cash-openings'&&value.holderId===holderId){setBasis(value.basis);setAmounts(value.amounts);setNotes(value.notes);setEdited(true)}}});
 async function read(){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const response=await fetch(access.origin+'/api/management/openings/'+encodeURIComponent(holderId),{headers:{Authorization:'Bearer '+await access.token()},signal:c.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();return (await response.json()).item;}finally{clearTimeout(timer)}}
 useEffect(()=>{let active=true;const mine=++generation.current;if(!basis&&!access.offlineOnly){const done=beginRequest();setBusy(true);void read().then(value=>{if(active&&mine===generation.current){setBasis(value);setAmounts(Object.fromEntries(value.accounts.filter((a:any)=>!a.initialized).map((a:any)=>[a.accountId,''])))}}).catch(()=>{if(active)setError(t('Account balances are unavailable. Return and reopen this view.','ไม่สามารถโหลดข้อมูลบัญชี กรุณากลับแล้วเปิดใหม่'))}).finally(()=>{done();if(active)setBusy(false)})}return()=>{active=false;generation.current++}},[holderId]);
 async function review(){if(busy||!basis||access.offlineOnly||!navigator.onLine)return;const openings=basis.accounts.filter((a:any)=>!a.initialized).map((a:any)=>({accountId:a.accountId,amount:amounts[a.accountId]??''}));if(!notes.trim()||!openings.length||openings.some((a:any)=>!/^(0|-?[1-9][0-9]*)$/.test(a.amount))){setError(t('Enter every opening as whole baht and include notes.','ระบุยอดยกมาทุกบัญชีเป็นจำนวนเต็มพร้อมหมายเหตุ'));return}const mine=generation.current,done=beginRequest();setBusy(true);setError('');try{const current=await read();if(mine!==generation.current)return;if(current.reviewedBasisHash!==basis.reviewedBasisHash){setError(t('Balances changed. Your entries are retained; return and review current balances before starting a new allocation.','ยอดคงเหลือเปลี่ยนแล้ว ข้อมูลที่กรอกยังอยู่ โปรดกลับไปตรวจสอบยอดปัจจุบัน'));return}await draft.freeze();if(mine!==generation.current)return;setCommand({requestId:crypto.randomUUID(),operation:'cash-openings.initialize',targetId:holderId,expectedVersion:basis.version,predecessorRequestId:null,receiptId:null,inputs:{openings,reviewedBasisHash:basis.reviewedBasisHash,notes}})}catch{if(mine===generation.current)setError(t('Review is unavailable. Your entries are retained.','ยังตรวจสอบไม่ได้ ข้อมูลที่กรอกยังอยู่'))}finally{done();if(mine===generation.current)setBusy(false)}}
 const money=(value:string|null)=>value===null?'—':'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(value));
 if(command)return <OperationConfirm access={access} thai={thai} command={command} domain="management" label={basis.holderLabel} draftKey={draft.key} onBack={()=>{setCommand(null);draft.resume()}} onApplied={onApplied}><dl>{command.inputs.openings.map((a:any)=><div key={a.accountId}><dt>{basis.accounts.find((v:any)=>v.accountId===a.accountId)?.label}</dt><dd>{money(a.amount)}</dd></div>)}</dl><p>{notes}</p></OperationConfirm>;
 return <section className="borrower-record"><div className="related-loans-heading"><HeaderBack className="icon-action" aria-label={t('Back to Cash Position','กลับสถานะเงินสด')} onClick={onBack}>←</HeaderBack><h2>{t('Initialize account openings','กำหนดยอดยกมาบัญชี')}</h2></div>{error&&<p role="alert">{error}</p>}{draft.error&&<p role="alert">{t('Draft not saved. Keep this form open.','ยังไม่ได้บันทึกร่าง โปรดเปิดหน้านี้ไว้')}</p>}{basis&&<form onSubmit={e=>{e.preventDefault();void review()}}><h3>{basis.holderLabel}</h3><dl><div><dt>{t('Holder balance','ยอดคงเหลือผู้ถือเงิน')}</dt><dd>{money(basis.holderBalance)}</dd></div></dl>{basis.accounts.map((a:any)=>a.initialized?<div key={a.accountId}>{a.label}: {money(a.balance)}</div>:<label key={a.accountId}><span className="field-title">{a.label}</span><input required inputMode="numeric" value={amounts[a.accountId]??''} onChange={e=>{setEdited(true);setAmounts({...amounts,[a.accountId]:e.target.value})}}/></label>)}<label><span className="field-title">{t('Notes','หมายเหตุ')}</span><textarea required value={notes} onChange={e=>{setEdited(true);setNotes(e.target.value)}}/></label><button disabled={busy||!draft.ready||access.offlineOnly||!navigator.onLine}>{t('Review openings','ตรวจสอบยอดยกมา')}</button></form>}</section>;
}
