import {borrowerLabel} from './borrower-label';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
/** Bounded named reference selection; no whole-directory prefetch or ID-as-label fallback. */
export function ManagementReference({access,kind,value,label,onChange,thai,required=false}:{access:CommandAccess;kind:'partners'|'cash-accounts'|'cash-holders'|'borrowers';value:string|null;label?:string|null;onChange:(id:string|null,label:string|null)=>void;thai:boolean;required?:boolean}){
 const [query,setQuery]=useState(''),[items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(false),generation=useRef(0),t=(en:string,th:string)=>thai?th:en;
 useEffect(()=>{if(!open||access.offlineOnly)return;const current=++generation.current,abort=new AbortController();let done:(()=>void)|undefined;const debounce=setTimeout(()=>{done=beginRequest();void(async()=>{try{const response=await fetch(access.origin+(kind==='borrowers'?'/api/borrower-options?q=':'/api/management/'+kind+'?limit=25&q=')+encodeURIComponent(query),{headers:{Authorization:'Bearer '+await access.token()},signal:abort.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const data=await response.json();if(current===generation.current){setItems(kind==='borrowers'?data.referrers.map((row:any)=>({...row,label:borrowerLabel(row.label,row.description)})):data.items);setError(false)}}catch{if(!abort.signal.aborted&&current===generation.current)setError(true)}finally{done?.()}})()},250);const timeout=setTimeout(()=>abort.abort(),15000);return()=>{generation.current++;clearTimeout(debounce);clearTimeout(timeout);abort.abort();done?.()}},[open,query,kind]);
 return <div className="management-reference"><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open}>{label||(value?t('Selected record','รายการที่เลือก'):t('Select','เลือก'))}</button>{required&&!value&&<input tabIndex={-1} aria-hidden="true" required value="" onChange={()=>{}} style={{position:'absolute',width:1,height:1,opacity:0}}/>}{open&&<><input aria-label={t('Search records','ค้นหารายการ')} value={query} onChange={event=>setQuery(event.target.value)}/>{error&&<p role="alert">{t('Search unavailable.','ค้นหาไม่ได้')}</p>}{items.map(row=><button type="button" className="borrower-card management-reference-option" key={row.id} onClick={event=>{event.preventDefault();event.stopPropagation();setOpen(false);onChange(row.id,row.label)}}>{row.label||t('Name unavailable','ไม่พบชื่อ')}{row.holderLabel&&<small>{row.holderLabel}</small>}</button>)}{!required&&<button type="button" onClick={event=>{event.preventDefault();event.stopPropagation();setOpen(false);onChange(null,null)}}>{t('Clear','ล้าง')}</button>}</>}</div>;
}
