import {RecordAction} from './RecordAction';
import {HeaderBack} from './HeaderBack';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {useContextRefresh} from './context-refresh';
import {OperationConfirm} from './OperationConfirm';
import {CompactPager} from './CompactPager';
import {displayDate,displayTimestamp} from './display-date';
import {borrowerLabel} from './borrower-label';
const chartDefinitions=[['distribution','Loan Distribution','สัดส่วนสินเชื่อ'],['profit30','Profit Contribution 30D','สัดส่วนกำไร 30 วัน'],['dailyInterest','Daily Interest Contribution','สัดส่วนดอกเบี้ยรายวัน'],['projected','Projected Monthly Profit Contribution','สัดส่วนประมาณการกำไรรายเดือน'],['daily','Daily Profit','กำไรรายวัน'],['weekly','Weekly Profit','กำไรรายสัปดาห์'],['monthly','Monthly Profit','กำไรรายเดือน'],['outstanding30','Daily Outstanding Principal 30D','เงินต้นคงค้างรายวัน 30 วัน'],['profit30Line','Daily Profit Last 30D','กำไรรายวัน 30 วัน']] as const;
const metrics=[['totalProfit','Total Profit','กำไรทั้งหมด'],['totalBusinessExpenses','Total Business Expenses','ค่าใช้จ่ายธุรกิจทั้งหมด'],['netProfit','Net Profit','กำไรสุทธิ'],['expectedDailyInterest','Expected Daily Interest','ดอกเบี้ยรายวันที่คาดหวัง'],['realizedProfitMtd','Realized Profit MTD','กำไรที่รับเดือนนี้'],['expensesMtd','Expenses MTD','ค่าใช้จ่ายเดือนนี้'],['netProfitMtd','Net Profit MTD','กำไรสุทธิเดือนนี้'],['forecastRemainingInterest','Forecast Remaining Interest','ประมาณการดอกเบี้ยที่เหลือ'],['projectedMonthlyProfit','Projected Monthly Profit','ประมาณการกำไรรายเดือน'],['forecastAverageDailyOutstandingPrincipal','Forecast Average Daily Outstanding Principal','ประมาณการเงินต้นคงค้างเฉลี่ยรายวัน'],['forecastMonthlyReturnOnAdo','Forecast Monthly Return on ADO','ประมาณการผลตอบแทนต่อเงินต้นเฉลี่ย'],['peakCashPool30d','Peak Cash Pool 30D','เงินทุนสูงสุด 30 วัน'],['peakCashPoolDate30d','Peak Cash Pool Date 30D','วันที่เงินทุนสูงสุด 30 วัน']] as const;
const palette=['#1976a3','#168447','#b77b08','#8054ad','#c94749','#007f83','#796746'];
function Chart({access,thai,metric,title,refresh}:{access:CommandAccess;thai:boolean;metric:string;title:string;refresh:number}){
 const t=(en:string,th:string)=>thai?th:en,[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[page,setPage]=useState(0),generation=useRef(0),cursors=useRef<(string|null)[]>([null]),controller=useRef<AbortController|null>(null);
 async function load(cursor:string|null=null,index=0){if(access.offlineOnly)return;const current=++generation.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;const done=beginRequest(),timer=setTimeout(()=>abort.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(access.origin+'/api/management/analytics-chart?metric='+metric+(cursor?'&cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+await access.token()},signal:abort.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const result=await response.json();if(current===generation.current){setData(result);setPage(index);cursors.current[index]=cursor}}catch{if(current===generation.current)setError(true)}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}}
 useEffect(()=>{setData(null);cursors.current=[null];void load();return()=>{generation.current++;controller.current?.abort()}},[metric,refresh]);
 const money=(v:any)=>v==null?'—':'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(v)),pie=Array.isArray(data?.pieItems),validPie=pie&&data.unknownCount===0&&data.negativeCount===0&&Number(data.totalValue)>0;
 const pieLegend=validPie?[...data.pieItems.map((row:any)=>({label:borrowerLabel(row.name,row.description),value:row.value})),...(Number(data.otherValue)!==0?[{label:t('Other borrowers','ผู้กู้อื่น ๆ'),value:data.otherValue}]:[])]:[];
 let gradient='';if(validPie){let at=0;gradient=[...data.pieItems.map((r:any)=>r.value),data.otherValue].map((v:any,n:number)=>{const start=at;at+=Number(v)/Number(data.totalValue)*100;return palette[n%palette.length]+' '+start+'% '+at+'%'}).join(',')}
 const bars=['daily','weekly','monthly'].includes(metric),points=data?.items??[],known=points.filter((p:any)=>p.value!==null&&p.unknownCount===0),low=Math.min(0,...known.map((p:any)=>Number(p.value))),high=Math.max(1,...known.map((p:any)=>Number(p.value))),line=points.map((p:any,n:number)=>p.value===null||p.unknownCount>0?null:[72+(points.length<2?220:n/(points.length-1)*420),185-(Number(p.value)-low)/(high-low)*160]);
 const y=(value:number)=>185-(value-low)/(high-low)*160,zero=y(0),ticks=[...new Set([low,0,high])],dateTicks=[...new Set([0,Math.floor((points.length-1)/2),points.length-1])].filter(n=>n>=0&&n<points.length),tickLabel=(label:string)=>/^\d{4}-\d{2}-\d{2}$/.test(label)?displayDate(label):label;
 return <article className="management-chart"><h3>{title}</h3>{error?<p role="alert">{t('Chart unavailable.','ไม่สามารถโหลดกราฟ')} <button onClick={()=>void load()}>{t('Retry','ลองอีกครั้ง')}</button></p>:data&&<>{pie?<><p>{money(data.totalValue)} · {data.count} {t('borrowers','ผู้กู้')}</p>{validPie?<div className="management-pie" role="img" aria-label={title+' · '+money(data.totalValue)} style={{background:'conic-gradient('+gradient+')'}}/>:<p>{t('A complete positive total is required for a pie chart. Values are shown below.','กราฟวงกลมต้องมียอดบวกครบถ้วน ดูข้อมูลด้านล่าง')}</p>}{validPie&&<ul className="analytics-pie-legend">{pieLegend.map((row:any,index:number)=><li key={index}><span className="pie-swatch" aria-hidden="true" style={{background:palette[index%palette.length]}}/><span>{row.label}</span><strong>{money(row.value)}</strong></li>)}</ul>}{!validPie&&Number(data.otherValue)!==0&&<p>{t('Other borrowers','ผู้กู้อื่น ๆ')}: {money(data.otherValue)}</p>}</>:<><svg className="management-line-chart" viewBox="0 0 550 235" role="img" aria-label={title+' · '+t('Amounts in baht','จำนวนเงินเป็นบาท')}>
{ticks.map(value=><g key={value}><line x1="72" x2="510" y1={y(value)} y2={y(value)} stroke={value===0?'#555':'#ddd'} strokeWidth={value===0?1.5:1}/><text x="64" y={y(value)+4} textAnchor="end" className="chart-tick">{new Intl.NumberFormat(thai?'th-TH':'en-GB',{notation:'compact',maximumFractionDigits:1}).format(value)}</text></g>)}<text x="8" y="14" className="chart-tick">฿</text>
{dateTicks.map(n=><text key={n} x={line[n]?.[0]??(72+(points.length<2?220:n/(points.length-1)*420))} y="216" textAnchor={n===0?'start':n===points.length-1?'end':'middle'} className="chart-tick">{tickLabel(points[n].label)}</text>)}
{line.map((point:any,n:number)=>point&&(bars?<rect key={n} x={point[0]-Math.min(24,400/Math.max(1,points.length))/2} y={Math.min(point[1],zero)} width={Math.min(24,400/Math.max(1,points.length))} height={Math.max(1,Math.abs(point[1]-zero))} fill={Number(points[n].value)<0?'#b3261e':Number(points[n].value)>0?'#168447':'#555'}><title>{points[n].label+': '+money(points[n].value)}</title></rect>:<React.Fragment key={n}>{n>0&&line[n-1]&&<line x1={line[n-1][0]} y1={line[n-1][1]} x2={point[0]} y2={point[1]} stroke="#1976a3" strokeWidth="2"/>}<circle cx={point[0]} cy={point[1]} r="3" fill={Number(points[n].value)<0?'#b3261e':Number(points[n].value)>0?'#168447':'#555'}><title>{points[n].label+': '+money(points[n].value)}</title></circle></React.Fragment>))}</svg>{data.truncated&&<p>{t('This chart is truncated; the displayed rows are not the full source.','กราฟนี้แสดงข้อมูลบางส่วน ไม่ใช่ข้อมูลทั้งหมด')}</p>}</>}<details><summary>{t('Values','ข้อมูล')}</summary><div className="management-table-scroll" role="region" tabIndex={0} aria-label={title+' · '+t('Values','ข้อมูล')}><table><tbody>{points.map((row:any,n:number)=><tr key={row.id??row.label??n}><th>{pie?borrowerLabel(row.name,row.description):/^\d{4}-\d{2}-\d{2}$/.test(row.label)?displayDate(row.label):row.label}</th><td>{money(row.value)}{row.unknownCount>0?' · '+t('Incomplete','ไม่ครบถ้วน'):''}</td></tr>)}</tbody></table></div>{pie&&<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={data.nextCursor?()=>void load(data.nextCursor,page+1):undefined} previousLabel={t('Previous borrowers','ผู้กู้ก่อนหน้า')} nextLabel={t('Next borrowers','ผู้กู้ถัดไป')}/>}</details></>}</article>;
}
export function ManagementAnalytics({access,thai}:{access:CommandAccess;thai:boolean}){
 const t=(en:string,th:string)=>thai?th:en,[overview,setOverview]=useState<any>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[command,setCommand]=useState<any>(null),[validation,setValidation]=useState(false),generation=useRef(0),controller=useRef<AbortController|null>(null);
 async function load(){if(access.offlineOnly)return;const current=++generation.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;const done=beginRequest(),timer=setTimeout(()=>abort.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(access.origin+'/api/management/analytics-overview',{headers:{Authorization:'Bearer '+await access.token()},signal:abort.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const result=await response.json();if(current===generation.current)setOverview(result)}catch{if(current===generation.current)setError(true)}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}}
 useEffect(()=>{void load();return()=>{generation.current++;controller.current?.abort()}},[refresh]);useContextRefresh(!command&&!validation,t('Refresh analytics view','รีเฟรชมุมมองวิเคราะห์'),()=>setRefresh(v=>v+1));
 const money=(v:any)=>v==null?'—':'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(v));
 if(command)return <OperationConfirm access={access} thai={thai} command={command} domain="management" label={t('Recalculate analytics','คำนวณข้อมูลวิเคราะห์ใหม่')} onBack={()=>setCommand(null)} onApplied={()=>{setCommand(null);setRefresh(v=>v+1)}}><p>{command.inputs.mode==='Full'?t('Rebuild the complete supported history.','คำนวณประวัติที่รองรับทั้งหมดใหม่'):t('Recalculate yesterday and today.','คำนวณข้อมูลเมื่อวานและวันนี้ใหม่')}</p></OperationConfirm>;
 if(validation)return <AnalyticsValidation access={access} thai={thai} onBack={()=>setValidation(false)}/>;
 return <section><header className="related-loans-heading"><h2>{t('Analytics','การวิเคราะห์')}</h2><div className="borrower-direct-actions"><RecordAction icon="▤" onClick={()=>setValidation(true)}>{t('Daily Analytics Validation','ตรวจสอบข้อมูลรายวัน')}</RecordAction>{(['Recent','Full'] as const).map(mode=><RecordAction icon={mode==='Recent'?'↻':'∑'} key={mode} disabled={busy||!overview?.refreshTarget||access.offlineOnly} onClick={()=>setCommand({requestId:crypto.randomUUID(),operation:'analytics.refresh',targetId:overview.refreshTarget.id,expectedVersion:overview.refreshTarget.version,predecessorRequestId:null,receiptId:null,inputs:{mode}})}>{mode==='Recent'?t('Recalculate recent','คำนวณล่าสุด'):t('Recalculate full history','คำนวณประวัติทั้งหมด')}</RecordAction>)}</div></header>{error&&<p role="alert">{t('Analytics unavailable.','ไม่สามารถโหลดการวิเคราะห์')} <button onClick={()=>void load()}>{t('Retry','ลองอีกครั้ง')}</button></p>}{overview&&<div className="management-cards"><article><h3>{t('Analytics Data','ข้อมูลวิเคราะห์')}</h3><dl>{metrics.map(([key,en,th])=><div key={key}><dt>{t(en,th)}</dt><dd>{key==='peakCashPoolDate30d'?displayDate(overview.metrics[key]):key==='forecastMonthlyReturnOnAdo'?overview.metrics[key]==null?'—':new Intl.NumberFormat(thai?'th-TH':'en-GB',{style:'percent',maximumFractionDigits:2}).format(Number(overview.metrics[key])):money(overview.metrics[key])}</dd></div>)}</dl></article><article><h3>{t('Outstanding Principal','เงินต้นคงค้าง')}</h3><strong>{money(overview.metrics.outstandingPrincipal)}</strong><p>{overview.metrics.activeLoans??'—'} {t('Active Loans','สินเชื่อที่ใช้งาน')}</p></article></div>}<div className="management-chart-grid">{chartDefinitions.map(([metric,en,th])=><Chart key={metric} access={access} thai={thai} metric={metric} title={t(en,th)} refresh={refresh}/>)}</div></section>;
}
function AnalyticsValidation({access,thai,onBack}:{access:CommandAccess;thai:boolean;onBack:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,[data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[page,setPage]=useState(0),generation=useRef(0),cursors=useRef<(string|null)[]>([null]);
 async function load(cursor:string|null=null,index=0){if(access.offlineOnly)return;const current=++generation.current,c=new AbortController(),done=beginRequest(),timer=setTimeout(()=>c.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(access.origin+'/api/management/analytics-validation?limit=25'+(cursor?'&cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+await access.token()},signal:c.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const result=await response.json();if(current===generation.current){setData(result);setPage(index);cursors.current[index]=cursor}}catch{if(current===generation.current)setError(true)}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}}
 useEffect(()=>{void load();return()=>{generation.current++}},[]);useContextRefresh(true,t('Refresh daily validation','รีเฟรชการตรวจสอบรายวัน'),()=>void load(cursors.current[page],page));
 return <section className="borrower-record"><header className="related-loans-heading"><HeaderBack className="icon-action" aria-label={t('Back','กลับ')} onClick={()=>selected?setSelected(null):onBack()}>←</HeaderBack><h2>{t('Daily Analytics Validation','ตรวจสอบข้อมูลรายวัน')}</h2></header>{error&&<p role="alert">{t('Data unavailable.','ไม่สามารถโหลดข้อมูล')} <button onClick={()=>void load()}>{t('Retry','ลองอีกครั้ง')}</button></p>}{selected?<dl>{Object.entries(selected).filter(([key])=>key!=='id').map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g,' $1').replace(/^./,v=>v.toUpperCase())}</dt><dd>{value==null?'—':key==='generatedAt'?displayTimestamp(String(value)):key==='date'||key==='cashAvailableFrom'?displayDate(String(value)):['modelVersion','loansIssued','repaymentsCount','activeLoansEod','activeBorrowersEod','cashBalanceStatus'].includes(key)?String(value):'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(value))}</dd></div>)}</dl>:<>{data?.items.map((row:any)=><button className="borrower-card" key={row.id} onClick={()=>setSelected(row)}><span>{displayDate(row.date)}</span><span>{row.cashBalanceStatus??'—'}</span></button>)}<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={data?.nextCursor?()=>void load(data.nextCursor,page+1):undefined} previousLabel={t('Previous page','หน้าก่อน')} nextLabel={t('Next page','หน้าถัดไป')}/></>}</section>;
}
