import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {CompactPager} from './CompactPager';
import {displayDate} from './display-date';
import {ManagementFinancialWorkspace} from './ManagementFinancialWorkspace';
export function ManagementPosition({access,thai,data,onInitialize}:{access:CommandAccess;thai:boolean;data:any;onInitialize:(id:string)=>void}){
 const t=(en:string,th:string)=>thai?th:en,money=(v:any)=>v==null?'—':'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(v));
 const [ledger,setLedger]=useState<any>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[page,setPage]=useState(0),generation=useRef(0),abort=useRef<AbortController|null>(null),cursors=useRef<(string|null)[]>([null]);
 async function load(cursor:string|null=null,index=0){if(access.offlineOnly)return;const epoch=++generation.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;const done=beginRequest(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(access.origin+'/api/management/cash-movements?limit=25'+(cursor?'&cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const value=await response.json();if(epoch===generation.current){setLedger(value);setPage(index);cursors.current[index]=cursor}}catch{if(epoch===generation.current)setError(true)}finally{clearTimeout(timer);done();if(epoch===generation.current)setBusy(false)}}
 useEffect(()=>{cursors.current=[null];void load();return()=>{generation.current++;abort.current?.abort()}},[data]);
 if(selected)return <ManagementFinancialWorkspace access={access} thai={thai} section="cash-movements" initialId={selected} onBack={()=>setSelected(null)}/>;
 const values=(row:any,account=false)=><dl>{[...(account?[['openingBalance','Opening Balance','ยอดยกมา']]:[]),['cashIn','Cash In','เงินเข้า'],['cashOut','Cash Out','เงินออก'],['currentBalance','Current Balance','ยอดคงเหลือ'],['businessCashHeld','Business Cash Held','เงินธุรกิจที่ถืออยู่'],['reimbursementDue','Reimbursement / Advance Due','ยอดคืนเงิน / เงินทดรอง']].map(([key,en,th])=><div key={key}><dt>{t(en,th)}</dt><dd>{money(row[key])}</dd></div>)}</dl>;
 return <section className="management-position"><article><h2>{t('Cash Holder Summary','สรุปผู้ถือเงิน')}</h2><div className="management-cards">{data.holders.map((row:any)=><article key={row.id}><h3>{row.label??t('Unavailable','ไม่พร้อมใช้งาน')}</h3>{values(row)}</article>)}</div></article><div className="management-chart-grid"><article className="management-chart"><h2>{t('Cash Ledger Recent','รายการเงินสดล่าสุด')}</h2>{error?<p role="alert">{t('Transactions unavailable.','ไม่สามารถโหลดรายการ')} <button onClick={()=>void load()}>{t('Retry','ลองอีกครั้ง')}</button></p>:ledger?.items.map((row:any)=><button className="borrower-card" key={row.id} onClick={()=>setSelected(row.id)}><span>{displayDate(row.date)}<small>{row.movementType}</small><small>{row.fromAccountLabel??'—'} → {row.toAccountLabel??'—'}</small></span><strong>{money(row.amount)}</strong></button>)}<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={ledger?.nextCursor?()=>void load(ledger.nextCursor,page+1):undefined} previousLabel={t('Previous transactions','รายการก่อนหน้า')} nextLabel={t('Next transactions','รายการถัดไป')}/></article><article className="management-chart"><h2>{t('Cash Account Summary','สรุปบัญชีเงินสด')}</h2>{data.accounts.map((row:any)=><article key={row.id}><h3>{row.holderLabel} · {row.label}</h3>{!row.initialized&&<button disabled={access.offlineOnly} onClick={()=>onInitialize(row.holderId)}>{t('Initialize holder accounts','กำหนดยอดยกมาบัญชีผู้ถือเงิน')}</button>}{values(row,true)}</article>)}</article></div></section>;
}
