import {RecordAction} from './RecordAction';
import {ManagementWorkspace} from './ManagementWorkspace';
import {ManagementFinancialForm} from './ManagementFinancialForm';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {CompactPager} from './CompactPager';
import {displayDate} from './display-date';
import {ManagementFinancialWorkspace} from './ManagementFinancialWorkspace';
export function ManagementPosition({access,thai,data,onInitialize,onRefresh}:{access:CommandAccess;thai:boolean;data:any;onInitialize:(id:string)=>void;onRefresh:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,money=(v:any)=>v==null?'—':'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(v));
 const [creating,setCreating]=useState(false),[account,setAccount]=useState<string|null>(null),[ledger,setLedger]=useState<any>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[page,setPage]=useState(0),generation=useRef(0),abort=useRef<AbortController|null>(null),cursors=useRef<(string|null)[]>([null]);
 async function load(cursor:string|null=null,index=0){if(access.offlineOnly)return;const epoch=++generation.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;const done=beginRequest(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(access.origin+'/api/management/cash-movements?limit=20'+(cursor?'&cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(epoch!==generation.current||controller.signal.aborted)return;if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const value=await response.json();if(epoch===generation.current){setLedger(value);setPage(index);cursors.current[index]=cursor}}catch{if(epoch===generation.current)setError(true)}finally{clearTimeout(timer);done();if(epoch===generation.current)setBusy(false)}}
 useEffect(()=>{void load(cursors.current[page],page);return()=>{generation.current++;abort.current?.abort()}},[data]);
 const changed=()=>{void load(cursors.current[page],page);onRefresh()};
 if(account)return <ManagementWorkspace access={access} thai={thai} section="cash-accounts" initialId={account} onBack={()=>setAccount(null)}/>;
 if(creating)return <ManagementFinancialForm access={access} thai={thai} kind="cash-movement" businessDate={data.businessDate} onBack={()=>setCreating(false)} onApplied={()=>{setCreating(false);changed()}}/>;
 if(selected)return <ManagementFinancialWorkspace access={access} thai={thai} section="cash-movements" initialId={selected} onBack={()=>setSelected(null)} onChanged={changed}/>;
 const columns=[['cashIn','Cash In','เงินเข้า'],['cashOut','Cash Out','เงินออก'],['currentBalance','Current Balance','ยอดคงเหลือ'],['businessCashHeld','Business Cash Held','เงินธุรกิจที่ถืออยู่'],['reimbursementDue','Reimbursement / Advance Due','ยอดคืนเงิน / เงินทดรอง']];
 const table=(rows:any[],accounts=false)=><div className="cash-table-scroll"><table><thead><tr><th>{accounts?t('Account / Holder','บัญชี / ผู้ถือเงิน'):t('Cash Holder','ผู้ถือเงิน')}</th>{accounts&&<th>{t('Opening Balance','ยอดยกมา')}</th>}{columns.map(([key,en,th])=><th key={key}>{t(en,th)}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{accounts?<><button className="record-field-link" onClick={()=>setAccount(row.id)}>{row.label??t('Unavailable','ไม่พร้อมใช้งาน')}</button><small>{row.holderLabel}</small>{!row.initialized&&<RecordAction icon="＋" disabled={access.offlineOnly} onClick={()=>onInitialize(row.holderId)}>{t('Initialize holder accounts','กำหนดยอดยกมาบัญชีผู้ถือเงิน')}</RecordAction>}</>:row.label??t('Unavailable','ไม่พร้อมใช้งาน')}</td>{accounts&&<td>{money(row.openingBalance)}</td>}{columns.map(([key])=><td key={key}>{money(row[key])}</td>)}</tr>)}</tbody></table></div>;
 return <section className="management-position"><header className="root-record-heading"><h2>{t('Cash Position','สถานะเงินสด')}</h2><RecordAction icon="＋" disabled={access.offlineOnly} onClick={()=>setCreating(true)}>{t('New cash movement','เพิ่มรายการเงินสด')}</RecordAction></header><article><h3>{t('Cash Holder Summary','สรุปผู้ถือเงิน')}</h3>{table(data.holders)}</article><article><h3>{t('Cash Account Summary','สรุปบัญชีเงินสด')}</h3>{table(data.accounts,true)}</article><article className="management-chart"><h3>{t('Cash Ledger Recent','รายการเงินสดล่าสุด')}</h3>{error?<p role="alert">{t('Transactions unavailable.','ไม่สามารถโหลดรายการ')} <button onClick={()=>void load(cursors.current[page],page)}>{t('Retry','ลองอีกครั้ง')}</button></p>:<div className="cash-table-scroll"><table><thead><tr><th>{t('Date','วันที่')}</th><th>{t('Transaction','รายการ')}</th><th>{t('From / To','จาก / ถึง')}</th><th>{t('Amount','จำนวนเงิน')}</th></tr></thead><tbody>{ledger?.items.map((row:any)=><tr key={row.id}><td>{displayDate(row.date)}</td><td><button className="record-field-link" onClick={()=>setSelected(row.id)}>{row.movementType}</button></td><td>{row.fromAccountLabel??'—'} → {row.toAccountLabel??'—'}</td><td>{money(row.amount)}</td></tr>)}</tbody></table></div>}<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={ledger?.nextCursor?()=>void load(ledger.nextCursor,page+1):undefined} previousLabel={t('Previous transactions','รายการก่อนหน้า')} nextLabel={t('Next transactions','รายการถัดไป')}/></article></section>;
}
