import {RecordAction} from './RecordAction';
import {ManagementWorkspace} from './ManagementWorkspace';
import {ManagementFinancialForm} from './ManagementFinancialForm';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {CompactPager} from './CompactPager';
import {displayDate,displayTimestamp} from './display-date';
import {ManagementFinancialWorkspace} from './ManagementFinancialWorkspace';
export function ManagementPosition({access,thai,data,onInitialize,onRefresh}:{access:CommandAccess;thai:boolean;data:any;onInitialize:(id:string)=>void;onRefresh:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,money=(v:any)=>v==null?'—':'฿'+new Intl.NumberFormat(thai?'th-TH':'en-GB',{maximumFractionDigits:0}).format(Number(v));
 const [expanded,setExpanded]=useState<Set<string>>(new Set()),[creating,setCreating]=useState(false),[account,setAccount]=useState<string|null>(null),[ledger,setLedger]=useState<any>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[page,setPage]=useState(0),generation=useRef(0),abort=useRef<AbortController|null>(null),cursors=useRef<(string|null)[]>([null]);
 async function load(cursor:string|null=null,index=0){if(access.offlineOnly)return;const epoch=++generation.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;const done=beginRequest(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(access.origin+'/api/management/cash-movements?limit=20'+(cursor?'&cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(epoch!==generation.current||controller.signal.aborted)return;if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const value=await response.json();if(epoch===generation.current){setLedger(value);setPage(index);cursors.current[index]=cursor}}catch{if(epoch===generation.current)setError(true)}finally{clearTimeout(timer);done();if(epoch===generation.current)setBusy(false)}}
 useEffect(()=>{void load(cursors.current[page],page);return()=>{generation.current++;abort.current?.abort()}},[data]);
 const changed=()=>{void load(cursors.current[page],page);onRefresh()};
 if(account)return <ManagementWorkspace access={access} thai={thai} section="cash-accounts" initialId={account} onBack={()=>setAccount(null)}/>;
 if(creating)return <ManagementFinancialForm access={access} thai={thai} kind="cash-movement" businessDate={data.businessDate} onBack={()=>setCreating(false)} onApplied={()=>{setCreating(false);changed()}}/>;
 if(selected)return <ManagementFinancialWorkspace access={access} thai={thai} section="cash-movements" initialId={selected} onBack={()=>setSelected(null)} onChanged={changed}/>;
 const columns=[['cashIn','Cash In','เงินเข้า'],['cashOut','Cash Out','เงินออก'],['currentBalance','Current Balance','ยอดคงเหลือ'],['businessCashHeld','Business Cash Held','เงินธุรกิจที่ถืออยู่'],['reimbursementDue','Reimbursement / Advance Due','ยอดคืนเงิน / เงินทดรอง']];
 const toggle=(id:string)=>setExpanded(previous=>{const next=new Set(previous);next.has(id)?next.delete(id):next.add(id);return next});
 const accountRow=(row:any)=><tr className="cash-position-account" key={'account:'+row.id}><td><button className="record-field-link" onClick={()=>setAccount(row.id)}>{row.label??t('Unavailable','ไม่พร้อมใช้งาน')}</button>{!row.initialized&&<RecordAction icon="＋" disabled={access.offlineOnly} onClick={()=>onInitialize(row.holderId)}>{t('Initialize holder accounts','กำหนดยอดยกมาบัญชีผู้ถือเงิน')}</RecordAction>}</td><td>{money(row.openingBalance)}</td>{columns.map(([key])=><td key={key}>{money(row[key])}</td>)}</tr>;
 const tree=<div className="cash-table-scroll"><table className="cash-position-tree"><thead><tr><th>{t('Cash Holder / Account','ผู้ถือเงิน / บัญชี')}</th><th>{t('Opening Balance','ยอดยกมา')}</th>{columns.map(([key,en,th])=><th key={key}>{t(en,th)}</th>)}</tr></thead><tbody>{data.holders.map((holder:any)=><React.Fragment key={holder.id}><tr className="cash-position-holder"><td><button className="cash-holder-toggle" aria-expanded={expanded.has(holder.id)} onClick={()=>toggle(holder.id)}><span aria-hidden="true">{expanded.has(holder.id)?'▾':'▸'}</span> {holder.label??t('Unavailable','ไม่พร้อมใช้งาน')}</button></td><td>—</td>{columns.map(([key])=><td key={key}>{money(holder[key])}</td>)}</tr>{expanded.has(holder.id)&&data.accounts.filter((row:any)=>row.holderId===holder.id).map(accountRow)}</React.Fragment>)}{data.accounts.filter((row:any)=>!data.holders.some((holder:any)=>holder.id===row.holderId)).map(accountRow)}</tbody></table></div>;
 const compactAccount=(row:any)=><div className="cash-mobile-account" key={row.id}><button className="record-field-link" onClick={()=>setAccount(row.id)}>{row.label??t('Unavailable','ไม่พร้อมใช้งาน')}</button><span>{money(row.currentBalance)}</span></div>;
 const compact=<div className="cash-mobile-position"><div className="cash-mobile-position-heading"><span>{t('Cash Holder / Account','ผู้ถือเงิน / บัญชี')}</span><span>{t('Current Balance','ยอดคงเหลือ')}</span></div>{data.holders.map((holder:any)=><React.Fragment key={holder.id}><button className="cash-mobile-holder" aria-expanded={expanded.has(holder.id)} onClick={()=>toggle(holder.id)}><span><span aria-hidden="true">{expanded.has(holder.id)?'▾':'▸'}</span> {holder.label??t('Unavailable','ไม่พร้อมใช้งาน')}</span><strong>{money(holder.currentBalance)}</strong></button>{expanded.has(holder.id)&&data.accounts.filter((row:any)=>row.holderId===holder.id).map(compactAccount)}</React.Fragment>)}{data.accounts.filter((row:any)=>!data.holders.some((holder:any)=>holder.id===row.holderId)).map(compactAccount)}<details className="cash-position-more"><summary>{t('All balance details','รายละเอียดยอดเงินทั้งหมด')}</summary><small>{t('Swipe to see all columns.','เลื่อนเพื่อดูทุกคอลัมน์')}</small>{tree}</details></div>;
 const recordedTime=(row:any)=>row.createdAt?displayTimestamp(row.createdAt).split(' ').at(-1):null;
 return <section className="management-position"><header className="root-record-heading"><h2>{t('Cash Position','สถานะเงินสด')}</h2><RecordAction icon="＋" disabled={access.offlineOnly} onClick={()=>setCreating(true)}>{t('New cash movement','เพิ่มรายการเงินสด')}</RecordAction></header><article><div className="cash-desktop-position">{tree}</div>{compact}</article><article className="management-chart"><h3>{t('Cash Ledger Recent','รายการเงินสดล่าสุด')}</h3>{error?<p role="alert">{t('Transactions unavailable.','ไม่สามารถโหลดรายการ')} <button onClick={()=>void load(cursors.current[page],page)}>{t('Retry','ลองอีกครั้ง')}</button></p>:<div className="cash-table-scroll cash-ledger-scroll"><table className="cash-ledger-table"><thead><tr><th>{t('Date','วันที่')}</th><th>{t('From / To','จาก / ถึง')}</th><th>{t('Amount','จำนวนเงิน')}</th></tr></thead><tbody>{ledger?.items.map((row:any)=><tr key={row.id} className="cash-ledger-row" tabIndex={0} role="button" aria-label={t('Open cash movement','เปิดรายการเงินสด')+' · '+displayDate(row.date)+' · '+money(row.amount)+' · '+(row.fromAccountLabel??'—')+' → '+(row.toAccountLabel??'—')} onClick={()=>setSelected(row.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(row.id)}}}><td>{displayDate(row.date)}{recordedTime(row)&&<span title={t('Recorded at ','บันทึกเมื่อ ')+displayTimestamp(row.createdAt)}> {recordedTime(row)}</span>}</td><td className="cash-ledger-counterparty" title={(row.fromAccountLabel??'—')+' → '+(row.toAccountLabel??'—')}><span>{row.fromAccountLabel??'—'}</span><span>→ {row.toAccountLabel??'—'}</span></td><td>{money(row.amount)}</td></tr>)}</tbody></table></div>}<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={ledger?.nextCursor?()=>void load(ledger.nextCursor,page+1):undefined} previousLabel={t('Previous transactions','รายการก่อนหน้า')} nextLabel={t('Next transactions','รายการถัดไป')}/></article></section>;
}
