import {HeaderBack} from './HeaderBack';
import React,{useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {useDomainDraft} from './domain-draft';
import {OperationConfirm} from './OperationConfirm';
import {ManagementReference} from './ManagementReference';
export type ManagementKind='cash-holder'|'cash-account'|'partner';
const definitions:Record<ManagementKind,[string,string,string,string,boolean?][]>={
 'cash-holder':[['holderName','Holder Name','ชื่อผู้ถือเงิน','text',true],['active','Active','ใช้งาน','checkbox'],['sortOrder','Sort Order','ลำดับ','number',true]],
 'cash-account':[['cashHolderId','Cash Holder','ผู้ถือเงิน','holder',true],['accountLabel','Account Label','ชื่อบัญชี','text',true],['bankName','Bank Name','ชื่อธนาคาร','text',true],['accountNumber','Account Number','เลขบัญชี','text'],['defaultAccount','Default Account','บัญชีเริ่มต้น','checkbox'],['active','Active','ใช้งาน','checkbox'],['sortOrder','Sort Order','ลำดับ','number',true],['alternativeAccountNumber','Alternative Account Number','เลขบัญชีทางเลือก','text']],
 partner:[['partnerName','Partner Name','ชื่อหุ้นส่วน','text',true],['partnerRole','Partner Role','บทบาทหุ้นส่วน','role',true],['email','Email','อีเมลแจ้งเตือน','email',true],['instagramUsername','Instagram Username','ชื่อผู้ใช้ Instagram','text'],['languagePreference','Language Preference','ภาษา','language'],['igIntegrationEnabled','IG Integration Enabled','เปิดใช้การเชื่อมต่อ IG','checkbox'],['loginEmail','Login Email','อีเมลเข้าสู่ระบบ','email'],['aiReviewer','AI Reviewer','ผู้ตรวจสอบ AI','checkbox']],
};
function sourceInputs(kind:ManagementKind,source:any){if(kind==='cash-holder')return {holderName:source?.label??'',active:source?.active??true,sortOrder:source?.sortOrder??1};if(kind==='cash-account')return {...(!source?{cashHolderId:''}:{}),accountLabel:source?.label??'',bankName:source?.bankName??'',accountNumber:source?.accountNumber??null,alternativeAccountNumber:source?.alternativeAccountNumber??null,defaultAccount:source?.isDefault??false,active:source?.active??true,sortOrder:source?.sortOrder??1};return {partnerName:source?.label??'',partnerRole:source?.partnerRole??'',loginEmail:source?.loginEmail??null,email:source?source.email:'welct0407@mw-credit.com',instagramUsername:source?.instagramUsername??null,languagePreference:source?.languagePreference??null,igIntegrationEnabled:source?.igIntegrationEnabled??null,aiReviewer:source?source.aiReviewer:false};}
export function ManagementForm({access,thai,kind,source,savedDraft,onBack,onApplied}:{access:CommandAccess;thai:boolean;kind:ManagementKind;source?:any;savedDraft?:any;onBack:()=>void;onApplied:()=>void}){
 const t=(en:string,th:string)=>thai?th:en,id=useRef(savedDraft?.id??source?.id??crypto.randomUUID()),original=useRef(savedDraft?.source??source??null),[inputs,setInputs]=useState<any>(savedDraft?.inputs??sourceInputs(kind,source)),[edited,setEdited]=useState(!!savedDraft),[command,setCommand]=useState<any>(null),[holderLabel,setHolderLabel]=useState<string|null>(savedDraft?.holderLabel??source?.holderLabel??null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const title=t(source?'Edit record':'New record',source?'แก้ไขรายการ':'เพิ่มรายการ');
 const draft=useDomainDraft({repository:access.offline,id:id.current,domain:'management',label:inputs.partnerName||inputs.accountLabel||inputs.holderName||title,value:{kind,id:id.current,source:original.current,inputs,holderLabel},enabled:edited&&!command,restore:value=>{if(value?.kind===kind&&value.id===id.current){original.current=value.source;setInputs(value.inputs);setHolderLabel(value.holderLabel??null);setEdited(true)}}});

 async function review(){if(busy||!draft.ready)return;setBusy(true);await draft.freeze();setBusy(false);setCommand({requestId:crypto.randomUUID(),operation:kind+(original.current?'.update':'.create'),targetId:id.current,expectedVersion:original.current?.version??null,predecessorRequestId:null,receiptId:null,inputs});}
 if(command)return <OperationConfirm access={access} command={command} domain="management" label={title} draftKey={draft.key} thai={thai} onBack={()=>{setCommand(null);draft.resume()}} onApplied={onApplied}>{kind==='partner'&&original.current?.loginEmail!==inputs.loginEmail&&<p role="alert">{t('Changing this sign-in email can remove access. Later requests require the current partner mapping.','การเปลี่ยนอีเมลเข้าสู่ระบบอาจทำให้ไม่สามารถเข้าถึงได้ คำขอถัดไปต้องตรงกับข้อมูลหุ้นส่วนปัจจุบัน')}</p>}<dl>{definitions[kind].filter(([key])=>key in inputs).map(([key,en,th])=><div key={key}><dt>{t(en,th)}</dt><dd>{key==='cashHolderId'?holderLabel??'—':typeof inputs[key]==='boolean'?inputs[key]?t('Yes','ใช่'):t('No','ไม่'):inputs[key]??'—'}</dd></div>)}</dl></OperationConfirm>;
 return <section className="borrower-record"><div className="related-loans-heading"><HeaderBack className="icon-action" aria-label={t('Back to details','กลับรายละเอียด')} onClick={onBack}>←</HeaderBack><h2>{title}</h2></div>{error&&<p role="alert">{error}</p>}{draft.error&&<p role="alert">{t('This draft is not saved. Keep the form open or free a saved-draft slot.','ร่างนี้ยังไม่ถูกบันทึก โปรดเปิดหน้านี้ไว้หรือเพิ่มพื้นที่สำหรับร่าง')}</p>}<form onSubmit={event=>{event.preventDefault();void review()}}>{definitions[kind].filter(([key])=>key in inputs).map(([key,en,th,type,required])=><label key={key}><span className="field-title">{t(en,th)}</span>{type==='holder'?<ManagementReference access={access} thai={thai} kind="cash-holders" value={inputs[key]||null} label={holderLabel} required={required} onChange={(value,label)=>{setEdited(true);setInputs({...inputs,[key]:value});setHolderLabel(label)}}/>:['role','language'].includes(type)?<select required={required} value={inputs[key]??''} onChange={event=>{setEdited(true);setInputs({...inputs,[key]:event.target.value||null})}}><option value="">—</option>{(type==='role'?[['A','A'],['B','B']]:[['English','English'],['ไทย','ไทย']]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input type={type} disabled={key==='igIntegrationEnabled'||key==='aiReviewer'} required={required} step={type==='number'?1:undefined} checked={type==='checkbox'?inputs[key]===true:undefined} value={type==='checkbox'?undefined:inputs[key]??''} onChange={event=>{setEdited(true);setInputs({...inputs,[key]:type==='checkbox'?event.target.checked:type==='number'?Number(event.target.value):event.target.value})}}/>}</label>)}<button disabled={busy||!draft.ready||access.offlineOnly||!navigator.onLine}>{t('Review change','ตรวจสอบการเปลี่ยนแปลง')}</button></form></section>;
}
