import React,{useEffect,useState} from 'react';
import {SelectedCharges,type CommandAccess} from './SelectedCharges';
export function OfflinePayments({access,thai}:{access:CommandAccess;thai:boolean}){
 const t=(en:string,th:string)=>thai?th:en;
 const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<string|null>(null),[locked,setLocked]=useState(true),[initializing,setInitializing]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const saved=()=>setRevision(value=>value+1),failed=()=>setError(t('The unsent draft could not be saved. Storage is unavailable or full.','บันทึกร่างที่ยังไม่ส่งไม่ได้ พื้นที่จัดเก็บใช้ไม่ได้หรือเต็ม'));window.addEventListener('mw-offline-saved',saved);window.addEventListener('mw-offline-save-failed',failed);return()=>{window.removeEventListener('mw-offline-saved',saved);window.removeEventListener('mw-offline-save-failed',failed)}},[]);
 useEffect(()=>{let active=true;setInitializing(true);setLocked(true);void(async()=>{try{if(!await access.offline?.authorized())return;const snapshots=await access.offline!.list('snapshot'),drafts=await access.offline!.list('draft'),pending=await access.offline!.list('pending');if(active){setLocked(false);const merged=new Map<string,any>();for(const row of snapshots)merged.set(row.value.borrower.id,{id:row.value.borrower.id,label:row.value.borrower.displayName,savedAt:row.savedAt});for(const row of drafts){const id=row.key.slice('draft:'.length);if(!merged.has(id))merged.set(id,{id,label:t('Saved draft','ร่างที่บันทึกไว้'),savedAt:row.savedAt})}for(const row of pending){const id=row.value.borrowerId;if(!merged.has(id))merged.set(id,{id,label:t('Pending payment','คำขอรับชำระที่ยังไม่ทราบผล'),savedAt:row.savedAt})}setRows([...merged.values()]);}}catch{if(active)setError(t('Offline storage is unavailable.','พื้นที่จัดเก็บออฟไลน์ใช้ไม่ได้'));}finally{if(active)setInitializing(false)}})();return()=>{active=false}},[access.offline,revision]);
 if(initializing)return <p role="status">{t('Checking saved workspace access…','กำลังตรวจสอบสิทธิ์เปิดข้อมูลที่บันทึกไว้…')}</p>;
 if(locked)return <p>{t('Connect to verify this account before accessing saved records.','เชื่อมต่อเพื่อตรวจสอบบัญชีก่อนเปิดข้อมูลที่บันทึกไว้')}{error}</p>;
 if(selected)return <SelectedCharges access={access} borrowerId={selected} thai={thai} onBack={()=>setSelected(null)}/>;
 return <section aria-label={t('Saved offline payment drafts','ร่างรับชำระที่บันทึกออฟไลน์')}><p role="alert">{error}</p><h3>{t('Saved on this device — may be outdated','ข้อมูลที่บันทึกบนอุปกรณ์นี้ — อาจไม่เป็นปัจจุบัน')}</h3>{rows.map(row=><button className="secondary-button" key={row.id} onClick={()=>setSelected(row.id)}>{row.label} · {new Date(row.savedAt).toLocaleString()}</button>)}{!rows.length&&<p>{t('No saved payment views or drafts.','ไม่มีข้อมูลรับชำระหรือร่างที่บันทึกไว้')}</p>}</section>;
}
