import {PaymentRecord} from './PaymentRecord';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {PaymentResult} from './PaymentResult';
import {CompactPager} from './CompactPager';
import {beginRequest} from './request-activity';
export function PaymentHistory({access,borrowerId,thai,compact=false}:{access:CommandAccess;borrowerId:string;thai:boolean;compact?:boolean}){
 const t=(en:string,th:string)=>thai?th:en;
 const [open,setOpen]=useState(false),[items,setItems]=useState<any[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(0),[detail,setDetail]=useState<string|null>(null);
 const generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]);
 useEffect(()=>{generation.current++;setOpen(false);setItems([]);setCursor(null);setDetail(null);cursors.current=[undefined];return()=>{generation.current++}},[borrowerId]);
 async function load(next?:string,index=0){const current=++generation.current;setOpen(true);setBusy(true);setError('');const done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(access.origin+'/api/borrowers/'+encodeURIComponent(borrowerId)+'/payments'+(next?'?cursor='+encodeURIComponent(next):''),{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const result=await response.json();if(current===generation.current){if(index===0)cursors.current=[undefined];cursors.current[index]=next;setPage(index);setItems(result.items);setCursor(result.nextCursor)}}catch{if(current===generation.current)setError(t('Payment history unavailable.','ประวัติรับชำระใช้ไม่ได้'));}finally{done();clearTimeout(timer);if(current===generation.current)setBusy(false)}}
 return <><button className={compact?"secondary-button icon-action":"secondary-button"} aria-label={t('Payment history','ประวัติรับชำระ')} title={t('Payment history','ประวัติรับชำระ')} disabled={busy} onClick={()=>{setDetail(null);void load()}}>{compact?<svg aria-hidden="true" viewBox="0 0 24 24"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Zm3 5h6m-6 4h6m-6 4h4"/></svg>:t('Payment history','ประวัติรับชำระ')}</button>{error&&<p role="status">{error}</p>}{detail?<div className="payment-history-panel"><button className="secondary-button" onClick={()=>setDetail(null)}>{t('Back to payment history','กลับประวัติรับชำระ')}</button>{access.ownerTesting?<PaymentRecord access={access} id={detail} thai={thai} onBack={()=>{setDetail(null);void load(cursors.current[page],page)}}/>:<PaymentResult access={access} requestId={detail} thai={thai}/>}</div>:open&&<div className="payment-history-panel">{items.map(row=><article className="collection-charge" key={row.id}><strong>{row.paymentDate??'—'} · {row.status}</strong><p>{new Intl.NumberFormat(thai?'th-TH':'en-US',{style:'currency',currency:'THB',currencyDisplay:'narrowSymbol',maximumFractionDigits:2}).format(Number(row.amountReceived))} · {row.accountLabel??'—'}</p><pre>{row.notes}</pre>{row.receiptReference&&<p>{t('Manual receipt attached','มีหลักฐานที่อัปโหลดเอง')}</p>}{(access.ownerTesting||row.requestId)&&<button className="text-action" onClick={()=>setDetail(access.ownerTesting?row.id:row.requestId)}>{t('Payment details','รายละเอียดรับชำระ')}</button>}</article>)}<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={cursor?()=>void load(cursor,page+1):undefined} previousLabel={t('Previous payment history page','ประวัติรับชำระหน้าก่อน')} nextLabel={t('Next payment history page','ประวัติรับชำระหน้าถัดไป')}/></div>}</>;
}
