import React,{useEffect,useRef} from 'react';import type {CommandAccess} from './SelectedCharges';import {beginRequest} from './request-activity';import {CompactPager} from './CompactPager';import {displayDate} from './display-date';
export type PaymentTree=Record<string,{open:boolean;items:any[];next:string|null;page:number;cursors:(string|undefined)[];busy:boolean;error:boolean}>;
function Group({access,query,borrower,month,epoch,tree,setTree,onOpen,thai,hideBorrowerHeading=false}:{access:CommandAccess;query:string;borrower:any;month?:any;epoch:number;tree:PaymentTree;setTree:React.Dispatch<React.SetStateAction<PaymentTree>>;onOpen:(id:string)=>void;thai:boolean;hideBorrowerHeading?:boolean}){
 const t=(en:string,th:string)=>thai?th:en,key=JSON.stringify([borrower.borrowerId,month===undefined?'months':['payments',month.month]]),state=tree[key]??{open:false,items:[],next:null,page:0,cursors:[undefined],busy:false,error:false},generation=useRef(0);
 const patch=(change:any)=>setTree(previous=>({...previous,[key]:{...(previous[key]??state),...change}}));
 async function load(cursor?:string,index=0){const current=++generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);patch({busy:true,error:false});try{const params=new URLSearchParams({q:query,limit:'25'});if(borrower.borrowerId===null)params.set('unassigned','true');else params.set('borrowerId',borrower.borrowerId);if(month!==undefined)params.set('month',month.month??'undated');if(cursor)params.set('cursor',cursor);const response=await fetch(access.origin+'/api/payment-records?'+params,{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const data=await response.json();if(current!==generation.current)return;if(!data.items.length&&index>0){void load(state.cursors[index-1],index-1);return;}const cursors=index===0?[undefined]:[...state.cursors];cursors[index]=cursor;patch({items:data.items,next:data.nextCursor,page:index,cursors,busy:false})}catch{if(current===generation.current)patch({error:true,items:[],next:null,busy:false})}finally{clearTimeout(timer);done()}}
 useEffect(()=>{if(state.open)void load(state.cursors[state.page],state.page);return()=>{generation.current++}},[epoch,state.open,query]);
 const money=(value:any)=>value==null?'—':'฿'+new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(value));
 return <details className={month===undefined?'payment-borrower-group':'payment-month-group'} open={state.open} onToggle={event=>{event.stopPropagation();if(event.currentTarget.open!==state.open)patch({open:event.currentTarget.open})}}><summary hidden={hideBorrowerHeading&&month===undefined}>{month===undefined?borrower.borrowerDisplayName:<><span>{month.month??'—'}</span><span>{t('Amount Received','ยอดรับชำระ')} {money(month.amountReceived)}</span></>}</summary>{state.open&&<>{state.error&&<p role="alert">{t('Payments unavailable.','โหลดรายการรับชำระไม่ได้')}<button onClick={()=>void load(state.cursors[state.page],state.page)}>{t('Retry payments','ลองโหลดรายการรับชำระอีกครั้ง')}</button></p>}{month===undefined?state.items.map(row=><Group key={row.month??'undated'} {...{access,query,borrower,epoch,tree,setTree,onOpen,thai}} month={row}/>):state.items.map(row=><button className="borrower-card payment-compact-row" key={row.id} disabled={state.busy} aria-label={displayDate(row.paymentDate)+' · '+(row.accountLabel??'—')+' · '+money(row.amountReceived)+' · '+(row.status??t('Unavailable','ไม่มีข้อมูล'))} title={row.status??t('Unavailable','ไม่มีข้อมูล')} onClick={()=>onOpen(row.id)}><span className="payment-date-account"><time>{displayDate(row.paymentDate)}</time><span>{row.accountLabel??'—'}</span></span><strong className={'payment-status-'+(row.status==='Posted'?'posted':row.status==='Error'?'error':row.status==='Processing'?'processing':'unknown')}><span aria-hidden="true" className="payment-status-symbol">{row.status==='Posted'?'✓':row.status==='Error'?'!':row.status==='Processing'?'◷':'?'}</span>{money(row.amountReceived)}</strong></button>)}<CompactPager busy={state.busy} previous={state.page>0?()=>void load(state.cursors[state.page-1],state.page-1):undefined} next={state.next?()=>void load(state.next!,state.page+1):undefined} previousLabel={month===undefined?t('Previous payment months','เดือนรับชำระก่อนหน้า'):t('Previous payments in month','รายการรับชำระก่อนหน้าในเดือน')} nextLabel={month===undefined?t('Next payment months','เดือนรับชำระถัดไป'):t('Next payments in month','รายการรับชำระถัดไปในเดือน')}/></>}</details>;
}
export function PaymentGroups(props:{access:CommandAccess;query:string;items:any[];epoch:number;tree:PaymentTree;setTree:React.Dispatch<React.SetStateAction<PaymentTree>>;onOpen:(id:string)=>void;thai:boolean;hideBorrowerHeading?:boolean}){return <><p className="list-meaning-legend">{props.thai?'✓ ลงบัญชีแล้ว · ◷ กำลังดำเนินการ · ! ผิดพลาด · ? ไม่มีข้อมูล':'✓ Posted · ◷ Processing · ! Error · ? Unavailable'}</p>{props.items.map(row=><Group key={JSON.stringify(row.borrowerId)} {...props} borrower={row}/>)}</>}
