import React,{useEffect,useRef,useState} from 'react';
import {BorrowerRecord} from './BorrowerRecord';import {BorrowerPayments} from './BorrowerPayments';import {LoanRecords,type LoanRecord as LoanRow} from './LoanRecords';import {LoanRecord} from './LoanRecord';import {LoanForm} from './LoanForm';import {beginRequest} from './request-activity';import {useContextRefresh} from './context-refresh';import type {CommandAccess} from './SelectedCharges';
export function SharedBorrowerDetail({access,id,label,thai,onBack,onSaved}:{access:CommandAccess;id:string;label?:string;thai:boolean;onBack:()=>void;onSaved?:(id:string|null)=>void}){
 const [history,setHistory]=useState(false),[newLoan,setNewLoan]=useState(false),[loan,setLoan]=useState<string|null>(null),[version,setVersion]=useState(0),[items,setItems]=useState<LoanRow[]>([]),[next,setNext]=useState<string|null>(null),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(false),generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]);
 async function load(cursor?:string,index=0){if(access.offlineOnly||!navigator.onLine){setError(true);setBusy(false);return;}const current=++generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(import.meta.env.VITE_API_ORIGIN+'/api/borrowers/'+encodeURIComponent(id)+'/loans?limit=25'+(cursor?'&cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const data=await response.json();if(current!==generation.current)return;if(index===0)cursors.current=[undefined];cursors.current[index]=cursor;setPage(index);setItems(data.items);setNext(data.nextCursor)}catch{if(current===generation.current)setError(true)}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}}
 useEffect(()=>{void load();return()=>{generation.current++}},[id]);useContextRefresh(!history&&!newLoan&&!loan,thai?'โหลดสินเชื่อที่เกี่ยวข้อง':'Refresh related loans',()=>void load());
 if(loan)return <LoanRecord access={access} id={loan} thai={thai} onBack={()=>{setLoan(null);void load(cursors.current[page],page)}}/>;
 if(newLoan)return <LoanForm access={access} borrowerId={id} borrowerLabel={label??items[0]?.borrowerDisplayName??''} thai={thai} onBack={()=>setNewLoan(false)} onSaved={value=>{setNewLoan(false);setLoan(value)}}/>;
 if(history)return <BorrowerPayments access={access} borrowerId={id} label={label??items[0]?.borrowerDisplayName??(thai?'ผู้กู้':'Borrower')} thai={thai} onBack={()=>setHistory(false)}/>;
 return <BorrowerRecord key={id+':'+version} access={access} id={id} displayName={label} thai={thai} onBack={onBack} onNewLoan={()=>setNewLoan(true)} onHistory={()=>setHistory(true)} onSaved={value=>{onSaved?.(value);if(value){setVersion(old=>old+1);void load()}else onBack()}} related={<LoanRecords thai={thai} page={page+1} items={items} selected={null} busy={busy} loading={busy} error={error?{code:'unavailable'}:null} nextCursor={next} listAsOf="" detailAsOf="" onSelect={setLoan} onBack={()=>{}} onRefresh={()=>void load(cursors.current[page],page)} onPrevious={page>0?()=>void load(cursors.current[page-1],page-1):undefined} onNext={()=>{if(next)void load(next,page+1)}}/>}/>;
}
