import {HeaderBack} from './HeaderBack';
import {displayDate,displayTimestamp} from './display-date';
import {wholeBaht} from './display-money';
import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {useContextRefresh} from './context-refresh';
import {CompactPager} from './CompactPager';
import {LoanRecord} from './LoanRecord';
export function StandaloneUpcoming({access,thai}:{access:CommandAccess;thai:boolean}){
 const t=(en:string,th:string)=>thai?th:en,[data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[event,setEvent]=useState<any>(null),[loan,setLoan]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[page,setPage]=useState(0),generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]),flight=useRef<AbortController|null>(null),root=useRef<any>(null);
 function cancel(){generation.current++;flight.current?.abort();flight.current=null}
 async function load(scope:any=selected,cursor?:string,index=0){cancel();const current=generation.current,done=beginRequest(),controller=new AbortController();flight.current=controller;const timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const path=scope?'/api/upcoming-charges/'+encodeURIComponent(scope.borrowerId)+'/'+scope.dueDate:'/api/upcoming-charges',query=new URLSearchParams({limit:'25'});if(scope)query.set('businessDate',scope.businessDate);if(cursor)query.set('cursor',cursor);
 const value=await Promise.race([(async()=>{const response=await fetch(access.origin+path+'?'+query,{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();return response.json()})(),new Promise<never>((_,reject)=>controller.signal.addEventListener('abort',()=>reject(Error('Cancelled')),{once:true}))]);
 if(current!==generation.current)return;if(index===0)cursors.current=[undefined];cursors.current[index]=cursor;setPage(index);setData(value);if(!scope)root.current={data:value,page:index,cursors:[...cursors.current]};}catch{if(current===generation.current)setError(true)}finally{clearTimeout(timer);done();if(current===generation.current){flight.current=null;setBusy(false)}}}
 function open(row:any){const scope={...row,businessDate:data.businessDate};setSelected(scope);setData(null);void load(scope)}
 function back(){cancel();setSelected(null);setError(false);setBusy(false);if(root.current){setData(root.current.data);setPage(root.current.page);cursors.current=[...root.current.cursors]}else{setData(null);void load(null)}}
 useEffect(()=>{void load(null);return cancel},[]);useContextRefresh(!loan&&!event,t('Refresh Upcoming Charges','รีเฟรชรายการเรียกเก็บล่วงหน้า'),()=>void load(selected));
 if(loan)return <LoanRecord access={access} id={loan} thai={thai} onBack={()=>setLoan(null)}/>;
 if(event)return <section className="borrower-record upcoming-event"><div className="related-loans-heading"><HeaderBack className="icon-action" aria-label={t('Back to upcoming date','กลับรายการในวันที่เลือก')} onClick={()=>setEvent(null)}>←</HeaderBack><h2>{selected?.label??data?.borrowerLabel}</h2></div><dl>{[[t('Charge Date','วันที่เรียกเก็บ'),displayDate(selected?.dueDate)],[t('Principal Remaining','เงินต้นคงเหลือ'),wholeBaht(event.principal)],[t('Interest Remaining','ดอกเบี้ยคงเหลือ'),wholeBaht(event.interest)],[t('Amount Remaining','ยอดคงเหลือ'),wholeBaht(event.amount)],[t('Basis','ที่มา'),event.basis]].map(([label,value])=><React.Fragment key={label}><dt>{label}</dt><dd>{value??'—'}</dd></React.Fragment>)}</dl>{event.loanId&&<button className="text-action" onClick={()=>setLoan(event.loanId)}>{t('Loan details','รายละเอียดสินเชื่อ')} · {displayDate(event.loanDate)} · {wholeBaht(event.loanPrincipal)}</button>}</section>;
 return <section className="borrower-record upcoming-directory" aria-label={t('Upcoming Charges','รายการเรียกเก็บล่วงหน้า')}>{selected&&<div className="related-loans-heading"><HeaderBack className="icon-action" aria-label={t('Back to Upcoming Charges','กลับรายการเรียกเก็บล่วงหน้า')} onClick={back}>←</HeaderBack><h2>{selected.label||t('Unnamed borrower','ไม่ระบุชื่อผู้กู้')}</h2></div>}{error&&<p role="alert">{t('Upcoming charges unavailable. Refresh for the current day.','ไม่สามารถโหลดรายการล่วงหน้า โปรดรีเฟรชข้อมูลวันปัจจุบัน')}<button onClick={()=>void load(selected,cursors.current[page],page)}>{t('Retry Upcoming Charges','ลองโหลดรายการล่วงหน้าอีกครั้ง')}</button></p>}{data&&<>{selected&&<h3>{displayDate(data.dueDate)} · {wholeBaht(data.totalCharge)}</h3>}{data.items.map((row:any,index:number)=>selected?<button className="borrower-card upcoming-row" key={row.id} disabled={busy||!row.loanId} onClick={()=>{cancel();setBusy(false);setEvent(row)}}><span>{displayDate(row.loanDate)} · {row.loanType}<small>{wholeBaht(row.loanPrincipal)} · {row.basis}</small></span><strong>{wholeBaht(row.amount)}</strong></button>:<React.Fragment key={row.id}>{(index===0||data.items[index-1].dueDate!==row.dueDate)&&<h3>{displayDate(row.dueDate)} · {wholeBaht(data.dateTotals.find((total:any)=>total.date===row.dueDate)?.amount)}</h3>}<button className="borrower-card upcoming-row" disabled={busy} onClick={()=>open(row)}><span>{row.label||t('Unnamed borrower','ไม่ระบุชื่อผู้กู้')}</span><strong>{wholeBaht(row.totalCharge)}</strong></button></React.Fragment>)}{!data.items.length&&!busy&&<p>{t('No upcoming charges.','ไม่มีรายการเรียกเก็บล่วงหน้า')}</p>}<CompactPager busy={busy} previous={page>0?()=>void load(selected,cursors.current[page-1],page-1):undefined} next={data.nextCursor?()=>void load(selected,data.nextCursor,page+1):undefined} previousLabel={t('Previous upcoming page','รายการล่วงหน้าหน้าก่อน')} nextLabel={t('Next upcoming page','รายการล่วงหน้าถัดไป')}/></>}</section>;
}
