import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {SelectedCharges} from './SelectedCharges';
import {LoanRecord} from './LoanRecord';import {PaymentRecord} from './PaymentRecord';import {LoanForm} from './LoanForm';
import {loanDisplayKey} from './LoanRecords';import {CompactPager} from './CompactPager';import {beginRequest} from './request-activity';import {useContextRefresh} from './context-refresh';
export function StandaloneRecords({access,kind,query,thai}:{access:CommandAccess;kind:'loans'|'payments';query:string;thai:boolean}){
 const t=(en:string,th:string)=>thai?th:en,[items,setItems]=useState<any[]>([]),[next,setNext]=useState<string|null>(null),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(false),[selected,setSelected]=useState<string|null>(null),[adding,setAdding]=useState(false),[borrower,setBorrower]=useState<any>(null),[options,setOptions]=useState<any[]>([]),[lookup,setLookup]=useState(''),generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]),panel=useRef<HTMLElement|null>(null),scroll=useRef({window:0,panel:0});
 const endpoint=kind==='loans'?'loan-records':'payment-records';
 async function load(cursor?:string,index=0,restore=false){const current=++generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const response=await fetch(access.origin+'/api/'+endpoint+'?limit=25&q='+encodeURIComponent(query)+(cursor?'&cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const data=await response.json();if(current!==generation.current)return;if(!data.items.length&&index>0){void load(cursors.current[index-1],index-1,restore);return;}if(index===0)cursors.current=[undefined];cursors.current[index]=cursor;setPage(index);setItems(data.items);setNext(data.nextCursor);requestAnimationFrame(()=>{if(current===generation.current){window.scrollTo(0,restore?scroll.current.window:0);if(panel.current)panel.current.scrollTop=restore?scroll.current.panel:0}})}catch{if(current===generation.current){setItems([]);setNext(null);setError(true)}}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}}
 useEffect(()=>{setSelected(null);setAdding(false);setBorrower(null);void load();return()=>{generation.current++}},[kind,query]);
 useEffect(()=>{if(!adding||borrower)return;let active=true;const controller=new AbortController();const timer=setTimeout(()=>{const done=beginRequest(),timeout=setTimeout(()=>controller.abort(),15000);void(async()=>{try{const r=await fetch(access.origin+'/api/borrower-options?q='+encodeURIComponent(lookup.trim()),{signal:controller.signal,headers:{Authorization:'Bearer '+await access.token()},cache:'no-store',credentials:'omit',redirect:'error'});if(r.status===401||r.status===403)access.authFailure(r.status);if(!r.ok)throw Error();const data=await r.json();if(active)setOptions((data.referrers??[]).map((row:any)=>({...row,label:(row.label??'')+' - '+(row.description??'')})))}catch{if(active)setOptions([])}finally{clearTimeout(timeout);done()}})()},250);return()=>{active=false;clearTimeout(timer);controller.abort()}},[adding,borrower,lookup]);
 useContextRefresh(!selected&&!adding,kind==='loans'?t('First loans page / refresh','หน้าแรกของสินเชื่อ / รีเฟรช'):t('First payments page / refresh','หน้าแรกของการรับชำระ / รีเฟรช'),()=>void load());
 const back=()=>{setSelected(null);setAdding(false);setBorrower(null);void load(cursors.current[page],page,true)};
 if(selected)return kind==='loans'?<LoanRecord access={access} id={selected} thai={thai} onBack={back}/>:<PaymentRecord access={access} id={selected} thai={thai} onBack={back}/>;
 if(adding&&borrower)return kind==='loans'?<LoanForm access={access} borrowerId={borrower.id} borrowerLabel={borrower.label} thai={thai} onBack={()=>setBorrower(null)} onSaved={id=>{setAdding(false);setBorrower(null);setSelected(id)}}/>:<SelectedCharges access={access} borrowerId={borrower.id} thai={thai} onBack={back}/>;
 const money=(value:string|null)=>value===null?'—':new Intl.NumberFormat(thai?'th-TH':'en-US',{style:'currency',currency:'THB',currencyDisplay:'narrowSymbol',maximumFractionDigits:2}).format(Number(value));
 if(adding)return <section><div className="related-loans-heading"><button className="icon-action" aria-label={t('Back to records','กลับรายการ')} onClick={back}>←</button><h2>{t('Choose borrower','เลือกผู้กู้')}</h2></div><label>{t('Search borrowers','ค้นหาผู้กู้')}<input value={lookup} maxLength={100} onChange={e=>setLookup(e.target.value)}/></label>{options.map(row=><button className="borrower-card" key={row.id} onClick={()=>setBorrower(row)}>{row.label}</button>)}</section>;
 return <section className="standalone-records" ref={panel} aria-label={kind==='loans'?t('Loans list','รายการสินเชื่อ'):t('Payments list','รายการรับชำระ')}><div className="related-loans-heading"><h2>{kind==='loans'?t('Loans','สินเชื่อ'):t('Payments','การรับชำระ')}</h2><button className="icon-action" aria-label={kind==='loans'?t('Add loan','เพิ่มสินเชื่อ'):t('Receive payment','รับชำระ')} disabled={busy||access.offlineOnly||!navigator.onLine} onClick={()=>{scroll.current={window:window.scrollY,panel:panel.current?.scrollTop??0};setAdding(true)}}>+</button></div>{error&&<p role="alert">{t('Records unavailable.','ไม่สามารถโหลดรายการ')}<button onClick={()=>void load(cursors.current[page],page)}>{t('Retry records','ลองโหลดรายการอีกครั้ง')}</button></p>}{items.map((row,index)=>{const prior=items[index-1];return <React.Fragment key={row.id}>{(!prior||(kind==='loans'?prior.rank!==row.rank:false))&&kind==='loans'&&<h3 className="record-group-heading">{row.rank===0?t('Active loans','สินเชื่อที่ยังไม่ปิด'):row.rank===1?t('Closed loans','สินเชื่อที่ปิดแล้ว'):t('Status unavailable','ไม่มีข้อมูลสถานะ')}</h3>}{(!prior||prior.borrowerId!==row.borrowerId||(kind==='loans'?prior.rank!==row.rank:prior.month!==row.month))&&<h3 className="record-group-heading">{row.borrowerDisplayName}{kind==='payments'&&<> · {row.month??'—'}<span> · {t('Amount Received','ยอดรับชำระ')} {money(row.groupAmountReceived)}</span></>}</h3>}<button className={'borrower-card '+(kind==='loans'&&row.rank===1?'inactive':'')} disabled={busy} onClick={()=>{scroll.current={window:window.scrollY,panel:panel.current?.scrollTop??0};setSelected(row.id)}}><span className="person"><strong>{kind==='loans'?loanDisplayKey(row):row.paymentDate??'—'}</strong><span>{row.status??t('Unavailable','ไม่มีข้อมูล')}</span></span><span className="card-amount">{kind==='loans'?<><strong>{money(row.totalInterestReceived)}</strong><span>{t('Total Interest Received','ดอกเบี้ยรับรวม')}</span><strong>{row.principalRecoveredByInterestRatio===null?'—':new Intl.NumberFormat(thai?'th-TH':'en-US',{style:'percent',maximumFractionDigits:0}).format(Number(row.principalRecoveredByInterestRatio))}</strong></>:<><strong>{money(row.amountReceived)}</strong><span>{t('Posted','บันทึกยอดแล้ว')}: {money(row.postedAmount)}</span></>}</span></button></React.Fragment>})}{!items.length&&!busy&&!error&&<p>{t('No matching records.','ไม่พบรายการที่ตรงกัน')}</p>}<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={next?()=>void load(next,page+1):undefined} previousLabel={kind==='loans'?t('Previous loans page','สินเชื่อหน้าก่อน'):t('Previous payments page','การรับชำระหน้าก่อน')} nextLabel={kind==='loans'?t('Next loans page','สินเชื่อหน้าถัดไป'):t('Next payments page','การรับชำระหน้าถัดไป')}/></section>;
}
