import React,{useEffect,useRef,useState} from 'react';
import type {CommandAccess} from './SelectedCharges';
import {beginRequest} from './request-activity';
import {useContextRefresh} from './context-refresh';
import {CompactPager} from './CompactPager';
export function StandaloneUpcoming({access,thai}:{access:CommandAccess;thai:boolean}){
 const t=(en:string,th:string)=>thai?th:en,[data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[page,setPage]=useState(0),generation=useRef(0),cursors=useRef<(string|undefined)[]>([undefined]);
 async function load(cursor?:string,index=0){const current=++generation.current,done=beginRequest(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);setBusy(true);setError(false);try{const path=selected?'/api/upcoming-charges/'+encodeURIComponent(selected.borrowerId)+'/'+selected.dueDate:'/api/upcoming-charges',query=new URLSearchParams({limit:'25'});if(selected)query.set('businessDate',selected.businessDate);if(cursor)query.set('cursor',cursor);const response=await fetch(access.origin+path+'?'+query,{headers:{Authorization:'Bearer '+await access.token()},signal:controller.signal,cache:'no-store',credentials:'omit',redirect:'error'});if(response.status===401||response.status===403)access.authFailure(response.status);if(!response.ok)throw Error();const value=await response.json();if(current!==generation.current)return;if(index===0)cursors.current=[undefined];cursors.current[index]=cursor;setPage(index);setData(value)}catch{if(current===generation.current)setError(true)}finally{clearTimeout(timer);done();if(current===generation.current)setBusy(false)}}
 useEffect(()=>{setData(null);void load();return()=>{generation.current++}},[selected]);useContextRefresh(true,t('Refresh Upcoming Charges','รีเฟรชรายการเรียกเก็บล่วงหน้า'),()=>void load());
 return <section className="borrower-record" aria-label={t('Upcoming Charges','รายการเรียกเก็บล่วงหน้า')}>{selected&&<div className="record-context"><button className="icon-button" aria-label={t('Back to Upcoming Charges','กลับรายการเรียกเก็บล่วงหน้า')} onClick={()=>setSelected(null)}>←</button><strong>{selected.label||t('Unnamed borrower','ไม่ระบุชื่อผู้กู้')}</strong></div>}{error&&<p role="alert">{t('Upcoming charges unavailable. Refresh for the current day.','ไม่สามารถโหลดรายการล่วงหน้า โปรดรีเฟรชข้อมูลวันปัจจุบัน')}<button onClick={()=>void load(cursors.current[page],page)}>{t('Retry Upcoming Charges','ลองโหลดรายการล่วงหน้าอีกครั้ง')}</button></p>}{data&&<>{selected&&<h3>{data.dueDate} · ฿{data.totalCharge??t('Unavailable','ไม่มีข้อมูล')}</h3>}{data.items.map((row:any,index:number)=>selected?<div className="borrower-card" key={row.id}><span>{row.loanDate} · {row.loanType} · ฿{row.loanPrincipal}</span><strong>฿{row.amount??t('Unavailable','ไม่มีข้อมูล')}</strong><span>{row.basis}</span></div>:<React.Fragment key={row.id}>{(index===0||data.items[index-1].dueDate!==row.dueDate)&&<h3>{row.dueDate} · ฿{data.dateTotals.find((total:any)=>total.date===row.dueDate)?.amount??t('Unavailable','ไม่มีข้อมูล')}</h3>}<button className="borrower-card" disabled={busy} onClick={()=>setSelected({...row,businessDate:data.businessDate})}><span>{row.label||t('Unnamed borrower','ไม่ระบุชื่อผู้กู้')}</span><strong>฿{row.totalCharge??t('Unavailable','ไม่มีข้อมูล')}</strong></button></React.Fragment>)}{!data.items.length&&!busy&&<p>{t('No upcoming charges.','ไม่มีรายการเรียกเก็บล่วงหน้า')}</p>}<CompactPager busy={busy} previous={page>0?()=>void load(cursors.current[page-1],page-1):undefined} next={data.nextCursor?()=>void load(data.nextCursor,page+1):undefined} previousLabel={t('Previous upcoming page','รายการล่วงหน้าหน้าก่อน')} nextLabel={t('Next upcoming page','รายการล่วงหน้าถัดไป')}/>{data.forecastNote&&<p>{data.forecastNote}</p>}<small>{new Date(data.asOf).toLocaleString(thai?'th-TH':'en')}</small></>}</section>;
}
