import React from 'react';
export type UpcomingSummary = { ok: true; source: 'dev'; businessDate: string; asOf: string; horizonEnd: string; reviewRequired: boolean; previews?: UpcomingDetail[]; items: { id: string; dueDate: string; totalCharge: string | null }[] };
export type UpcomingDetail = Omit<UpcomingSummary, 'items' | 'previews'> & { dueDate: string; totalCharge: string | null; nextCursor: string | null; items: { id: string; loanId: string; loanDisplayKey: string; principalRemaining: string | null; interestRemaining: string | null; amountRemaining: string | null; basis: string }[] };
export function UpcomingCharges({ thai, summary, detail, page, busy, error, onDate, onBack, onRefresh, onNext, onDetailRefresh }: { thai: boolean; summary: UpcomingSummary | null; detail: UpcomingDetail | null; page: number; busy: boolean; error: string | null; onDate: (date: string) => void; onBack: () => void; onRefresh: () => void; onNext: () => void; onDetailRefresh: () => void }) {
  const t = (en: string, th: string) => thai ? th : en;
  const date = (value: string) => new Intl.DateTimeFormat(thai ? 'th-TH' : 'en-GB', { dateStyle: 'medium', timeZone: 'Asia/Bangkok' }).format(new Date(value + 'T00:00:00Z'));
  const money = (value: string | null) => value === null ? t('Unavailable', 'ไม่มีข้อมูล') : new Intl.NumberFormat(thai ? 'th-TH' : 'en-TH', { style: 'currency', currency: 'THB', currencyDisplay: 'narrowSymbol', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(Number(value));
  const basis = (value: string) => ({ Recorded: t('Recorded', 'บันทึกแล้ว'), 'Recorded settlement': t('Recorded settlement', 'รายการชำระที่บันทึกแล้ว'), 'Recorded - review status': t('Recorded - review status', 'บันทึกแล้ว - ตรวจสอบสถานะ'), Projected: t('Projected', 'คาดการณ์') })[value] ?? t('Unavailable', 'ไม่มีข้อมูล');
  const source = detail ?? summary;
  return <section className="upcoming-charges" aria-label={t('Upcoming Charges', 'ยอดเรียกเก็บล่วงหน้า')} aria-busy={busy}>
    {detail && <button className="secondary-button" onClick={onBack}>{t('Back to borrower summary', 'กลับสรุปผู้กู้')}</button>}
    <div className="related-loans-heading"><h3>{t('Upcoming Charges', 'ยอดเรียกเก็บล่วงหน้า')}</h3></div>
    <p className="loan-order-note">{t('Projected amounts assume scheduled principal is collected.', 'ยอดคาดการณ์สมมติว่าได้รับชำระเงินต้นตามกำหนด')}</p>
    {source?.reviewRequired && <p className="issue-note" role="status">{t('Schedule data is incomplete or loan status needs review.', 'ข้อมูลตารางชำระไม่ครบถ้วนหรือสถานะสินเชื่อต้องตรวจสอบ')}</p>}
    {error && <p role="status">{error === 'not_found' ? t('This upcoming date is no longer available. Refresh upcoming charges.', 'ไม่พบวันที่เรียกเก็บล่วงหน้านี้แล้ว กรุณารีเฟรช') : t('Unable to load upcoming charges.', 'ไม่สามารถโหลดรายการเรียกเก็บล่วงหน้าได้')}</p>}
    {detail ? <><h3>{date(detail.dueDate)} · {money(detail.totalCharge)}</h3><p className="live-page-status">{t('Total charge for this date', 'ยอดเรียกเก็บรวมสำหรับวันที่นี้')}</p>{detail.items.map(row => <article className="collection-charge" key={row.id}><h4>{row.loanDisplayKey}</h4><dl><div><dt>{t('Principal remaining', 'เงินต้นคงเหลือ')}</dt><dd>{money(row.principalRemaining)}</dd></div><div><dt>{t('Interest remaining', 'ดอกเบี้ยคงเหลือ')}</dt><dd>{money(row.interestRemaining)}</dd></div><div><dt>{t('Amount remaining', 'ยอดคงเหลือ')}</dt><dd>{money(row.amountRemaining)}</dd></div><div><dt>{t('Basis', 'ที่มา')}</dt><dd>{basis(row.basis)}</dd></div></dl></article>)}<p className="live-page-status">{t('Upcoming details page', 'หน้ารายละเอียดล่วงหน้า')} {page}{!detail.nextCursor ? t(' · End of list', ' · สิ้นสุดรายการ') : ''}</p><div className="loan-page-actions"><button className="secondary-button" disabled={busy} onClick={onDetailRefresh}>{t('First upcoming details page / refresh', 'หน้าแรกของรายละเอียดล่วงหน้า / รีเฟรช')}</button>{detail.nextCursor && <button className="secondary-button" disabled={busy} onClick={onNext}>{t('Next upcoming details page', 'หน้าถัดไปของรายละเอียดล่วงหน้า')}</button>}</div></> : <>
      {summary && !summary.items.length && !error && <p>{t('No upcoming charge dates.', 'ไม่มีวันที่เรียกเก็บล่วงหน้า')}</p>}
      {summary?.items.map(row => <button className="upcoming-date-row" disabled={busy} key={row.id} onClick={() => onDate(row.dueDate)}><span><span>{t('Date', 'วันที่')}</span><strong>{date(row.dueDate)}</strong></span><span><span>{t('Total Charge', 'ยอดเรียกเก็บรวม')}</span><strong>{money(row.totalCharge)}</strong></span></button>)}
      <button className="secondary-button upcoming-refresh" disabled={busy} onClick={onRefresh}>{t('Refresh Upcoming Charges', 'รีเฟรชยอดเรียกเก็บล่วงหน้า')}</button>
    </>}

  </section>;
}
