export type ViewedDomain='borrower'|'loan'|'charge'|'payment'|'expense';
export type ViewedSnapshot={schemaVersion:1;domain:ViewedDomain;recordId:string;sourceVersion:string;asOf:string;businessDate:string;record:Record<string,unknown>;related:Record<string,{rows:Record<string,unknown>[];hasMore:boolean;truncated:boolean}>};
const fields:Record<ViewedDomain,string[]>={
 borrower:['id','name','description','createdDate','preferredReceivingAccountLabel','referrerLabel','details'],
 loan:['id','borrowerId','borrowerLabel','borrowerDisplayName','loanDate','principal','transferFee','disbursingAccountLabel','type','dueDate','dailyPayment','fixedInterest','currentDailyInterest','originalRate','paymentInterval','scheduleAnchor','arrangement','autoChargeEnabled','status','defaulted','closeDate','outstandingPrincipal','principalReceived','interestReceived','amountReceived','totalPrincipalReceived','totalInterestReceived','totalAmountReceived'],
 charge:['id','loanId','loanLabel','borrowerId','borrowerLabel','chargeDate','principalDue','interestDue','principalReceived','interestReceived','amountRemaining','paymentStatus','notes'],
 payment:['id','borrowerId','borrowerName','borrowerDescription','amountReceived','postedAmount','paymentDate','paymentMethod','allocationMethod','cashAccountLabel','notes','status','originalOutcomeStatus','originalRecordedAt','createdAt','processedAt'],
 expense:['id','expenseDate','category','amount','payeeName','payeeBorrowerLabel','relatedBorrowerLabel','relatedLoanLabel','notes','paidByAccountLabel','paidByHolderLabel','sourceType','grossProfitBasis','allocationBasis','partnerAShare','partnerBShare','partnerAExpense','partnerBExpense','ruleVersion','createdAt']
};
const detailFields=['totalAmountLoaned','totalInterestEarned','totalNumberOfLoans','outstandingPrincipal','activeInterest','hasActiveLoan','hasClosedLoan','activeReturn','activeProfit','closedPrincipal','closedInterest','closedReturn','coverageDate'];
const childFields:Record<string,string[]>={loans:['id','loanDate','type','principal','status','outstandingPrincipal'],charges:['id','chargeDate','principalDue','interestDue','amountRemaining','notes'],upcoming:['id','dueDate','totalCharge','basis'],assessments:['id','date','status'],payments:['id','paymentDate','amountReceived','postedAmount','status','notes'],allocations:['id','chargeId','loanDisplayKey','chargeDate','allocationOrder','principal','interest','amount'],repayments:['id','chargeId','allocationId','paymentDate','principal','interest'],cashMovements:['id','movementDate','movementType','amount','fromAccount','toAccount'],reimbursements:['id','movementDate','movementType','amount','entryOrigin','fromAccountLabel','toAccountLabel']};
const relatedNames:Record<ViewedDomain,string[]>={borrower:['loans','upcoming','assessments'],loan:['charges','payments','repayments'],charge:['repayments','allocations'],payment:['allocations','repayments','cashMovements'],expense:['reimbursements']};
const object=(value:unknown):value is Record<string,any>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const pick=(value:Record<string,any>,keys:string[])=>Object.fromEntries(keys.filter(key=>Object.hasOwn(value,key)).map(key=>[key,value[key]]));
/** Explicit safe projections, never raw API DTO or auth/storage metadata. */
export function projectViewedSnapshot(domain:ViewedDomain,source:Record<string,any>,businessDate:string,asOf=new Date().toISOString()):ViewedSnapshot{
 if(!Object.hasOwn(fields,domain)||!object(source)||typeof source.id!=='string'||!source.id||typeof source.version!=='string'||!/^[a-f0-9]{64}$/.test(source.version))throw Error('Invalid viewed record');
 const record=pick(source,fields[domain]);if(domain==='borrower'&&object(source.details))record.details=pick(source.details,detailFields);
 if(domain==='payment'){record.manualReceiptPresent=!!source.receiptReference;record.agentReceiptPresent=!!source.agentReceiptPresent;}
 let remaining=100;const related:ViewedSnapshot['related']={};
 for(const name of relatedNames[domain]){if(source[name]===undefined)continue;if(!Array.isArray(source[name]))throw Error('Invalid related records');const input=source[name];const rows=input.slice(0,remaining).map((row:unknown)=>{if(!object(row))throw Error('Invalid related record');return pick(row,childFields[name])});remaining-=rows.length;related[name]={rows,hasMore:input.length>rows.length||source[name+'HasMore']===true,truncated:input.length>rows.length};}
 const value:ViewedSnapshot={schemaVersion:1,domain,recordId:source.id,sourceVersion:source.version,asOf,businessDate,record,related};validateViewedSnapshot(value);return value;
}
export function validateViewedSnapshot(value:unknown,now=Date.now()):asserts value is ViewedSnapshot{
 if(!object(value)||Object.keys(value).sort().join(',')!=='asOf,businessDate,domain,record,recordId,related,schemaVersion,sourceVersion'||value.schemaVersion!==1||!Object.hasOwn(fields,value.domain)||typeof value.recordId!=='string'||!value.recordId||value.recordId.length>256||!/^[a-f0-9]{64}$/.test(value.sourceVersion)||typeof value.asOf!=='string'||!Number.isFinite(Date.parse(value.asOf))||new Date(value.asOf).toISOString()!==value.asOf||Date.parse(value.asOf)>now||!/^\d{4}-\d{2}-\d{2}$/.test(value.businessDate)||!Number.isFinite(Date.parse(value.businessDate+'T00:00:00Z'))||new Date(value.businessDate+'T00:00:00Z').toISOString().slice(0,10)!==value.businessDate||!object(value.record)||!object(value.related))throw Error('Invalid viewed snapshot');
 const domain=value.domain as ViewedDomain,allowed=[...fields[domain],...(domain==='payment'?['manualReceiptPresent','agentReceiptPresent']:[])];
 if(Object.keys(value.record).some(key=>!allowed.includes(key))||value.record.id!==value.recordId)throw Error('Invalid viewed projection');
 if(domain==='borrower'&&value.record.details!==undefined&&(!object(value.record.details)||Object.keys(value.record.details).some(key=>!detailFields.includes(key))||Object.values(value.record.details).some(item=>item!==null&&!['string','number','boolean'].includes(typeof item))))throw Error('Invalid borrower summary');
 for(const [key,item] of Object.entries(value.record)){if(key==='details'&&domain==='borrower')continue;if(item!==null&&!['string','number','boolean'].includes(typeof item))throw Error('Invalid projected value');}
 let count=0;for(const [name,group] of Object.entries(value.related)){if(!relatedNames[domain].includes(name)||!object(group)||Object.keys(group).sort().join(',')!=='hasMore,rows,truncated'||!Array.isArray(group.rows)||typeof group.hasMore!=='boolean'||typeof group.truncated!=='boolean'||(group.truncated&&!group.hasMore))throw Error('Invalid related projection');count+=group.rows.length;for(const row of group.rows)if(!object(row)||Object.keys(row).some(key=>!childFields[name].includes(key))||Object.values(row).some(item=>item!==null&&!['string','number','boolean'].includes(typeof item)))throw Error('Invalid related values');}if(count>100||new TextEncoder().encode(JSON.stringify(value)).byteLength>524288)throw Error('Snapshot exceeds device bound');
}
