-- R007: ordinary, read-only OLAP analytics. No base-table or trigger changes.
-- Source contract: saved DEV OLAP 1.000129, captured 2026-09-18.
-- Bangkok matches the accepted client/API reporting timezone. Stable per statement.
CREATE FUNCTION public.olap_reporting_date() RETURNS date
LANGUAGE sql STABLE SET search_path=pg_catalog AS $$
 SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')::date
$$;

CREATE VIEW public.olap_charges_analytics AS
WITH ctx AS (SELECT d, date_trunc('month',d)::date ms,
 (date_trunc('month',d)+interval '1 month - 1 day')::date me FROM (SELECT public.olap_reporting_date() d) q),

rp AS (SELECT "Ref Charges" id,min("Payment Date") first_date,max("Payment Date") last_date,
 bool_or("Payment Date"=d) today FROM public."Repayments" CROSS JOIN ctx GROUP BY 1),
a AS (SELECT c.*, coalesce(c."Principal Due"::numeric,0)+coalesce(c."Interest Due"::numeric,0) "Amount Due",
 rp.first_date "First Payment Date",rp.last_date "Last Payment Date",
 CASE WHEN c."Payment Status"='ชำระแล้ว' AND c."Payment Date" IS NOT NULL
 THEN greatest(0,c."Payment Date"-c."Charge Date") WHEN c."Charge Date"<d THEN d-c."Charge Date" ELSE 0 END "Days Late",
 CASE WHEN (c."Payment Status" IS DISTINCT FROM 'ชำระแล้ว' AND c."Charge Date"<=d)
 OR (c."Payment Status"='ชำระแล้ว' AND c."Payment Date"=d) OR rp.today
 THEN l."Ref Borrowers" END "Ref Collection Borrower"
 FROM public."Charges" c CROSS JOIN ctx LEFT JOIN rp ON rp.id=c."Row ID"
 LEFT JOIN public."Loans" l ON l."Row ID"=c."Ref Loans"),
final AS (SELECT a.*,coalesce("Charge Date"<d AND "Payment Status"='ชำระแล้ว' AND "Days Late"=0,false) "Historical On Time",
 coalesce("Charge Date"<d AND "Days Late">0,false) "Historical Late" FROM a CROSS JOIN ctx)

SELECT x."Row ID",
 x."Ref Loans",
 x."Charge Date",
 x."Interest Due",
 x."Principal Due",
 x."Notes",
 x."Principal Paid",
 x."Interest Paid",
 x."Total Paid",
 x."Principal Remaining",
 x."Interest Remaining",
 x."Amount Remaining",
 x."Payment Count",
 x."Payment Status",
 x."Payment Date",
 round(x."Amount Due"::numeric,0) AS "Amount Due",
 x."Last Payment Date",
 x."First Payment Date",
 x."Days Late",
 x."Historical On Time",
 x."Historical Late",
 x."Ref Collection Borrower" FROM final x;

CREATE VIEW public.olap_repayments_analytics AS
WITH ctx AS (SELECT d, date_trunc('month',d)::date ms,
 (date_trunc('month',d)+interval '1 month - 1 day')::date me FROM (SELECT public.olap_reporting_date() d) q),

events AS (SELECT c."Contribution Date" dt,
 sum(CASE WHEN c."Transaction Type"='Contribution' THEN c."Amount"::numeric ELSE -c."Amount"::numeric END) pool,
 sum(CASE WHEN c."Transaction Type"='Contribution' THEN c."Amount"::numeric ELSE -c."Amount"::numeric END) FILTER(WHERE p."Partner Role"='A') a,
 sum(CASE WHEN c."Transaction Type"='Contribution' THEN c."Amount"::numeric ELSE -c."Amount"::numeric END) FILTER(WHERE p."Partner Role"='B') b
 FROM public."Cash Pool Contributions" c LEFT JOIN public."Partners" p ON p."Row ID"=c."Ref Partner" GROUP BY 1),
running AS MATERIALIZED (SELECT dt,sum(pool) OVER w pool,sum(a) OVER w a,sum(b) OVER w b
 FROM events WINDOW w AS (ORDER BY dt ROWS UNBOUNDED PRECEDING)),
a AS (SELECT r.*,coalesce(h.pool,0) "Pool Total at Payment Date",coalesce(h.a,0) "Partner A Contribution at Payment Date",
 coalesce(h.b,0) "Partner B Contribution at Payment Date",
 CASE WHEN h.pool>0 THEN coalesce(h.a,0)/h.pool ELSE 0 END "Partner A Profit Share",
 CASE WHEN h.pool>0 THEN coalesce(h.b,0)/h.pool ELSE 0 END "Partner B Profit Share",
 CASE WHEN coalesce(r."Principal Paid"::numeric,0)<=0 OR r."Payment Date">d THEN 0
 ELSE coalesce(r."Principal Paid"::numeric,0)*CASE WHEN r."Payment Date" BETWEEN ms AND me THEN d-r."Payment Date"+1 ELSE extract(day FROM d) END END "Principal Returned Days MTD",
 CASE WHEN r."Payment Date"<d-29 OR r."Payment Date">d THEN 0 ELSE coalesce(r."Principal Paid"::numeric,0)*(d-r."Payment Date"+1) END "30D Principal Reduction Days",
 coalesce(r."Principal Paid"::numeric,0)+coalesce(r."Interest Paid"::numeric,0) "Amount Received"
 FROM public."Repayments" r CROSS JOIN ctx LEFT JOIN LATERAL
 (SELECT * FROM running WHERE dt<=r."Payment Date" ORDER BY dt DESC LIMIT 1) h ON true),
final AS (SELECT a.*,round(coalesce(a."Interest Paid"::numeric,0)*"Partner A Profit Share") "Partner A Profit",
 round(coalesce(a."Interest Paid"::numeric,0)*"Partner B Profit Share") "Partner B Profit" FROM a)

SELECT x."Row ID",
 x."Payment Date",
 x."Principal Paid",
 x."Interest Paid",
 x."Notes",
 x."Ref Loans",
 x."Ref Charges",
 x."Created By",
 x."Ref Payment",
 x."Ref Payment Allocation",
 x."Principal Returned Days MTD",
 round(x."Pool Total at Payment Date"::numeric,0) AS "Pool Total at Payment Date",
 round(x."Partner A Contribution at Payment Date"::numeric,0) AS "Partner A Contribution at Payment Date",
 round(x."Partner B Contribution at Payment Date"::numeric,0) AS "Partner B Contribution at Payment Date",
 round(x."Partner A Profit Share"::numeric,2) AS "Partner A Profit Share",
 round(x."Partner B Profit Share"::numeric,2) AS "Partner B Profit Share",
 round(x."Partner A Profit"::numeric,0) AS "Partner A Profit",
 round(x."Partner B Profit"::numeric,0) AS "Partner B Profit",
 round(x."30D Principal Reduction Days"::numeric,2) AS "30D Principal Reduction Days",
 round(x."Amount Received"::numeric,0) AS "Amount Received" FROM final x;

CREATE VIEW public.olap_loans_analytics AS
WITH ctx AS (SELECT d, date_trunc('month',d)::date ms,
 (date_trunc('month',d)+interval '1 month - 1 day')::date me FROM (SELECT public.olap_reporting_date() d) q),

cr AS (SELECT "Ref Loans" id,max("Days Late") late,max("Charge Date") FILTER(WHERE "Charge Date"<=d) last_interest,
 max("Charge Date") last_charge,sum("Interest Remaining") FILTER(WHERE "Charge Date">d AND "Charge Date"<=me) scheduled
 FROM public.olap_charges_analytics CROSS JOIN ctx GROUP BY 1),
br AS (SELECT "Ref Borrowers" id,sum("Total Interest Received") total FROM public."Loans" GROUP BY 1),
a AS (SELECT l.*,coalesce(br.total,0) "Borrower Total Interest",
 CASE WHEN coalesce(l."Principal Amount"::numeric,0)>0 THEN coalesce(l."Total Interest Received",0)/l."Principal Amount"::numeric ELSE 0 END "Principal Recovered by Interest %",
 CASE WHEN l."Loan Date">d THEN 0 ELSE coalesce(l."Principal Amount"::numeric,0)*CASE WHEN l."Loan Date" BETWEEN ms AND me THEN d-l."Loan Date"+1 ELSE extract(day FROM d) END END "Principal Days MTD",
 (l."Loan Date"-date '2000-01-01')::numeric "Loan Start Day Index",
 l."Close Date" "Loan End Date",CASE WHEN l."Close Date" IS NOT NULL THEN l."Close Date"-l."Loan Date"+1 END "Loan Duration",
 CASE WHEN l."Loan Date">d THEN 0 ELSE coalesce(l."Principal Amount"::numeric,0)*(d-greatest(l."Loan Date",d-29)+1) END "30D Principal Days",
 d-l."Loan Date" "Loan Age Days",coalesce(l."Defaulted",false) "Defaulted Flag",
 greatest(0,cr.late) "Maximum Days Late",cr.last_interest "Last Interest Charge Date",
 greatest(0,d-coalesce(cr.last_interest,l."Loan Date")) "Accrued Interest Days",
 cr.last_charge,coalesce(cr.scheduled,0) scheduled,least(l."Due Date",me) forecast_end,
 (l."Due Date"-l."Loan Date"+1) term_days
 FROM public."Loans" l CROSS JOIN ctx LEFT JOIN cr ON cr.id=l."Row ID" LEFT JOIN br ON br.id=l."Ref Borrowers"),
b AS (SELECT a.*,coalesce(a."Principal Amount"::numeric,0)*"Loan Start Day Index" "Principal Start Weight",
 CASE WHEN "Loan Age Days"<=10 THEN '0-10 Days' WHEN "Loan Age Days"<=20 THEN '11-20 Days' WHEN "Loan Age Days"<=30 THEN '21-30 Days' WHEN "Loan Age Days"<=60 THEN '31-60 Days' ELSE '60+ Days' END "Loan Age Bucket",
 CASE WHEN "Auto Charge Enabled" AND "Loan Type"='ดอกเบี้ยรายวัน' THEN coalesce(a."Current Daily Interest"::numeric,0)*"Accrued Interest Days" ELSE 0 END "Accrued Interest",
 CASE WHEN "Loan Type"='ผ่อนชำระรายวัน' AND "Loan Date" IS NOT NULL AND "Due Date">="Loan Date"
 THEN floor(coalesce(a."Principal Amount"::numeric,0)/nullif(term_days,0)) ELSE 0 END "Daily Installment Base Principal",
 CASE "Loan Type" WHEN 'ดอกเบี้ยรายวัน' THEN coalesce(a."Current Daily Interest"::numeric,0)/nullif("Principal Amount"::numeric,0)
 WHEN 'กำหนดวันชำระ' THEN coalesce(a."Fixed Interest"::numeric,0)/nullif(term_days,0)/nullif("Principal Amount"::numeric,0)
 WHEN 'ผ่อนชำระรายวัน' THEN (coalesce(a."Daily Payment Amount"::numeric,0)*term_days-coalesce(a."Principal Amount"::numeric,0))/nullif(term_days,0)/nullif("Principal Amount"::numeric,0)
 ELSE 0 END "Effective Daily Interest Rate" FROM a),
final AS (SELECT b.*,CASE WHEN "Loan Status"='ปิดยอดแล้ว' THEN 0
 WHEN NOT coalesce("Auto Charge Enabled",false) OR ("Loan Type"='ดอกเบี้ยรายวัน' AND coalesce(b."Current Daily Interest"::numeric,0)=0) THEN scheduled
 WHEN "Loan Type"='ดอกเบี้ยรายวัน' THEN greatest(0,"Accrued Interest")+coalesce(b."Current Daily Interest"::numeric,0)*(me-d)
 WHEN "Loan Type"='กำหนดวันชำระ' THEN CASE WHEN "Due Date">d AND "Due Date"<=me THEN coalesce(b."Fixed Interest"::numeric,0) ELSE 0 END
 WHEN "Loan Type"='ผ่อนชำระรายวัน' THEN CASE WHEN last_charge IS NOT NULL AND forecast_end>last_charge
 THEN coalesce(b."Daily Payment Amount"::numeric,0)*(forecast_end-last_charge)
 -(floor(coalesce(b."Principal Amount"::numeric,0)/nullif(term_days,0))*(forecast_end-last_charge)
 +greatest(0,least(forecast_end-"Loan Date"+1,mod(coalesce(b."Principal Amount"::numeric,0),nullif(term_days,0)))-(last_charge-"Loan Date"+1))) ELSE 0 END
 ELSE 0 END "Expected Interest This Month" FROM b CROSS JOIN ctx)

SELECT x."Row ID",
 x."Loan Date",
 x."Close Date",
 x."Principal Amount",
 x."Due Date",
 x."Ref Borrowers",
 x."Loan Arrangement",
 x."Loan Status",
 x."Loan Type",
 x."Current Daily Interest",
 x."Fixed Interest",
 x."Transfer Fee",
 x."Interest Payment Interval",
 x."Created By",
 x."Closed By",
 x."Defaulted",
 x."Default Loss Amount",
 x."Daily Payment Amount",
 x."Auto Charge Enabled",
 x."Interest Schedule Anchor Date",
 x."Ref Closing Payment",
 x."Charge Generation Request",
 x."Total Interest Received",
 x."Total Principal Received",
 x."Outstanding Principal",
 x."Total Amount Received",
 x."Expected Daily Interest Amount",
 round(x."Borrower Total Interest"::numeric,0) AS "Borrower Total Interest",
 round(x."Expected Interest This Month"::numeric,0) AS "Expected Interest This Month",
 round(coalesce(x."Effective Daily Interest Rate",0)::numeric,4) AS "Effective Daily Interest Rate",
 round(x."Principal Recovered by Interest %"::numeric,2) AS "Principal Recovered by Interest %",
 x."Principal Days MTD",
 round(x."Loan Start Day Index"::numeric,0) AS "Loan Start Day Index",
 round(x."Principal Start Weight"::numeric,0) AS "Principal Start Weight",
 x."Loan End Date",
 x."Loan Duration",
 round(x."30D Principal Days"::numeric,2) AS "30D Principal Days",
 x."Loan Age Days",
 x."Loan Age Bucket",
 x."Defaulted Flag",
 x."Maximum Days Late",
 x."Last Interest Charge Date",
 x."Accrued Interest Days",
 round(x."Accrued Interest"::numeric,0) AS "Accrued Interest",
 x."Daily Installment Base Principal" FROM final x;

CREATE VIEW public.olap_borrowers_analytics AS
WITH ctx AS (SELECT d, date_trunc('month',d)::date ms,
 (date_trunc('month',d)+interval '1 month - 1 day')::date me FROM (SELECT public.olap_reporting_date() d) q),

lr AS (SELECT l."Ref Borrowers" id,
 count(*) FILTER(WHERE l."Loan Status"='ยังไม่ปิดยอด') active,
 max(l."Loan Age Days") FILTER(WHERE l."Loan Status"='ยังไม่ปิดยอด') oldest,
 greatest(0,max(l."Principal Amount"::numeric) FILTER(WHERE l."Loan Status"='ปิดยอดแล้ว' AND l."Defaulted"=false)) largest,
 coalesce(avg(l."Principal Amount"::numeric) FILTER(WHERE l."Loan Status"='ปิดยอดแล้ว' AND l."Defaulted"=false),0) average_success,
 count(*) FILTER(WHERE l."Defaulted"=true) defaults,
 coalesce(sum(l."Default Loss Amount"::numeric) FILTER(WHERE l."Defaulted"=true),0) loss,
 coalesce(sum(l."30D Principal Days"),0) gross_days,coalesce(sum(l."Expected Interest This Month"),0) forecast,
 bool_or(l."Defaulted"=true AND l."Outstanding Principal">0) current_default
 FROM public.olap_loans_analytics l GROUP BY 1),
rr AS (SELECT l."Ref Borrowers" id,
 coalesce(sum(r."Interest Paid"::numeric) FILTER(WHERE r."Payment Date" BETWEEN d-29 AND d AND r."Interest Paid"::numeric>0),0) profit30,
 coalesce(sum(r."Interest Paid"::numeric) FILTER(WHERE r."Payment Date">=d-10 AND r."Payment Date"<d AND r."Interest Paid"::numeric>0),0) profit10,
 coalesce(sum(r."Interest Paid"::numeric) FILTER(WHERE r."Payment Date" BETWEEN ms AND me),0) mtd,
 coalesce(sum(r."30D Principal Reduction Days"),0) reduction
 FROM public.olap_repayments_analytics r JOIN public."Loans" l ON l."Row ID"=r."Ref Loans" CROSS JOIN ctx GROUP BY 1),
cash AS (SELECT c."Ref Collection Borrower" id,coalesce(sum(r."Amount Received"),0) collected
 FROM public.olap_repayments_analytics r JOIN public.olap_charges_analytics c ON c."Row ID"=r."Ref Charges"
 CROSS JOIN ctx WHERE r."Payment Date"=d AND c."Ref Collection Borrower" IS NOT NULL GROUP BY 1),
cr AS (SELECT l."Ref Borrowers" id,
 coalesce(sum(c."Amount Remaining") FILTER(WHERE c."Charge Date"<d AND c."Payment Status" IS DISTINCT FROM 'ชำระแล้ว'),0) overdue,
 count(*) FILTER(WHERE c."Charge Date"<d AND c."Payment Status" IS DISTINCT FROM 'ชำระแล้ว') overdue_count,
 count(*) FILTER(WHERE c."Charge Date"<d) history,count(*) FILTER(WHERE c."Historical On Time") ontime,
 count(*) FILTER(WHERE c."Charge Date">=d-30 AND c."Charge Date"<d) recent_count,count(*) FILTER(WHERE c."Charge Date">=d-30 AND c."Charge Date"<d AND c."Historical On Time") recent_ontime,
 count(*) FILTER(WHERE c."Historical Late") late_count,count(*) FILTER(WHERE c."Charge Date">=d-30 AND c."Charge Date"<d AND c."Historical Late") recent_late,
 greatest(0,max(c."Days Late")) max_late,max(c."Charge Date") FILTER(WHERE c."Days Late">0) last_late,
 count(*) FILTER(WHERE c."Charge Date">=d-180 AND c."Charge Date"<d) history180,count(*) FILTER(WHERE c."Charge Date">=d-180 AND c."Charge Date"<d AND c."Historical On Time") ontime180,
 count(*) FILTER(WHERE c."Charge Date">=d-90 AND c."Charge Date"<d) history90,bool_or(l."Defaulted") FILTER(WHERE c."Charge Date">=d-90 AND c."Charge Date"<d) default90,
 greatest(0,max(c."Days Late") FILTER(WHERE c."Charge Date">=d-90 AND c."Charge Date"<d)) late90,
 greatest(0,max(c."Days Late") FILTER(WHERE c."Charge Date"<d AND c."Amount Remaining">0)) unpaid_late,
 bool_or(c."Total Paid">0) FILTER(WHERE c."Charge Date"=d AND c."Amount Remaining">0) partial_today,
 count(*) FILTER(WHERE c."Charge Date"=d AND c."Amount Remaining">0) unpaid_today,
 min(c."Charge Date") FILTER(WHERE c."Charge Date"<d) first_history,
 count(*) FILTER(WHERE c."Ref Collection Borrower" IS NOT NULL) collection_count,
 count(*) FILTER(WHERE c."Ref Collection Borrower" IS NOT NULL AND c."Charge Date"<d AND c."Payment Status" IS DISTINCT FROM 'ชำระแล้ว') collection_overdue,
 count(*) FILTER(WHERE c."Ref Collection Borrower" IS NOT NULL AND c."Payment Status"='รอชำระ') collection_pending,
 count(*) FILTER(WHERE c."Ref Collection Borrower" IS NOT NULL AND c."Payment Status"='ชำระบางส่วน') collection_partial,
 count(*) FILTER(WHERE c."Ref Collection Borrower" IS NOT NULL AND c."Payment Status"='ชำระแล้ว') collection_paid,
 coalesce(sum(c."Amount Due") FILTER(WHERE c."Ref Collection Borrower" IS NOT NULL AND c."Charge Date"<=d),0) collection_due,
 coalesce(sum(c."Amount Remaining") FILTER(WHERE c."Ref Collection Borrower" IS NOT NULL AND c."Charge Date"<=d),0) collection_remaining,
 coalesce(sum(c."Interest Remaining") FILTER(WHERE c."Charge Date"<=d),0) interest_remaining
 FROM public.olap_charges_analytics c JOIN public."Loans" l ON l."Row ID"=c."Ref Loans" CROSS JOIN ctx GROUP BY 1),
er AS (SELECT "Ref Payee Borrower" id,sum("Amount"::numeric) rebate FROM public."Business Expenses" WHERE "Source Type"='Referral Rebate' GROUP BY 1),
pt AS (SELECT coalesce(sum("Outstanding Principal"),0) portfolio FROM public."Loans"),
bt AS (SELECT coalesce(sum("Total Outstanding Principal"),0) borrower_portfolio,
 count(*) FILTER(WHERE "Has Active Loan"=true) active_borrowers FROM public."Borrowers"),
a AS (SELECT b.*,
 CASE WHEN b."Total Outstanding Principal">0 THEN b."Active Loan Interest Earned"/b."Total Outstanding Principal" ELSE 0 END "Return on Active Principal",
 coalesce(rr.profit30,0) "Profit Last 30 Days",coalesce(rr.profit10,0) "Profit Last 10 Days",
 CASE WHEN b."Total Outstanding Principal"<=0 THEN NULL WHEN b."Active Loan Interest Earned">=b."Total Outstanding Principal" THEN d
 WHEN b."Active Daily Interest">0 THEN d+ceil((b."Total Outstanding Principal"-b."Active Loan Interest Earned")/b."Active Daily Interest")::integer END "Projected Interest Coverage Date",
 coalesce(b."Total Interest Earned",0)-coalesce(b."Active Loan Interest Earned",0) "Closed Loan Interest Earned",
 coalesce(b."Total Amount Loaned",0)-coalesce(b."Total Outstanding Principal",0) "Closed Loan Principle",
 coalesce(lr.gross_days,0) "30D Gross Principal Days",coalesce(rr.reduction,0) "30D Principal Reduction Days",
 round((coalesce(lr.gross_days,0)-coalesce(rr.reduction,0))/30) "30D Average Outstanding Principal",
 CASE WHEN coalesce(cr.collection_count,0)=0 THEN NULL WHEN cr.collection_overdue>0 THEN 'Overdue'
 WHEN cr.collection_pending=0 AND cr.collection_partial=0 THEN 'Fully Paid'
 WHEN cr.collection_partial>0 OR (cr.collection_paid>0 AND cr.collection_pending>0) THEN 'Partially Paid' ELSE 'Not Paid' END "Daily Collection Status",
 coalesce(cr.collection_due,0) "Todays Amount Due",coalesce(cash.collected,0) "Todays Amount Collected",coalesce(cr.collection_remaining,0) "Todays Amount Remaining",
 CASE WHEN bt.borrower_portfolio=0 THEN 0 ELSE coalesce(b."Total Outstanding Principal",0)/bt.borrower_portfolio END "Portfolio Exposure %",
 coalesce(lr.active,0) "Active Loan Count",coalesce(lr.oldest,0) "Oldest Active Loan Age",
 coalesce(cr.overdue,0) "Overdue Amount",coalesce(cr.overdue_count,0) "Overdue Charge Count",
 coalesce(cr.history,0) "Historical Charge Count",coalesce(cr.ontime,0) "On Time Charge Count",
 coalesce(cr.recent_count,0) "Recent 30D Charge Count",coalesce(cr.recent_ontime,0) "Recent 30D On Time Count",
 coalesce(cr.late_count,0) "Lifetime Late Payment Count",coalesce(cr.recent_late,0) "Recent 30D Late Payment Count",
 coalesce(cr.max_late,0) "Maximum Days Late",cr.last_late "Last Late Payment Date",
 coalesce(lr.largest,0) "Largest Successful Loan",round(coalesce(lr.average_success,0)) "Average Successful Loan Size",
 coalesce(lr.defaults,0) "Default Count",coalesce(lr.loss,0) "Lifetime Default Loss",pt.portfolio "Portfolio Outstanding Principal",
 coalesce(rr.mtd,0)+coalesce(cr.interest_remaining,0)+coalesce(lr.forecast,0) "Projected Monthly Profit Contribution",
 bt.active_borrowers "Matrix Active Borrower Count",1/nullif(bt.active_borrowers,0) "Matrix Equal Share Benchmark",
 cr.recent_ontime*100/nullif(cr.recent_count,0) "Matrix Recent Reliability Score",
 cr.ontime180*100/nullif(cr.history180,0) "Matrix Historical Reliability Score",
 CASE WHEN coalesce(cr.history90,0)=0 THEN NULL WHEN cr.default90 THEN 0 WHEN cr.late90=0 THEN 100 WHEN cr.late90<=1 THEN 90 WHEN cr.late90<=3 THEN 70 WHEN cr.late90<=7 THEN 40 ELSE 10 END "Matrix Delay Severity Score",
 CASE WHEN lr.current_default THEN 0 WHEN cr.unpaid_late>3 THEN 20 WHEN cr.unpaid_late>=2 THEN 40 WHEN cr.unpaid_late>=1 THEN 60 WHEN cr.partial_today THEN 75 WHEN cr.unpaid_today>0 THEN 90 ELSE 100 END "Matrix Current Condition Score",
 coalesce(d-cr.first_history>=3,true) "Matrix History Sufficient",
 coalesce(er.rebate,0) "Total Referral Rebate Earned"
 FROM public."Borrowers" b CROSS JOIN ctx CROSS JOIN pt CROSS JOIN bt
 LEFT JOIN lr ON lr.id=b."Row ID" LEFT JOIN rr ON rr.id=b."Row ID" LEFT JOIN cr ON cr.id=b."Row ID"
 LEFT JOIN cash ON cash.id=b."Row ID" LEFT JOIN er ON er.id=b."Row ID"),
b AS (SELECT a.*,
 CASE WHEN "Has Closed Loan" AND "Closed Loan Principle">0 THEN "Closed Loan Interest Earned"/"Closed Loan Principle" ELSE 0 END "Return on Closed Loans",
 CASE WHEN "30D Average Outstanding Principal">0 THEN "Profit Last 30 Days"/"30D Average Outstanding Principal" ELSE 0 END "30D Return on Average Principal",
 CASE WHEN "Historical Charge Count"=0 THEN 0 ELSE "On Time Charge Count"/"Historical Charge Count" END "Lifetime On Time Rate",
 CASE WHEN "Recent 30D Charge Count"=0 THEN 0 ELSE "Recent 30D On Time Count"/"Recent 30D Charge Count" END "Recent 30D On Time Rate",
 CASE WHEN sum("Profit Last 10 Days") FILTER(WHERE "Has Active Loan") OVER()>0
 THEN round("Profit Last 10 Days"/sum("Profit Last 10 Days") FILTER(WHERE "Has Active Loan") OVER(),2) END "Matrix Economic Contribution",
 trunc(round(10*(coalesce("Matrix Recent Reliability Score"*0.45,0)+coalesce("Matrix Historical Reliability Score"*0.20,0)+coalesce("Matrix Delay Severity Score"*0.20,0)+"Matrix Current Condition Score"*0.15)
 /(CASE WHEN "Matrix Recent Reliability Score" IS NOT NULL THEN 0.45 ELSE 0 END+CASE WHEN "Matrix Historical Reliability Score" IS NOT NULL THEN 0.20 ELSE 0 END+CASE WHEN "Matrix Delay Severity Score" IS NOT NULL THEN 0.20 ELSE 0 END+0.15))/10) "Matrix Stability Score"
 FROM a),
c AS (SELECT b.*,least(1,coalesce("Matrix Economic Contribution",0)*"Matrix Active Borrower Count"/2) "Matrix Scaled Economic Contribution" FROM b),
final AS (SELECT c.*,CASE WHEN "Has Active Loan"=false THEN NULL
 WHEN "Matrix Economic Contribution" IS NULL OR "Matrix Scaled Economic Contribution" IS NULL THEN 'Unclassified'
 WHEN "Matrix History Sufficient"=false THEN 'Provisional - insufficient history'
 WHEN "Matrix Economic Contribution">="Matrix Equal Share Benchmark" AND "Matrix Scaled Economic Contribution">=0.5 THEN 'Star'
 WHEN "Matrix Economic Contribution"<"Matrix Equal Share Benchmark" AND "Matrix Scaled Economic Contribution">=0.5 THEN 'Cash Cow'
 WHEN "Matrix Economic Contribution">="Matrix Equal Share Benchmark" AND "Matrix Scaled Economic Contribution"<0.5 THEN 'Question Mark' ELSE 'Dog' END "Matrix Quadrant" FROM c)

SELECT x."Row ID",
 x."Borrower Name",
 x."Description",
 x."Creation Date",
 x."Hidden Flag",
 x."Communication Name",
 x."Instagram Username",
 x."AI Collection Enabled",
 x."City",
 x."Working Location",
 x."Address",
 x."Total Interest Earned",
 x."Total Amount Loaned",
 x."Total Number of Loans",
 x."Total Outstanding Principal",
 x."Active Loan Interest Earned",
 x."Active Daily Interest",
 x."Has Closed Loan",
 x."Has Active Loan",
 x."Ref Referrer",
 round(x."Return on Active Principal"::numeric,2) AS "Return on Active Principal",
 round(x."Profit Last 30 Days"::numeric,0) AS "Profit Last 30 Days",
 x."Projected Interest Coverage Date",
 round(x."Closed Loan Interest Earned"::numeric,0) AS "Closed Loan Interest Earned",
 round(x."Closed Loan Principle"::numeric,0) AS "Closed Loan Principle",
 round(x."Return on Closed Loans"::numeric,2) AS "Return on Closed Loans",
 round(x."30D Gross Principal Days"::numeric,0) AS "30D Gross Principal Days",
 round(x."30D Principal Reduction Days"::numeric,0) AS "30D Principal Reduction Days",
 round(x."30D Average Outstanding Principal"::numeric,0) AS "30D Average Outstanding Principal",
 round(x."30D Return on Average Principal"::numeric,2) AS "30D Return on Average Principal",
 x."Daily Collection Status",
 round(x."Todays Amount Due"::numeric,0) AS "Todays Amount Due",
 round(x."Todays Amount Collected"::numeric,0) AS "Todays Amount Collected",
 round(x."Todays Amount Remaining"::numeric,0) AS "Todays Amount Remaining",
 round(x."Portfolio Exposure %"::numeric,4) AS "Portfolio Exposure %",
 x."Active Loan Count",
 x."Oldest Active Loan Age",
 round(x."Overdue Amount"::numeric,0) AS "Overdue Amount",
 x."Overdue Charge Count",
 x."Historical Charge Count",
 x."On Time Charge Count",
 round(x."Lifetime On Time Rate"::numeric,4) AS "Lifetime On Time Rate",
 x."Recent 30D Charge Count",
 x."Recent 30D On Time Count",
 round(x."Recent 30D On Time Rate"::numeric,4) AS "Recent 30D On Time Rate",
 x."Lifetime Late Payment Count",
 x."Recent 30D Late Payment Count",
 x."Maximum Days Late",
 x."Last Late Payment Date",
 round(x."Largest Successful Loan"::numeric,2) AS "Largest Successful Loan",
 round(x."Average Successful Loan Size"::numeric,2) AS "Average Successful Loan Size",
 x."Default Count",
 round(x."Lifetime Default Loss"::numeric,2) AS "Lifetime Default Loss",
 round(x."Portfolio Outstanding Principal"::numeric,0) AS "Portfolio Outstanding Principal",
 round(x."Projected Monthly Profit Contribution"::numeric,0) AS "Projected Monthly Profit Contribution",
 x."Matrix Active Borrower Count",
 round(x."Matrix Equal Share Benchmark"::numeric,4) AS "Matrix Equal Share Benchmark",
 round(x."Matrix Economic Contribution"::numeric,2) AS "Matrix Economic Contribution",
 x."Matrix Recent Reliability Score",
 x."Matrix Historical Reliability Score",
 x."Matrix Delay Severity Score",
 x."Matrix Current Condition Score",
 x."Matrix History Sufficient",
 x."Matrix Stability Score",
 x."Matrix Quadrant",
 round(x."Profit Last 10 Days"::numeric,0) AS "Profit Last 10 Days",
 round(x."Matrix Scaled Economic Contribution"::numeric,4) AS "Matrix Scaled Economic Contribution",
 round(x."Total Referral Rebate Earned"::numeric,0) AS "Total Referral Rebate Earned" FROM final x;

CREATE VIEW public.olap_portfolio_summary AS
WITH ctx AS (SELECT d, date_trunc('month',d)::date ms,
 (date_trunc('month',d)+interval '1 month - 1 day')::date me FROM (SELECT public.olap_reporting_date() d) q),

lr AS (SELECT coalesce(sum("Outstanding Principal"),0) principal,count(*) FILTER(WHERE "Loan Status"='ยังไม่ปิดยอด') active,
 coalesce(sum("Expected Interest This Month"),0) forecast,coalesce(sum("Principal Days MTD"),0) days,
 coalesce(sum("Expected Daily Interest Amount"),0) daily,coalesce(sum("Total Interest Received") FILTER(WHERE "Loan Status"='ยังไม่ปิดยอด'),0) active_profit FROM public.olap_loans_analytics),
rr AS (SELECT coalesce(sum("Interest Paid"::numeric),0) profit,coalesce(sum("Interest Paid"::numeric) FILTER(WHERE "Payment Date"=d),0) today,
 coalesce(sum("Interest Paid"::numeric) FILTER(WHERE "Payment Date"=d-1),0) yesterday,coalesce(sum("Interest Paid"::numeric) FILTER(WHERE "Payment Date" BETWEEN ms AND me),0) mtd,
 coalesce(sum("Principal Returned Days MTD"),0) returned_days,coalesce(sum("Partner A Profit"),0) profit_a,coalesce(sum("Partner B Profit"),0) profit_b
 FROM public.olap_repayments_analytics CROSS JOIN ctx),
cr AS (SELECT coalesce(sum("Amount Remaining") FILTER(WHERE nullif("Ref Loans",'') IS NOT NULL AND "Charge Date"<=d),0) pending,
 coalesce(sum("Interest Remaining") FILTER(WHERE nullif("Ref Loans",'') IS NOT NULL AND "Charge Date"<=d),0) interest,
 coalesce(sum("Amount Due") FILTER(WHERE "Charge Date"=d),0) due,coalesce(sum("Total Paid") FILTER(WHERE "Charge Date"=d),0) paid,
 coalesce(sum("Amount Remaining") FILTER(WHERE "Charge Date"=d),0) remaining FROM public.olap_charges_analytics CROSS JOIN ctx),
br AS (SELECT count(*) FILTER(WHERE "Daily Collection Status"='Fully Paid') full_count,count(*) FILTER(WHERE "Daily Collection Status"='Partially Paid') partial_count,
 count(*) FILTER(WHERE "Daily Collection Status"='Overdue') overdue_count,count(*) FILTER(WHERE "Daily Collection Status"='Not Paid') notpaid_count FROM public.olap_borrowers_analytics),
top3 AS (SELECT coalesce(sum(v),0) total FROM (SELECT "Total Outstanding Principal" v FROM public."Borrowers" WHERE "Total Outstanding Principal">0 ORDER BY 1 DESC LIMIT 3) q),
pool AS (SELECT coalesce(sum(CASE WHEN "Transaction Type"='Contribution' THEN "Amount"::numeric ELSE -"Amount"::numeric END),0) total FROM public."Cash Pool Contributions"),
settled AS (SELECT coalesce(sum(s."Amount"::numeric),0) total FROM public."Settlements" s JOIN public."Partners" p ON p."Row ID"=s."Ref Partner" WHERE s."Status"='Completed'),
earned AS (SELECT coalesce(sum(CASE p."Partner Role" WHEN 'A' THEN rr.profit_a WHEN 'B' THEN rr.profit_b ELSE 0 END),0) total FROM public."Partners" p CROSS JOIN rr),
er AS (SELECT coalesce(sum("Amount"::numeric),0) total,coalesce(sum("Amount"::numeric) FILTER(WHERE "Expense Date" BETWEEN ms AND d),0) mtd FROM public."Business Expenses" CROSS JOIN ctx),
recent AS (SELECT a.* FROM public."Daily Analytics" a WHERE a."Snapshot Date">=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Bangkok')-interval '30 days'),
peak AS (SELECT coalesce(max("Outstanding Principal EOD"::numeric),0) amount FROM recent),
peakdate AS (SELECT max("Snapshot Date") dt FROM recent CROSS JOIN peak WHERE "Outstanding Principal EOD"::numeric=peak.amount),
a AS (SELECT s."Row ID",s."Statistics ID",rr.profit "Total Profit",lr.principal "Outstanding Principal",lr.principal "Total Outstanding Principal",
 lr.active "Active Loans",rr.today "Today's Profit",rr.yesterday "Yesterday's Profit",rr.mtd "Realized Profit MTD",
 rr.mtd+cr.interest+lr.forecast "Projected Monthly Profit",cr.pending "Pending Payment Amount",lr.forecast "Forecast Remaining Interest",cr.interest "Today's Outstanding Interest",
 lr.days-rr.returned_days "Net Principal Days MTD",lr.principal*(me-d) "Forecast Remaining Principal Days",
 round((lr.days-rr.returned_days+lr.principal*(me-d))/extract(day FROM me)) "Forecast Average Daily Outstanding Principal",
 peak.amount "Peak Cash Pool 30D",peakdate.dt "Peak Cash Pool Date 30D",lr.daily "Expected Daily Interest",lr.active_profit "Total Profit of Outstanding Loans",
 CASE WHEN lr.principal>0 THEN lr.active_profit/lr.principal ELSE 0 END "Profit Coverage of Outstanding Principal",
 pool.total "Total Cash Pool",earned.total-settled.total "Total Unsettled Profit",
 pool.total-lr.principal+earned.total-settled.total "Expected Loan Account Balance",
 CASE WHEN lr.principal=0 THEN 0 ELSE top3.total/lr.principal END "Top 3 Borrower Concentration",
 br.full_count "Borrowers Fully Paid Today",br.partial_count "Borrowers Partially Paid Today",br.overdue_count "Borrowers with Overdue Payment",br.notpaid_count "Borrowers Not Paid Today",
 cr.due "Amount Due Today",cr.paid "Amount Collected Today",cr.remaining "Amount Outstanding Today",
 CASE WHEN cr.due=0 THEN 0 ELSE cr.paid/cr.due END "Amount Collection Rate Today",
 er.total "Total Business Expenses",rr.profit-er.total "Net Profit",er.mtd "Expenses MTD",rr.mtd-er.mtd "Net Profit MTD",
 earned.total-settled.total-er.total "Net Unsettled Profit",pool.total-lr.principal+earned.total-settled.total-er.total "Net Expected Loan Account Balance",
 rr.mtd "Operating Income MTD",-er.mtd "Income Statement Expenses MTD"
 FROM public."Statistics" s CROSS JOIN ctx CROSS JOIN lr CROSS JOIN rr CROSS JOIN cr CROSS JOIN br CROSS JOIN top3 CROSS JOIN pool CROSS JOIN settled CROSS JOIN earned CROSS JOIN er CROSS JOIN peak CROSS JOIN peakdate),
final AS (SELECT a.*,CASE WHEN "Forecast Average Daily Outstanding Principal">0 THEN "Projected Monthly Profit"/"Forecast Average Daily Outstanding Principal" ELSE 0 END "Forecast Monthly Return on ADO" FROM a)

SELECT x."Row ID",
 x."Statistics ID",
 round(x."Total Profit"::numeric,0) AS "Total Profit",
 round(x."Outstanding Principal"::numeric,0) AS "Outstanding Principal",
 x."Active Loans",
 round(x."Today's Profit"::numeric,0) AS "Today's Profit",
 round(x."Yesterday's Profit"::numeric,0) AS "Yesterday's Profit",
 round(x."Realized Profit MTD"::numeric,0) AS "Realized Profit MTD",
 round(x."Projected Monthly Profit"::numeric,0) AS "Projected Monthly Profit",
 round(x."Pending Payment Amount"::numeric,0) AS "Pending Payment Amount",
 round(x."Forecast Remaining Interest"::numeric,0) AS "Forecast Remaining Interest",
 round(x."Today's Outstanding Interest"::numeric,0) AS "Today's Outstanding Interest",
 x."Net Principal Days MTD",
 x."Forecast Remaining Principal Days",
 round(x."Forecast Average Daily Outstanding Principal"::numeric,0) AS "Forecast Average Daily Outstanding Principal",
 round(x."Forecast Monthly Return on ADO"::numeric,2) AS "Forecast Monthly Return on ADO",
 round(x."Peak Cash Pool 30D"::numeric,0) AS "Peak Cash Pool 30D",
 x."Peak Cash Pool Date 30D",
 round(x."Expected Daily Interest"::numeric,0) AS "Expected Daily Interest",
 round(x."Total Profit of Outstanding Loans"::numeric,0) AS "Total Profit of Outstanding Loans",
 round(x."Profit Coverage of Outstanding Principal"::numeric,2) AS "Profit Coverage of Outstanding Principal",
 round(x."Total Cash Pool"::numeric,0) AS "Total Cash Pool",
 round(x."Total Unsettled Profit"::numeric,0) AS "Total Unsettled Profit",
 round(x."Expected Loan Account Balance"::numeric,0) AS "Expected Loan Account Balance",
 round(x."Total Outstanding Principal"::numeric,0) AS "Total Outstanding Principal",
 round(x."Top 3 Borrower Concentration"::numeric,4) AS "Top 3 Borrower Concentration",
 x."Borrowers Fully Paid Today",
 x."Borrowers Partially Paid Today",
 x."Borrowers with Overdue Payment",
 x."Borrowers Not Paid Today",
 round(x."Amount Due Today"::numeric,0) AS "Amount Due Today",
 round(x."Amount Collected Today"::numeric,0) AS "Amount Collected Today",
 round(x."Amount Outstanding Today"::numeric,0) AS "Amount Outstanding Today",
 x."Amount Collection Rate Today",
 round(x."Total Business Expenses"::numeric,0) AS "Total Business Expenses",
 round(x."Net Profit"::numeric,0) AS "Net Profit",
 round(x."Expenses MTD"::numeric,0) AS "Expenses MTD",
 round(x."Net Profit MTD"::numeric,0) AS "Net Profit MTD",
 round(x."Net Unsettled Profit"::numeric,0) AS "Net Unsettled Profit",
 round(x."Net Expected Loan Account Balance"::numeric,0) AS "Net Expected Loan Account Balance",
 round(x."Income Statement Expenses MTD"::numeric,0) AS "Income Statement Expenses MTD",
 round(x."Operating Income MTD"::numeric,0) AS "Operating Income MTD" FROM final x;
