[CmdletBinding()]
param(
 [ValidateSet('development','production')][string]$Environment='development'
)
. "$PSScriptRoot/Common.ps1"
$target=Get-DbEnvironment $Environment
$sql=@'
SELECT jsonb_build_object('kind','db_column','table',table_name,'name',column_name,'position',ordinal_position,'type',data_type,'nullable',is_nullable,'default',column_default) FROM information_schema.columns WHERE table_schema='public' AND (table_name='Business Expenses' OR (table_name='Borrowers' AND column_name='Ref Referrer') OR (table_name='Daily Analytics' AND column_name IN ('Business Expenses','Net Profit','Net Unsettled Profit EOD'))) ORDER BY table_name,ordinal_position;
SELECT jsonb_build_object('kind','db_constraint','table',c.conrelid::regclass::text,'name',c.conname,'type',c.contype,'validated',c.convalidated,'definition',pg_get_constraintdef(c.oid)) FROM pg_constraint c WHERE c.conrelid='public."Business Expenses"'::regclass OR (c.conrelid='public."Borrowers"'::regclass AND (c.conname='borrower_not_own_referrer' OR c.conname LIKE '%Ref Referrer%'));
SELECT jsonb_build_object('kind','db_index','table',tablename,'name',indexname,'definition',indexdef) FROM pg_indexes WHERE schemaname='public' AND (tablename='Business Expenses' OR indexname='borrowers_referrer_idx');
SELECT jsonb_build_object('kind','synthetic_referral','id',e."Row ID",'loan',e."Ref Related Loan",'amount',e."Amount"::numeric,'basis',e."Gross Profit Basis"::numeric,'a',e."Partner A Expense"::numeric,'b',e."Partner B Expense"::numeric,'payee_matches',e."Ref Payee Borrower"=b."Ref Referrer",'borrower_matches',e."Ref Related Borrower"=l."Ref Borrowers",'source_key',e."Source Key") FROM public."Business Expenses" e JOIN public."Loans" l ON l."Row ID"=e."Ref Related Loan" JOIN public."Borrowers" b ON b."Row ID"=l."Ref Borrowers" WHERE l."Loan Arrangement" LIKE 'BE15-%';
SELECT jsonb_build_object('kind','synthetic_loan','id',l."Row ID",'principal',l."Principal Amount"::numeric,'gross',l."Total Interest Received"::numeric,'status',l."Loan Status",'auto_charge',l."Auto Charge Enabled",'referrer_present',b."Ref Referrer" IS NOT NULL,'charges',(SELECT count(*) FROM public."Charges" WHERE "Ref Loans"=l."Row ID")) FROM public."Loans" l JOIN public."Borrowers" b ON b."Row ID"=l."Ref Borrowers" WHERE l."Loan Arrangement" LIKE 'BE15-%';
SELECT jsonb_build_object('kind','net_analytics','dates',count(*),'mismatches',count(*) FILTER(WHERE "Business Expenses" IS DISTINCT FROM coalesce((SELECT sum("Amount") FROM public."Business Expenses" e WHERE e."Expense Date"=d."Snapshot Date"),0::money) OR "Net Profit" IS DISTINCT FROM "Interest Received"-"Business Expenses" OR "Net Unsettled Profit EOD" IS DISTINCT FROM "Unsettled Profit EOD"-coalesce((SELECT sum("Amount") FROM public."Business Expenses" e WHERE e."Expense Date"<=d."Snapshot Date"),0::money)),'oldest_refresh',min("Generated At")) FROM public."Daily Analytics" d;
WITH alloc AS (SELECT p."Partner Role" role,r."Interest Paid"::numeric interest,CASE WHEN c.pool>0 THEN coalesce(c.owned,0)/c.pool ELSE 0 END share FROM public."Partners" p CROSS JOIN public."Repayments" r CROSS JOIN LATERAL (SELECT sum(CASE WHEN c."Transaction Type"='Contribution' THEN c."Amount"::numeric ELSE -c."Amount"::numeric END) pool,sum(CASE WHEN c."Transaction Type"='Contribution' THEN c."Amount"::numeric ELSE -c."Amount"::numeric END) FILTER(WHERE cp."Partner Role"=p."Partner Role") owned FROM public."Cash Pool Contributions" c LEFT JOIN public."Partners" cp ON cp."Row ID"=c."Ref Partner" WHERE c."Contribution Date"<=r."Payment Date") c WHERE p."Partner Role" IN ('A','B')) SELECT jsonb_build_object('kind','rounding_diagnostic','role',role,'exact',sum(interest*share),'row_whole',sum(round(interest*share)),'percent_whole',sum(interest*round(share,2)),'two_decimals',sum(round(interest*share,2))) FROM alloc GROUP BY role;
SELECT jsonb_build_object('kind','expense_summary','count',count(*),'referrals',count(*) FILTER(WHERE "Source Type"='Referral Rebate'),'amount',sum("Amount"::numeric),'a',sum("Partner A Expense"::numeric),'b',sum("Partner B Expense"::numeric)) FROM public."Business Expenses";
SELECT jsonb_build_object('kind','synthetic_expense','id',"Row ID",'date',"Expense Date",'amount',"Amount"::numeric,'source',"Source Type",'a_share',"Partner A Share",'b_share',"Partner B Share",'a',"Partner A Expense"::numeric,'b',"Partner B Expense"::numeric,'allocation',"Allocation Basis",'created_at',"Created At") FROM public."Business Expenses" WHERE "Notes" LIKE '%BE15-%' ORDER BY "Created At";
SELECT jsonb_build_object('kind','partner_reconciliation','role',p."Partner Role",'gross',public.partner_net_profit(p."Row ID")+coalesce((SELECT sum(CASE WHEN p."Partner Role"='A' THEN "Partner A Expense"::numeric ELSE "Partner B Expense"::numeric END) FROM public."Business Expenses"),0),'net',public.partner_net_profit(p."Row ID"),'settlements',coalesce((SELECT sum("Amount"::numeric) FROM public."Settlements" WHERE "Ref Partner"=p."Row ID"),0)) FROM public."Partners" p WHERE p."Partner Role" IN ('A','B') ORDER BY p."Partner Role";
'@
$prior=@{};foreach($name in @('PGPASSWORD','PGSSLMODE','PGCONNECT_TIMEOUT')){$prior[$name]=[Environment]::GetEnvironmentVariable($name,'Process')}
try{
 $env:PGPASSWORD=(Get-Content -LiteralPath $target.passwordFile -Raw).Trim();$env:PGSSLMODE='require';$env:PGCONNECT_TIMEOUT='10'
 $sql | & (Join-Path (Get-PgBin) 'psql.exe') -X -v ON_ERROR_STOP=1 -h $target.host -U $target.user -d $target.database -At
 if($LASTEXITCODE){throw 'Read-only acceptance audit failed'}
}finally{foreach($name in $prior.Keys){[Environment]::SetEnvironmentVariable($name,$prior[$name],'Process')}}
