import test from 'node:test';import assert from 'node:assert/strict';
import {createDevReadHandler} from '../../services/api/dev-read-handler.mjs';
import {createBorrowerReadStore} from '../../services/api/borrower-read-store.mjs';
import {encodeCollectionCursor,decodeCollectionCursor,projectCollection} from '../../services/api/collection-read-contract.mjs';
const config={ownerEmail:'owner@example.test',origin:'https://client.example.test'};
const board={kind:'collection',businessDate:'2026-10-07',rank:0,id:'a'};const child={kind:'collection-charges',businessDate:'2026-10-07',parentId:'p',chargeDate:'2026-10-07',id:'c'};
test('Collection canonical cursor rejects kind parent date rank extra-field and obsolete substitution',()=>{const b=encodeCollectionCursor(board),c=encodeCollectionCursor(child);assert.equal(decodeCollectionCursor(b,'collection').id,'a');assert.equal(decodeCollectionCursor(c,'collection-charges','p').id,'c');for(const [cursor,kind,parent] of [[b,'collection-charges','p'],[c,'collection'],[c,'collection-charges','other'],[b+'=','collection'],[Buffer.from(JSON.stringify({...board,v:2})).toString('base64url'),'collection'],[Buffer.from(JSON.stringify({...board,v:1,extra:true})).toString('base64url'),'collection']])assert.throws(()=>decodeCollectionCursor(cursor,kind,parent));for(const value of [{...board,businessDate:'0000-01-01'},{...child,chargeDate:'0000-01-01'},{...board,rank:4},{...board,businessDate:'2026-02-30'},{...child,chargeDate:null}])assert.throws(()=>encodeCollectionCursor(value))});
async function request(handler,url,method='GET'){let status,body;await handler({method,url,headers:{authorization:'Bearer synthetic'}},{setHeader(){},set statusCode(v){status=v},end(v){body=v?JSON.parse(v):null}});return{status,body}}
test('Collection auth denial and invalid HTTP inputs never call business store',async()=>{let calls=0;const store={listCollection:async()=>{calls++;return{ok:true}},getCollectionCharges:async()=>{calls++;return{ok:true}}};for(const code of ['sign_in_required','session_invalid','access_denied']){const h=createDevReadHandler({config,store,verifyPrincipal:async()=>({ok:false,status:code==='access_denied'?403:401,code})});for(const url of ['/api/collection','/api/collection/p/charges'])assert.equal((await request(h,url)).body.code,code)}const h=createDevReadHandler({config,store,verifyPrincipal:async()=>({ok:true,email:config.ownerEmail})});for(const url of ['/api/collection?businessDate=2026-01-01','/api/collection?status=paid','/api/collection?limit=2&limit=3','/api/collection?limit=-1','/api/collection/%ZZ/charges','/api/collection/p/charges?cursor=a&cursor=b'])assert.equal((await request(h,url)).status,400);assert.equal((await request(h,'/api/collection','POST')).status,405);assert.equal(calls,0)});
test('Collection invalid bounded store requests reject without database connection and projections exclude extras',async()=>{let connects=0;const store=createBorrowerReadStore({config,pool:{connect:async()=>{connects++;throw Error()}}});for(const options of [{limit:0},{limit:101},{limit:1.5},{cursor:'%%%'}])assert.equal((await store.listCollection(config.ownerEmail,options)).status,400);assert.equal((await store.getCollectionCharges(config.ownerEmail,'other',{cursor:encodeCollectionCursor(child)})).status,400);assert.equal(connects,0);const value=projectCollection({id:'a',rank:3,borrower_name:'Name',borrower_description:'English',amount_due:'0',amount_collected:'-1.01',amount_remaining:null,privateBank:'never'});assert.equal(value.amountCollected,'-1.01');assert.equal(JSON.stringify(value).includes('never'),false);assert.equal(Object.keys(value).length,6)});
