import test from 'node:test';
import assert from 'node:assert/strict';
import {loadDevReadConfig,DEV_PROJECT,DEV_INSTANCE,OWNER_EMAIL} from '../../services/api/dev-read-config.mjs';
import {createFirebasePrincipalVerifier} from '../../services/api/firebase-principal.mjs';
import {createBorrowerReadStore,encodeCursor,decodeCursor} from '../../services/api/borrower-read-store.mjs';
import {createDevReadHandler} from '../../services/api/dev-read-handler.mjs';
const env=()=>({APP_ENV:'dev',AUTH_MODE:'firebase',FIREBASE_PROJECT_ID:DEV_PROJECT,DB_NAME:'loan_manager_dev',INSTANCE_CONNECTION_NAME:DEV_INSTANCE,DB_USER:'mw-credit-app-read-dev@clever-oasis-508610-n7.iam',OWNER_IDENTITY_MODE:'uid-pinned',OWNER_FIREBASE_UID:'synthetic-owner-uid',ALLOWED_WEB_ORIGINS:JSON.stringify(['https://mw-credit-app-dev-737787224638.web.app'])});
const config=()=>loadDevReadConfig(env());
const claims=()=>({aud:DEV_PROJECT,iss:`https://securetoken.google.com/${DEV_PROJECT}`,sub:'synthetic-owner-uid',exp:2000,iat:900,auth_time:900,email_verified:true,email:OWNER_EMAIL.toUpperCase(),firebase:{sign_in_provider:'google.com'}});
const verifier=(fn=async()=>claims())=>createFirebasePrincipalVerifier(fn,{ownerUid:'synthetic-owner-uid',identityMode:'uid-pinned',now:()=>1000000});
const sample=(id='sample-1')=>({id,name:'Synthetic borrower',createdDate:'2026-10-07',hasActiveLoan:true,outstandingPrincipal:'1234.56',note:null,bankAccount:'not-for-dto',address:'not-for-dto',email:'not-for-dto',file:'not-for-dto'});
function fixture({mapping=[{id:'synthetic-partner'}],rows=[sample()],identity,throwQuery}={}){
 const queries=[];let connects=0,releases=0;
 const client={query:async(sql,params)=>{queries.push({sql,params});if(throwQuery&&sql.includes(throwQuery))throw Error('private-error-detail');if(sql.includes('current_database'))return{rows:identity||[{database:'loan_manager_dev',principal:config().dbUser}]};if(sql.includes('public."Partners"'))return{rows:mapping};if(sql.includes('public."Borrowers"'))return{rows};return{rows:[]}},release:()=>releases++};
 const pool={connect:async()=>{connects++;return client}};
 return{store:createBorrowerReadStore({pool,config:config(),now:()=>new Date('2026-10-07T18:00:00Z')}),queries,counts:()=>({connects,releases})};
}
async function request(handler,{url='/api/borrowers',method='GET',headers={authorization:'Bearer synthetic-token'}}={}){const result={headers:{},status:0,body:null};const res={setHeader:(key,value)=>result.headers[key.toLowerCase()]=value,set statusCode(value){result.status=value},end:body=>result.body=body?JSON.parse(body):null};await handler({url,method,headers},res);return result;}
test('DEV configuration pins project database principal origin and disables emulator',()=>{assert.equal(config().ownerEmail,OWNER_EMAIL);for(const key of ['APP_ENV','AUTH_MODE','FIREBASE_PROJECT_ID','DB_NAME','INSTANCE_CONNECTION_NAME','DB_USER','OWNER_IDENTITY_MODE','OWNER_FIREBASE_UID','ALLOWED_WEB_ORIGINS']){const bad=env();bad[key]='';assert.throws(()=>loadDevReadConfig(bad),key)}assert.throws(()=>loadDevReadConfig({...env(),FIREBASE_AUTH_EMULATOR_HOST:'localhost:9099'}))});
test('real verifier seam invokes revocation checking and normalizes owner identity',async()=>{let args;const verify=verifier(async(...a)=>{args=a;return claims()});assert.deepEqual(await verify('Bearer opaque-test-token'),{ok:true,subject:'synthetic-owner-uid',email:OWNER_EMAIL});assert.deepEqual(args,['opaque-test-token',true])});
test('missing malformed and oversized bearer never reach verifier',async()=>{let calls=0;const verify=verifier(async()=>{calls++;return claims()});for(const value of [undefined,'','Basic value','Bearer one two','Bearer '+('x'.repeat(17000))])assert.equal((await verify(value)).status,401);assert.equal(calls,0)});
for(const [name,change] of [['audience',c=>c.aud='other'],['issuer',c=>c.iss='other'],['expired',c=>c.exp=1000],['future issued',c=>c.iat=1001],['future auth',c=>c.auth_time=1001],['unverified email',c=>c.email_verified=false],['password provider',c=>c.firebase.sign_in_provider='password'],['tenant',c=>c.firebase.tenant='other'],['missing subject',c=>c.sub='']])test('Firebase boundary rejects '+name,async()=>{const c=claims();change(c);assert.deepEqual(await verifier(async()=>c)('Bearer token'),{ok:false,status:401,code:'session_invalid'})});
for(const reason of ['auth/id-token-revoked','auth/user-disabled','auth/id-token-expired','auth/invalid-id-token'])test('SDK rejection sanitized '+reason,async()=>{assert.deepEqual(await verifier(async()=>{throw Object.assign(Error('secret'),{code:reason})})('Bearer token'),{ok:false,status:401,code:'session_invalid'})});
test('valid nonowner email or UID denied independently',async()=>{for(const change of [c=>c.email='other@example.test',c=>c.sub='different-uid']){const c=claims();change(c);assert.deepEqual(await verifier(async()=>c)('Bearer token'),{ok:false,status:403,code:'access_denied'})}});
test('denied bearer and nonowner stop before any SQL',async()=>{const f=fixture();for(const verifyPrincipal of [verifier(async()=>{throw Error('token')}),verifier(async()=>({...claims(),email:'other@example.test'}))]){const response=await request(createDevReadHandler({config:config(),verifyPrincipal,store:f.store}));assert.ok([401,403].includes(response.status));assert.equal(response.headers['cache-control'],'no-store')}assert.equal(f.counts().connects,0)});
test('unique Login Email mapping precedes Borrowers and absent/duplicate maps deny',async()=>{for(const mapping of [[],[{id:'a'},{id:'b'}]]){const f=fixture({mapping});assert.equal((await f.store.listBorrowers(OWNER_EMAIL)).code,'access_denied');assert.equal(f.queries.some(q=>q.sql.includes('public."Borrowers"')),false);assert.equal(f.queries.at(-1).sql,'ROLLBACK');assert.equal(f.counts().releases,1)}});
test('identity mismatch never reads Partners or Borrowers',async()=>{const f=fixture({identity:[{database:'loan_manager_prod',principal:config().dbUser}]});assert.equal((await f.store.listBorrowers(OWNER_EMAIL)).code,'read_unavailable');assert.equal(f.queries.some(q=>q.sql.includes('public.')),false)});
test('read-only transaction parameterizes pagination and exposes only allowlisted DTO',async()=>{const f=fixture({rows:[sample('row-2'),sample('row-3')]});const result=await f.store.listBorrowers(OWNER_EMAIL,{limit:1,cursor:encodeCursor({...sample(),id:"row-1' OR true--"})});assert.equal(result.items.length,1);assert.equal(result.items[0].outstandingPrincipal,'1234.56');assert.equal(result.items[0].note,null);assert.equal(JSON.stringify(result).includes('not-for-dto'),false);assert.equal(result.nextCursor,encodeCursor(sample('row-2')));assert.equal(result.businessDate,'2026-10-08');assert.equal(result.source,'dev');assert.equal(f.queries[0].sql,'BEGIN READ ONLY');const mapping=f.queries.find(q=>q.sql.includes('public."Partners"'));assert.deepEqual(mapping.params,[OWNER_EMAIL]);assert.match(mapping.sql,/"Login Email"/);const sql=f.queries.find(q=>q.sql.includes('public."Borrowers"'));assert.match(sql.sql,/"Hidden Flag" IS FALSE/);assert.match(sql.sql,/COLLATE "C"/);assert.deepEqual(sql.params,[true,0,"2026-10-07","row-1' OR true--",2]);assert.equal(sql.sql.includes('OR true--'),false);assert.equal(f.queries.at(-1).sql,'COMMIT');assert.equal(f.counts().releases,1)});
test('malformed limits and cursors reject without connecting',async()=>{const f=fixture();for(const options of [{limit:0},{limit:101},{limit:1.5},{cursor:'%%%'}])assert.equal((await f.store.listBorrowers(OWNER_EMAIL,options)).status,400);assert.equal(f.counts().connects,0);assert.equal(decodeCursor(encodeCursor(sample('synthetic-ไทย'))).id,'synthetic-ไทย');assert.throws(()=>decodeCursor('YQ='))});
test('detail parameterization hidden missing and invalid IDs stay generic',async()=>{const f=fixture({rows:[]});assert.equal((await f.store.getBorrower(OWNER_EMAIL,"x'--")).status,404);const q=f.queries.find(q=>q.sql.includes('public."Borrowers"'));assert.deepEqual(q.params,["x'--"]);assert.match(q.sql,/"Hidden Flag" IS FALSE/);for(const id of ['',null,'x'.repeat(257),'x\u0000'])assert.equal((await f.store.getBorrower(OWNER_EMAIL,id)).status,404)});
test('DB error rolls back releases and hides underlying private diagnostics',async()=>{const f=fixture({throwQuery:'public."Borrowers"'});assert.deepEqual(await f.store.listBorrowers(OWNER_EMAIL),{ok:false,status:503,code:'read_unavailable'});assert.equal(f.queries.at(-1).sql,'ROLLBACK');assert.equal(f.counts().releases,1)});
test('CORS and HTTP methods deny before auth or SQL; no credentials allowed',async()=>{let auth=0;const f=fixture();const handler=createDevReadHandler({config:config(),verifyPrincipal:async()=>{auth++;return {ok:false,status:401,code:'sign_in_required'}},store:f.store});for(const input of [{method:'POST'},{headers:{origin:'https://wrong.example.test'}},{method:'OPTIONS',headers:{origin:config().origins[0],'access-control-request-method':'POST'}}])assert.ok([403,405].includes((await request(handler,input)).status));assert.equal(auth,0);const good=await request(handler,{method:'OPTIONS',headers:{origin:config().origins[0],'access-control-request-method':'GET','access-control-request-headers':'Authorization'}});assert.equal(good.status,204);assert.equal(good.headers['access-control-allow-origin'],config().origins[0]);assert.equal(good.headers['access-control-allow-credentials'],undefined)});
test('unsupported or repeated list inputs never reach store and errors leak no auth',async()=>{const f=fixture(),handler=createDevReadHandler({config:config(),verifyPrincipal:verifier(),store:f.store});for(const url of ['/api/borrowers?search=secret','/api/borrowers?limit=1&limit=2','/api/borrowers?limit=1.5','/api/borrowers?cursor=a&cursor=b']){const response=await request(handler,{url});assert.equal(response.status,400);assert.equal(JSON.stringify(response).includes('synthetic-token'),false)}assert.equal(f.counts().connects,0)});
test('explicit email bootstrap allows verified owner without UID pin and never other email',async()=>{const e=env();e.OWNER_IDENTITY_MODE='email-bootstrap';delete e.OWNER_FIREBASE_UID;assert.equal(loadDevReadConfig(e).identityMode,'email-bootstrap');const verify=createFirebasePrincipalVerifier(async()=>({...claims(),sub:'first-owner-login'}),{identityMode:'email-bootstrap',now:()=>1000000});assert.equal((await verify('Bearer token')).ok,true);const denied=createFirebasePrincipalVerifier(async()=>({...claims(),email:'other@example.test'}),{identityMode:'email-bootstrap',now:()=>1000000});assert.equal((await denied('Bearer token')).status,403);const noMode=createFirebasePrincipalVerifier(async()=>claims(),{now:()=>1000000});assert.equal((await noMode('Bearer token')).status,403)});
test('malformed encoded detail ID returns client error with no SQL',async()=>{const f=fixture();const response=await request(createDevReadHandler({config:config(),verifyPrincipal:verifier(),store:f.store}),{url:'/api/borrowers/%ZZ'});assert.equal(response.status,400);assert.equal(f.counts().connects,0)});
test('public readiness path never triggers SQL',async()=>{const f=fixture();const handler=createDevReadHandler({config:config(),verifyPrincipal:verifier(),store:f.store});assert.equal((await request(handler,{url:'/readyz',headers:{}})).status,401);assert.equal((await request(handler,{url:'/readyz'})).status,404);assert.equal(f.counts().connects,0)});
test('nonreserved public health is static and legacy z paths cannot reach SQL',async()=>{const f=fixture();const handler=createDevReadHandler({config:config(),verifyPrincipal:verifier(),store:f.store});const health=await request(handler,{url:'/health',headers:{}});assert.equal(health.status,200);assert.deepEqual(health.body,{status:'ok',environment:'dev',service:'borrower-read'});assert.equal(health.headers['cache-control'],'no-store');assert.equal((await request(handler,{url:'/healthz',headers:{}})).status,401);assert.equal(f.counts().connects,0)});
