import test from 'node:test';
import assert from 'node:assert/strict';
import {createBorrowerReadStore,encodeCursor,decodeCursor} from '../../services/api/borrower-read-store.mjs';
import {encodeLoanCursor,decodeLoanCursor,borrowerDisplayName,projectLoan} from '../../services/api/loan-read-contract.mjs';
const config={ownerEmail:'owner@example.test',database:'loan_manager_dev',dbUser:'synthetic-reader'};
const rank=b=>b.hasActiveLoan===true?0:b.hasActiveLoan===false?1:2;
const loanRank=b=>b.status==='ยังไม่ปิดยอด'?0:b.status==='ปิดยอดแล้ว'?1:2;
const compare=(a,b,date,descending,r)=>r(a)-r(b)||(a[date]===b[date]?0:a[date]===null?1:b[date]===null?-1:(a[date]<b[date]?-1:1)*(descending?-1:1))||(a.id<b.id?-1:a.id>b.id?1:0);
function storeFor(rows,isLoan=false){const sqls=[];const client={release(){},async query(sql,p){sqls.push({sql,p});if(sql.includes('current_database'))return{rows:[{database:config.database,principal:config.dbUser}]};if(sql.includes('public."Partners"'))return{rows:[{id:'partner'}]};if(isLoan&&sql.includes('SELECT "Row ID" AS id FROM public."Borrowers"'))return{rows:[{id:'parent'}]};if(sql.includes(isLoan?'public."Loans"':'public."Borrowers"')){const [has,group,date,id,limit]=isLoan?p.slice(1):p;const key=isLoan?'loanDate':'createdDate';const fn=isLoan?loanRank:rank;const cursor={id,[key]:date,hasActiveLoan:group===0?true:group===1?false:null,status:group===0?'ยังไม่ปิดยอด':group===1?'ปิดยอดแล้ว':null};return{rows:rows.filter(row=>!has||compare(row,cursor,key,isLoan,fn)>0).sort((a,b)=>compare(a,b,key,isLoan,fn)).slice(0,limit)}}return{rows:[]}}};return{store:createBorrowerReadStore({pool:{connect:async()=>client},config}),sqls};}
for(const isLoan of [false,true])test(`${isLoan?'loan':'borrower'} grouped keyset traverses 58 unchanged fixtures without omission or duplicate`,async()=>{
 const rows=Array.from({length:58},(_,i)=>({id:'synthetic-'+String(i).padStart(2,'0'),borrowerId:'parent',hasActiveLoan:i<26?true:i<52?false:null,status:i<26?'ยังไม่ปิดยอด':i<52?'ปิดยอดแล้ว':i%2?'unexpected':null,createdDate:i%13===0?null:'2026-10-'+String(i%3+1).padStart(2,'0'),loanDate:i%13===0?null:'2026-10-'+String(i%3+1).padStart(2,'0'),name:'ชื่อ',description:'Name',totalProfitEarned:i===0?'-123.45':i===1?'0':null}));
 const f=storeFor(rows,isLoan);let cursor=null;const ids=[];let pages=0;do{const result=isLoan?await f.store.listLoans(config.ownerEmail,'parent',{cursor}):await f.store.listBorrowers(config.ownerEmail,{cursor});assert.equal(result.ok,true);ids.push(...result.items.map(x=>x.id));cursor=result.nextCursor;pages++;assert.ok(pages<=3)}while(cursor);assert.equal(pages,3);assert.equal(new Set(ids).size,58);assert.deepEqual(ids,[...rows].sort((a,b)=>compare(a,b,isLoan?'loanDate':'createdDate',isLoan,isLoan?loanRank:rank)).map(x=>x.id));
 const query=f.sqls.find(x=>x.sql.includes('ORDER BY'));assert.match(query.sql,/CASE WHEN/);assert.match(query.sql,/ELSE 2 END\) > \$[23]::integer OR/);assert.match(query.sql,/ELSE 2 END\) = \$[23]::integer AND/);assert.match(query.sql,isLoan?/"Loan Date" DESC NULLS LAST/:/"Creation Date" ASC NULLS LAST/);assert.match(query.sql,/"Row ID" COLLATE "C" ASC/);
});
test('v2 cursors reject obsolete cross-resource rank extra-fields and malformed shapes',()=>{const b={id:'a',createdDate:null,hasActiveLoan:false};const l={id:'a',loanDate:null,status:'ปิดยอดแล้ว'};const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');for(const value of [{v:1,id:'a'},{v:2,rank:3,createdDate:null,id:'a'},{v:2,rank:0,createdDate:'2026-02-30',id:'a'},{v:2,rank:0,createdDate:null,id:'a',extra:true}])assert.throws(()=>decodeCursor(enc(value)));assert.throws(()=>decodeCursor(encodeLoanCursor('parent',l)));assert.throws(()=>decodeLoanCursor(encodeCursor(b),'parent'));assert.throws(()=>decodeLoanCursor(encodeLoanCursor('other',l),'parent'));assert.equal(decodeCursor(encodeCursor(b)).rank,1);assert.equal(decodeLoanCursor(encodeLoanCursor('parent',l),'parent').rank,1)});
test('borrower label retains both names and source profit negative zero null independent of principal',async()=>{assert.equal(borrowerDisplayName('สมชาย','Somchai'),'สมชาย - Somchai');assert.equal(borrowerDisplayName(null,null),' - ');for(const value of ['-12.34','0',null]){const f=storeFor([{id:'a',name:'สมชาย',description:'Somchai',createdDate:null,hasActiveLoan:null,totalProfitEarned:value,outstandingPrincipal:'9000.00'}]);const result=await f.store.listBorrowers(config.ownerEmail);assert.equal(result.items[0].borrowerDisplayName,'สมชาย - Somchai');assert.equal(result.items[0].totalProfitEarned,value);assert.match(f.sqls.find(x=>x.sql.includes('ORDER BY')).sql,/"Total Interest Earned"::text AS "totalProfitEarned"/);}});
test('loan projection uses joined bilingual name and original source rate including zero',()=>{for(const rate of ['0','2',null]){const result=projectLoan({id:'l',borrowerId:'p',borrowerName:'สมชาย',borrowerDescription:'Somchai',loanDate:null,originalDailyInterestRate:rate},'p');assert.equal(result.borrowerDisplayName,'สมชาย - Somchai');assert.equal(result.originalDailyInterestRate,rate)}});
