import test from 'node:test';
import assert from 'node:assert/strict';
import {createBorrowerReadStore} from '../../services/api/borrower-read-store.mjs';
import {createDevReadHandler} from '../../services/api/dev-read-handler.mjs';
import {projectLoan,encodeLoanCursor,decodeLoanCursor} from '../../services/api/loan-read-contract.mjs';
const owner='owner@example.test';const config={ownerEmail:owner,database:'loan_manager_dev',dbUser:'synthetic-reader',origin:'https://client.example.test'};
const loan=(id='loan-a',extra={})=>({id,borrowerId:'borrower-a',loanDate:'2026-10-07',dueDate:'2026-11-07',closeDate:null,loanType:'กำหนดวันชำระ',status:'ยังไม่ปิดยอด',principalAmount:'1000.25',outstandingPrincipal:'800.20',totalPrincipalReceived:'200.05',totalInterestReceived:'35.50',totalAmountReceived:'235.55',defaulted:false,autoChargeEnabled:true,...extra});
function fixture({parents=[{id:'borrower-a'}],mapping=[{id:'partner-a'}],loans=[loan()],failure}={}){const queries=[];let connections=0,releases=0;const client={query:async(sql,params)=>{queries.push({sql,params});if(failure&&sql.includes(failure))throw Error('private synthetic diagnostic');if(sql.includes('current_database'))return{rows:[{database:config.database,principal:config.dbUser}]};if(sql.includes('public."Partners"'))return{rows:mapping};if(sql.includes('public."Loans"'))return{rows:loans};if(sql.includes('public."Borrowers"'))return{rows:parents};return{rows:[]}},release:()=>releases++};return{store:createBorrowerReadStore({pool:{connect:async()=>{connections++;return client}},config,now:()=>new Date('2026-10-07T05:00:00Z')}),queries,counts:()=>({connections,releases})};}
async function request(handler,url,authorization='Bearer synthetic'){const result={headers:{}};const res={setHeader:(key,value)=>result.headers[key]=value,set statusCode(s){result.status=s},end:body=>result.body=body?JSON.parse(body):null};await handler({method:'GET',url,headers:{authorization}},res);return result;}
const handler=f=>createDevReadHandler({config,verifyPrincipal:async()=>({ok:true,email:owner,subject:'synthetic'}),store:f.store});
test('nested reads recheck unique partner mapping and visible parent every time',async()=>{const f=fixture();await f.store.listLoans(owner,'borrower-a');await f.store.getLoan(owner,'borrower-a','loan-a');assert.equal(f.queries.filter(q=>q.sql.includes('public."Partners"')).length,2);for(const q of f.queries.filter(q=>q.sql.includes('public."Loans"'))){assert.match(q.sql,/JOIN public\."Borrowers"/);assert.match(q.sql,/b\."Hidden Flag" IS FALSE/);assert.match(q.sql,/b\."Row ID" = \$1/);assert.equal(q.params[0],'borrower-a')}assert.equal(f.queries.filter(q=>q.sql==='BEGIN READ ONLY').length,2);assert.equal(f.counts().releases,2)});
test('missing hidden or duplicate parent list yields generic404 and no Loans query',async()=>{for(const parents of [[],[{id:'a'},{id:'a'}]]){const f=fixture({parents});assert.deepEqual(await f.store.listLoans(owner,'borrower-a'),{ok:false,status:404,code:'not_found'});assert.equal(f.queries.some(q=>q.sql.includes('public."Loans"')),false)}});
test('missing or duplicate partner denies nested list/detail before Loans',async()=>{for(const mapping of [[],[{id:'a'},{id:'b'}]]){const f=fixture({mapping});assert.equal((await f.store.listLoans(owner,'borrower-a')).status,403);assert.equal((await f.store.getLoan(owner,'borrower-a','loan-a')).status,403);assert.equal(f.queries.some(q=>q.sql.includes('public."Loans"')),false)}});
test('wrong-parent detail is scoped by both parameters and empty result404',async()=>{const f=fixture({loans:[]});assert.deepEqual(await f.store.getLoan(owner,'borrower-b','loan-a'),{ok:false,status:404,code:'not_found'});const q=f.queries.find(q=>q.sql.includes('public."Loans"'));assert.deepEqual(q.params,['borrower-b','loan-a']);assert.match(q.sql,/l\."Row ID" = \$2/);assert.throws(()=>projectLoan(loan(),'borrower-b'))});
test('closed defaulted and null-date loans remain in list with no active status filter',async()=>{const rows=[loan('closed',{status:'ปิดยอดแล้ว',closeDate:'2026-10-01'}),loan('defaulted',{defaulted:true}),loan('undated',{loanDate:null})];const f=fixture({loans:rows});const result=await f.store.listLoans(owner,'borrower-a');assert.deepEqual(result.items.map(r=>r.id),['closed','defaulted','undated']);assert.equal(result.items[1].defaulted,true);const q=f.queries.find(q=>q.sql.includes('public."Loans"'));assert.match(q.sql,/ORDER BY l\."Loan Date" DESC NULLS LAST, l\."Row ID" COLLATE "C" ASC/);assert.doesNotMatch(q.sql,/AND.*(?:"Loan Status"|"Defaulted"|"Close Date")\s*=/)});
test('bounded pagination uses date/id cutoff and borrower-bound next cursor',async()=>{const f=fixture({loans:[loan('tie-a'),loan('tie-b')]});const result=await f.store.listLoans(owner,'borrower-a',{limit:1});assert.equal(result.items.length,1);assert.deepEqual(decodeLoanCursor(result.nextCursor,'borrower-a'),{v:1,borrowerId:'borrower-a',loanDate:'2026-10-07',id:'tie-a'});await f.store.listLoans(owner,'borrower-a',{limit:1,cursor:result.nextCursor});const qs=f.queries.filter(q=>q.sql.includes('public."Loans"'));assert.deepEqual(qs[1].params,['borrower-a',true,'2026-10-07','tie-a',2]);assert.match(qs[1].sql,/l\."Loan Date" < \$3::date OR l\."Loan Date" IS NULL/);assert.match(qs[1].sql,/l\."Loan Date" = \$3::date AND l\."Row ID" COLLATE "C" > \$4/);assert.throws(()=>decodeLoanCursor(result.nextCursor,'borrower-b'))});
test('null-date cursor remains within trailing null-date segment',async()=>{const f=fixture();const cursor=encodeLoanCursor('borrower-a',loan('null-a',{loanDate:null}));await f.store.listLoans(owner,'borrower-a',{cursor});const q=f.queries.find(q=>q.sql.includes('public."Loans"'));assert.deepEqual(q.params,['borrower-a',true,null,'null-a',26]);assert.match(q.sql,/\$3::date IS NULL AND l\."Loan Date" IS NULL AND l\."Row ID" COLLATE "C" > \$4/)});
test('malformed and cross-parent cursors or limits reject before SQL',async()=>{const f=fixture();for(const options of [{limit:0},{limit:101},{limit:1.2},{cursor:'%%%'},{cursor:encodeLoanCursor('other',loan())}])assert.equal((await f.store.listLoans(owner,'borrower-a',options)).status,400);assert.equal(f.counts().connections,0);for(const cursor of ['e30','not-json',encodeLoanCursor('borrower-a',loan())+'='])assert.throws(()=>decodeLoanCursor(cursor,'borrower-a'))});
test('loan projection preserves exact decimals null and safe fields without inference',()=>{const source=loan('id',{principalAmount:'999999999999999999.123456',outstandingPrincipal:null,defaulted:null,autoChargeEnabled:null,dueDate:'2026-02-30',closeDate:'invalid',bankAccount:'secret-bank',files:['secret-file']});const result=projectLoan(source,'borrower-a');assert.equal(result.principalAmount,'999999999999999999.123456');assert.equal(result.outstandingPrincipal,null);assert.equal(result.defaulted,null);assert.equal(result.autoChargeEnabled,null);assert.equal(result.dueDate,null);assert.equal(result.closeDate,null);assert.equal(JSON.stringify(result).includes('secret-'),false);assert.equal(Object.keys(result).length,14);assert.throws(()=>projectLoan(loan('bad',{loanDate:'2026-02-30'}),'borrower-a'));assert.equal(projectLoan(loan('bad',{principalAmount:12}),'borrower-a').principalAmount,null)});
test('invalid source or SQL failure returns sanitized unavailable and releases',async()=>{for(const options of [{loans:[loan('bad',{borrowerId:'other'})]},{failure:'public."Loans"'}]){const f=fixture(options);assert.deepEqual(await f.store.listLoans(owner,'borrower-a'),{ok:false,status:503,code:'read_unavailable'});assert.equal(f.queries.at(-1).sql,'ROLLBACK');assert.equal(f.counts().releases,1)}});
test('nested bad auth does not enter store; direct loan routes unavailable',async()=>{const f=fixture();const denied=createDevReadHandler({config,verifyPrincipal:async()=>({ok:false,status:401,code:'session_invalid'}),store:f.store});for(const url of ['/api/borrowers/a/loans','/api/borrowers/a/loans/l'])assert.equal((await request(denied,url)).status,401);assert.equal(f.counts().connections,0);assert.equal((await request(handler(f),'/api/loans/l')).status,404);assert.equal(f.counts().connections,0)});
test('nested routing rejects unsupported queries and malformed encoded IDs without SQL',async()=>{const f=fixture();for(const url of ['/api/borrowers/a/loans?limit=1&limit=2','/api/borrowers/a/loans?search=name','/api/borrowers/a/loans?limit=1.5','/api/borrowers/a/loans/l?cursor=x','/api/borrowers/%ZZ/loans'])assert.equal((await request(handler(f),url)).status,400);assert.equal(f.counts().connections,0)});
