import test from 'node:test';
import assert from 'node:assert/strict';
import {readPaymentRecord} from '../../services/business/payments.mjs';
import {closeSummary} from '../../services/payment-command/close-summary.mjs';
import {canonicalPaymentCorrection} from '../../services/contracts/payment-correction.mjs';
test('pinned UX allocation labels retain every historical line and do not enter canonical correction',async()=>{
 const rows=Array.from({length:27},(_,i)=>({id:'allocation-'+i,chargeId:'charge-'+i,chargeDate:'2026-10-09',allocationOrder:i+1,principal:'1',interest:'0',amount:'1',loanPrincipal:i%2?'200':'100',loanDate:'2026-10-01',rate:'0.1',loanBorrowerName:'Synthetic',loanBorrowerDescription:'TE',labelLoanId:i===26?null:'loan-'+i%2}));
 let allocationSql='';const client={query:async(sql,args)=>{assert.deepEqual(args,['synthetic-payment']);if(sql.includes('FROM public."Payments" p'))return{rows:[{id:'synthetic-payment'}]};if(sql.includes('pwa_payment_version'))return{rows:[{version:'a'.repeat(64)}]};if(sql.includes('pwa_effective_payment'))return{rows:[{value:null}]};if(sql.includes('FROM public."Payment Allocations"')){allocationSql=sql;return{rows}}return{rows:[]}}};
 const item=await readPaymentRecord(client,'synthetic-payment');assert.equal(item.allocations.length,27);assert.equal(item.allocations[0].chargeDate,'2026-10-09');assert.notEqual(item.allocations[0].loanDisplayKey,item.allocations[1].loanDisplayKey);assert.equal(item.allocations[26].loanDisplayKey,null);assert.match(allocationSql,/a\."Charge Date Snapshot"/);assert.match(allocationSql,/LEFT JOIN public\."Charges"/);assert.match(allocationSql,/LEFT JOIN public\."Loans"/);assert.doesNotMatch(allocationSql,/LIMIT|WHERE[^]*c\."Charge Date"/);assert.equal(item.allocations[26].principal,'1');
 const fields={borrowerId:'borrower',amountReceived:'27',paymentDate:'2026-10-09',paymentMethod:'Cash',cashAccountId:'account',notes:null,allocationMethod:'Selected Charges',targetChargeId:null,targetLoanId:null,allocations:rows.map(r=>({chargeId:r.chargeId,principal:r.principal,interest:r.interest,expectedPrincipalRemaining:'1',expectedInterestRemaining:'0',chargeDate:r.chargeDate}))};const input={kind:'pwa-plan',fields,receiptMode:'preserve'};const before=JSON.stringify(canonicalPaymentCorrection(input));await readPaymentRecord(client,'synthetic-payment');assert.equal(JSON.stringify(canonicalPaymentCorrection(input)),before);assert.ok(!before.includes('loanDisplayKey'));
});
test('pinned UX closing component summary uses exact plan cents including zero and mismatch',()=>{
 assert.deepEqual(closeSummary({amount:'0.30',allocations:[{principal:'0.10',interest:'0.20'}]}),{principalAmount:'0.10',interestAmount:'0.20'});assert.deepEqual(closeSummary({amount:'100',allocations:[{principal:'100',interest:'0'}]}),{principalAmount:'100.00',interestAmount:'0.00'});assert.deepEqual(closeSummary({amount:'9007199254740993.99',allocations:[{principal:'9007199254740993.98',interest:'0.01'}]}),{principalAmount:'9007199254740993.98',interestAmount:'0.01'});for(const calculation of[{amount:'0.31',allocations:[{principal:'0.10',interest:'0.20'}]},{amount:'0',allocations:[]},{amount:'1',allocations:[{principal:'bad',interest:'0'}]}])assert.deepEqual(closeSummary(calculation),{principalAmount:null,interestAmount:null});
});
