import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateReadAccess} from '../../services/api/read-access.mjs';
import {createSyntheticReadAdapter} from '../../services/api/synthetic-read-adapter.mjs';
const context=()=>({config:{mode:'synthetic',environment:'dev',issuer:'test-verifier',audience:'test-client'},nowMs:1000,principal:{serverVerified:true,emailVerified:true,subject:'s1',email:' Login@Example.Invalid ',expiresAtMs:2000,revoked:false,disabled:false,environment:'dev',issuer:'test-verifier',audience:'test-client'},grants:[{subject:'s1',environment:'dev',enabled:true,permissions:['oltp.read']}],partners:[{id:'partner-1',loginEmail:'login@example.invalid',deliveryEmail:'shared@example.invalid',role:'B'}]});
const row=(id,overrides={})=>({id,name:{en:'Sample '+id,th:'ตัวอย่าง'},initials:'S',area:{en:'Synthetic district',th:'สมมติ'},hidden:false,hasActiveLoan:true,outstandingPrincipal:'100.00',collection:{status:'not_paid',amountDue:'10.00',amountCollected:'0.00',amountRemaining:'10.00'},loans:[{id:'loan-'+id,outstandingPrincipal:'100.00',nextDate:'2026-10-08',charges:[{id:'charge-'+id,label:{en:'Charge',th:'เรียกเก็บ'},amount:'10.00',date:'2026-10-07'}]}],...overrides});
const adapter=(rows,ctx=context())=>createSyntheticReadAdapter({getAccessContext:()=>ctx,getRows:()=>rows,businessDate:'2026-10-07',asOf:'2026-10-07T05:00:00Z'});
test('allowed synthetic principal maps normalized login email only',()=>{assert.deepEqual(evaluateReadAccess(context()),{ok:true,partnerId:'partner-1',permission:'oltp.read'})});
for(const [label,change,code] of [
 ['missing configuration',c=>delete c.config,'configuration_invalid'],['non-synthetic mode',c=>c.config.mode='live','configuration_invalid'],['missing clock',c=>c.nowMs=NaN,'configuration_invalid'],['signed out',c=>c.principal=null,'signed_out'],
 ...['serverVerified','emailVerified'].map(key=>[key,c=>c.principal[key]=false,'access_denied']),
 ...['revoked','disabled'].map(key=>[key,c=>c.principal[key]=true,'access_denied']),
 ...['environment','issuer','audience'].map(key=>['wrong '+key,c=>c.principal[key]='wrong','access_denied']),
 ['expired at boundary',c=>c.principal.expiresAtMs=1000,'expired'],['missing expiry',c=>delete c.principal.expiresAtMs,'expired'],['blank subject',c=>c.principal.subject=' ','access_denied'],['missing revocation state',c=>delete c.principal.revoked,'access_denied'],
 ['no grant',c=>c.grants=[],'access_denied'],['disabled grant',c=>c.grants[0].enabled=false,'access_denied'],['wrong grant subject',c=>c.grants[0].subject='other','access_denied'],['wrong grant environment',c=>c.grants[0].environment='prod','access_denied'],['wrong permission',c=>c.grants[0].permissions=['oltp.write'],'access_denied'],['duplicate grant',c=>c.grants.push({...c.grants[0]}),'access_denied'],
 ['unmapped login',c=>c.partners=[],'unmapped_login'],['duplicate login mapping',c=>c.partners.push({...c.partners[0],id:'partner-2'}),'unmapped_login'],['delivery email is not login identity',c=>{c.partners[0].deliveryEmail='login@example.invalid';c.partners[0].loginEmail='other@example.invalid'},'unmapped_login'],['Partner A role grants nothing',c=>{c.grants=[];c.partners[0].role='A'},'access_denied']
])test('default deny: '+label,()=>{const ctx=context();change(ctx);assert.deepEqual(evaluateReadAccess(ctx),{ok:false,code})});
test('denied adapter never touches source or leaks records/counts',()=>{let reads=0;const a=createSyntheticReadAdapter({getAccessContext:()=>({...context(),principal:null}),getRows:()=>{reads++;throw Error('sensitive')},businessDate:'2026-10-07',asOf:'fixed'});for(const result of [a.listBorrowers(),a.listCollection(),a.getBorrowerDetail('secret')])assert.deepEqual(result,{ok:false,code:'signed_out'});assert.equal(reads,0)});
test('rechecks access on every read after revocation',()=>{const ctx=context(),a=adapter([row('one')],ctx);assert.equal(a.listBorrowers().ok,true);ctx.principal.revoked=true;assert.deepEqual(a.listBorrowers(),{ok:false,code:'access_denied'})});
test('collection status eligibility and order differ from borrower hidden membership',()=>{const rows=[row('fully',{collection:{status:'fully_paid',amountDue:'10.00',amountCollected:'10.00',amountRemaining:'0.00'}}),row('overdue',{hidden:true,collection:{status:'overdue',amountDue:'10.00',amountCollected:'0.00',amountRemaining:'10.00'}}),row('partial',{collection:{status:'partially_paid',amountDue:'10.00',amountCollected:'3.00',amountRemaining:'7.00'}}),row('unpaid'),row('not-in-collection',{collection:{status:null,amountDue:null,amountCollected:null,amountRemaining:null}})];const a=adapter(rows);assert.deepEqual(a.listCollection().items.map(r=>r.id),['unpaid','partial','overdue','fully']);assert.deepEqual(a.listBorrowers().items.map(r=>r.id),['fully','partial','unpaid','not-in-collection']);for(const item of a.listCollection().items)assert.equal(Number(item.collection.amountDue),Number(item.collection.amountCollected)+Number(item.collection.amountRemaining));assert.deepEqual(a.getBorrowerDetail('overdue'),{ok:false,code:'not_found'});assert.equal(a.getBorrowerDetail('overdue','collection').ok,true);assert.deepEqual(a.getBorrowerDetail('not-in-collection','collection'),{ok:false,code:'not_found'})});
test('detail unknown invalid ambiguous and wrong-view IDs return generic not found',()=>{const a=adapter([row('one')]);for(const result of [a.getBorrowerDetail('missing'),a.getBorrowerDetail(''),a.getBorrowerDetail(null),a.getBorrowerDetail(undefined),a.getBorrowerDetail('duplicate','unauthorized')])assert.deepEqual(result,{ok:false,code:'not_found'})});
test('DTO allowlist excludes sensitive fields recursively and keeps decimal/null semantics',()=>{const source=row('safe',{email:'private-email',bankAccount:'private-bank',address:'private-address',files:['private-file'],outstandingPrincipal:null});source.name.secret='private-name-extra';source.loans[0].bank='private-loan';source.loans[0].charges[0].receipt='private-receipt';const a=adapter([source]),list=a.listBorrowers(),detail=a.getBorrowerDetail('safe');assert.equal(list.source,'synthetic');assert.equal(list.timezone,'Asia/Bangkok');assert.equal(list.items[0].loans,undefined);assert.equal(detail.item.outstandingPrincipal,null);assert.equal(detail.item.collection.amountRemaining,'10.00');assert.equal(detail.item.loans[0].charges[0].amount,'10.00');assert.equal(JSON.stringify(detail).includes('private-'),false);detail.item.name.en='changed';assert.notEqual(source.name.en,'changed');assert.deepEqual(Object.keys(a).sort(),['getBorrowerDetail','listBorrowers','listCollection'])});
test('invalid money is null rather than false zero',()=>{const a=adapter([row('bad',{outstandingPrincipal:25,collection:{status:'not_paid',amountDue:'bad',amountCollected:null,amountRemaining:'NaN'}})]);assert.equal(a.listBorrowers().items[0].outstandingPrincipal,null);assert.deepEqual(a.listBorrowers().items[0].collection,{status:'not_paid',amountDue:null,amountCollected:null,amountRemaining:null})});
test('source cap and source errors fail without data',()=>{assert.deepEqual(adapter(Array.from({length:101},(_,i)=>row(String(i)))).listBorrowers(),{ok:false,code:'source_unavailable'});const a=createSyntheticReadAdapter({getAccessContext:context,getRows:()=>{throw Error('secret')},businessDate:'fixed',asOf:'fixed'});assert.deepEqual(a.listCollection(),{ok:false,code:'source_unavailable'})});
test('invalid source identity or status fails entire list rather than silently dropping records',()=>{for(const bad of [row(' '),row('bad',{hidden:'false'}),row('bad',{collection:{status:'unexpected'}})]){const a=adapter([row('good'),bad]);assert.deepEqual(a.listCollection(),{ok:false,code:'source_unavailable'});assert.deepEqual(a.listBorrowers(),{ok:false,code:'source_unavailable'})}assert.deepEqual(adapter([row('same'),row('same')]).getBorrowerDetail('same'),{ok:false,code:'source_unavailable'})});
test('invalid envelope dates fail closed',()=>{for(const [businessDate,asOf] of [['2026-02-30','2026-10-07T05:00:00Z'],['2026-10-07','invalid'],['2026-10-07','2026-02-30T05:00:00Z']]){const a=createSyntheticReadAdapter({getAccessContext:context,getRows:()=>[row('one')],businessDate,asOf});assert.deepEqual(a.listBorrowers(),{ok:false,code:'source_unavailable'})}});
test('impossible detail dates become null and stable charge IDs survive projection',()=>{const source=row('one');source.loans[0].nextDate='2026-02-30';source.loans[0].charges[0].date='2026-13-01';const detail=adapter([source]).getBorrowerDetail('one');assert.equal(detail.item.loans[0].nextDate,null);assert.equal(detail.item.loans[0].charges[0].date,null);assert.equal(detail.item.loans[0].charges[0].id,'charge-one')});
