import test from 'node:test';import assert from 'node:assert/strict';import {readRecordList} from '../../services/business/record-lists.mjs';
test('standalone payment provider-result seam retains unposted nullable sources and encoded null cursor branches',async()=>{
 const row=id=>({id,borrowerId:null,borrowerDisplayName:'Unavailable',paymentDate:null,createdAt:null,status:'Processing',amountReceived:'7',postedAmount:'0',accountLabel:null,manualReceiptPresent:false,agentReceiptPresent:false,month:null,groupAmountReceived:'14',borrowerNull:1,borrowerSort:'',monthNull:1,monthSort:'',dateNull:1,dateSort:'',createdNull:1,createdSort:''});let calls=[];
 const client={async query(sql,params){calls.push({sql,params});return {rows:calls.length===1?[row('A'),{...row('B'),status:'Error'}]:[{...row('B'),status:'Error'}]}}};
 const first=await readRecordList(client,'payments',{q:'ไทย %_',limit:1});assert.equal(first.items[0].status,'Processing');assert.equal(first.items[0].paymentDate,null);assert.equal(first.items[0].createdAt,null);assert.equal(first.items[0].groupAmountReceived,'14');const cursor=JSON.parse(Buffer.from(first.nextCursor,'base64url'));assert.deepEqual(cursor.tuple,['Unavailable',1,'',1,'',1,'',1,'','A']);
 const second=await readRecordList(client,'payments',{q:'ไทย %_',limit:1,cursor:first.nextCursor});assert.equal(second.items[0].status,'Error');assert.equal(second.nextCursor,null);assert.deepEqual(calls[1].params,['ไทย %_',...cursor.tuple,2]);
 for(const {sql}of calls){assert.doesNotMatch(sql,/(?:WHERE|AND)\s+p\."Status"\s*(?:=|IN)/i);assert.match(sql,/p\."Payment Date" IS NULL/);assert.match(sql,/p\."Created At" IS NULL/);assert.match(sql,/coalesce\(p\."Payment Date"::text,''\)/);assert.match(sql,/coalesce\(p\."Created At"::text,''\)/);assert.match(sql,/sum\(p\."Amount Received"\) OVER/);assert.match(sql,/"monthNull" ASC/);assert.match(sql,/"dateNull" ASC/);assert.match(sql,/"createdNull" ASC/)}
 await assert.rejects(readRecordList(client,'payments',{q:'different',cursor:first.nextCursor}),/invalid_request/);assert.equal(calls.length,2);
});
