import test from 'node:test';import assert from 'node:assert/strict';import {readRecordList} from '../../services/business/record-lists.mjs';
const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
test('standalone payment provider-result seam retains unposted nullable sources and encoded null cursor branches',async()=>{
 const q='ไทย %_',calls=[];
 const root={async query(sql,params){calls.push({sql,params});return{rows:calls.length===1?[{id:'',borrowerId:null,borrowerDisplayName:'Unavailable',nullRank:1},{id:'Z',borrowerId:'Z',borrowerDisplayName:'Z',nullRank:0}]:[{id:'Z',borrowerId:'Z',borrowerDisplayName:'Z',nullRank:0}]}}};
 const borrowers=await readRecordList(root,'payments',{q,limit:1});assert.equal(borrowers.level,'borrowers');assert.equal(borrowers.items[0].borrowerId,null);const rootCursor=JSON.parse(Buffer.from(borrowers.nextCursor,'base64url'));assert.deepEqual(rootCursor,{v:2,kind:'payment-borrowers',q,borrowerId:null,month:null,tuple:['Unavailable',1,'']});assert.equal((await readRecordList(root,'payments',{q,limit:1,cursor:borrowers.nextCursor})).nextCursor,null);assert.deepEqual(calls[1].params,[q,...rootCursor.tuple,2]);for(const{sql}of calls){assert.match(sql,/GROUP BY p\."Ref Borrower"/);assert.match(sql,/"borrowerDisplayName" COLLATE "C" ASC/);assert.match(sql,/"nullRank" ASC/)}
 const monthCalls=[];const months={async query(sql,params){monthCalls.push({sql,params});return{rows:monthCalls.length===1?[{month:null,amountReceived:'14',count:2,nullRank:1,monthKey:''}]:[]}}};const summary=await readRecordList(months,'payments',{q,limit:1,unassigned:true});assert.deepEqual(summary,{level:'months',items:[{month:null,amountReceived:'14',count:2}],nextCursor:null});const monthCursor=encode({v:2,kind:'payment-months',q,borrowerId:null,month:null,tuple:[1,'']});await readRecordList(months,'payments',{q,limit:1,unassigned:true,cursor:monthCursor});assert.deepEqual(monthCalls[1].params,[q,null,1,'',2]);for(const{sql}of monthCalls){assert.match(sql,/sum\(p\."Amount Received"\)::numeric::text/);assert.match(sql,/GROUP BY to_char\(p\."Payment Date",'YYYY-MM'\)/);assert.match(sql,/"nullRank" ASC,"monthKey" COLLATE "C" DESC/)}
 const row=id=>({id,paymentDate:null,createdAt:null,status:id==='A'?'Processing':'Error',amountReceived:'7',nullRank:1,dateKey:'',createdNull:1,createdKey:''}),leafCalls=[];const leaf={async query(sql,params){leafCalls.push({sql,params});return{rows:leafCalls.length===1?[row('A'),row('B')]:[row('B')]}}};
 const first=await readRecordList(leaf,'payments',{q,limit:1,unassigned:true,month:'undated'});assert.equal(first.level,'payments');assert.deepEqual(first.items,[{id:'A',paymentDate:null,createdAt:null,status:'Processing',amountReceived:'7'}]);const cursor=JSON.parse(Buffer.from(first.nextCursor,'base64url'));assert.deepEqual(cursor,{v:2,kind:'payment-payments',q,borrowerId:null,month:'undated',tuple:[1,'',1,'','A']});const second=await readRecordList(leaf,'payments',{q,limit:1,unassigned:true,month:'undated',cursor:first.nextCursor});assert.equal(second.items[0].status,'Error');assert.equal(second.nextCursor,null);assert.deepEqual(leafCalls[1].params,[q,null,null,...cursor.tuple,2]);
 for(const{sql}of leafCalls){assert.match(sql,/p\."Payment Date" IS NULL/);assert.match(sql,/p\."Created At" IS NULL/);assert.match(sql,/coalesce\(p\."Payment Date"::text,''\)/);assert.match(sql,/coalesce\(p\."Created At"::text,''\)/);assert.match(sql,/"nullRank" ASC,"dateKey" COLLATE "C" DESC,"createdNull" ASC/);assert.match(sql,/p\."Ref Borrower" IS NOT DISTINCT FROM \$2::text/);assert.match(sql,/to_char\(p\."Payment Date",'YYYY-MM'\) IS NOT DISTINCT FROM \$3::text/)}
 for(const{sql}of [...calls,...monthCalls,...leafCalls])assert.doesNotMatch(sql,/(?:WHERE|AND)\s+p\."Status"\s*(?:=|IN)/i);
 for(const options of [{q:'different',unassigned:true,month:'undated',cursor:first.nextCursor},{q,borrowerId:'other',month:'undated',cursor:first.nextCursor},{q,unassigned:true,month:'2026-10',cursor:first.nextCursor},{q,cursor:first.nextCursor},{q,unassigned:true,cursor:borrowers.nextCursor}])await assert.rejects(readRecordList(leaf,'payments',options),/invalid_request/);assert.equal(leafCalls.length,2);
});
