import test from 'node:test';import assert from 'node:assert/strict';
import {readUpcoming,encodeUpcomingCursor,decodeUpcomingCursor} from '../../services/api/upcoming-read-contract.mjs';
import {createBorrowerReadStore} from '../../services/api/borrower-read-store.mjs';
import {createDevReadHandler} from '../../services/api/dev-read-handler.mjs';
const c={parentId:'parent',businessDate:'2026-10-07',dueDate:'2026-10-12',loanId:'loan',id:'event'};
const coverage={businessDate:c.businessDate,horizonEnd:'2027-01-07',expectedHorizonEnd:'2027-01-07',reviewLoans:0};
function client(overrides={}){const queue=[[{businessDate:c.businessDate,asOf:'2026-10-07T05:00:00Z'}],[{invalid:false}],[{id:'parent'}],overrides.coverage??[coverage],[{invalid:overrides.invalidBasis??false,dates:overrides.summary??[{id:'date',dueDate:c.dueDate,totalCharge:null}],events:overrides.details??[{id:'event',loanId:'loan',dueDate:c.dueDate,principalRemaining:null,interestRemaining:'2.125',amountRemaining:null,basis:'Recorded',name:'Synthetic',description:'English',principal:'1000',loanDate:'2026-10-01',rate:'2'}]}]];return{query:async()=>({rows:queue.shift()})}}
test('Upcoming cursor binds canonical date parent event and loan; malformed requests never connect',async()=>{const encoded=encodeUpcomingCursor(c);assert.equal(decodeUpcomingCursor(encoded,c.parentId,c.businessDate,c.dueDate).id,c.id);for(const args of [[encoded,'other',c.businessDate,c.dueDate],[encoded,c.parentId,'2026-10-08',c.dueDate],[encoded,c.parentId,c.businessDate,'2026-10-13'],[encoded+'=',c.parentId,c.businessDate,c.dueDate],[Buffer.from(JSON.stringify({...c,v:1,kind:'collection-upcoming',extra:1})).toString('base64url'),c.parentId,c.businessDate,c.dueDate]])assert.throws(()=>decodeUpcomingCursor(...args));let connections=0;const store=createBorrowerReadStore({config:{ownerEmail:'owner@example.test'},pool:{connect:async()=>{connections++;throw Error()}}});for(const options of [{},{businessDate:'0000-01-01'},{businessDate:'2026-02-30'},{businessDate:c.businessDate,limit:101},{businessDate:c.businessDate,cursor:encoded},{businessDate:c.businessDate,dueDate:c.dueDate,cursor:'%%%'}])assert.equal((await store.getCollectionUpcoming('owner@example.test','parent',options)).status,400);assert.equal(connections,0)});
test('Upcoming coverage missing invalid and date mismatch cannot masquerade as empty',async()=>{for(const rows of [[],[coverage,coverage],[{...coverage,reviewLoans:null}],[{...coverage,reviewLoans:-1}],[{...coverage,reviewLoans:0.5}],[{...coverage,horizonEnd:'2027-01-08'}],[{...coverage,businessDate:null}]])assert.equal((await readUpcoming(client({coverage:rows}),{borrowerId:'parent',businessDate:c.businessDate})).collectionError,'source_unavailable');assert.equal((await readUpcoming(client({coverage:[{...coverage,businessDate:'2026-10-06'}]}),{borrowerId:'parent',businessDate:c.businessDate})).collectionStatus,409);const empty=await readUpcoming(client({summary:[]}),{borrowerId:'parent',businessDate:c.businessDate});assert.deepEqual(empty.items,[]);assert.equal(empty.reviewRequired,false)});
test('Upcoming nullable decimals survive; malformed amounts basis and duplicate summaries fail closed',async()=>{const options={borrowerId:'parent',businessDate:c.businessDate,dueDate:c.dueDate};const value=await readUpcoming(client(),options);assert.equal(value.totalCharge,null);assert.equal(value.items[0].amountRemaining,null);assert.equal(value.items[0].interestRemaining,'2.125');assert.equal((await readUpcoming(client({invalidBasis:true}),options)).collectionError,'source_unavailable');for(const amount of ['NaN','Infinity','1e3',''])await assert.rejects(readUpcoming(client({summary:[{id:'date',dueDate:c.dueDate,totalCharge:amount}]}),options));assert.equal((await readUpcoming(client({summary:[{id:'a',dueDate:c.dueDate,totalCharge:'1'},{id:'b',dueDate:c.dueDate,totalCharge:'1'}]}),options)).collectionError,'source_unavailable')});
async function request(handler,url,method='GET'){let status,body;await handler({method,url,headers:{authorization:'Bearer synthetic'}},{setHeader(){},set statusCode(v){status=v},end(v){body=v?JSON.parse(v):null}});return{status,body}}
test('Upcoming HTTP authentication and strict query parsing gate store access',async()=>{let calls=0;const config={origin:'https://client.example.test'},store={getCollectionUpcoming:async()=>{calls++;return{ok:true}}};for(const status of [401,403]){const h=createDevReadHandler({config,store,verifyPrincipal:async()=>({ok:false,status,code:'denied'})});for(const path of ['/api/collection/p/upcoming?businessDate=2026-10-07','/api/collection/p/upcoming/2026-10-12?businessDate=2026-10-07'])assert.equal((await request(h,path)).status,status)}const h=createDevReadHandler({config,store,verifyPrincipal:async()=>({ok:true,email:'owner@example.test'})});for(const path of ['/api/collection/p/upcoming','/api/collection/p/upcoming?businessDate=a&businessDate=b','/api/collection/p/upcoming?businessDate=a&limit=25','/api/collection/%ZZ/upcoming?businessDate=a','/api/collection/p/upcoming/2026-10-12?businessDate=a&limit=-1'])assert.equal((await request(h,path)).status,400);assert.equal((await request(h,'/api/collection/p/upcoming?businessDate=a','POST')).status,405);assert.equal(calls,0)});
